### ISSUE TITLE
[EXTERNAL] New Instance of VS Code defaults C# kernel instead of C# .NET Interactive 

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/interactive#1000]
### Describe the bug
Opening a new  instances of VSCode. Complete end to end scenario [here](https://github.com/dotnet/interactive/issues/999) 

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

Version: 1.0.207202+44048161314453a09faa402f72c6f8cb088c6f3c

Build date: 2021-01-22T19:17:38.0237327Z

 Jupyter Extension Dependency v2020.12.414227025

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
   
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Other Environment details 
- There is no local Jupyter install
-  No  python 
### Opening a New Notebook 
-  Open a new window in VS Code `Ctrl + Shift + N`
- Opened a new notebook - Using the Jupyter 
![image](https://user-images.githubusercontent.com/2546640/105515629-e9172e80-5ca2-11eb-8f1b-5b5f588f721d.png)
- [ ] Cell default to a non .NET Interactive kernel 
![image](https://user-images.githubusercontent.com/2546640/105524675-f1c13200-5cad-11eb-8755-59617de785a2.png)
*what kernel is it looking at ?*
- [ ] Switching to C# .NET Interactive by clicking on the `c#` label.  This brings up a long list of kernels that do not exist on the machine.  This very different from [scenario 1](https://github.com/dotnet/interactive/issues/999#issue-792168058) were only .NET Interactive kernel + Markdown.
![image](https://user-images.githubusercontent.com/2546640/105525094-98a5ce00-5cae-11eb-80c3-a55434598e9c.png)
- [ ]  Selected `C# .NET Interactive` hit run and promoted to select a kernel
![image](https://user-images.githubusercontent.com/2546640/105525650-621c8300-5caf-11eb-9530-1139b31f0c36.png)
Given the current users developer environment the user is left stuck.

**Comment by brettfo** [comment]
Dependent on:

- microsoft/vscode-jupyter#4423
- microsoft/vscode-jupyter#4363
