### ISSUE TITLE
[EXTERNAL]New Instance of VS Code - .NET Interactive isn't honored or activated

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/interactive#1009]
### Describe the bug
Post-VS Code new instance .NET interactive isn't activated. 

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

Version: 1.0.207202+44048161314453a09faa402f72c6f8cb088c6f3c

Build date: 2021-01-22T19:17:38.0237327Z

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code
    - [ ] Other (please specify)
Other Environment details
- There is no local Jupyter install
- No python

### Screenshots
- [ ] Switching to C# .NET Interactive by clicking on the `c#` label.  This brings up a long list of kernels that do not exist on the machine.  
![image](https://user-images.githubusercontent.com/2546640/105525094-98a5ce00-5cae-11eb-80c3-a55434598e9c.png)
- [ ]  Selected `C# .NET Interactive` hit run and promoted to select a kernel
![image](https://user-images.githubusercontent.com/2546640/105525650-621c8300-5caf-11eb-9530-1139b31f0c36.png)

**Comment by LadyNaggaga** [comment]
Opened an issued here https://github.com/microsoft/vscode-jupyter/issues/4490

**Comment by jonsequitur** [comment]
I haven't seen a repro of this one lately. I think it's fixed but please reopen if you see it again.
