### ISSUE TITLE
Cannot close unsaved notebook

### ISSUE THREAD

**Issue by colombod** [dotnet/interactive#1013]
After creating an untitled notebook I am stuck with that file, can't save it or close the window.
When trying to save I get the following error

![image](https://user-images.githubusercontent.com/375556/105882703-dfbcf780-5ffd-11eb-9c2e-76aa26d1fb41.png)

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

![image](https://user-images.githubusercontent.com/375556/105882790-fc592f80-5ffd-11eb-95ac-2085c86ed2de.png)

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
@colombod Do still have a stable repro for this?

**Comment by colombod** [comment]
@jonsequitur I could no repro again so I am closing this issue

**Comment by FinickyCode** [comment]
I experienced this issue also, I know the issue is closed, posting how I resolved the issue for others.

I noticed that if I renamed the project folder the issue disappeared. When I renamed the project folder back to the same name the issue reoccurred. This lead me to believe it is an issue with the state cache for the project workspace.

I ended up deleting the most recently modified folder in the `data\user-data\User\workspaceStorage` VSCode folder and the issue is now resolved.

**Comment by IIT-CCHT** [comment]
> I experienced this issue also, I know the issue is closed, posting how I resolved the issue for others.
> 
> I noticed that if I renamed the project folder the issue disappeared. When I renamed the project folder back to the same name the issue reoccurred. This lead me to believe it is an issue with the state cache for the project workspace.
> 
> I ended up deleting the most recently modified folder in the `data\user-data\User\workspaceStorage` VSCode folder and the issue is now resolved.

good point! that solved my issue too.
i've restricted the delete operation to the folders inside workspaceStorage with today's date, since the issue for me happened this morning.
thanks for sharing!

**Comment by colombod** [comment]
Vscode sometimes changes storage format and the updated contains migration code that gets removed. Manually updating vscode or not using it regurarly can create issues like this.
