### ISSUE TITLE
Strange ModuleLoadException due to a WPF dependency

### ISSUE THREAD

**Issue by thakkarparth007** [dotnet/interactive#1018]
I have been using the .NET C# kernel in JupyterLab and it has been working quite fantastically. Except when I ran some code that has a dependency on `System.Windows.Media.DisableDpiAwarenessAttribute` class from assembly `WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35`.

Here's the error stack trace:
```
System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.

 ---> System.TypeLoadException: Could not load type 'System.Windows.Media.DisableDpiAwarenessAttribute' from assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at CModuleInitialize.IsProcessDpiAware(CModuleInitialize* )
   at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   at ?A0x52b3a002.InitCmiStartupRunner()
   at ?A0x52b3a002.??__E?A0x52b3a002@unused@@YMXXZ()
   at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.ThrowModuleLoadException(String errorMessage, Exception innerException)
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
<<<< omitting stack trace of code that depends upon this library >>>>
```

Note that I have included the assembly using `#r ""C:\Windows\Microsoft.NET\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll"` and there was no error while loading the dependency. I have also been able to run code that depends upon other random DLLs, so I don't think DLL loading in general is a problem. Apart from that, I'm not really sure what's going on. Am I loading incorrect DLL? There were multiple WindowsBase.dll, but this seemed to match the version. I did try some other DLLs and it didn't seem to help.

**Which version of .NET Interactive are you using?**

Version: 1.0.155302+ea10eecdeb2eb5f0ccbac5d7eec8b97a99453388

Build date: 2021-01-19T13:09:34.6320576Z

- OS: Windows 10
- Browser: Chrome
- Frontend: Jupyter Lab

--------

Interestingly, this error does not happen with C# interactive console in Visual Studio.

**Comment by KevinRansom** [comment]
@thakkarparth007 , could you provide the code that demonstrates this crash, that would help with diagnosing the broken dependency.

**Comment by thakkarparth007** [comment]
@KevinRansom , pinged you internally on Teams.

**Comment by KevinRansom** [comment]
@thakkarparth007 ,

c# interactive doesn't automagically probe for missing 'dlls.  So your list of depencies may not be complete.  It also doesn't know how to automagically resolve native dependencies.  The best solution is to create nuget packages containing the dependencies you are trying to load and reference them in notebooks using #r "nuget:PackageName, version#".
