### ISSUE TITLE
Extension fails to activate and says command create new blank notebook resulted in an error

### ISSUE THREAD

**Issue by meganrogge** [dotnet/interactive#1019]
Issue Type: <b>Bug</b>

I installed this extension and tried to create a new blank notebook and it wouldn't work. I uninstalled, reloaded the window, re-installed, reloaded the window, and it still wouldn't work.

Extension version: 1.0.207203
VS Code version: Code - Insiders 1.53.0-insider (7b0cfdd04ad530a9c8d782c618afd79290be3d64, 2021-01-27T08:59:32.031Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (13.41GB free)|
|Process Argv|--crash-reporter-id 3420d46c-96c2-459d-a2a6-a3ea05795ead|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30247033

```

</details>

![recording (12)](https://user-images.githubusercontent.com/29464607/106177977-0d18bb00-614e-11eb-8585-6cfe79078a94.gif)

**Comment by brettfo** [comment]
Are you still having issues activating the extension?
