### ISSUE TITLE
The number of lines scrolled by a scroll wheel in an interactive notebook in VS Code is not constant

### ISSUE THREAD

**Issue by DavidZidar** [dotnet/interactive#1025]
### Describe the bug
When scrolling with a scroll wheel on a mouse in Visual Studio Code the number of lines varies a lot depending on what the mouse cursor is hovering above which is very disorienting and makes navigating code very frustrating.

On my computer I scroll about 3 lines when the mouse cursor is over code or blank space, but the moment the mouse cursor is over a result set, like a table or a Plotly graph, it is scrolling about 15 lines.

### Please complete the following:

**Which version of .NET Interactive are you using?**
1.0.207203+f90ff415badc98a82c7db599658df94ad527328a

- OS
    - [x] Windows 10
 - Frontend
    - [x] Visual Studio Code

### Screenshots
![GIF 2021-01-30 23-11-30](https://user-images.githubusercontent.com/381720/106369303-926bbd80-6350-11eb-8660-8deaca4a38ff.gif)

**Comment by colombod** [comment]
@jrieken Is this behaviour correct, I am assuming that scrolling inside input cell does it by line while on output cell does it by cell

**Comment by jrieken** [comment]
@rebornix will now

**Comment by DavidZidar** [comment]
If this behavior is intentional, could you at least make it configurable? I find this incredibly frustrating because I constantly scroll way too far unintentionally just because my mouse pointer happened to end up over an output cell, then I have to spend time trying to find my way back and may end up overshooting again because of the same thing.

**Comment by DavidZidar** [comment]
I didn't think about this before but the correct amount of scrolling is actually happening when the mouse is hovering over results.

So the issue is in fact that it is scrolling too little when hovering over code which is annoying because then I have to scroll much more than I usually do and when the mouse pointer passes over a result I end up scrolling WAY too far and have to backtrack.

**Comment by DavidZidar** [comment]
This has been resolved in VS Code, now scrolling is maddeningly slow but at least it's consistent.
