### ISSUE TITLE
Nuget can not be used with dotnet interactive in private networks

### ISSUE THREAD

**Issue by Frassle** [dotnet/interactive#1028]
### Describe the bug
Due to how dotnet interactive does nuget restores it can not be used in private networks that are segregated from the internet. 
In `src\Microsoft.DotNet.Interactive\PackageRestoreContext.cs` the url `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json` is unconditionally added as a nuget source. 
There is no way to disable this via nuget or dotnet.interactive configuration (`dotnet nuget restore` accepts a `--ignore-failed-sources` argument, but there's no way to pass that through dotnet.interactive) As such when on a private network with no access to that url *every* nuget restore fails because the source is unreachable (this is standard nuget behavior).

### Please complete the following:

**Which version of .NET Interactive are you using?**
1.0.155302

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [X] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

**Comment by Frassle** [comment]
## Workarounds

Restoring the package to the global nuget cache and then telling dotnet.interactive to restore that specific version will skip all network access in nuget and work ok.

**Comment by jonsequitur** [comment]
We should remove the implicit adding of that package source.

**Comment by Frassle** [comment]
Can confirm that this is fixed in https://www.nuget.org/packages/Microsoft.dotnet-interactive/1.0.210803

**Comment by colombod** [comment]
> Can confirm that this is fixed in https://www.nuget.org/packages/Microsoft.dotnet-interactive/1.0.210803

This release removed the pre-configured nuget source that caused the issue. The behaviour of the package management is now equivalent to dotnet add package / dotnet restore
