### ISSUE TITLE
Version 1.0.210103 don't handle net5.0

### ISSUE THREAD

**Issue by rfrerebe-stx** [dotnet/interactive#1029]
### Describe the bug
Latest version (as of 02-Feb-2021) is 1.0.210103 and is not compatible with net5.0

### Please complete the following:

**Which version of .NET Interactive are you using?** 

```bash
root@7ec8f9820aec:/# dotnet tool list -g
Package Id                        Version         Commands
--------------------------------------------------------------------
microsoft.dotnet-interactive      1.0.210103      dotnet-interactive
```
The issue is **not** present with version `1.0.210101`

Steps to reproduce :
- `docker run -it --rm mcr.microsoft.com/dotnet/sdk:5.0`
- `export PATH="$PATH:/root/.dotnet/tools"`
- `dotnet tool install -g Microsoft.dotnet-interactive  --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"`

The issue can be seen just when asking the version : `dotnet interactive --version`

```bash
root@7ec8f9820aec:/# dotnet interactive --version
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.2 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=debian.10-x64
```

The issue can be fixed by specify a previous version : `dotnet tool install -g Microsoft.dotnet-interactive --version  1.0.210101 --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"`

List of versions for microsoft.dotnet-interactive package:
[https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/flat2/microsoft.dotnet-interactive/index.json](https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/flat2/microsoft.dotnet-interactive/index.json)

**Comment by brettfo** [comment]
We recently had some build issues that published an older tool to the feed, but that's been sorted now.

Any tool version after 1.0.210202 will work.
