### ISSUE TITLE
MSSQL: Messages Shouldn't Output in nteract Data Explorer

### ISSUE THREAD

**Issue by chlafreniere** [dotnet/interactive#1052]
### Describe the bug
Messages from SQL Server shouldn't also use the nteract data explorer to display data.

Example are `SELECT @@LANGID` or `SELECT @@VERSION`

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.

- OS
    - [x] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/40371649/107451740-c38c8080-6afc-11eb-82f5-2e2ca2d97baf.png)

**Comment by jonsequitur** [comment]
Any scalar result should probably not default to the data explorer.

**Comment by corivera** [comment]
@chlafreniere Displaying the messages in the results table matches the behavior in SSMS and ADS. What should we be doing differently here?

**Comment by lucyzhang929** [comment]
@corivera We still want to display the results table, just not in nteract since it wouldn't make sense for something like @@VERSION to be shown in the data explorer.

**Comment by corivera** [comment]
Looks like the data type for these values is just nvarchar, so how are we supposed to tell the difference between these and other string types? We aren't emitting any separate query messages, going by the query message handler callback.

**Comment by lucyzhang929** [comment]
Theres two separate issues:
1. Displaying the messages returned by sqltoolsservice Ex. "(1 row affected)" which we can do using the query message handler. 
2. Displaying scalar values (any result with one cell) without using nteract.

**Comment by corivera** [comment]
The first seems like it should be tracked by a separate issue, like "Add Query Messages tab" or something. For the second, special casing these outputs doesn't seem useful because these are actual query results, and if we dump the user out to a generic string instead of a table it would look weird. Plus then we have to maintain separate tests for single value queries.

**Comment by lucyzhang929** [comment]
Makes sense I'll create another issue to track messages. @jonsequitur @chlafreniere thoughts for second point?

**Comment by jonsequitur** [comment]
The default dictionary formatter is similar to what we want I think.

Quick mockup:

![image](https://user-images.githubusercontent.com/547415/108573380-3cdc5e00-72c9-11eb-9717-0dc3b778d14e.png)
