### ISSUE TITLE
MSSQL + nteract Data Explorer's Default Height is Too Large

### ISSUE THREAD

**Issue by chlafreniere** [dotnet/interactive#1053]
### Describe the bug
Run a query for mssql, and notice that the output area for that cell is much larger (too high) for nteract Data Explorer.

Possibly related to hardcoding `100ch` for the height.
Not super familiar with this codebase, but potentially set here? https://github.com/dotnet/interactive/blob/3e46eb1e404d04d786dacd18fb6473eb9fafcb11/src/Microsoft.DotNet.Interactive.ExtensionLab/NteractKernelExtension.cs#L54

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.

- OS
    - [x] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/40371649/107452404-fb47f800-6afd-11eb-9d79-52861f77eb0d.png)

**Comment by brettfo** [comment]
nteract data explorer integration was experimental and maintained.
