### ISSUE TITLE
Running printf "Hello world" or "!#about" magic command succeeds but doesn't have any output

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [dotnet/interactive#1065]
### Describe the bug

Running simple commands in a a dotnet interactive notebook succeeds but outputs no results:

https://i.imgur.com/iNjBAwo.mp4
https://i.imgur.com/39niKW4.mp4

### Please complete the following:

**Which version of .NET Interactive are you using?**
```bash
% dotnet interactive --version
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.0-rc.1.20451.17 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      5.0.0 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      5.0.1 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=osx.11.0-x64
```

Dotnet interactive notebooks have previously been working.

- OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android

 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

**Comment by DavidZidar** [comment]
I am on Windows 10 and also have this issue since I updated VS Code the other day, in fact I don't get any output at all any more.

**Comment by jonsequitur** [comment]
Are you still seeing this on the latest update to Code Insiders? If so, can you please let us know which version of the extension you're using?

**Comment by kurt-mueller-osumc** [comment]
Success!

![Screen Shot 2021-02-16 at 1 25 28 PM](https://user-images.githubusercontent.com/66080261/108105311-778c8f00-705a-11eb-83b7-805f3f9e03d2.png)

**Comment by DavidZidar** [comment]
XPlot graphs are still broken, I'm only getting a result table with Width, Height and an Id, not the actual graph.

**Comment by jonsequitur** [comment]
@DavidZidar That's a separate issue: #1070.
