### ISSUE TITLE
Unable to open notebook 'Filename.ipynb': Cannot read property 'Rich' of undefined

### ISSUE THREAD

**Issue by markjamesm** [dotnet/interactive#1066]
### Describe the bug
I recently upgraded to the latest version of VS Code Insiders and now I cannot load any of my .NET Interactive notebooks. Trying to open an existing notebook results in the following error:

`Unable to open 'Testing.ipynb': Cannot read property 'Rich' of undefined.`

Moreover, trying to create a new blank notebook using F# (.NET Interactive) and printing a variable to console shows the success checkmark, but no output is visible:

![Basic](https://user-images.githubusercontent.com/20845425/107865849-b93def80-6e38-11eb-9d80-ac337fa5e0ff.png)

**Which version of .NET Interactive are you using?**

> dotnet interactive --version
1.0.207602+316234b8fe05f226396667dd663df635e40b9ed5

Visual Studio Code - Insiders (Version 1.54.0-insider)

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

![Undefined](https://user-images.githubusercontent.com/20845425/107865742-db833d80-6e37-11eb-998f-f6d19d3ea8cb.png)

**Comment by arkada38** [comment]
> dotnet interactive --version
> 1.0.142601+586ab2f29818edea7c19c383874977fe5d0391fc
It looks like after the last update the issue is fixed

**Comment by markjamesm** [comment]
> > dotnet interactive --version
> > 1.0.142601+586ab2f29818edea7c19c383874977fe5d0391fc
> 
> It looks like after the last update the issue is fixed

After installing .NET Interactive version 1.0.207602+316234b8fe05f226396667dd663df635e40b9ed5 this morning, I can confirm that the issue is now fixed.
