### ISSUE TITLE
XPlot.Plotly plots no longer show up in the output of F# cells in Visual Studio Code

### ISSUE THREAD

**Issue by bmitchell-cfs** [dotnet/interactive#1070]
### Describe the bug

**Urgency: Very Urgent**. I have a presentation on Thursday in which I am going to be presenting F#, including .NET Interactive Notebooks in Visual Studio Code with F#, to my company, and it would be necessary for me to be able to run and show off the plotting functionality of the notebooks.

I am using XPlot.Plotly through an F# interactive notebook in Visual Studio Code. Previously, plotting worked just fine where the plots would show up in the output. Now, after .NET Interactive updated, the plots do not show. Instead, I have the following:

![image](https://user-images.githubusercontent.com/64422988/107987786-a8a68a00-6f9c-11eb-8065-da679d719aa0.png)

It should look like this:

![image](https://user-images.githubusercontent.com/64422988/107987877-d7246500-6f9c-11eb-804b-c72a01958347.png)

(I am able to get the image because the notebook was saved in source code control with the plot.)

The dependencies are either `#r "nuget: FsLab"` or `#r "nuget: XPlot.Plotly"`. The code to reproduce this is attached.
[code.zip](https://github.com/dotnet/interactive/files/5983786/code.zip)

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

**.NET 5 SDKs**:
```
> dotnet --list-sdks
3.1.405 [C:\Program Files\dotnet\sdk]
5.0.101 [C:\Program Files\dotnet\sdk]
5.0.103 [C:\Program Files\dotnet\sdk]
```

**.NET Interactive version**:
Version: 1.0.211402+a41fa7adec36d6321dee8e4510d532cd96379210
Build date: 2021-02-15T19:13:57.9034457Z

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

See above. The code is also attached above.

**Comment by jonsequitur** [comment]
We've moved the formatter support for Plotly out to a separate package [Xplot.Plotly.Interactive](https://www.nuget.org/packages/XPlot.Plotly.Interactive/), which you can install in your notebook using the following:

```csharp
#r "nuget:xplot.plotly.interactive"
```

**Comment by bmitchell-cfs** [comment]
Hi @jonsequitur. Thanks for the tip! However, I am unable to install that package. I get:

```
C:\Users\bmitchell\AppData\Local\Temp\nuget\17868--5c60450e-e360-484c-a31d-07b1ca75d43a\Project.fsproj : error NU1102: Unable to find package Microsoft.DotNet.Interactive.PowerShell with version (>= 1.0.0-beta.21108.4)
C:\Users\bmitchell\AppData\Local\Temp\nuget\17868--5c60450e-e360-484c-a31d-07b1ca75d43a\Project.fsproj : error NU1102:   - Found 5 version(s) in nuget.org [ Nearest version: 1.0.0-beta.21108.3 ]
C:\Users\bmitchell\AppData\Local\Temp\nuget\17868--5c60450e-e360-484c-a31d-07b1ca75d43a\Project.fsproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
C:\Users\bmitchell\AppData\Local\Temp\nuget\17868--5c60450e-e360-484c-a31d-07b1ca75d43a\Project.fsproj : error NU1102: Unable to find package Microsoft.DotNet.Interactive with version (>= 1.0.0-beta.21108.4)
C:\Users\bmitchell\AppData\Local\Temp\nuget\17868--5c60450e-e360-484c-a31d-07b1ca75d43a\Project.fsproj : error NU1102:   - Found 10 version(s) in nuget.org [ Nearest version: 1.0.0-beta.21108.3 ]
C:\Users\bmitchell\AppData\Local\Temp\nuget\17868--5c60450e-e360-484c-a31d-07b1ca75d43a\Project.fsproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
C:\Users\bmitchell\AppData\Local\Temp\nuget\17868--5c60450e-e360-484c-a31d-07b1ca75d43a\Project.fsproj : error NU1102: Unable to find package Microsoft.Dotnet.Interactive.http with version (>= 1.0.0-beta.21108.4)
C:\Users\bmitchell\AppData\Local\Temp\nuget\17868--5c60450e-e360-484c-a31d-07b1ca75d43a\Project.fsproj : error NU1102:   - Found 2 version(s) in nuget.org [ Nearest version: 1.0.0-beta.21108.3 ]
C:\Users\bmitchell\AppData\Local\Temp\nuget\17868--5c60450e-e360-484c-a31d-07b1ca75d43a\Project.fsproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
C:\Users\bmitchell\AppData\Local\Temp\nuget\17868--5c60450e-e360-484c-a31d-07b1ca75d43a\Project.fsproj : error NU1102: Unable to find package Microsoft.Dotnet.Interactive.Formatting with version (>= 1.0.0-beta.21108.4)
C:\Users\bmitchell\AppData\Local\Temp\nuget\17868--5c60450e-e360-484c-a31d-07b1ca75d43a\Project.fsproj : error NU1102:   - Found 10 version(s) in nuget.org [ Nearest version: 1.0.0-beta.21108.3 ]
C:\Users\bmitchell\AppData\Local\Temp\nuget\17868--5c60450e-e360-484c-a31d-07b1ca75d43a\Project.fsproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
```

Any thoughts?

**Comment by jonsequitur** [comment]
Sorry about that. If you also add this it should work:

```csharp
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"
```

**Comment by bmitchell-cfs** [comment]
Thanks! It looks like I still need to add in and explicitly reference System.CommandLine. So what I have that works is:

```
#i "nuget: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"
#r "nuget: System.CommandLine"
#r "nuget: FSharp.Data"
#r "nuget: XPlot.Plotly"
#r "nuget: XPlot.Plotly.Interactive"
```

**Comment by jonsequitur** [comment]
We already reference System.CommandLine but if there's a version mismatch on it, you can also add:

```cs
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json"
```

**Comment by Curtis-64** [comment]
I do not get any rendering graphic. I get the table only or output to web. Are we sure this is working now?

**Comment by iennacca** [comment]
Had an issue with the D3 network graph; it rendered as a table. I'm guessing this is also a Formatter issue?
