### ISSUE TITLE
Display BigInteger values as decimals, not objects

### ISSUE THREAD

**Issue by idg10** [dotnet/interactive#1096]
The `BigInteger` type (in `System.Numerics`) built into .NET does not display its numeric value in a Notebook. So if you have, for example:

```cs
BigInteger v = 42;
display(v);
```

You will see this tabular output:

IsPowerOfTwo | IsZero | IsOne | IsEven | Sign
-- | -- | -- | -- | --
False | False | False | True | 1

In other words, the notebook has displayed all the properties, instead of the numeric value. This is surprising. Normally when I ask a notebook to display a number I expect its numeric value in some form.

Currently I need to call `ToString()` on a `BigInteger` to get its value. This feels like something .NET Interactive should be doing automatically.

**Comment by WhiteBlackGoose** [comment]
@jonsequitur if you think it's not hard to fix it, assign me to this one, I'll try to work on it

**Comment by jonsequitur** [comment]
All yours. Thanks @WhiteBlackGoose!
