### ISSUE TITLE
MSSQL: Charts are lost when reopening the notebook

### ISSUE THREAD

**Issue by MsSQLGirl** [dotnet/interactive#1113]
### Describe the bug
I've successfully run various SQL statements in code cells and playing around with the chart in a notebook. 
I close VSCode. 
I open VSCode again, and reopen the file. It doesn't display the charts. 

Sample file to repro: https://gist.github.com/MsSQLGirl/c056241209c000f33043da6bbaad973e

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.

.NET Interactive
Version: 1.0.212602+6fd92eb9d72c119b6e7822ca87d96427399a3307
Build date: 2021-02-27T15:23:49.1457837Z

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

Version: 1.54.0-insider (user setup)
Commit: e590188f17162393f50feec19263398e6fe02d13
Date: 2021-02-26T20:39:10.253Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

### Screenshots
![image](https://user-images.githubusercontent.com/6405919/109391394-b37dea80-78cb-11eb-932b-2fc4e7952253.png)

**Comment by colombod** [comment]
Html and JavaScript are not re-evaluated on open. The data viewer for tables require JavaScript execution. The behaviour your are seeing is the normal behaviour for that visualisation component

**Comment by MsSQLGirl** [comment]
I see. Does this mean that it requires users to re-run all upon opening the notebook (with the saved visualizations)?

**Comment by colombod** [comment]
For those visualisations yes. Cell must be executed again
