### ISSUE TITLE
[EXTERNAL] Python kernel with C# cell doesn't execute with C# kernel

### ISSUE THREAD

**Issue by Xarkam** [dotnet/interactive#1122]
### Describe the bug
Can't execute C# code into ipynb file in vscode stable. But with jupyter-lab I can:
![image](https://user-images.githubusercontent.com/331816/109791133-66bf4a00-7c12-11eb-98c3-e1248d4833e5.png)

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
1.0.215204

* In a notebook, run the `#!about` magic command. 
Nothing, just say 0.6s
![image](https://user-images.githubusercontent.com/331816/109790791-0cbe8480-7c12-11eb-9102-626d3a2773c0.png)
![image](https://user-images.githubusercontent.com/331816/109790818-12b46580-7c12-11eb-8f15-c87cf42f28d2.png)

* At the command line, run `dotnet interactive --version`.
1.0.215204+974732778592b69c526648c54ef4c48219058e97

- OS
    - [ ] Windows 10
    - [ ] macOS
    - [x] Linux KDE Neon
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [x] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/331816/109790554-d3861480-7c11-11eb-93d3-55b9389d4e28.png)
![image](https://user-images.githubusercontent.com/331816/109790642-ea2c6b80-7c11-11eb-80e1-7e3a831d8c9c.png)
![image](https://user-images.githubusercontent.com/331816/109791722-0a105f00-7c13-11eb-8a82-ad9b91d863f0.png)
![image](https://user-images.githubusercontent.com/331816/109791863-35934980-7c13-11eb-9b06-c4b4965bb84a.png)
![image](https://user-images.githubusercontent.com/331816/109791906-3fb54800-7c13-11eb-946f-fa9fd735cc7e.png)

## Linux Distribution
![image](https://user-images.githubusercontent.com/331816/109791507-d2091c00-7c12-11eb-8eaf-8471439aece0.png)

**Comment by colombod** [comment]
What extension do you have? It seems that the code is sent to a python kernel. Despite the language selected in the cell can you verify that you are using the .NET Interactive kernel by using the command palette and then start looking for the choose kernel command?

**Comment by Xarkam** [comment]
Hi,
That's right, despite the choice of .NET Interactive, it is positioned on python.
![image](https://user-images.githubusercontent.com/331816/110201073-84ceb980-7e61-11eb-8e33-963f3907a36d.png)

**Comment by colombod** [comment]
How are you opening the notebook?

**Comment by colombod** [comment]
@brettfo do you have any suggestion?

**Comment by Xarkam** [comment]
> How are you opening the notebook?

How I'm opening ? Tutorial https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode
I just follow the indications of the "doc"

**Comment by colombod** [comment]
can you check if the the settings for your extension look like this?
![image](https://user-images.githubusercontent.com/375556/110208777-008c2e80-7e81-11eb-8caf-3312b9ad6116.png)

**Comment by Xarkam** [comment]
![image](https://user-images.githubusercontent.com/331816/110213637-21647c00-7ea1-11eb-8792-0866020fdb36.png)
Not checked by default on my installation.

**Comment by jonsequitur** [comment]
You typically have to select the kernel before the language chooser will work correctly. The experience is still awkward there.

If you're still seeing output from Python instead of .NET, try opening the VS Code command palette, select `View: Reopen Editor With...`, and select `.NET Interactive for Jupyter`.

**Comment by Xarkam** [comment]
> You typically have to select the kernel before the language chooser will work correctly. The experience is still awkward there.
> 
> If you're still seeing output from Python instead of .NET, try opening the VS Code command palette, select `View: Reopen Editor With...`, and select `.NET Interactive for Jupyter`.

Thank you. So while waiting for the experience to become satisfactory, wouldn't it be wise to add a section in the doc for this kind of problem?

**Comment by brettfo** [comment]
This has been a major point of confusion for users in the past.

The issue appears to be that the Python kernel was selected for the notebook, but the individual cell's language was set to "C# (.NET Interactive)" so editor language services were getting routed to C# appropriately, but cell execution was honoring the kernel.

There are two related issues open against the Jupyter extension, microsoft/vscode-jupyter#4510 and microsoft/vscode-jupyter#4490 that call out how a kernel can (and should?) restrict it's language list, so the Python kernel should ideally not list C# as a possible language.
