### ISSUE TITLE
Variable sharing between c# and sql

### ISSUE THREAD

**Issue by sarah-unilin** [dotnet/interactive#1136]
**Is your feature request related to a problem? Please describe.**

So in the insiders edition you can get a value from a file like #!value --name name --from-file file
Which is very nice, but I wish there was a way to use this loaded value in an #!sql cell which doesn't seem to be possible (yet?)

**Describe the solution you'd like**

Be able to use the #!share command in the same way you can share between c# and f# for example to then be able to do an update command in sql.

**Describe alternatives you've considered**

**Comment by jonsequitur** [comment]
This has been implemented in the latest release.
