### ISSUE TITLE
[EXTERNAL] LaTeX support for markdown blocks

### ISSUE THREAD

**Issue by jogvan-k** [dotnet/interactive#1143]
**Is your feature request related to a problem? Please describe.**
I'm currently using .NET Interactive notebooks to write interactive guides on how to implement various machine learning models in ML.NET and F#. These guides are based on equations. Not being able to show properly formatted equations hampers the guide quality.

**Describe the solution you'd like**
Extend the markdown rendering with a library supporting LaTex, such as MathJax.

**Describe alternatives you've considered**
Adding support to manually add external rendering libraries to the notebook.

**Comment by colombod** [comment]
is this happening in vscode extension?

**Comment by jogvan-k** [comment]
Yes, it is in the vscode extension. Sorry, should have clarified.

**Comment by colombod** [comment]
This seems to be a frontend issue in vscode rendering

**Comment by rebornix** [comment]
we already support latex in VS Code.
