### ISSUE TITLE
Enable stop button in VS Code to halt cell execution

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#1144]
Clicking the cancel button is not currently wired up to send the `Cancel` command. Once it's wired up and #1125 is merged, cancellation will be enabled for code that makes use of the provided `KernelInvocation.CancellationToken`.

Example code that can be cancelled:

```cs
using Microsoft.DotNet.Interactive;

var message = "Waiting";

var output = display(message);

while (!KernelInvocationContext.Current.CancellationToken.IsCancellationRequested)
{
    output.Update(message = message + ".");
    await Task.Delay(1000);
}
```

**Comment by colombod** [comment]
![image](https://user-images.githubusercontent.com/375556/110394344-32111f80-8064-11eb-80b4-1cbf2ed7ff79.png)
