### ISSUE TITLE
System.TimeoutException: Timeout resolving the kernel's HTTP endpoint. Please try again.

### ISSUE THREAD

**Issue by mshakurov** [dotnet/interactive#1155]
### Describe the bug

https://notebooks.gesis.org/binder/jupyter/user/dotnet-interactive-......../lab/tree/polyglot/COVID-19.ipynb

cell: 
notebookScope.plot = function (plotTarget) { ...

error text begins with:
System.TimeoutException: Timeout resolving the kernel's HTTP endpoint. Please try again.
   at Microsoft.DotNet.Interactive.App.CommandLine.CommandLineParser.<>c__DisplayClass6_0.<SetUpFormatters>b__2(ScriptContent script, TextWriter writer) in D:\workspace\_work\1\s\src\dotnet-interactive\CommandLine\CommandLineParser.cs:line 563
.....

### Please complete the following:

.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.215404+5efac58497373bbb4f6f0c299453321ff4920572
Build date: 2021-03-04T23:38:22.0000000Z
https://github.com/dotnet/interactive

- OS
    - [* ] Windows 10
 - Browser 
    - [* ] Chrome
    - [* ] Edge
    - [* ] Firefox
 - Frontend
    - [* ] Jupyter Lab

### Screenshots
![image](https://user-images.githubusercontent.com/5284014/110778783-da490300-8273-11eb-9e1a-2b10cfa75847.png)
![image](https://user-images.githubusercontent.com/5284014/110778837-ea60e280-8273-11eb-8576-0ae356f6d52a.png)
![image](https://user-images.githubusercontent.com/5284014/110778949-0b293800-8274-11eb-8345-e9c1054bc86b.png)

**Comment by colombod** [comment]
The js api needs access to the http port that .NET Interactive opens. Can you clarify how the jupyter server is hosted? the ployglot notebook you are using won't work in scenarios like mybinder because a port forwarding must be performed server side.
