### ISSUE TITLE
after running an F# cell, the cell output disappears and the cell language switches to C#

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#1175]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

**Which version of .NET Interactive are you using?** 

Version: 1.0.216815+9e5a2e1e1e8c79c9f02525879e1e76b6e100bb28
Build date: 2021-03-19T08:58:26.0000000Z

Extension version is: v1.0.2168151

Jupyter extension is also installed at version 2021.4.641214696.

- OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [x] Visual Studio Code Insiders
    - [ ] Other (please specify)

**Comment by colombod** [comment]
Fixed in #1201
