### ISSUE TITLE
Sql Kernel not working on Code insiders version

### ISSUE THREAD

**Issue by unuunc** [dotnet/interactive#1178]
1.Add a sql connection
2. Just do a select top 1 * from table

Expected : 

Expecting to see a row 

Actual
Exception
![image](https://user-images.githubusercontent.com/5947364/111968289-00498f80-8b1f-11eb-8be8-e85274b248f2.png)

Version v1.0.2168151 on windows

**Comment by unuunc** [comment]
![image](https://user-images.githubusercontent.com/5947364/112021123-f3e12900-8b56-11eb-9d0a-a727b66ca4ea.png)

**Comment by jonsequitur** [comment]
Could you include which version of the VS Code extension you're using?

Also, are you using VS Code stable or Insiders, and do you have custom NuGet sources configured?

**Comment by unuunc** [comment]
The version in mentioned 
![image](https://user-images.githubusercontent.com/5947364/112050527-f94e6b80-8b76-11eb-9051-33bd9d90fa14.png)

**Comment by unuunc** [comment]
I can confirm that the issue is only in code - insiders , not on code release version. I checked both and same notebook is working on release version and fails on code insiders version 

![image](https://user-images.githubusercontent.com/5947364/112284209-02425880-8caf-11eb-8d32-41969d108594.png)

**Comment by colombod** [comment]
can you test if this repro with latest .NET Interactive extensions

**Comment by unuunc** [comment]
Yeah it s working now , thanks a lot.
