### ISSUE TITLE
Failing on #r "nuget" puts the kernel in unusable state

### ISSUE THREAD

**Issue by colombod** [dotnet/interactive#1181]
### Describe the bug
If a cell performs `#r "nuget"` with errors no other package loading instruction will work;
![image](https://user-images.githubusercontent.com/375556/112088765-4ab32680-8b88-11eb-8929-7c1e9c8432cb.png)

## Version
1.0.216815

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [X] Visual Studio Code Insiders
    - [ ] Other (please specify)

**Comment by KevinRansom** [comment]
Fixed
