### ISSUE TITLE
Sudden "vscode.notebook.createNotebookCellExecutionTask is not a function" error for no apparent reason

### ISSUE THREAD

**Issue by reinux** [dotnet/interactive#1184]
### Describe the bug
I've had an F# notebook open for a few days, opened another one in another window, tried to run it, and got this error.

Restarted the first notebook, and that's also giving me the same error now as well.

No updates, no reboots... Really, no apparent reason.

Maybe it updated in the background and caused it to break?

### Please complete the following:

**Which version of .NET Interactive are you using?** 1.0.2174011

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [x] Edge
    - [x] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [x] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/5127297/112351637-4c174880-8c87-11eb-83f2-ebe79b99754f.png)

**Comment by jonsequitur** [comment]
Did you restart Code Insiders? It looks like you have an update pending and the VS Code notebook APIs change frequently in Insiders. I believe there was a breaking change yesterday. 

You might also try the stable version of VS Code. Insiders is no longer required.

**Comment by reinux** [comment]
Oh... I knew that. Yep. Just testing you guys. Totally intentional.

(Really though, sorry about that! Restart by itself didn't help, but updating did.)
