### ISSUE TITLE
Saving notebook with python cells converts all cells to plain text

### ISSUE THREAD

**Issue by jmoss-qos** [dotnet/interactive#1193]
Issue Type: <b>Bug</b>

When writing .NET interactive notebooks, saving python cells reverts them to plain text. To rerun the notebook in python the user must click on each cell and change it back to python.

Steps to reproduce:

_STEP 1:_ Use the "Python: select interpreter" to select an appropriate python version or conda environment. 
RESULT: Environment is selected, shown in bottom of UI, and logs indicate selected interpreter and startup of language servers.

_STEP 2:_ Use the ".NET Interactive: Create new blank notebook" command to create a a new notebook. 
RESULT: Notebook is created as Untitled-1.ipynb and first cell is set to python language mode.

_STEP 3:_ Write some trivial python and test the cell. e.g.

```python
import sys
print(sys.api_version)
```
RESULT: Cell executes correctly.

<img width="363" alt="python-result" src="https://user-images.githubusercontent.com/42978411/112691706-eec3f880-8e3a-11eb-9b7b-8bfaf98854ef.PNG">

_STEP 4:_ Save notebook to the filesystem with any name / any path.
RESULT: Cell language type is immediately converted to Plain Text. Reopening the file contains the same plain text cell types and each cell must be converted back to python to execute.

<img width="361" alt="plaintext-annoyance" src="https://user-images.githubusercontent.com/42978411/112691775-0d29f400-8e3b-11eb-8946-719b816edcf5.PNG">

<hr/>

Sample notebook follows:

```json
{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "dotnet_interactive": {
          "language": "python"
        }
      },
      "source": [
        "import sys\n",
        "print(sys.api_version)"
      ],
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "application/x.notebook.stdout": "1013\n"
          },
          "execution_count": 1,
          "metadata": {}
        }
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": ".NET (C#)",
      "language": "C#",
      "name": ".net-csharp"
    },
    "language_info": {
      "file_extension": ".cs",
      "mimetype": "text/x-csharp",
      "name": "C#",
      "pygments_lexer": "csharp",
      "version": "8.0"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}
```

Extension version: 1.0.2175031
VS Code version: Code - Insiders 1.55.0-insider (d06d2f1d6245ce00b1c36a9cd81a9087d225173e, 2021-03-26T14:01:14.867Z)
OS version: Windows_NT x64 10.0.19041

**Comment by rchiodo** [comment]
For me, if .NET interactive is installed it always writes itself as the kernel in the metadata.
