### ISSUE TITLE
Compatibility issue with netcoreapp3.1

### ISSUE THREAD

**Issue by arun-siv** [dotnet/interactive#1194]
C:\WINDOWS\system32>dotnet tool install --global Microsoft.dotnet-interactive --version 1.0.210803
error NU1202: Package Microsoft.dotnet-interactive 1.0.210803 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any. Package Microsoft.dotnet-interactive 1.0.210803 supports: net5.0 (.NETCoreApp,Version=v5.0) / any
The tool package could not be restored.
Tool 'microsoft.dotnet-interactive' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-toolC:\WINDOWS\system32>dotnet tool install --global Microsoft.dotnet-interactive --version 1.0.210803
error NU1202: Package Microsoft.dotnet-interactive 1.0.210803 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any. Package Microsoft.dotnet-interactive 1.0.210803 supports: net5.0 (.NETCoreApp,Version=v5.0) / any
The tool package could not be restored.
Tool 'microsoft.dotnet-interactive' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by colombod** [comment]
.NET Interactive is a .NET 5 application, you will need latest stable sdk of .NET 5 to be able to install it and use it, what versions do you have (you can find out with the command `dotnet --list-sdks`
