### ISSUE TITLE
Stopped all kernals now get dotnet-sdk.acquirestatus not found

### ISSUE THREAD

**Issue by Curtis-64** [dotnet/interactive#1195]
### Describe the bug
I stopped all kernals. Now i get dotnet-sdk.acquirestatus not found. I have restarted, disabled, renabled but always get this error now.  I see a failed to set document metadata, as well.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

Cannot run-- latest version from VS Code Insiders.

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.

- OS
    - [X ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [X ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots

Update:
I was able to get the error to go away by uninstall and reinstall. Nothing else worked.

**Comment by jonsequitur** [comment]
Out of curiosity, did you try a VS Code Insiders update prior to the reinstall? Insiders updates daily and the notebook APIs are unstable. A VS Code error like this usually indicates the latest extension is targeting an older Insiders version, but we try to keep pace. That said, you can use .NET Interactive in VS Code stable as well, and you'll see this less often.

![image](https://user-images.githubusercontent.com/547415/112886898-625a4580-9087-11eb-8403-50bce52ad6d4.png)
