### ISSUE TITLE
Unable display xplot inline

### ISSUE THREAD

**Issue by Curtis-64** [dotnet/interactive#1197]
### Describe the bug
I can only get Xplot to render to web or get the table. I reference the prior bugs with the fix:

#r "nuget: XPlot.Plotly"
#r "nuget: XPlot.Plotly.Interactive"

This does not work for me.  I cannot get it to render graphics inside VS Code. I do not get any errors but I get the table view or render to web page only.

### Please complete the following:
**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.

- OS
    - [X ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [X ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots

Tried many combinations-- including pulling in old 3.0.4
![image](https://user-images.githubusercontent.com/47219692/112786181-addb0800-9023-11eb-99b9-b03275eed3b9.png)

**Comment by cartermp** [comment]
I get an internal exception when evaluating an F# cell in the latest build + GA VSCode (no Python installed). cc @jonsequitur

**Comment by jonsequitur** [comment]
@cartermp What was the code and what was the exception?

**Comment by WalternativE** [comment]
Is it the same error as here, @cartermp? https://github.com/plotly/Plotly.NET/issues/67 If yes it would be connected to a dependency upgrade in the extension mechanism that has to have happened quite recently. If that would be the case just bumping the .NET Interactive dependency in the XPlot interactive extension would fix it.

**Comment by cartermp** [comment]
In this case the code was:

`fsharp
12
```
Looks like it might be related to https://github.com/plotly/Plotly.NET/issues/67 indeed, that's the error I saw. I'll see if I can update xplot

**Comment by jonsequitur** [comment]
`12` is a notoriously complex expression to compile.

**Comment by cartermp** [comment]
Hmm, well I updated packages but now I get this:

![image](https://user-images.githubusercontent.com/6309070/112913275-2f777800-90ae-11eb-8a86-0d0673abbb7f.png)

I think it thinks I'm in powershell:

![image](https://user-images.githubusercontent.com/6309070/112913380-5766db80-90ae-11eb-9e0c-2e9c12f1851b.png)

**Comment by cartermp** [comment]
And to be clear, yes, it is setting F# as the language in the UI

![image](https://user-images.githubusercontent.com/6309070/112913415-68175180-90ae-11eb-973b-ce049e53e046.png)

**Comment by cartermp** [comment]
Okay, the issue as initially written can be closed. With updated Xplot.Plotly packages it all just works: 

![image](https://user-images.githubusercontent.com/6309070/112913474-867d4d00-90ae-11eb-8d0b-1904976e64df.png)

However, @jonsequitur this is what happened to get me into "it thinks I am in powershell" mode:

* Opened my desktop as a workspace
* Created a new file
* It defaulted to PowerShell as the kernel (no clue why)
* I switched it to F# by clicking the UI in the notebook
* This didn't work
* I only got it to _really_ be F# if I selected the dongle at the bottom:

![image](https://user-images.githubusercontent.com/6309070/112913551-b62c5500-90ae-11eb-8f97-450b94916bbb.png)

**Comment by WalternativE** [comment]
There are a couple of issues marked as high impact (like https://github.com/dotnet/interactive/issues/1175) which pretty much look what you described there. It's good to know, that you found a way to force it through the UI. My current workaround is to prepend the `#!fsharp` magic command in every cell.

**Comment by jonsequitur** [comment]
Agreed. The issues you're seeing @cartermp have been raised elsewhere and have to do with sharing the `.ipynb` file extension with other VS Code extensions. I'll close this issue.
