### ISSUE TITLE
System.MissingMethodException with Serilog in Jupyter Notebook

### ISSUE THREAD

**Issue by Tolyandre** [dotnet/interactive#1203]
### Describe the bug
Every one of these static methods throws `System.MissingMethodException` when running in Jupyter Notebook (ipynb):
```c#
#r "nuget:Serilog, 2.10.0"
using Serilog.Context;
using Serilog.Core.Enrichers;
 
LogContext.Push(new PropertyEnricher("A", 1));
LogContext.Clone();
LogContext.Reset(); 
```
E.g. for `Push()` exception is:
```
System.MissingMethodException: Method not found: 'System.IDisposable Serilog.Context.LogContext.Push(Serilog.Core.ILogEventEnricher)'.
```
Jupyter Notebook doesn't complain at compile-time, exception occurs at run time. Also these methods work as expected if I put code into file.csx and run `dotnet script file.csx`.

Also interesting, that some method from LogContext works in Jupyter Notebook normally. An example that does not throw:
```c#
#r "nuget:Serilog, 2.10.0"
using Serilog.Context;

LogContext.PushProperty("B", 2)
```
Source of LogContext for reference: https://github.com/serilog/serilog/blob/dev/src/Serilog/Context/LogContext.cs

### Please complete the following:

**Which version of .NET Interactive are you using?**   1.0.217604+a3dea7ced5d5f206116fcaec5d3f2ff5c2542e77

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [x] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/2414704/112906479-4beed100-90fd-11eb-81b5-534edbfb9154.png)

**Comment by jonsequitur** [comment]
This is because .NET Interactive carries a reference to an older Serilog. We can fix this by updating to a newer version. Longer-term, we'll be working on a more generalized approach to allowing dependencies at different versions from the ones .NET Interactive itself uses.

**Comment by Tolyandre** [comment]
Makes sense. I was wondering why Serilog's fixed bug (https://github.com/serilog/serilog/issues/1133) is still reproducible with Jupyter Notebook. It's clear now.

I am working on a demo about Serilog for my team. Updating to a newer version as a temporal fix would be fine for me.

**Comment by colombod** [comment]
The serilog has been updated, can you see if it addressing your bug?

**Comment by Tolyandre** [comment]
Now serilog works well, thank you!
