### ISSUE TITLE
How to display json data using C#

### ISSUE THREAD

**Issue by giggio** [dotnet/interactive#1220]
Hello there, I'm new to .NET Interactive, and I'm trying to experiment with it, but I haven't found a simple way to show some json data I got using `HttpClient`. I'm querying repository issues from the Github api, which returns an array of issues. From there, I'm stuck. This is what I have:

````csharp
using System.Net.Http;
using System.Net.Http.Headers;
var client = new HttpClient();
client.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("Net_Notebooks", "1.0"));
var response = await client.GetAsync("https://api.github.com/repos/giggio/node-chromedriver/issues");
#r "nuget:Newtonsoft.Json"
var responseString = await response.Content.ReadAsStringAsync();
var issues = Newtonsoft.Json.Linq.JArray.Parse(responseString);
// and now what?
````

I tried displaying it using JSON.net but it shows jibberish.

````csharp
dynamic issues = Newtonsoft.Json.JsonConvert.DeserializeObject(responseString);
issues
````

The value at `responseString` is correct, it contains a valid json array.

I'm not sure what is the idiomatic way to do this. Any pointers are appreciated.

Thanks.

**Comment by jonsequitur** [comment]
What you're seeing is the default HTML formatter, which isn't very useful in this case. We should probably provide a built-in viewer for JSON data like the tree view Jupyter Lab. 

![image](https://user-images.githubusercontent.com/547415/113881152-05d6e480-9771-11eb-9fdb-186aef3aec75.png)

(I didn't dig into why the fields are reading empty.)

It would fit nicely here as well:

![image](https://user-images.githubusercontent.com/547415/113881504-56e6d880-9771-11eb-86aa-7478e0ad83c9.png)

**Comment by jonsequitur** [comment]
@giggio Thoughts on #1233?

**Comment by giggio** [comment]
@jonsequitur I don't like it.
I'd like to see a table. If I have:

````js
[{a:1, b:2}, {a:3, b:4}]
````

I'd like to see:

<table>
<tr>
	<td>a
	<td>b
<tr>
	<td>1
	<td>2
<tr>
	<td>3
	<td>4
</table>

I'm not sure how it would work on more complex objects/arrays, maybe with nested tables, but this is what I was looking for.

**Comment by WhiteBlackGoose** [comment]
What about cases where the fields of objects in an array do not coincide? Also, with nested tables it will explode in side very quickly, instead of a tree hierarchy you will get a huge object you can't read.

**Comment by jonsequitur** [comment]
A suggestion by @eerhardt was to make it look more like the JSON displays in browser developer tools:

![image](https://user-images.githubusercontent.com/547415/115049218-534d0300-9e8f-11eb-8a37-9156a53eb1a0.png)

**Comment by jonsequitur** [comment]
The first iteration is merged now. I'd like to do another iteration to improve the styling. 

Here's how it looks: 

![image](https://user-images.githubusercontent.com/547415/116439670-a6667480-a804-11eb-9fb3-30ec4231827a.png)

![image](https://user-images.githubusercontent.com/547415/116439701-aebeaf80-a804-11eb-9aa1-af88f73d95db.png)
