### ISSUE TITLE
.NET PowerShell notebook does not work with Plotly

### ISSUE THREAD

**Issue by DBremen** [dotnet/interactive#1230]
### Describe the bug
Trying to execute code within a .NET PowerShell notebook (locally using Jupyter lab, locally using VS Code and also online) does throw an error when trying to display Plotly charts via `New-PlotlyChart`.
Example code:
`$chart = [Graph.Bar]::new()

$chart.x = 20,14,23
$chart.y = 'lions', 'tigers', 'bears'
$chart.orientation='h'

New-PlotlyChart -Trace $chart | Out-Display`

Error:
InvalidOperation: Unable to find type [Graph.Bar].
The term 'New-PlotlyChart' is not recognized as a name of a cmdlet, function, script file

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
1.0.216002+26986fc7149e69110f7485a7e02d5f8db166eebf

- OS
    - [x ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ x] Jupyter Lab
    - [ ] nteract
    - [ x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/10835918/114148994-4e79d380-9912-11eb-9075-90e83065b40a.png)
![image](https://user-images.githubusercontent.com/10835918/114149080-6a7d7500-9912-11eb-9913-073c760d1c12.png)

**Comment by colombod** [comment]
I have the plotting working
![image](https://user-images.githubusercontent.com/375556/114407009-e6402180-9b9f-11eb-926b-b44c1a023c2b.png)

Just notice that the first cell is now loading the extension (is no longer laoded automatically)

```csharp
#!csharp
#r "nuget: XPlot.Plotly.Interactive"
```

**Comment by DBremen** [comment]
Hi @colombod ,
Thank you, that did the trick within VSCode.
In Jupyter Notebooks I'm still getting an error.
`System.IO.FileNotFoundException: Could not load file or assembly 'System.Management.Automation, Version=7.1.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'System.Management.Automation, Version=7.1.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()`

Even when I try to adding the packet explicitly: `#!csharp
#r "nuget: System.Management.Automation"`

Cheers,
Dirk

**Comment by colombod** [comment]
That is very strange

Dr Diego Colombo PhD

**Comment by jhoneill** [comment]
A new notebook has a PSModulePath with 
`~\.dotnet\tools\.store\microsoft.dotnet-interactive\1.0.221202\microsoft.dotnet-interactive\1.0.221202\tools\net5.0\any\Modules`
and
`~\.dotnet\tools\.store\microsoft.dotnet-interactive\1.0.221202\microsoft.dotnet-interactive\1.0.221202\tools\net5.0\any\runtimes\win\lib\net5.0\Modules`
(a bit of a mess but seems to work)  the default powerShell modules +   Microsoft.DotNet.Interactive.PowerShell are distributed between these two 

#!csharp
#r "nuget: XPlot.Plotly.Interactive"

Downloads the files and adds 
`~\.nuget\packages\xplot.plotly.interactive\4.0.1\interactive-extensions\dotnet\Modules`
To the module path **for that session only**  
And also adds **Every** Nuget folder to the path **for that session only**  

That allows the xplot module's .PSD1 file to load form 
`~\.nuget\packages\xplot.plotly.interactive\4.0.1\interactive-extensions\dotnet\Modules\XPlot.Plotly.Interactive`
this loads 1 dll file which needs to be on the path 
`~\.nuget\packages\xplot.plotly.interactive\4.0.1\interactive-extensions\dotnet\XPlot.Plotly.Interactive.dll`

It's pretty horrible, but you can move the files around so they will load in another session.  


It looks like a lot of the type names have changed  last time I was looking at notebooks, this worked
```Powershell
New-Object -TypeName XPlot.Plotly.Graph+Bar -Property @{
            x = @('C#', 'JavaScript', 'PHP', 'PowerShell','Python')
            y = @(23,17,12,35,29)
} | New-PlotlyChart -Title 'Students' | Out-Display
```

Now ` XPlot.Plotly.Graph+Bar ` needs to be ` XPlot.Plotly.Bar`

**Comment by jonsequitur** [comment]
@jhoneill One thing to note is that you're likely using different versions of .NET Interactive between VS Code and Jupyter. VS Code installs its own version, independent of the one you might install yourself for Jupyter using `dotnet tool install -g`. You can verify the version by running `#!about`.

Also, those `XPlot` classes were indeed un-nested. 

> Question Has setting the code type on the cell stopped working, I've been away from notebooks in VS Code for while, and could not initially get PowerShell to without #!pwsh when the notebook was convinced it was a c# one and once the default switch to PowerShell - I don't know how - marking a cell as C Sharp won't work without #!Csharp

Do you still have a repro of this and if so could you provide a screen shot of the enture VS Code window when it happens? Thanks.

**Comment by jhoneill** [comment]
@jonsequitur I had quite a lot of back and forth to get the version the latest VS-code was loading up to 1.0.221202 it was loading much older. Normally VS-Code has that days version of .NET interactive and Jupyter has whatever I last installed. Starting via Anaconda and from VS-Code now get me to the the same version in the about box. 

`Get-CimInstance -ClassName win32_process -Filter "processID = $($p.id)" |  select -expand commandline `
Now reports 
`<profile>\.dotnet\tools\dotnet-interactive.exe" jupyter --default-kernel powershell <profile>\AppData\Local\Temp\tmp-20920iHm7weggSBoX.json`
When I  hopped back to Jupyter it changed the default kernel from C sharp to PowerShell (which is what I want, but I don't know how it's controlled).  So now PS is fine but c# doesn't work if I set the cell type 

![image](https://user-images.githubusercontent.com/16209593/114593775-62ac3080-9c84-11eb-9a6c-394848e54d01.png)

That's powershell's message about var
![image](https://user-images.githubusercontent.com/16209593/114595338-2e397400-9c86-11eb-8148-f49da86076f3.png)
Now I get a c# error :-)  but it works with ; in place. 

Plotly is now all manual ? 
My comment above missed out loading  `\.nuget\packages\xplot.plotly\4.0.1\lib\netstandard2.0\XPlot.Plotly.dll`

**Comment by jhoneill** [comment]
@jonsequitur  Supplemental. I have two machines. "MY" machine happily changes the language of cells, and applied and used the latest update with no messing about.  "Work's" machine is doing all the strange stuff. It may not matter but mine doesn't have a Python / Jupyter install it's VS-Code only (no Jupyter message on the status bar either). Whether there is some conflict on work's - which also has Azure Data Studio in the mix - I couldn't say, but it does look to be config specific.

**Comment by colombod** [comment]
If you open the command palette and then select the `Notebook: Select Notebook Kernel`
![image](https://user-images.githubusercontent.com/375556/114610509-e7547a00-9c97-11eb-856a-ecc924b11d51.png)
What is the current kernel?

Make sure you switch to .NET Interactive
![image](https://user-images.githubusercontent.com/375556/114610728-25ea3480-9c98-11eb-852b-b63eae516dd8.png)

In insiders I am switching language without any problem as long as I am on the right kernel provider 
![image](https://user-images.githubusercontent.com/375556/114610478-ddcb1200-9c97-11eb-991a-5ef508ff3f28.png)

**Comment by jonsequitur** [comment]
The default kernel a command line parameter specified in the kernel.json for a given kernel. We drop three of them, one each for PowerShell, C#, and F#, so if `dotnet interactive` is launched with a `--default-kernel` option, then you know it was launched as a Jupyter kernel. To be clear, this is not our expected behavior in VS Code. It looks like it might be related to #1189. So if the command line you captured goes along with the screen shots, VS Code launched under Jupyter and language switching within the notebook may not work correctly.

**Comment by dfinke** [comment]
I have one machine, has VS Code, VS Code insiders, Azure Data Studio, Azure Data Studio insiders, and the anaconda install for Jupyter, Python etc. 

I was seeing the wonky language issue with cells. The `Notebook: Select Notebook Kernel` worked, although I had thought I was setting that by clicking on the VS Code taskbar and changing the kernel there, may have been a VS Code vs insiders thing.

@jhoneill what process did you set `$p` to get that command line info? Several `code` processes start for me. Tried it on `jupyter` after I launched that but did not see that dotnet info. Thanks.

`Get-CimInstance -ClassName win32_process -Filter "processID = $($p.id)" | select -expand commandline`

**Comment by jhoneill** [comment]
@dfinke  
Sorry fingers going faster than brain when I pasted. The whole thing is 
```powershell
#!pwsh
$pshome
$p = Get-process -id $pid   
$p, $p.Parent, $p.Parent.Parent,$p.Parent.Parent.parent,$p.Parent.Parent.parent.parent
Get-CimInstance -ClassName win32_process -Filter "processID = $($p.id)" |  select -expand commandline
Get-CimInstance -ClassName win32_process -Filter "processID = $($p.Parent.id)" |  select -expand commandline
Get-CimInstance -ClassName win32_process -Filter "processID = $($p.Parent.parent.id)" |  select -expand commandline
Get-CimInstance -ClassName win32_process -Filter "processID = $($p.Parent.parent.parent.id)" |  select -expand commandline
Get-CimInstance -ClassName win32_process -Filter "processID = $($p.Parent.parent.parent.parent.id)" |  select -expand commandline
```
The output is 
```
 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
    182   311.59     325.31       5.92   34192   1 dotnet-interactive
     21    11.54      23.05       0.39   13612   1 dotnet
     78    84.69      87.78       9.89   31108   1 Code - Insiders
     34   178.89     181.13      69.58   30032   1 Code - Insiders
     40    54.00      78.54      18.42   20188   1 Code - Insiders
"C:\Users\xxxxxx\.dotnet\tools\dotnet-interactive.exe" jupyter --default-kernel csharp C:\Users\xxx~1\AppData\Local\Temp\tmp-311089zVT7p0ij0My.json 
dotnet interactive jupyter --default-kernel csharp C:\Users\xxx~1\AppData\Local\Temp\tmp-311089zVT7p0ij0My.json
"C:\Users\xxxxxxx\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" --inspect-port=0   etc. et.c
```
Notice it's gone back to  ` --default-kernel csharp`

@colombod 
![image](https://user-images.githubusercontent.com/16209593/114619701-bded1b80-9ca2-11eb-9346-c5f32bf5c674.png)

Which gives me a clue 
If I change it to the last one  This disappears 
![image](https://user-images.githubusercontent.com/16209593/114621320-79627f80-9ca4-11eb-8afc-cb1e0355a344.png)

The language on the cell is respected and the two command lines become 
```
"C:\Program Files\dotnet\dotnet.exe" C:\Users\xxxxx\.nuget\packages\microsoft.dotnet-interactive\1.0.221202\tools/net5.0/any/Microsoft.DotNet.Interactive.App.dll [vscode] stdio --working-dir c:\Users\xxxx\Documents\AzDo\ --http-port 50111
dotnet tool run dotnet-interactive -- [vscode] stdio --working-dir c:\Users\xxxx\Documents\AzDo\ --http-port 50111
```

Every time I exit and restart vs code it reverts to the Jupyter version which would explain why I was getting the old version of .NET Interactive which was associated with the Jupyter Server and couldn't get `#!about` show anything current.  

If I start the server in anaconda and go to the browser I get these kernels 
![image](https://user-images.githubusercontent.com/16209593/114622148-816eef00-9ca5-11eb-8e71-0b2d8f4ab44f.png) 

Not quite the same set, and I get a third set in Az Data Studio. 

**Back at plotly** It needs to be added manually and downloaded for each session ? Is that expected to remain ?

**Comment by jonsequitur** [comment]
> Back at plotly It needs to be added manually and downloaded for each session ? Is that expected to remain ?

Yes. We want to make sure that other visualization libraries are all equally viable and to reduce our out-of-the-box dependency graph. We removed this once our extension mechanism was working correctly.

**Comment by colombod** [comment]
According to your screenshot the kernel provider to select is the last one
![image](https://user-images.githubusercontent.com/375556/114631796-3066f700-9cb5-11eb-9861-ee7ca76ac0ff.png)

All the other ones are using the jupyter server while the last one is the one from the .NET Interactive extension

**Comment by colombod** [comment]
The plotly extension for .NET Interactive with the Powershell support can be installed with the following `#r` command
![image](https://user-images.githubusercontent.com/375556/114631998-9a7f9c00-9cb5-11eb-9852-9c6a6d9986e8.png)

**Comment by jhoneill** [comment]
@colombod 

It works on one machine for me  on the other 
```
Error: C:\Program Files\dotnet\sdk\5.0.104\NuGet.targets(131,5): error : Failed to retrieve information about 'XPlot.Plotly.Interactive' from remote source 'https://powershell.myget.org/F/powershell-core-daily/FindPackagesById()?id='XPlot.Plotly.Interactive'&semVerLevel=2.0.0'. [C:\Users\mcp\AppData\Local\Temp\nuget\8804--277cd75b-df68-4928-9b27-b68d738cf5f7\Project.fsproj]
C:\Program Files\dotnet\sdk\5.0.104\NuGet.targets(131,5): error : Response status code does not indicate success: 404 (Not Found). [C:\Users\mcp\AppData\Local\Temp\nuget\8804--277cd75b-df68-4928-9b27-b68d738cf5f7\Project.fsproj]
```

It also needs to be reinstalled every session and re-added to paths.

**Comment by colombod** [comment]
Not sure but I think you have that path in some Nuget.Config. myget feeds are no longer supported and should be removed from your nuget sources. That is what is causing your code submission to fail.

Can you ensure your other machine doesn’t point to https://powershell.myget.org/F/powershell-core-daily/ ?

You are correct as the package needs to be reinstalled each session but after first success the package is in your local cache until a different version is loaded

**Comment by jhoneill** [comment]
@colombod  
I used  `dotnet nuget remove source powershell-daily`, and hey-presto that now works :-) **Thanks**.

Nuget each time is ugly, but until someone packages the plotly files in a different way it's OK as a work around.  I might look at that when I get the chance, but this was a rabbit hole I went down when a job someone is waiting for needed a notebook, and firing up notebooks on one machine led to one problem after another, there are way too many jobs on my stack to do that any time soon :-( 

I still don't know why the machine with anaconda and jupyter on it wants to default to the wrong kernel when VS-Code runs `.Net Interactive Create New Blank Notebook`  @jonsequitur  - should the code which creates a new notebook force the right Kernel ?  Knowing to select it is OK but I can see it causing issues for other people.

**Comment by jhoneill** [comment]
Btw if anyone wants a PowerShell module which wraps plotly with a nice DSL (well I think it's nice) and  a notebook with a stack of plotly examples in PowerShell (with and without the DSL)    plotly.psm1 and plotly.ipynb from here  https://github.com/jhoneill/Notebooks/tree/master/notebooks   - there's other junk in that repo, which people are free to help themselves to. 

A VS code option, a Nuget block and 2 search and replace operations and this has gone from everything I had looking totally broken, to the most complicated thing I have working beautifully again. Thanks again to those who helped.

**Comment by colombod** [comment]
@jhoneill the dsl is pretty cool, would you mind have a look at the repo for [XPlot](https://github.com/fslaborg/XPlot) and see if that could be embedded as part of the package extensions for poweshell support? [Here](https://github.com/fslaborg/XPlot/tree/main/src/XPlot.Plotly.Interactive/Modules/XPlot.Plotly.Interactive) is where we inject the powershell support

**Comment by jhoneill** [comment]
@colombod  Thanks :-)  I'm fairly sure it is possible, but the little time I've spent on it says what needs to be done isn't something obvious which can be completed in 5 minutes. When I get chance for a longer look I'll see what is possible.

**Comment by jonsequitur** [comment]
> I still don't know why the machine with anaconda and jupyter on it wants to default to the wrong kernel when VS-Code runs .Net Interactive Create New Blank Notebook

This has to do with the complexities around sharing the `.ipynb` file extension between multiple VS Code notebook extensions, any combination of which might be present. Though #1189 refers to Python, you might be seeing the same problem. The PowerShell language selection in your screen shot is not .NET Interactive. If it were, it would say `PowerShell (.NET Interactive)`. But it's not clear to me whether this was actually routed to .NET Interactive anyway. Do you have another PowerShell Jupyter kernel installed by any chance?

![image](https://user-images.githubusercontent.com/547415/114723945-f2d38f80-9cef-11eb-9ade-c766031d2bdd.png)

**Comment by jhoneill** [comment]
> 
> This has to do with the complexities around sharing the `.ipynb` file extension between multiple VS Code notebook extensions, any combination of which might be present. Though #1189 refers to Python, you might be seeing the same problem. The PowerShell language selection in your screen shot is not .NET Interactive. If it were, it would say `PowerShell (.NET Interactive)`. But it's not clear to me whether this was actually routed to .NET Interactive anyway. Do you have another PowerShell Jupyter kernel installed by any chance?

That makes sense,  among the screen shots above is one from the Jupyter where I have "PowerShell"  and ".NET (PowerShell)" - which I think was installed by Azure Data Studio. 

I'm just thinking that "New .Net interactive Notebook" should have an implicit "Set kernel" if that's possible. It also *seems to* revert to the other kernel on closing and re-opening the IPYNB file.

**Comment by colombod** [comment]
Is this particular issue resolved? I like the proposals in the discussion but might be worth opening a separate feature request / discussion. Might be easier to track that way

**Comment by DBremen** [comment]
Hi @colombod , it's resolved for me. Thanks, everyone for your input.

**Comment by jhoneill** [comment]
Just a nod that I'm fine with closing it. I think I've created two diversions which should be items in their own right. Sorry for that.

**Comment by colombod** [comment]
I would not call then diversions, they are interesting takes and feature improvements! Thank you for the contributions to the project. I would love to see more work that makes extension and api even more tuned into the kernel language consuming it. That will make the user experience incredibly better.
