### ISSUE TITLE
[EXTERNAL] Run Cell and Below button does not work with F# interactive

### ISSUE THREAD

**Issue by nhirschey** [dotnet/interactive#1234]
### Describe the bug
Create a new file .net interactive notebook called test.ipynb. Try to use the "Run cell and below" or "Run cell and above" buttons. You get errors about ipython. However, if I create a powershell cell, the buttons work.

![image](https://user-images.githubusercontent.com/5226115/114279225-81fc5100-9a2b-11eb-8811-5b35edf29ee5.png)

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

![image](https://user-images.githubusercontent.com/5226115/114279269-b07a2c00-9a2b-11eb-883e-8557b86138e0.png)

- OS
    - [ X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ X] Visual Studio Code Insiders
    - [ ] Other (please specify)

**Comment by colombod** [comment]
cc @brettfo

**Comment by brettfo** [comment]
The error messages in the cells show that the Python kernel is being used to execute the cells and not .NET Interactive.  The Python kernel is overly-aggressive in setting its own kernel (see #1189), but if you select .NET Interactive in the bottom right then you'll get the proper kernel execution.

**Comment by nhirschey** [comment]
Hi @brettfo , which "bottom right" for selecting the kernel? In my screenshot I show that had the f# interactive kernel selected for the cell.

I'm trying to reproduce it for you, but .NET interactive updated to a new version and now I cannot get any of the buttons in test.ipynb execute any code. However, if I save the same file as a test.dib file and open the .dib file it works. I tried changing folders, uninstalling jupyter and .net interactive extensions and reinstalling, etc.

**Comment by nhirschey** [comment]
I should also clarify that when I had this issue Saturday, the big arrow on the left of the cell to run that specific cell with the F# kernel worked fine. The precise issue was the "Run cell above" and "Run cell below" buttons tried to use the python kernel.

**Comment by brettfo** [comment]
@nhirschey I suspect your VS Code looks similar to this:

![image](https://user-images.githubusercontent.com/926281/114447087-d831d700-9b86-11eb-91bc-5707a279a910.png)

In this example, the cell's language is set correctly to F#, but the notebook kernel in the bottom right of the window is what's still set to Python.  Click on the red circle then select ".NET Interactive" from the dropdown:

![image](https://user-images.githubusercontent.com/926281/114447236-031c2b00-9b87-11eb-90de-06a05016113c.png)

**Comment by nhirschey** [comment]
Thanks for the tip (My earlier problem today was because I disabled the Python extension. I enabled that and am now able to reproduce my issue from the weekend). 

See this screenshot, I seem to have every kernel selected correctly at the bottom left. The button on the left of the cell works (see 2nd cell). But the first cell tries the python kernel when I click the "run cell and below" button on the right of the cell.

![image](https://user-images.githubusercontent.com/5226115/114448840-f79f2300-9bcb-11eb-8b0d-60215da44d56.png)

**Comment by brettfo** [comment]
That cell is still trying to execute with the Python kernel.  Did you re-run that cell?  If not that may be stale output from the previous attempt, but with the kernel selected on the bottom right of the window and the language set at the bottom right of the cell, the execute command should be sent to .NET Interactive and not Python anymore.

**Comment by nhirschey** [comment]
It's not stale. I can clear the cell and run the cell with the button on the left of the cell. But if then clear it again and run it with the button on the right-side of the cell, it will try to use the python kernel.

**Comment by nhirschey** [comment]
Perhaps this helps? When I do `>view reopen editor with` I only see 
- Text editor
- Jupyter Notebook (custom)
- Jupyter Notebook (preview)

However, I do not see the .NET interactive for Jupyter versions seen in these screen shots at this issue comment https://github.com/dotnet/interactive/issues/1188#issuecomment-806945421

This is despite being able to switch between .NET and Python kernels at the bottom right of the VS Code window. 

Version: 1.56.0-insider (user setup)
Commit: 01466cf692c3e54f0eeb82ef0539a42391f185de
Date: 2021-04-12T05:17:32.143Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

I have the .NET interactive, jupyter, and python extensions installed.

**Comment by brettfo** [comment]
Can you "open with..." "Jupyter Notebook (preview)"?  We recently updated our Insiders extension to use the Jupyter extension, but it depends on the preview editor; I'm wondering if that notebook was opened with the older Jupyter editor that always assumes Python.

**Comment by nhirschey** [comment]
Thanks for the help. This is a quite frustrating debug. 

1. I just now created a new notebook using the command pallette. The kernel defaulted to c#. I changed it to F#. The kernel at the kernel at the bottom right of the window says .net interactive.
2. I entered
```fsharp
#r "nuget: FSharp.Data"
open System
```

I ran the cell using the left button. It worked. But when I try the buttons on the right of the cell, now nothing happens. It doesn't run the python kernel, but it also doesn't run the F# kernel.

**Comment by brettfo** [comment]
Thanks for helping us figure this out.  It appears that the issue is the Jupyter extension (which we're using to handle notebook reading/writing and is using us for execution) isn't properly calling into us when you click the run above/below buttons (but it _is_ working when each cell is directly executed.)

I've filed issue microsoft/vscode-jupyter#5497 against the Jupyter extension to track this.

Re-opening for visibility with external flags set.
