### ISSUE TITLE
Hot key for Clear Cell Output does not work

### ISSUE THREAD

**Issue by Keboo** [dotnet/interactive#1236]
### Describe the bug
I have a C# code cell with some output that was written to standard out.
The tooltip for the button shows that Alt+Delete is the hotkey, however when I press Alt+Delete the cell output is not cleared.
Clicking the button does in fact clear the output.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* v1.0.2210011
.NET Interactive Notebooks for VS Code. Git SHA 06ac1da7d95da4306e81624ddea927e64ffb98f4

Version: 1.56.0-insider (user setup)
Commit: 5904b7b686e9274631893d560fdbc55a5567f878
Date: 2021-04-08T17:51:28.503Z (2 days ago)
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

### Screenshots
![ClearCellOutput](https://user-images.githubusercontent.com/952248/114293325-01991880-9a4a-11eb-80df-6acbcabca26b.gif)
NB: Keyboard input shown using Carnac

**Comment by colombod** [comment]
What version of the jupyter extension do you have? I just run the `ALT+DELETE` shortcut and worked, this is the configuration:
Version: 1.56.0-insider (user setup)
Commit: 845efe5d8e31079cc858131c95c36103d9439e74
Date: 2021-04-09T09:50:06.816Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

.NET Interactive (ms-dotnettools.dotnet-interactive-vscode) : v1.0.2210011

Jupyter (ms-toolsai.jupyter) : v2021.6.732501275

**Comment by colombod** [comment]
Actually I was able to reproduce it. The shortcut doesn't work if you select just the input cell. @rebornix

**Comment by DonJayamanne** [comment]
@colombod The keyboard shortcut functionality is provided by VS Code.
To my knowledge this keybaord shortcut works only when the cell is in focus & not the editor in the cell (i.e. in command mode)
As you can have keyboard shortcuts that maps to editor fucntionality such as commending code.

**Comment by colombod** [comment]
@DonJayamanne thank you for the additional info. @rebornix Will open this in vscode then
