### ISSUE TITLE
Unable to run .Net interactive kernels on Azure Machine Learning Notebooks

### ISSUE THREAD

**Issue by YnnamTenob** [dotnet/interactive#1242]
I am unble to run the dotnet interactive kernels in any remote editor or on the AML notebooks with the exception of VS Code when running a local Jupyter Server. When a .Net kernel is selected for a notebook it eventually comes back with the error "_**Kernel not found or was deleted. Your state may be lost. Please select a kernel and re-run cells to connect**_". Using VS Code remotely I was able to generate some output that might be useful in troubleshooting this. I am attaching four files which are the outputs of the jupyter console in VSCODE. 

1. [Switching to Remote Jupyter Server](https://github.com/dotnet/interactive/files/6306716/SWITCHTOREMOTE.txt)
2. [Switching to Local Jupyter Server](https://github.com/dotnet/interactive/files/6306715/SWITCHTOLOCAL.txt)
3. [Execute a cell on the Remote Server](https://github.com/dotnet/interactive/files/6306714/EXECUTECELLAFTERSWITCHTOREMOTE.txt)
4. [Execute a cell on the Local Server](https://github.com/dotnet/interactive/files/6306713/EXECUTECELLAFTERSWITCHINGTOLOCAL.txt)

The compute node that Jupyter runs on is:
 
Azure Compute Node:

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64

Installation steps I followed on compute node:
 ## 1. Check the installed frameworks 
```bash
dotnet --info
```
## 2. Install or update sdk and aspnetcore runtime as needed
```bash
wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-5.0
```
## 3. Re-check installed framweworks
```bash
dotnet --info
```
## 4. install the dotnet interactive tool
```bash
dotnet tool install -g --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" Microsoft.dotnet-interactive
```
## 5. check dotnet interactive installed
```bash
dotnet tool list -g 
```
## 6. check the installed kernels
```bash
jupyter kernelspec list
```
## 7. install the dotnet interactive kernels on jupyter
```bash
dotnet interactive jupyter install 
```
## 8 re check the installed kernels
```bash
jupyter kernelspec list
```

**Comment by jonsequitur** [comment]
What output did you get on steps 3, 5, and 8?

**Comment by luisquintanilla** [comment]
@YnnamTenob you might want to checkout this guide. It's using .NET Core 3.1, but not much should change other than switching to .NET 5. I think the step you're missing is adding .NET global tools directory to your path. 

https://www.luisquintanilla.me/posts/dotnet-jupyter-notebooks-azure-machine-learning-compute-instance.html

Snippet from that blog explaining why this step is needed. You can get more details there.

> The Jupyter Notebook server is managed by a systemd service. Although during installation .NET Interactive is added to your PATH environment variable, it's not added to the environment file /etc/environment which is used by systemd. Therefore, in order to run .NET Interactive, you have to add the .NET global tools directory to that file.

**Comment by YnnamTenob** [comment]
Hi Luis my path already has /home/azure/.dotnet/tools in it

/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/bin:/anaconda/envs/azureml_py38/bin:/anaconda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin:/home/azureuser/.dotnet/tools

**Comment by YnnamTenob** [comment]
Hi @jonsequitur 

step 3
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  3.1.407 [/usr/share/dotnet/sdk]
  5.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
azureuser@cpu-ds3-v2-2-tenob-m:/etc$ 

step 5

Package Id                        Version         Commands          
--------------------------------------------------------------------
microsoft.dotnet-interactive      1.0.221001      dotnet-interactive

step 8

Available kernels:
  .net-csharp         /home/azureuser/.local/share/jupyter/kernels/.net-csharp
  .net-fsharp         /home/azureuser/.local/share/jupyter/kernels/.net-fsharp
  .net-powershell     /home/azureuser/.local/share/jupyter/kernels/.net-powershell
  python3             /anaconda/envs/azureml_py38/share/jupyter/kernels/python3
  ir                  /usr/local/share/jupyter/kernels/ir
  python3-azureml     /usr/local/share/jupyter/kernels/python3-azureml
  python38-azureml    /usr/local/share/jupyter/kernels/python38-azureml

**Comment by lqdev** [comment]
@YnnamTenob does the `/etc/environment` file have it in the `PATH` variable though? If not, add it there and restart the Jupyter service.

```bash
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/azureuser/.dotnet/tools"
``` 

```bash
sudo service jupyter restart
```

**Comment by YnnamTenob** [comment]
got it @lqdev Eureka. I got the wrong PATH. How silly of me. Thank you. Can we all say confusing or at least not consistant.  Thnaks again.

**Comment by YnnamTenob** [comment]
Note: Editing and running .Net interactive kernels via Jupyter Lab and the VS Code remote jupyter server works well. The native AML Notebooks environment hangs and the cells stay *_Queued_ .

**Comment by luisquintanilla** [comment]
@YnnamTenob Great! Glad to hear you got it working 😄

**Comment by jonsequitur** [comment]
Thanks for helping out here @lqdev! (Or should I call you @luisquintanilla?) 😄
