### ISSUE TITLE
Custom CommandEvent runnable with Keyboard Shortcut

### ISSUE THREAD

**Issue by PawelStadnicki** [dotnet/interactive#1245]
My solution has following requirement that I think is not possible to fulfill right now:
- run/execute notebook cell normally on first occasion that displays the (html) output
- no output update on second and later execution: this should only notify the kernel extension to "recompile" the code but update the current display under the cover, for example with HMR/webpack

What I know VS Code will clear entire output on every cell execution which I haveto avoid : I don't want re-render my html, it will be updated by HMR. Maybe some overriding of keyboard shorcut could send special command to my kernel extension ?

**Comment by brettfo** [comment]
The interaction model with VS Code notebooks is to clear the outputs on every cell evaluation.
