### ISSUE TITLE
#i "nuget:some invalid path" poisons the resolve

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/interactive#1249]
#i "nuget:some invalid path" poisons the resolve

Originaly the script had #i "c:\temp1", once the script had been fixed subsequent submits still fail.

![image](https://user-images.githubusercontent.com/5175830/114828987-61abf980-9d7f-11eb-9980-9f824e5e7228.png)

**Comment by dburriss** [comment]
This seems to be true for nuget references too `#r`.
I typo'd a nugget package and had to close and reopen VS Code to get it to load correctly.

**Comment by jonsequitur** [comment]
@dburriss, if you get stuck you can also restart the kernel, so you don't have to close VS Code. From the command pallet, select `.NET Interactive: Restart the current notebook's kernel`.
