### ISSUE TITLE
could not find jupiter kernelspec module

### ISSUE THREAD

**Issue by HansUrschel** [dotnet/interactive#125]
I tred to install jupyter notebook. I started Anaconda prompt. At the prompt i wrote: dotnet tool install -g dotnet-try. with success. I wrote: dotnet try jupyter install and i got this error message:
.NET kernel installation failed with error: Could not find jupyter kernelspec module.
My .Net Core SDK is 3.1.101.

**Comment by HansUrschel** [comment]
I use dotnet-try version 1.0.19553.4

**Comment by HansUrschel** [comment]
Now i tried dotnet-interactive. this is what i done.
1.) i started anaconda prompt an wrote: jupyper kernelspec list and i got
Available kernels:
  python3    C:\Anaconda3\share\jupyter\kernels\python3
2.) now i install interactive and got a success-message. version 1.0.110520 successfull installed
3.) IIn anaconda-prompt i wrote: dotnet interactive jupyter install and i got the same error
(base) C:\Users\xxxxx>dotnet interactive  jupyter install
.NET kernel installation failed with error: Could not find jupyter kernelspec module
.NET kernel installation failed with error: Could not find jupyter kernelspec module
.NET kernel installation failed with error: Could not find jupyter kernelspec module

**Comment by colombod** [comment]
@HansUrschel we have changed the name if the tool, could you please install it using the following command

```
dotnet tool install -g --add-source "https://dotnet.myget.org/F/dotnet-try/api/v3/index.json" Microsoft.dotnet-interactive
```

Then from the anaconda prompt

```
dotnet interactive jupyter install
```
