### ISSUE TITLE
A Discord server instead of the gitter one?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/interactive#1250]
My idea is to move the chat to a Discord server. A lot more people use it than gitter, it might result in more users and contributors.

There are two ways of moving to it.
1. Moving to an existing .NET server, for example, CSharp or DotNetEvolution. But then we will only have one channel, not too far from what we have now.
2. Creating a dedicated server for it. In my opinion, it's the best solution. Then we can have multiple channels (`support`, `contributing`, `general`, etc.), custom role management (`maintainer`, `contributor`, or something like this), and the invite link would lead specifically to it, not to a general .NET or C# server.

So, what do you think?

**Comment by colombod** [comment]
I am not familiar with Discord but you proposal number 2 sounds very cool

**Comment by WhiteBlackGoose** [comment]
I can explain more, if you want

**Comment by vzarytovskii** [comment]
> I am not familiar with Discord but you proposal number 2 sounds very cool

Think of Discord as hosted IRC with bells and whistles.

**Comment by jonsequitur** [comment]
Here's the invite link: https://discord.gg/3pvut9YujN
