### ISSUE TITLE
Printing nested objects should be similar to printing JSON

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/interactive#1257]
That's what we have for nested dictionaries now.
![image](https://user-images.githubusercontent.com/31178401/114974020-4843a400-9e8a-11eb-9312-0ca3f1641c9b.png)

Imho it should have a tree format, not a table. Similar to #1233.

**Comment by jonsequitur** [comment]
Simple, common objects are also very hard to read when rendered using the nested plain text formatter:

<img width="916" alt="image" src="https://user-images.githubusercontent.com/547415/182661512-f9807759-bec3-40d9-a3d4-c96ac28236a9.png">

**Comment by jonsequitur** [comment]
Changes to the plain text format (merged) and styling (in PR #2610) yields the following, which is an improvement. But we're still planning to do the expanding treeview-style view soon.

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/547415/211691881-e2fcb290-f079-49cd-8ace-fb653233e5b2.png">
