### ISSUE TITLE
Exiting Jupyter Console with F# Kernel

### ISSUE THREAD

**Issue by zachwaite** [dotnet/interactive#1259]
### Describe the bug
Please provide as much information as you can.

I've encountered a few challenges exiting the jupyter console when using the F# kernel.

1. The `#quit` command is the normal way to exit the FSI repl, but sending it through a Jupyter console causes the .NET interactive kernel to respond as "busy" forever. In Jupyter Lab, I can use the menu items to recover by interrupting or shutting down the kernel, but I suspect "busy" forever is not the desired behavior.
2. Exiting from the command line with `jupyter console --kernel=.net-fsharp` isn't very easy to do right. `CTL-D` prints a message "Shutting down kernel", but does not shut down the dotnet interactive processes. To completely exit in this case, I need to send `#quit`, which never returns, then `CTL-C` to interrupt the console, then `CTL-D` to exit the console. 

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.

.NET Interactive version = 1.0.221301+e8ec238deebb902ad7e5d45df000d08ca7add349

- OS
    - [ ] Windows 10
    - [ ] macOS
    - [x] Linux (Ubuntu 18)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [x] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [x] Other (jupyter console cli)

### Screenshots

Fig.1 Jupyter Lab Console Busy Forever
![image](https://user-images.githubusercontent.com/6884125/115035823-f6efe080-9e9a-11eb-81f3-37b670a6a909.png)

Fig.2 Jupyter Console CLI - Hanging Processes

![image](https://user-images.githubusercontent.com/6884125/115035626-c1e38e00-9e9a-11eb-966a-21ae27fdb931.png)

**Comment by jonsequitur** [comment]
What `#quit` doing, I think, is shutting down your FSI session (which is in-process), but .NET Interactive is unaware this has happened and is still waiting for a response. Not ideal, I know. Shutting down the whole `dotnet-interactive` process from within the F# subkernel seems like it might not always be desirable either, especially if `dotnet-interactive` is cloud-hosted. Out of curiosity, would restarting just the subkernel have solved your issue?

The way we've been thinking about this so far is that the hosting application (in this case, Jupyter Lab and Jupyter Console) owns the process. They started it and they should be responsible for shutting it down or restarting it. So for the moment, if you want a clean shutdown, you can do it via the controls those hosts provide.

**Comment by brettfo** [comment]
There have been some changes around exiting/shutdown and should have shipped in the previous release.
