### ISSUE TITLE
Ipynb corruption when moving PowerShell notebook from jupyter to VSCode and Back

### ISSUE THREAD

**Issue by jhoneill** [dotnet/interactive#1261]
###  If an IPYNB file saved in Jupyter is opened and saved in VSCode, it will no longer work in Jupyter. 

To see this 
*  In Jupyter's web UI create click New and choose .Net (PowerShell) 
*  Create a notebook with one code cell., with one line $PSVersionTable. Execute it and save the notebook. 

The Key parts of the JSON will look like this 
```json
{
 "cells": [
    {"cell_type": "code",   "execution_count": 1,   "metadata": {},
     "source": ["$psversionTable"  ],
     "outputs": [
       { "name": "stdout",  "output_type": "stream","text": [
          "\n",
          "Name                           Value\n",
          "----                           -----\n",
          "PSVersion                      7.1.3\n",

          "WSManStackVersion              3.0\n",
          "\n"
 ]}]}],
 "metadata": {
  "kernelspec": {"display_name": ".NET (PowerShell)", "language": "PowerShell","name": ".net-powershell" },
  "language_info": {"file_extension": ".ps1",   "mimetype": "text/x-powershell",   "name": "PowerShell",
                    "pygments_lexer": "powershell",   "version": "7.0"  }
 }, "nbformat": 4,  "nbformat_minor": 4
}
```
* Opened in VS Code it looks like this     
![image](https://user-images.githubusercontent.com/16209593/115060161-73a4ae00-9edf-11eb-9da9-32f78ffffbb6.png)

* After executing the code it looks like this    
![image](https://user-images.githubusercontent.com/16209593/115060301-99ca4e00-9edf-11eb-9b9a-ee1ef66bdbfd.png)    
It's doubled spaced and  in the JSON `outputs` has changed
```json
"outputs": [
    {"data": {"text/plain": "\r\n"                                    }, "output_type": "unknown"},
    {"data": {"text/plain": "Name                           Value\r\n"}, "output_type": "unknown"},
    {"data": {"text/plain": "----                           -----\r\n"}, "output_type": "unknown"},
    {"data": {"text/plain": "PSVersion                      7.1.3\r\n"}, "output_type": "unknown"},

    {"data": {"text/plain": "WSManStackVersion              3.0\r\n"  },  "output_type": "unknown"},
    {"data": {"text/plain": "\r\n"                                    },  "output_type": "unknown"
    }
]
```
And so has the Kernel spec 
```json
"kernelspec": {"display_name": ".NET (C#)",  "language": "C#","name": ".net-csharp" }
```
The `KernelSpec` change means the notebook has changed language when it reopens in Jupyter,    
![image](https://user-images.githubusercontent.com/16209593/115061882-9c2da780-9ee1-11eb-9709-01043fbb8123.png)

Worse, the `outputs` section` can't be processed... 
![image](https://user-images.githubusercontent.com/16209593/115061522-30e3d580-9ee1-11eb-8bbe-aa474a540059.png)

![image](https://user-images.githubusercontent.com/16209593/115062109-e31b9d00-9ee1-11eb-9bbf-701cba99513d.png)

**Which version of .NET Interactive are you using?**  `1.0.221202` 

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [x] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [x] Visual Studio Code Insiders
    - [ ] Other (please specify)

**Comment by brettfo** [comment]
We've switched how the output items are generated and this _should_ be fixed.  Can you give it a shot again?
