### ISSUE TITLE
Make nuget package acquirer SDK-independent

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/interactive#1263]
Using an embedded interactive package is a great feature. However, to enjoy it fully, you might want to enable NuGet package installation for it, *which requires SDK installed*.

The idea is to ship this NuGet package installer with embedded interactive packages.

**Comment by jonsequitur** [comment]
@KevinRansom 👀

**Comment by brettfo** [comment]
This would be a better fit in the (`dotnet/fsharp`)[https://github.com/dotnet/fsharp] repo because that's where the NuGet package resolution code is implemented.
