### ISSUE TITLE
Unable to use .NET Interactive in VSCode Insiders

### ISSUE THREAD

**Issue by vritant24** [dotnet/interactive#1265]
### Describe the bug
Cannot use .NET interactive in VSCode as I see the following error:
```
Error: Error executing cell: Error: command 'dotnet-sdk.acquireStatus' not found
```
This occurs for any language selected. This is thee first time I am using .NET Interactive and so I don't know if I'm missing an installation. I did install .NET 5 SDK on my machine and have the interactive extension installed.

### Please complete the following:
`1.0.221505+e29a5169b998976335b389d825d6a99a08d58654`

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [x] Visual Studio Code Insiders
    - [ ] Other (please specify)

![image](https://user-images.githubusercontent.com/13074644/115127655-0fd8be80-9f8d-11eb-9efe-e42053ff2ec0.png)

### Screenshots
![image](https://user-images.githubusercontent.com/13074644/115127515-e53a3600-9f8b-11eb-9296-08b4f727e73b.png)

**Comment by jonsequitur** [comment]
Have you tried VS Code stable? We'd recommend preferring stable for now. There are a number of breaking changes coming in the notebook APIs in Insiders and we can't always keep pace.

**Comment by vritant24** [comment]
Ah it looks like VSCode stable works fine. I'll continue using this on the stable version instead. Thanks :)
