### ISSUE TITLE
After loading existing notebook, all cells default to C# language

### ISSUE THREAD

**Issue by pkese** [dotnet/interactive#1266]
If I restart the kernel or load an existing notebook,  
all cells with F# code are marked as C# and won't run until I manually switch them back to F#.

I've tested this in vscode-insiders.

This is so annoying, that it practically renders the whole interactive concept useless.

**Comment by colombod** [comment]
Hi, we are tracking this issue (microsoft/vscode-jupyter#5477) as it is surfaced by the Jupyter file handling and not the .NET Interactive itself. We are actively working with the team to address this issues as soon as possible

**Comment by jhoneill** [comment]
> Hi, we are tracking this issue ([microsoft/vscode-jupyter#5477](https://github.com/microsoft/vscode-jupyter/issues/5477)) as it is surfaced by the Jupyter file handling and not the .NET Interactive itself. We are actively working with the team to address this issues as soon as possible

Unsurprisingly this also breaks PowerShell.. 
Lots of these messages 
![image](https://user-images.githubusercontent.com/16209593/115250407-71319680-a121-11eb-97af-8f574547b009.png)


Things might not be quite so bad if .NET Interactive in VS Code did not treat every  notebook as C# and then say every cell is an 
exception.

**Comment by gbaydin** [comment]
I have faced the same problem as well. I agree that this is a major problem affecting usability.

**Comment by jonsequitur** [comment]
We're trying to address this issue tactically in the short term via #1281. This is partly because while this issue is frustrating, we want to make the workaround apparent. 

The actual solution will take a bit longer for us to work through with the VS Code team and other teams building notebook experiences, which is why we spent time on the tactical bandage.

**Comment by jonsequitur** [comment]
(And even without #1281, the workaround is available. From the command pallet, select `View: Reopen editor with` and then `.NET Interactive for Jupyter`.

**Comment by jhoneill** [comment]
I think this is being mis-diagnosed. 

.Net Interactive can mix cells of multiple languages in a single notebook.  
Jupyter server cannot

Jupyter will create a notebook like this 

```
"cells": [
  {   "cell_type": "code",   "metadata": {}  }
],
"metadata": {
  "kernelspec": {   "display_name": ".NET (PowerShell)",   "language": "PowerShell",   "name": ".net-powershell"  },
  "language_info": {   "file_extension": ".ps1",   "mimetype": "text/x-powershell",   "name": "PowerShell"   }
```

When loaded in VS code this changes we get   
` {  "cell_type": "code",  "metadata": { "dotnet_interactive": {  "language": "pwsh"  }  }` 

And Kernelspec and language info are changed to C#.  

So you can't create an Ipynb file in Code and share it with someone using jupyter. And if you take a file from Jupyter and open it in code when you save it, it's VS Code only from then on. 

IIRC at one time VS-Code notebooks  put the language magic command at the start of every cell, so a notebook which wasn't 100% C# would work in other things which opened ipynb files. Now Vs-Code ipynb files are incompatible.

**Comment by jonsequitur** [comment]
In Jupyter, we support two ways of specifying a cell language: cell metadata and magics. Our VS Code extension writes the cell metadata and this gets passed on cell execution in Jupyter, so this should all work. This removes the need for the magic commands to designate a cell's language, but the magic command approach is also still available.

**Comment by jhoneill** [comment]
@jonsequitur But it does not work! 
A simple PowerShell cell 

![image](https://user-images.githubusercontent.com/16209593/116054434-8f444d00-a673-11eb-90c1-08afd09c349a.png)

Here's the json vscode writes
```
{ "cell_type": "code",    
  "metadata": {"dotnet_interactive": {"language": "pwsh"} },
  "outputs": [ ...  ],
  "source": [ "$psversionTable" ]   
}
```

The worst part is if he ipynb file came from Jupyter with *notebook* metadata specifying something else in `kernelspec` and `language_info`, the vs code extension re-writes it to c# even if there are no c# cells. Take it back to jupyter  it's a c# ,notebook and the PowerShell cells are broken    
![image](https://user-images.githubusercontent.com/16209593/116054649-ca468080-a673-11eb-8c38-901e46d0fa08.png)

From the POV of a Jupyter user who shares an IPYNB with a vscode user, **vscode corrupts existing ipynb files**

Notice also one object which outputs on *n*  lines outputs as *n* objects giving  double spacing in code and `out[1]` , `out[1]`, `out[1]` in Jupyter

**Comment by pkese** [comment]
### C#: all your cells are belong to us ;-)

**Comment by colombod** [comment]
Most of the extension was designed during a meeting in Mordor....

**Comment by jhoneill** [comment]
@colombod   - you're welcome, most of the time I'm seeing things from your side and saying "why can't people explain the problem properly"
