### ISSUE TITLE
Plain output in a list despite a preference

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/interactive#1273]
### Describe the bug
It might be expected behaviour, I'm not sure. But why despite the `html` preference for `MyType`, it still uses plain output in a list?

![image](https://user-images.githubusercontent.com/31178401/115303469-59333480-a16c-11eb-8d1d-85b6ee1c2d6f.png)

### Please complete the following:

**Which version of .NET Interactive are you using?** last `main`

- OS
    - [x] Windows 10
 - Browser 
    - [x] Opera
 - Frontend
    - [x] Jupyter Notebook

**Comment by jonsequitur** [comment]
This is because nested formatters use MIME type `"text/plain"`. This should work once  #1233 is merged.

**Comment by WhiteBlackGoose** [comment]
Right, so much dependent on that PR. Waiting for it to be merged!
