### ISSUE TITLE
Explore extension method doesn't work for entity framework context

### ISSUE THREAD

**Issue by elonmallin** [dotnet/interactive#1283]
### Describe the bug
After creating a EF context and querying the DB I get no ouput with the `Explore` function. I've followed this post: https://devblogs.microsoft.com/dotnet/net-interactive-with-sql-net-notebooks-in-visual-studio-code/ however I'm using my own DB.

So basically:
```
#!connect mssql --create-dbcontext --kernel-name myContextEF "Initial Catalog=somedb;Data Source=someserver;Integrated Security=True"
```
```
var qty = myContextEF.SomeTable.ToList();
qty; // Shows output
qty.Explore(); // Shows no output
```

Not sure what could be wrong?

### Please complete the following:

Version: 1.0.222003+fe53e060a771d7354e09e8e1ae38616fcc78f648
Build date: 2021-04-21T09:45:04.3754481Z

- OS
    - [x] Windows 10
 - Frontend
    - [x] Visual Studio Code

**Comment by colombod** [comment]
That is a bug but also we are deleting that gesture. The correct way is to use `.ExploreWithSandDance()` or `.ExploreWithNteract()` to obtain an explorer object.

Once you have it you can call `.Display()` on it for immediate rendering.

**Comment by elonmallin** [comment]
Thanks that works =)
