### ISSUE TITLE
Comment after "r" magic command causes unexpected behaviour

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/interactive#1288]
### Describe the bug
Let's consider installation of Plotly.NET:
```cs
#r "nuget: Plotly.NET.Interactive, *-*"
open Plotly.NET
let xData = [0. .. 10.]
let yData = [0. .. 10.]
let myFirstChart = Chart.Point(xData,yData)
myFirstChart
```
The output of the first magic command is
```
Installed package Plotly.NET.Interactive version 2.0.0-beta8
Loading extensions from Plotly.NET.Interactive.dll

Added Kernel Extension including formatters for GenericChart
```
<details><summary><strong>Screenshot</strong></summary>
<img src="https://user-images.githubusercontent.com/31178401/115667838-f77ef000-a34e-11eb-8d2a-fd9fccbe66df.png">
</details>

Now, let me add a comment right after the magic command and keep all other commands (restart beforehand):
```cs
#r "nuget: Plotly.NET.Interactive, *-*" // ducks best
open Plotly.NET
let xData = [0. .. 10.]
let yData = [0. .. 10.]
let myFirstChart = Chart.Point(xData,yData)
myFirstChart
```
Now, the package is **still installed**. But
1) It doesn't produce the log message (like "package installing...")
2) What's more important, it does not apply the kernel extension formatter.
<details><summary><strong>Screenshot</strong></summary>
<img src="https://user-images.githubusercontent.com/31178401/115668256-8ee44300-a34f-11eb-8c7e-2053b38d81fa.png">
</details>

**Which version of .NET Interactive are you using?**: 2021-04-20T18:25:10.9573324Z
- OS
    - [x] Windows 10
 - Browser 
    - [x] Opera
 - Frontend
    - [x] Jupyter Notebook

**Comment by brettfo** [comment]
Magic commands, including `#r`, etc., don't allow for inline comments.
