### ISSUE TITLE
Extension not working with VS Code insiders 1.56.0 2021-04-22 build 

### ISSUE THREAD

**Issue by jhoneill** [dotnet/interactive#1289]
On Today's VS Code    
![image](https://user-images.githubusercontent.com/16209593/115688615-357e1300-a353-11eb-83d1-d03b208b09c4.png)

With current extension (Rolling back to an earlier version of the extension doesn't help)
![image](https://user-images.githubusercontent.com/16209593/115688791-60686700-a353-11eb-9cb0-747b7c7f9288.png)

-----

1.  Press F1 and choose `NET Interactive: Open notebook` results in an error: the full text is `Command '.NET Interactive: Open notebook' resulted in an error (command 'dotnet-interactive.openNotebook' not found)`

2. Open a notebook  and the message appears on the status bar to say we are working via the Jupyter server  
![image](https://user-images.githubusercontent.com/16209593/115689007-94dc2300-a353-11eb-8c49-8e27cf87ae40.png)

3. Try to change Kernel - the list of kernels is
![image](https://user-images.githubusercontent.com/16209593/115689141-b63d0f00-a353-11eb-9cc6-3773721482e7.png)

    On another machine where VS code has not been updated I see the expected kernel - it was on this machine before VS code updated. 
![image](https://user-images.githubusercontent.com/16209593/115689311-dcfb4580-a353-11eb-9f2e-486421c49441.png)

**Comment by colombod** [comment]
We recommend to use VSCode stable as Insiders has a faster update cycle and the Notebook apis are quickly evolving. the PR #1286 is addressing this cycle of updates but there will likely e some more breaking changes happening in our build for VSCode Insiders

**Comment by colombod** [comment]
Those are cell languages, have you tried bringing up the kernel selection option using command palette (CTRL+SHIFT+P) ?
you should see an option like this 
![image](https://user-images.githubusercontent.com/375556/115718030-a680f300-a372-11eb-9642-797a631cbba8.png)

Then go ahead and you should see some options including .NET Interactive 
![image](https://user-images.githubusercontent.com/375556/115718140-c2849480-a372-11eb-8313-7f795423ae03.png)

**Comment by jhoneill** [comment]
@colombod   It's the select kernel list 

![image](https://user-images.githubusercontent.com/16209593/115757916-7b0fff80-a396-11eb-8d5b-63fee0d1c465.png)

if I click the cell language a selection box flashes and vanishes. 

> We recommend to use VSCode stable as Insiders  

Listen... Hear that...? it's the sound of my palm hitting my face over and over...   When did .NET interactive stop needing insiders ? :-) ?
