### ISSUE TITLE
Unable to open an ipynb when .NET interactive is installed

### ISSUE THREAD

**Issue by DonJayamanne** [dotnet/interactive#1291]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.

- OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots

**Fresh machine:**
* Install Jupyter extension
* Install .NET Interactive extension
* Open a Python ipynb, and i get an error message & the ipynb does not open.
![recording (1)](https://user-images.githubusercontent.com/1948812/115752523-082f6600-a34f-11eb-9b27-16b1adcf6ef2.gif)

**Comment by brettfo** [comment]
This is a combination of issues, specifically #1292 where a .NET SDK isn't installed (and we don't display a good message for that), and microsoft/vscode-jupyter#5477 which causes custom metadata to not be written to disk which led us to add our own custom .ipynb handler that confuses the VS Code file associations.

If #1292 is addressed and/or a .NET SDK is installed and a non-.NET notebook is opened with our extension, we'll tell the user that the notebook doesn't look like one of ours and should probably be re-opened.

**Comment by DonJayamanne** [comment]
Please feel free to close this issue if its a duplicate.
