### ISSUE TITLE
Extension should detect .NET is not installed and provide ability to install it

### ISSUE THREAD

**Issue by DonJayamanne** [dotnet/interactive#1292]
Install .NET Interactive extension on a new machine, I get errors  indicatinng the fact that .NET SDk is not installed.
I believe other .NET extensions download the SDK via the `.NET install Tool for Extension Authors`.

Work around - Installing the C# extension fixes this for me (as they provide the download experience).

I think this will improve the getting started experience (we too had similar issues in Jupyter, rather than throwing error messages its better to provide some guidance on what needs to be done - saving the user the trouble to figuring things out, e.g. `ok i got an error, now what`).

This would provide a better UX, else right now as a user i need to figure out how to install .NET core.
![Screen Shot 2021-04-22 at 09 45 18](https://user-images.githubusercontent.com/1948812/115753006-87bd3500-a34f-11eb-9cc7-5074415f0117.png)

**Comment by jonsequitur** [comment]
> I believe other .NET extensions download the SDK via the .NET install Tool for Extension Authors.

This extension installs the .NET runtime, not the SDK. We require the SDK and the SDK requires elevation to install, so we can't automate installation at this stage. 

But we should absolutely provide a message to the user to guide them to install the SDK.

**Comment by RandomFractals** [comment]
What if you installed .net runtime and added a prompt if a user would like to install .net sdk too.

I would probably do both if I were to use .net interactive notebooks with C# or F#.

**Comment by brettfo** [comment]
We now show a help markdown file if the proper SDK wasn't detected with an install link.
