### ISSUE TITLE
Unable to open an ipynb and use .NET interactive kernel in VS Code

### ISSUE THREAD

**Issue by DonJayamanne** [dotnet/interactive#1293]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.

- OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots

* Install VS Code Stable
* Install Jupyter & .NET Interactive
* Open ipynb (which has a C# jupyter kernel in medata) 
* I get a message from .NET extension suggesting i re-open this in .NET interactive.
![Screen Shot 2021-04-22 at 11 49 42](https://user-images.githubusercontent.com/1948812/115770078-17b7aa80-a361-11eb-852a-d89dffcffa9f.png)

**Comment by colombod** [comment]
if you click the button it re-opens with our handler for ipynb, if you close it (the X) it will keep using the editor from the jupyter extension

**Comment by DonJayamanne** [comment]
Thanks
