### ISSUE TITLE
v1.0.2226030 is no longer associated with IPYNB files

### ISSUE THREAD

**Issue by jhoneill** [dotnet/interactive#1306]
# with v1.0.**2226030**

![image](https://user-images.githubusercontent.com/16209593/116218622-a140f100-a742-11eb-9df8-47f35dd35267.png)    
`[F1]`  `.Net Interactive Open Notebook.` No `Ipynb` option
 
![image](https://user-images.githubusercontent.com/16209593/116218773-c5043700-a742-11eb-841d-68001403a554.png)    
Click click temp.ipynb, `Open-With...` no .net interactive option

# rolled back to v1.0.**2221020**
![image](https://user-images.githubusercontent.com/16209593/116219278-58d60300-a743-11eb-99fc-6eb93bdbe498.png)    
`[F1]` `.Net Interactive Open Notebook`   `Ipynb` option  *is* present

![image](https://user-images.githubusercontent.com/16209593/116219660-bf5b2100-a743-11eb-8677-11dede7d06a1.png)   
Click click temp.ipynb, `Open-With...` .net interactive option present

**Comment by brettfo** [comment]
Thanks for filing the issue, I've opened PR #1308 that addresses this.
