### ISSUE TITLE
[EXTERNAL] Opening an .ipynb doesn't always set the notebook controller.

### ISSUE THREAD

**Issue by brettfo** [dotnet/interactive#1315]
When a .ipynb notebook is opened that looks like our extension can handle, we tell VS Code to switch to our controller (executor/kernel) but in the latest insiders builds, that only prompts the user and doesn't necessarily do the actual selection.

Consider the following scenario with attached video:

https://user-images.githubusercontent.com/926281/116483633-4d1a3780-a83c-11eb-806c-8b36db520b1f.mp4

Scenario: I've been working with Python notebooks, but then open one of my .NET Interactive notebooks.  The following is what happens with timestamps:

- 0:02 - The .NET Interactive extension sees that this is one of ours and tells VS Code to set us as the controller (executor); UI is displayed confirming this, but the user doesn't notice or accidentally dismisses it.
- 0:04 - The Python executor is still selected from my last notebook session.
- 0:10 - The cell's language looks​ like it's fine.
- 0:14 - And sometimes I even get C# hover text.
- 0:17 - But when I click execute, Python starts to spin up.
- 0:20 - And I get errors that my code is invalid.

**Comment by rebornix** [comment]
@brettfo can you confirm if this is what you are still seeing?
