### ISSUE TITLE
Build with existing SDK

### ISSUE THREAD

**Issue by dhirschfeld** [dotnet/interactive#1321]
When I run `build.sh` it wants to download the `dotnet` SDK even though I have it already installed in my build environment.

Is there some way to prevent downloading the SDK / force the build to be with the existing `dotnet` SDK?

**Comment by jonsequitur** [comment]
If you set an environment variable `DisableArcade` to `1` and then clean your repo, you can use `dotnet build` normally and don't need the scripts.

**Comment by dhirschfeld** [comment]
Thanks - the below seems to do the job for me for installing the linux64/net5.0 version:
```bash
export DisableArcade=1

dotnet pack --configuration Release --runtime linux-x64 $SRC_DIR/src/dotnet-interactive/dotnet-interactive.csproj
dotnet tool install --framework net5.0 --add-source $SRC_DIR/src/dotnet-interactive/bin/Release --tool-path $DOTNET_TOOLS Microsoft.dotnet-interactive
```

...I'll close as answered!
