### ISSUE TITLE
Is dotnet interactive compatible with .net6 preview?

### ISSUE THREAD

**Issue by EverybodyKurts** [dotnet/interactive#1329]
**The package and version I'm asking about**: 

Running the `#!about` magic command results in the executing cell running without stopping. Running `dotnet interactive --version` results in the following:

```bash
$ dotnet interactive --version
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-interactive does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

I've installed the dotnet interactive exension via the vs code market place. The currently installed version is v1.0.2256021

### Question

Is dotnet interactive compatible with .net6 preview? I'm on an M1 Macbook so I have to use .net 6 preview.

**Comment by EverybodyKurts** [comment]
Any update this?

**Comment by jonsequitur** [comment]
Not yet. Keep an eye on #1482.
