### ISSUE TITLE
Add support for variable sharing within magic commands

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#1344]
Currently, magic commands don't allow providing arguments using variables defined in the kernel. An API for doing this would be very helpful. 

For example, in the Python kernel, you can do this:

```python
%magic $variable
```

Things to consider:

* How should a value be escaped when you want to pass a literal string that matches the variable expansion syntax, e.g. `#!magic "${variable}"`?
* How can the syntax support specifying the source kernel where the variable is declared, e.g. `#!magic ${fsharp:variable}`?
* How should the variable's value be stringified?
* Should object traversal be enabled, e.g.? `#!magic ${someObject.Property}`?
  * What about other expressions, e.g. `#!magic ${someObject.Things.Single()}`?  

I included the last top-level bullet for the sake of discussion, but I'm inclined not to support it because the tooling experience (code coloring, error squiggles, completions, etc.) becomes very complicated and potentially confusing across different languages.

**Comment by jonsequitur** [comment]
@LadyNaggaga @dsyme @tanhakabir We've discussed this a bit before so if you'd like to contribute to the discussion here, please do.

**Comment by SQLDBAWithABeard** [comment]
I would definitely be in favour of this. 

Potential use case I first thought of.

gather SQL instances from a database table or file with PowerShell using dbatools, create sql kernel connection dynamically to enable troubleshooting notebooks to be generic and passed to clients.

**Comment by jonsequitur** [comment]
Great use case! We have a few related issues under https://github.com/dotnet/interactive/labels/Area-Automation

**Comment by tanhakabir** [comment]
Hm quick thought:

> Should object traversal be enabled

I think this is quite important for my REST Book language since I save the entire response to one object/variable and have the user traverse in for the specific piece of information they want to use.

**Comment by yueyinqiu** [comment]
For anyone who is just finding a way to dynamically run a magic command, and does not mind to deal with stringifing the parameter and join the strings into a command, there is an alternative:

```csharp
using Microsoft.DotNet.Interactive;
using Microsoft.DotNet.Interactive.Commands;

var kernel = await Kernel.GetInputAsync("kernel-spec:");

var s = $"#!connect jupyter --kernel-name python --kernel-spec {kernel}";
await Kernel.Root.SendAsync(new SubmitCode(s));
```

**Comment by jonsequitur** [comment]
You can request input within a magic command using the following syntax:

```csharp
#!connect jupyter --kernel-name python --kernel-spec @input:kernelSpec
```

**Comment by jonsequitur** [comment]
This issue should have been closed as implemented a while back. The documentation about how to use shared variables within magic commands can be found here: 

https://github.com/dotnet/interactive/blob/main/docs/variable-sharing.md
