### ISSUE TITLE
���������� 

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/interactive#1345]
![image](https://user-images.githubusercontent.com/4510984/118302027-50891080-b516-11eb-9845-04c3f8c89f2c.png)

![image](https://user-images.githubusercontent.com/4510984/118302037-52eb6a80-b516-11eb-8977-2f2d6ef9c578.png)

![image](https://user-images.githubusercontent.com/4510984/118302043-541c9780-b516-11eb-95d1-fa05b2b62646.png)

**Comment by LadyNaggaga** [comment]
The package has successfully installed on machine
![image](https://user-images.githubusercontent.com/2546640/120366534-c2ff3c00-c2dd-11eb-8869-398fe4f72a2a.png)

@GF-Huang   can you please share the version you are using of .NET Interactive?  Enter `#!about` into a cell and run it?

**Comment by GF-Huang** [comment]
Latest of 18 days ago.
