### ISSUE TITLE
Anonymous type access modifier

### ISSUE THREAD

**Issue by Tolyandre** [dotnet/interactive#1349]
### Describe the bug
There is a different behaviour when running this code as a console app and as a dotnet script:
```c#
using System.Reflection;
using System;

Console.WriteLine(new {t=123}.GetType().IsPublic);
```
Console app: False
dotnet script: True

Is this intended that the access modifier of an anonymous type differs? This affects how Serilog handles anonymous types https://github.com/serilog/serilog-formatting-compact/issues/44

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
1.0.218103+b36733612287d9e8b3237e0120d8a5f19e28d836

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android

**Comment by jonsequitur** [comment]
Yes, this is intentional. The C# scripting variant works by creating an assembly for each code submission (e.g. notebook cell execution), so for anonymous types to be visible between submissions, they need to be public.

**Comment by Tolyandre** [comment]
Ok, thank you. Then we can close this
