### ISSUE TITLE
dotnet-interactive jupyter install should work without anaconda...

### ISSUE THREAD

**Issue by Jaykul** [dotnet/interactive#135]
### The problem
Currently the `dotnet interactive jupyter install` can only be run in an environment where Python with Jupyter is working. Why?

There are many implementations of the jupyter kernel.

Obviously you know about [nteract](https://nteract.io), since you've linked to in your article. It's not the only alternative implementation that does not need Python to be installed, nor the python jupyter.

Right now, if I have installed `Microsoft.dotnet-interactive` and `nteract` on a computer that doesn't have Python, all I have to do is copy the kernel.json files from another computer to make them work, so all we need is for the install command to work!

### The install command should have a default location

The "install" command should, if it can't find Juptyer, just install the kernels to the well-known default location that Jupyter (and nteract) uses. On Windows, that's `%AppData%\jupyter\kernels`

#### Alternatively
For Windows users, it would actually be really awesome if you packaged up nteract and the dotnet kernels with the dotnet runtime, and bundled them in an installer 😁 so we could download an actual desktop Windows app and get everything running.

**Comment by daxian-dbw** [comment]
@jonsequitur Is there a plan to improve the installation as suggested in this issue?
I think a more straightforward local installation can help the adoption of dotnet-interactive. If you think the work is relatively scoped, maybe we PowerShell team can help on this one 😄

**Comment by jonsequitur** [comment]
Absolutely agreed. Anaconda is not a requirement nor a dependency, it's just the simplest solution for most people to install Jupyter. The installer clearly needs to handle more cases.

@colombod and I had a discussion around what we might do here. A couple of ideas:

* If `jupyter kernelspec` is unavailable (whether not installed or not on the path), list a number of well-known paths as @Jaykul suggested and ask if we should install to those locations. (When available, `jupyter kernelspec install` which we currently use is the recommended and preferred approach.)
* Provide an option to specify the install location (e.g. `dotnet interactive jupyter install --location /path/to/kernelspecs`

Thoughts?

**Comment by daxian-dbw** [comment]
I like both ideas. When the `--location` flag is not specified, the installer by default leverages `jupyter kernelspec`, or list the well-known paths if the former is not available. When `--location` is specified, just simply install to the location.

**Comment by colombod** [comment]
PR #337 adds new behaviour for the install command
