### ISSUE TITLE
[EXTERNAL] Trusted Notebooks broken in Jupyter  Ext 

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/interactive#1354]
No action when you click on the trusted notebook icon.  See image below 

Jupyter Ext version - v2021.6.832593372
.NET interactive version - 1.0.225602+88e6d92f1cf8ead1c4c0b982e67b4a63902e00e6
![trust-notebook](https://user-images.githubusercontent.com/2546640/119137595-f7861480-ba0e-11eb-9ac7-954796bccb2b.gif)

Opened issue on VS Code -Jupyter repo: https://github.com/microsoft/vscode-jupyter/issues/5950

**Comment by colombod** [comment]
This is tracked with microsoft/vscode-jupyter#5546
