### ISSUE TITLE
PowerShell Notebook - Can't import Pester

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [dotnet/interactive#136]
#### Describe the bug
I tried to run one of my Azure Data Studio PowerShell notebooks into a PowerShell Notebook using .NET Jupyter. It worked fine until I tried to import my dbachecks module which uses Pester. I then created a new Notebook and tried to just run some Pester

The error I receive is 

````
Describe: The 'Describe' command was found in the module 'Pester', but the module could not be loaded. For more information, run 'Import-Module Pester'.
````

When I try to just import Pester by itself using any of my available versions even 3.4.0 I get

````
Get-Command: C:\Users\mrrob\Documents\PowerShell\Modules\pester\4.9.0\Pester.psm1
Line |
  94 |     $script:SafeCommands['Get-CimInstance'] = Get-Command -Name Get-CimInstance -Module CimCmdlets @safeCommandLookupParameters

     |                                               ^ The term 'Get-CimInstance' is not recognized as the name of a
     | cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
     | verify that the path is correct and try again.
Import-Module: The module to process 'Pester.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Users\mrrob\Documents\PowerShell\Modules\pester\4.9.0\pester.psd1' was not processed because no valid module was found in any module directory.
````

output of Get-Module Pester -ListAvailable

````
    Directory: C:\Users\mrrob\Documents\PowerShell\Modules
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     4.9.0                 Pester                              Desk      {Describe, Context, It, Should…}
Script     4.8.1                 Pester                              Desk      {Describe, Context, It, Should…}
    Directory: C:\Program Files\WindowsPowerShell\Modules
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     4.8.1                 Pester                              Desk      {Describe, Context, It, Should…}
Script     3.4.0                 Pester                              Desk      {Describe, Context, It, Should…}
````

#### Did this error occur while using `dotnet interactive`?
- [ X] .NET Jupyter Notebook 

#### Please complete the following:
 - OS
    - [X ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X ] Chrome
    - [ X] Edge
    - [ ] Safari
 - Frontend
    - [ ] Jupyter notebook
    - [X ] Jupyter lab
    - [ ] nteract

**Comment by SQLDBAWithABeard** [comment]
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# This is a new Notebook\n",
    "\n",
    "That has been written in .NET Interactive\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<pre></pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>Name                           Value</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>----                           -----</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>PSVersion                      7.0.0-rc.1</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>PSEdition                      Core</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>GitCommitId                    7.0.0-rc.1</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>OS                             Microsoft Windows 10.0.18362</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>Platform                       Win32NT</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>PSRemotingProtocolVersion      2.3</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>SerializationVersion           1.1.0.1</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>WSManStackVersion              3.0</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre></pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "$psversiontable"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<pre>Describe: The &#39;Describe&#39; command was found in the module &#39;Pester&#39;, but the module could not be loaded. For more information, run &#39;Import-Module Pester&#39;.</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "Describe \"Do things Exist\" {\n",
    "    Context \"Servers\" {\n",
    "        It \"The Server returns a ping - This will fail - Wrong Server Name\" {\n",
    "            (Test-Connection Exeter -Count 1 -Quiet -ErrorAction SilentlyContinue ) | Should Be $true\n",
    "        }\n",
    "        It \"The Server Bolton returns a ping\" {\n",
    "            (Test-Connection Bolton -Count 1 -Quiet -ErrorAction SilentlyContinue ) | Should Be $true\n",
    "        }\n",
    "        It \"Rob-XPS Operating System Version\" {\n",
    "            (Get-CimInstance -ClassName Win32_OperatingSystem).Version | Should Be '10.0.16299'\n",
    "        }\n",
    "    }\n",
    "}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<pre></pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre></pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>    Directory: C:\\Users\\mrrob\\Documents\\PowerShell\\Modules</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre></pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>ModuleType Version    PreRelease Name                                PSEdition ExportedCommands</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>---------- -------    ---------- ----                                --------- ----------------</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>Script     4.9.0                 Pester                              Desk      {Describe, Context, It, Should…}</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>Script     4.8.1                 Pester                              Desk      {Describe, Context, It, Should…}</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre></pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>    Directory: C:\\Program Files\\WindowsPowerShell\\Modules</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre></pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>ModuleType Version    PreRelease Name                                PSEdition ExportedCommands</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>---------- -------    ---------- ----                                --------- ----------------</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>Script     4.8.1                 Pester                              Desk      {Describe, Context, It, Should…}</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>Script     3.4.0                 Pester                              Desk      {Describe, Context, It, Should…}</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre></pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "Get-Module Pester -ListAvailable"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<pre>Get-Command: C:\\Users\\mrrob\\Documents\\PowerShell\\Modules\\pester\\4.9.0\\Pester.psm1\r\n",
       "Line |\r\n",
       "  94 |     $script:SafeCommands[&#39;Get-CimInstance&#39;] = Get-Command -Name Get-CimInstance -Module CimCmdlets @safeCommandLookupParameters\r\n",
       "\r\n",
       "     |                                               ^ The term &#39;Get-CimInstance&#39; is not recognized as the name of a\r\n",
       "     | cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,\r\n",
       "     | verify that the path is correct and try again.</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre>Import-Module: The module to process &#39;Pester.psm1&#39;, listed in field &#39;ModuleToProcess/RootModule&#39; of module manifest &#39;C:\\Users\\mrrob\\Documents\\PowerShell\\Modules\\pester\\4.9.0\\pester.psd1&#39; was not processed because no valid module was found in any module directory.</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "ipmo pester "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<pre>Import-Module: The term &#39;Get-CimInstance&#39; is not recognized as the name of a cmdlet, function, script file, or operable program.\r\n",
       "Check the spelling of the name, or if a path was included, verify that the path is correct and try again.</pre>\r\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "ipmo dbachecks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".NET (PowerShell)",
   "language": "PowerShell",
   "name": ".net-powershell"
  },
  "language_info": {
   "file_extension": ".ps1",
   "mimetype": "text/x-powershell",
   "name": "PowerShell",
   "pygments_lexer": "powershell",
   "version": "7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

**Comment by SQLDBAWithABeard** [comment]
The notebook can be seen 
https://gist.github.com/SQLDBAWithABeard/545b9c353c609ff5bb1bff4b6ccb57cd

**Comment by wsmelton** [comment]
This seems to be an issue with splatting in PowerShell when also providing named parameters:

![image](https://user-images.githubusercontent.com/11204251/74033640-3b6d1b80-497c-11ea-964e-a1e56a37f0c9.png)

**Comment by wsmelton** [comment]
A bit of a twist in how this is being done in the kernel, is likely going to be the issue:

![image](https://user-images.githubusercontent.com/11204251/74041668-b427a400-498b-11ea-9096-4bb597ebcc50.png)

**Comment by nohwnd** [comment]
@wsmelton I am seeing, I see it in your screenshot as well, do you have any fix for that?

```powershell
Import-Module: The module to process 'Pester.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest '...\Documents\PowerShell\Modules\pester\4.9.0\pester.psd1' was not processed because no valid module was found in any module directory.
```

**Comment by wsmelton** [comment]
I go by this, but then checking the Exported Commands and it is there:
![image](https://user-images.githubusercontent.com/11204251/74041964-48920680-498c-11ea-93ff-3a9dfa6f95ee.png)

![image](https://user-images.githubusercontent.com/11204251/74041994-547dc880-498c-11ea-93af-5f67c8e0d97a.png)

**Comment by wsmelton** [comment]
...but even changing the psm1 to this line of the module it still fails, so I think the implicit remoting is the issue:

```
$script:SafeCommands['Get-CimInstance'] = Get-Command -Name Get-CimInstance -Module CimCmdlets -CommandType Cmdlet -ErrorAction Stop -All
```

**Comment by wsmelton** [comment]
This is indeed the remoting issue because I just caught that the kernel is importing the Windows PowerShell version of the CimCmdlets module (note the version is `1.0.0.0` which is Windows release). The version matched to PowerShell 7 is version 7.0.0.0

![image](https://user-images.githubusercontent.com/11204251/74043093-63fe1100-498e-11ea-9147-0b7d6916e28e.png)

**Comment by daxian-dbw** [comment]
@wsmelton Thanks for reporting this! Yes, it was the CimCmdlets module from the system32 module path that got imported (via the `WinCompat` feature added in PS7). This is because currently the PS kernel don't ship all the built-in modules along with it ...
The built-in modules are not published anywhere and are platform specific, it's hard for an application that host powershell to ship them along. We have the issue https://github.com/PowerShell/PowerShell/issues/11783 to track this work.

**Comment by wsmelton** [comment]
@daxian-dbw maybe I'm missing something...

While it is true that not all modules are going to be shipped with PowerShell CIM cmdlets are not one of them, they are indeed shipped with the versions of PowerShell (both 6 and 7). You can find the DLL, `Microsoft.Management.Infrastructure.CimCmdlets.dll`, located in the root directory of each version of PowerShell:

![image](https://user-images.githubusercontent.com/11204251/74055477-ba2a7e80-49a5-11ea-867b-4a115d57dcff.png)

**Comment by daxian-dbw** [comment]
> While it is true that not all modules are going to be shipped with PowerShell, CIM cmdlets are not one of them, they are indeed shipped with the versions of PowerShell (both 6 and 7).

Yes, indeed.
What I meant is that not all built-in modules (literally the module folders) that come with PowerShell (6/7) out-of-box are currently shipped along with the PowerShell Jupyter kernel.

The following 7 modules are what the PowerShell Jupyter kernel currently ship, and we only have the `Utility` and `Management` built-in modules, no `CimCmdlets`.
We are working on get this fixed.

![image](https://user-images.githubusercontent.com/127450/74057191-3c13ab00-4998-11ea-9702-60c0b65b621a.png)

**Comment by SQLDBAWithABeard** [comment]
Of course it can be resolved by importing from the local PowerShell Core

**Comment by SQLDBAWithABeard** [comment]
That was a mistake that everyone at PowerShell Saturday Hamburg saw!!

Please re-open

**Comment by daxian-dbw** [comment]
@SQLDBAWithABeard The PR #189 brought in `CimCmdlets` and other built-in modules for the PowerShell kernel, so importing Pester should work fine now.
