### ISSUE TITLE
.NET Interactive as a network service

### ISSUE THREAD

**Issue by PawelStadnicki** [dotnet/interactive#1367]
I'm trying to set up any flavor of scalable .NET Interactive service on Azure based on the following: 
- dotnet interactive is listening on a server via cli: `dotnet interactive http --http-port 3000` as a separate hosting service
- js client is initiated to listen to that service using /resources/dotnet-interactive.js facilities

My problem is that this setup only works for me when both sides are on localhost and only on a **non-corporate** laptop (where I suspect antivirus or firewalls block websocket related traffic).

Elsewhere I'm getting messages similar to 
![image](https://user-images.githubusercontent.com/56049414/119771519-22181780-bebe-11eb-964c-761064a645e3.png)

My js code is based of @colombod great experimental repo, here is a sample:
![image](https://user-images.githubusercontent.com/56049414/119771759-791dec80-bebe-11eb-9dae-5fd1e084b8aa.png)

This error randomly shows on step 1 or 2 (marked in red). Only on localhost and non-corporate laptop codes goes to step 3.

What I know from twitter/github @idg10 has been involved with that JS implementation that is why I put him one the loop.

I tried to set up the dotnet interactive on Azure with numerous scenarios . 
I installed dotnet interactive on a separate Virtual Network, I tried to consume that service from App Service, I even tried to set up Application Gateway between them or use reversed proxy between IIS and DNI kestrel, 
with full or without https configuration. I don't have any issues with accessing dotnet-interactive.js file with any setup, the problem is only on (I believe) ongoing closing websocket (signalr) connection.

I'm lacking any further ideas not being expert to debug those hub websocket connections. I could further blindly read the DNI code but I hope you can help me based on your experience. You know how to setup codespace ( which is probably the same infrastructure in general that I want to achieve) and trydotnet applications.

Please kindly help me...

**Comment by colombod** [comment]
We are doing a lot of work on the proxy kernel feature and I think is worth keeping this scenario in mind to test what is going on. There is a bug you might be facing now related to new scheduling and submission parsing. If you could keep an eye on #1341 because we are doing work there that could simplify the situation. When this was working I used ngrok as https proxy to http on local host and @jonsequitur could just connect using signalR socket to my device and work with it.

**Comment by colombod** [comment]
Could this be related to address binding (see [this](https://stackoverflow.com/questions/22293445/http-503-service-is-unavailable-when-trying-to-browse-signalr-hubs/22972905#22972905))?
