### ISSUE TITLE
Submitting code from a C# cell using CSharpKernel.SubmitCodeAsync(string code) doesn't work properly

### ISSUE THREAD

**Issue by Lawlzee** [dotnet/interactive#1378]
### Describe the bug
When submitting code from a C# cell, dot net interactive cannot find the submitted code. On the other hand, the submitted code is available in the IntelliSense.

### Example
```
#!csharp

using Microsoft.DotNet.Interactive;
using Microsoft.DotNet.Interactive.CSharp;

CSharpKernel kernel  = (CSharpKernel)KernelInvocationContext.Current.HandlingKernel.FindKernel("csharp");
await kernel.SubmitCodeAsync("public class TestClass { public int A { get; set; } }");

#!csharp
//IntelliSense can see "TestClass", but dot net interactive can't
TestClass a = new TestClass();
```

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
```
.NET Interactive

© 2020 Microsoft Corporation

Version: 1.0.225503+3174511575ce656cd699fc7978d7c9a8ecd4353c

Build date: 2021-05-08T13:04:58.4839798Z

https://github.com/dotnet/interactive
```
* At the command line, run `dotnet interactive --version`.
`1.0.222801+f2ff13b19c29823ac625c235db4ee2343954cc87`

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/15711142/120078575-17a47c00-c07e-11eb-99d2-4808c182933d.png)

**Comment by Lawlzee** [comment]
I ended up fixing my problem by simply calling `kernel.DeferCommand(new SubmitCode(code));` instead.

**Comment by jonsequitur** [comment]
When submitting code to a kernel using that same kernel, using `DeferCommand` is the only supported approach.
