### ISSUE TITLE
Add Copy Cell Output button or context menu in .NET Interactive

### ISSUE THREAD

**Issue by doggy8088** [dotnet/interactive#1379]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I can't copy cell output easily when the output text are very long.

**Describe alternatives you've considered**
I would like to suggest two options:

1. Add a **Copy Cell Outputs** button in the context menu when right-click on the cell output

    ![image](https://user-images.githubusercontent.com/88981/120089202-9e169780-c12a-11eb-9347-9fb315997a85.png)

2. Add a **Copy** button on the top-right corner just like GitHub's code fence did.

    ![image](https://user-images.githubusercontent.com/88981/120089276-31e86380-c12b-11eb-8065-8e0e745aa932.png)

Related: https://github.com/dotnet/interactive/issues/862 
Microsoft/vscode issue: https://github.com/microsoft/vscode/issues/124917

**Comment by jonsequitur** [comment]
I'm closing this one as the VS Code repo you've linked to is the appropriate place for it.
