### ISSUE TITLE
Powershell kernet, out-display and HTML table alignment

### ISSUE THREAD

**Issue by eosfor** [dotnet/interactive#1388]
**The package and version I'm asking about**: 

.NET Interactive
Version: 1.0.230302+9ce1200b79a1904320b8669cde51dfb4d881ddb9
Build date: 2021-06-03T23:37:46.0000000Z
https://github.com/dotnet/interactive

Jupyter lab
Powershell kernel

### Question

In the following example, all values in the table aligned to the right. Is it possible to align them differently?

![image](https://user-images.githubusercontent.com/9363027/120743148-4622bc80-c4ad-11eb-9581-62b1478542aa.png)

**Comment by jonsequitur** [comment]
You can emit CSS using structural table selectors inside a `<style>` tag using an HTML cell:

```
#!html
<style>
/* CSS here */
</style>
```

**Comment by RandomFractals** [comment]
are those styles applied to the all the html output cells in the notebook or just the cells after it?

also, can you define those styles at the end of the notebook for more intro content and actual viz display at the top.

**Comment by jonsequitur** [comment]
You should be able to define the styles in any output cell and they'll apply globally, but I haven't looked into it deeply. 

This is really yet to be designed, but feedback on the preferred experience is welcome.

**Comment by RandomFractals** [comment]
I would prefer to have CSS styles and imports at the bottom of .net interactive notebook, and applied only to that notebook view, not all open notebook instances, so that I can use vscode notebooks for data story telling and insights, rather than code walk-throughs, which are tedious and boring for most folks trying to get insights from notebooks IMO.

**Comment by jonsequitur** [comment]
It should not apply to all open notebook instances. By globally I meant to all cells within a notebook, and regardless of cell order.

Is there a specific thing you're trying to do that you can't, and do you have a sense of whether this is a VS Code limitation versus a .NET Interactive limitation?

**Comment by RandomFractals** [comment]
nah, it's all good. I was just stating my preferences and ideal order of rendering for you and vscode dev team to take into account for the next phase of notebook apis update.

**Comment by RandomFractals** [comment]
ah, yes. there is one request I am pretty sure somebody already logged in vscode repo.

I would like to see cell output on top of the cell code and hide cell code, but still run it.

**Comment by eosfor** [comment]
> You can emit CSS using structural table selectors inside a `<style>` tag using an HTML cell:
> 
> ```
> #!html
> <style>
> /* CSS here */
> </style>
> ```
> 
> Over time we'll likely add more support for styling using well-known classes. For example, you'll see the `dni-plaintext` class applied to some of the elements within the table.

Well, I mean, this is all dynamic, I have a dynamic object in a variable. The `#!html` magic word lets me put a static HTML into a cell, right? I mean how do I apply  `#!html` to the contents of the variable? Do I misunderstand something?

**Comment by jonsequitur** [comment]
For example:

![image](https://user-images.githubusercontent.com/547415/123857745-925bf380-d8d7-11eb-8614-2285f0fd7962.png)

**Comment by eosfor** [comment]
> For example:
> 
> ![image](https://user-images.githubusercontent.com/547415/123857745-925bf380-d8d7-11eb-8614-2285f0fd7962.png)

shoot, now I got it, thanks! i'll try

**Comment by RandomFractals** [comment]
this is great, but we might need more than that.

so, I started working on this: https://github.com/RandomFractals/vscode-data-table

that table renderer will work in all vscode notebook tyhpes and will have and use proper grid that let's you toggle lots of things.

just dumps html table for now too :slightly_smiling_face: 

![data-table-renderer](https://user-images.githubusercontent.com/656833/124201789-81111380-da9e-11eb-8839-2c438978409d.png)
