### ISSUE TITLE
IntelliSense in Visual Studio Code is slow comparing to .cs files

### ISSUE THREAD

**Issue by apisarev** [dotnet/interactive#1391]
IntelliSense in Visual Studio Code is slow comparing to .cs files:
https://www.dropbox.com/s/r7csuef0ofc0cl9/Dotnet%20interactive%20intellisence.mp4?dl=0

- .NET Interactive version: 1.0.225602+88e6d92f1cf8ead1c4c0b982e67b4a63902e00e6
- OS: Windows 10
- Frontend: Visual Studio Code (1.56.2)

**Comment by Dimension4** [comment]
With F# it takes 2-6s for intellisense depending on included nuget packages. If I have no packages included it takses ~2s, with 

    #r "nuget: GlmSharp"
    open GlmSharp

it takes 6s to open the auto complete popup afterwards

**Comment by JasonWei512** [comment]
It also uses 100% more memory than plain ".csx" .Net Script + OmniSharp ([here's a demo](https://github.com/JasonWei512/DotNetInteractiveMemoryUsage)) on my machine. The entire .Net Interactive feels clunky.

**Comment by dharmatech** [comment]
> It also uses 100% more memory than plain ".csx" DotNet Script + OmniSharp on my machine. It uses more and more as the notebook gets bigger. The entire DotNet Interactive feels clunky and unoptimized. If Microsoft wants to make it a real tool other than a toy without using existing language server implementation like OmniSharp ([link](https://github.com/dotnet/interactive/issues/677#issuecomment-727625788)), then they need to put much more effort into it...

Just for another point of view, I really appreciate the tool as is. For me, I already consider it to be a *real tool* and far more than a toy. Sure, there's some performance issues with the completion but it's a work in progress and it's already hugely useful. Amazing work so far guys.

**Comment by GF-Huang** [comment]
> > It also uses 100% more memory than plain ".csx" DotNet Script + OmniSharp on my machine. It uses more and more as the notebook gets bigger. The entire DotNet Interactive feels clunky and unoptimized. If Microsoft wants to make it a real tool other than a toy without using existing language server implementation like OmniSharp ([link](https://github.com/dotnet/interactive/issues/677#issuecomment-727625788)), then they need to put much more effort into it...
> 
> Just for another point of view, I really appreciate the tool as is. For me, I already consider it to be a _real tool_ and far more than a toy. Sure, there's some performance issues with the completion but it's a work in progress and it's already hugely useful. Amazing work so far guys.
> 
> I'm just now getting around to trying this out and I feel like I'm late to the party. 🥳

If you've tried C# Interactive in Visual Studio, you won't think so.

**Comment by GF-Huang** [comment]
It is still slow, see https://github.com/dotnet/interactive/issues/2373#issuecomment-1370515985.
