### ISSUE TITLE
error CS0103: The name 'Formatter' does not exist in the current context

### ISSUE THREAD

**Issue by praveenraghuvanshi1512** [dotnet/interactive#1404]
### Describe the bug
I was following the tutorial [An Introduction to DataFrame](https://devblogs.microsoft.com/dotnet/an-introduction-to-dataframe/) and somehow the code for formatting the dataframe as table started throwing error "error CS0103: The name 'Formatter' does not exist in the current context". It used to work for me in the past, today seems something is broken.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.230701+897ec27256aa312cc872b52b261726684b29d42b
Build date: 2021-06-09T11:13:17.2992510Z

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [X] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
The `using` for the namespace is no longer included by default but it should work if you add:

```
using Microsoft.DotNet.Interactive.Formatting;
```

But I think the latest version of Microsoft.Data.Analysis might also include the table formatter.

**Comment by praveenraghuvanshi1512** [comment]
Thanks @jonsequitur for prompt response. 
Adding 'Microsoft.DotNet.Interactive.Formatting' package, it's working fine in Visual Studio.
However, it failed to identify Register Method in Jupyter Lab notebook.

![image](https://user-images.githubusercontent.com/39731863/121515329-b4660280-ca0a-11eb-9c07-c6a945e96083.png)

Also, default version of ''Microsoft.DotNet.Interactive.Formatting' is not installed properly in Notebook. As a result, I had to specify version '1.0.0-beta.20074.3' which got installed without any error.

**Comment by jonsequitur** [comment]
We already ship with this package in the build, so you don't need to do `#r` for it.

I just realized that there's another breaking change that we've made since that sample was published. Sorry I missed that before. The API now is `Formatter.Register<T>` rather than `Formatter<T>.Register`.

**Comment by praveenraghuvanshi1512** [comment]
Awesome... It worked... thanks!

Any idea how to enable intellisense?

**Comment by SebastianZug** [comment]
Hi @jonsequitur, @praveenraghuvanshi1512

many thanks for your hints related to the "Formatter not exist" problem. Unfortunately, I wasn't able to adapt the introduction example to the new `formatter` definition. Which additional steps would be necessary to use the existing `formatter`  configuration?

First, according to @jonsequitur,  a separate download is not necessary anymore?
```
#r "nuget:Microsoft.Data.Analysis"
using Microsoft.Data.Analysis;
using Microsoft.DotNet.Interactive.Formatting;
```
Second step, extending the Formatter definition according to comments of @praveenraghuvanshi1512 to the new API:

```csharp
using Microsoft.AspNetCore.Html;
// Formatter<DataFrame>.Register((df, writer) =>  // original version
Formatter.Register<DataFrame>(formatter: (df, writer) =>
{
    var headers = new List<IHtmlContent>();
    headers.Add(th(i("index")));
    headers.AddRange(df.Columns.Select(c => (IHtmlContent) th(c.Name)));
    var rows = new List<List<IHtmlContent>>();
    var take = 10;
    for (var i = 0; i < Math.Min(take, df.Rows.Count); i++)
    {
        var cells = new List<IHtmlContent>();
        cells.Add(td(i));
        foreach (var obj in df.Rows[i])
        {
            cells.Add(td(obj));
        }
        rows.Add(cells);
    }

    var t = table(
        thead(
            headers),
        tbody(
            rows.Select(
                r => tr(r))));

    writer.Write(t);
// }, "text/html"); =>  // original version
}, mimeType: "text/html");
```
Unfortunately, `th`, `i` ... `table` are not known now. How to adapt this code?

Many thanks!

Sebastian

**Comment by dandypanda** [comment]
It seems this is needed:
using static Microsoft.DotNet.Interactive.Formatting.PocketViewTags;

Take a look at https://github.com/dotnet/interactive/blob/main/samples/notebooks/csharp/Samples/HousingML.ipynb

**Comment by kanadaj** [comment]
@SebastianZug @jonsequitur the docs don't actually mention importing Microsoft.DotNet.Interactive.Formatting; maybe this is something to fix (https://github.com/dotnet/interactive/blob/main/docs/formatting.md)?

**Comment by jonsequitur** [comment]
I've made some updates to that document. Let me know what you think.
