### ISSUE TITLE
Is it possible to work with the output of a sql cell in a c#/f# cell?

### ISSUE THREAD

**Issue by JCarnall** [dotnet/interactive#1405]
Just learning the ropes with .Net interactive notebooks and I love it.  Hopefully a quick question.

Is it possible to work with the output of a sql cell in a subsequent c# or f# cell?

**Comment by jonsequitur** [comment]
We are working on this but currently, no. 

An option that's currently available is to use `#!connect mssql --create-dbcontext`, and then use the auto-scaffolded EF DbContext from C#.

Keep an eye on #1136.

**Comment by JCarnall** [comment]
@jonsequitur - thanks for the reply,  the EF DBContext method you suggest is a good a work around for the time being. I've also subscribed to 1136.

I'd like to contribute to the project, but not sure I understand the code 'under the hood' well enough yet.  I know you guys are very busy but if you ever do a session to help get new contributors started let me know.

**Comment by jonsequitur** [comment]
Thanks! This is a great suggestion. We can probably set something up.

You can also reach out any time on our Discord channel: https://discord.gg/3pvut9YujN
