### ISSUE TITLE
System.Net.Http.Json not recognised

### ISSUE THREAD

**Issue by raghavan-mk** [dotnet/interactive#1406]
Trying .net interactive via VS code extension. Writing a simple REST client, but getting the following error -

**Error: (3,23): error CS0234: The type or namespace name 'Json' does not exist in the namespace 'System.Net.Http' (are you missing an assembly reference?)
(14,15): error CS0103: The name 'JsonContent' does not exist in the current context**

Also tried adding System.Net.Http.Json package explicitly but to no avail

Is it a bug or am i doing something wrong ?

Here's the code

using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;

string baseUrl = "";
string api ="";

HttpClient client = new HttpClient
{
    BaseAddress = new Uri(baseUrl)
};
HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post,api)
{
    Content = JsonContent.Create(input)
};
request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
try
{
    var r = await client.SendAsync(request);
    Console.WriteLine(await r.Content.ReadAsStringAsync());
}
catch(Exception ex)
{
    Console.WriteLine(ex.ToString());
}

OS Windows 10 1909

.NET SDKs installed:
  3.1.409 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]

**Comment by arkada38** [comment]
```csharp
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using System.Net.Http.Json;

HttpClient client = new()
{
    BaseAddress = new("http://127.0.0.1:80"),
};

await client.GetFromJsonAsync<string>("/hello")
```

`Version: 1.0.256902+f53ac433f464fba47f569a75c837f08ece7c554d`
`dotnet 6.0.100`

https://user-images.githubusercontent.com/4335913/143004924-50aea46a-bddd-47c7-989b-a2187b4bbbfb.mp4

![image](https://user-images.githubusercontent.com/4335913/143005107-5c2b9716-8805-4168-b78c-c378ca439b16.png)

**Comment by smokedlinq** [comment]
Ran into this today, the 6.0.2 prerelease seems to work for now ...

**Comment by jonsequitur** [comment]
The example code compiles for me if I import the latest package first:

```cs
#r "nuget: System.Net.Http.Json, *-*"
```

**Comment by JorgePinetta** [comment]
I have the same problem.
(System.Net.Http.Json, 7.0.0)
![image](https://user-images.githubusercontent.com/86976958/210186903-ad2be151-38bb-4a22-a0a4-ce974b9909b8.png)

**Comment by MatisseHack** [comment]
This is broken for me as well. When I was using .NET 6, it would work if I installed version 7.0.0 of `System.Net.Http.Json`, but not if I installed version 6.0.0. Now that I’m on .NET 7, there is no version of the package that works.

I'm using version `1.0.410202` of `microsoft.dotnet-interactive`
