### ISSUE TITLE
Extension lab sample failed on "nuget:Microsoft.DotNet.Interactive.ExtensionLab,*-*"

### ISSUE THREAD

**Issue by Mryam1** [dotnet/interactive#1409]
### Describe the bug
While running the [sanddance sample](https://github.com/dotnet/interactive/blob/main/samples/ExtensionLab/ExtensionLab-SandDance.ipynb) I have got a failed package install in "nuget:Microsoft.DotNet.Interactive.ExtensionLab,*-*"

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
 
![image](https://user-images.githubusercontent.com/83891426/121605030-811e7600-ca00-11eb-80d7-d5c36395efcd.png)

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/83891426/121605150-be830380-ca00-11eb-9125-2e974a9bf7e2.png)

**Comment by jonsequitur** [comment]
Can you restart VS Code and try this again? There was an update today that could cause issues like this with the new packages running on the previous version of the VS Code extension.

If it's still happening please also provide the output of running `#!about`.

Thanks!

**Comment by jhoneill** [comment]
I think the following is a new issue but would have the same description. 
`#r "nuget:Microsoft.DotNet.Interactive.ExtensionLab,*-*"`    
produces 
```
Error: C:\Program Files\dotnet\sdk\5.0.302\NuGet.targets(131,5): error : Unable to load the service index for source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json. [C:\Users\P10506111\AppData\Local\Temp\nuget\20532--2847d59b-8305-42de-ba11-10cf045ebe12\Project.fsproj]
C:\Program Files\dotnet\sdk\5.0.302\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\Users\P10506111\AppData\Local\Temp\nuget\20532--2847d59b-8305-42de-ba11-10cf045ebe12\Project.fsproj]
```

It appears that it is trying to get a file from a site with an expired cert - confirmed by doing this in powershell. 
```
Invoke-WebRequest https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json
Invoke-WebRequest: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
```

**Comment by jonsequitur** [comment]
Are you still able to repro this?

**Comment by jhoneill** [comment]
@jonsequitur  I think that question was for @Mryam1   - my problem has gone :-)

**Comment by jonsequitur** [comment]
Yes. I'll close it. If anyone is still able to repro, feel free to reopen the issue.
