### ISSUE TITLE
$$ automatic variable not set in PowerShell

### ISSUE THREAD

**Issue by cgranade** [dotnet/interactive#142]
#### Describe the bug
When executing cells in the PowerShell kernel, the `$$` automatic variable isn't set for future cells.

#### Did this error occur while using `dotnet interactive`?
- [ ] .NET Jupyter Lab

#### Screenshots
![image](https://user-images.githubusercontent.com/31516/74072640-42b41980-49bc-11ea-9765-2338a35b10ef.png)

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Safari
 - Frontend
    - [ ] Jupyter notebook
    - [x] Jupyter lab
    - [ ] nteract

**Comment by SydneyhSmith** [comment]
@cgranade thanks for opening this, issue, we are able to reproduce this....we are making some updates to the console host which may resolve this issue, if not we will investigate further

**Comment by cgranade** [comment]
> @cgranade thanks for opening this, issue, we are able to reproduce this....we are making some updates to the host used by the PowerShell kernel which may resolve this issue, if not we will investigate further

Happy to help, I'm really excited for PowerShell Notebooks! ♥

**Comment by daxian-dbw** [comment]
I will get this fixed right after #202 gets merged.

**Comment by daxian-dbw** [comment]
BTW, additional problem: `Get-History` doesn't work in the PowerShell Jupyter notebook today. It will get fixed along with the `$$` variable.
