### ISSUE TITLE
Occasional "The name 'display' does not exist in the current context"

### ISSUE THREAD

**Issue by Eddie-Hartman** [dotnet/interactive#1421]
### Describe the bug
I've seen this in the couple notebooks I've made so far. Sometimes it goes away.

Right now, I have two notebooks open. One has display and will display results just fine, but the other won't work at all. I'm not sure what the problem is or what to do. Any ideas?

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
.NET Interactive

© 2020 Microsoft Corporation

Version: 1.0.230903+1a272ef3782d6e88b6d36ebd648fb1882da0a530

Build date: 2021-06-13T03:27:15.8960287Z

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/14089997/121978831-07b3ba00-cd57-11eb-9d45-4dd0ad08ca2a.png)

This is rest of the file. It's not meant to be too complicated yet:
![image](https://user-images.githubusercontent.com/14089997/121979011-5c573500-cd57-11eb-88eb-598c8ef2b760.png)

**Comment by brettfo** [comment]
This has been addressed with deferred commands.
