### ISSUE TITLE
When to run, "dotnet tool update -g Microsoft.dotnet-interactive"?

### ISSUE THREAD

**Issue by JCarnall** [dotnet/interactive#1422]
Apologies if this is an obvious question!  (I'm not a dotnet guru yet) 

Should one run "dotnet tool update -g Microsoft.dotnet-interactive" post updating their .Net SDK to latest?

When I originally installed the .Net Interactive Extension for VS Code I guess the install of the Microsoft.dotnet-interactive tool was done for me behind the scenes?

**Comment by jonsequitur** [comment]
If you're using the .NET Interactive Notebooks extension for VS Code, the installation of the `dotnet-interactive` tool is managed for you, and it's not a global install. If you've installed it using `dotnet tool install` with the `-g` flag, then that is a separate, global installation of the tool.

If you're also using a global install, e.g. for use with JupyterLab, then it might be worth it to do an update. Until/unless we move to targeting a higher .NET version though, the order is unimportant.

**Comment by JCarnall** [comment]
Ok, thanks for clarifying, very useful to understand the differences.
