### ISSUE TITLE
Error when running "#r "nuget:Microsoft.DotNet.Interactive.SqlServer,*-*"" in F# cell

### ISSUE THREAD

**Issue by JCarnall** [dotnet/interactive#1423]
Hi there

I'm trying out the code snippets in Maria's blog [here](https://devblogs.microsoft.com/dotnet/net-interactive-with-sql-net-notebooks-in-visual-studio-code/)

When I run "#r "nuget:Microsoft.DotNet.Interactive.SqlServer,*-*"" in an F# cell I get the following error

![image](https://user-images.githubusercontent.com/68747996/122001096-b5e75000-cda7-11eb-875c-ec573a64ebed.png)

I've tried the same thing in a C# cell and there is no error, but the next step does not display the expected results of the help command

![image](https://user-images.githubusercontent.com/68747996/122001323-11b1d900-cda8-11eb-95d7-3c3864ce6a91.png)

Version of .Net Interactive is 1.0.225602

![image](https://user-images.githubusercontent.com/68747996/122001668-93096b80-cda8-11eb-914a-587a8f6acce1.png)

- OS
    - [x ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
Please restart VS Code and update to the latest version and let us know if you still see the issue.

**Comment by JCarnall** [comment]
@jonsequitur - I've got it working now thanks.  The problem seems to be that I was working on a machine where VS Code was not set to auto update, so I was running a slightly older version of vs code.  Appreciate your help :)

**Comment by jonsequitur** [comment]
Good to hear. Thanks!
