### ISSUE TITLE
Work with .NET Framework V4.8

### ISSUE THREAD

**Issue by dubjap** [dotnet/interactive#1426]
**The package and version I'm asking about**: 
Version: 1.0.230903+1a272ef3782d6e88b6d36ebd648fb1882da0a530

### Question

Is it possible to have the .net interactive notebook in VS Code running against the .NET framework V4.8?
A certain program is providing an API by means of a DLL that is written in .NET framework.
It works in the C# interactive in VS but would be really cool to have it in a notebook.

**Comment by jonsequitur** [comment]
There's currently no plan to support this.
