### ISSUE TITLE
README link broken --> Install .NET Interactive to create and run .NET notebooks on your machine.

### ISSUE THREAD

**Issue by fortunewalla** [dotnet/interactive#1437]
The below link from README is broken:

[Install .NET Interactive](https://github.com/dotnet/interactive/blob/main/docs/NotebooksLocalExperience.md) to create and run .NET notebooks on your machine.

https://github.com/dotnet/interactive/blob/main/docs/NotebooksLocalExperience.md

**Comment by jonsequitur** [comment]
Thanks, @fortunewalla! Fixed.

**Comment by krptodr** [comment]
This is broken again.

**Comment by vzarytovskii** [comment]
> [Install .NET Interactive](https://github.com/dotnet/interactive/blob/main/docs/NotebooksLocalExperience.md) to create and run .NET notebooks on your machine.

Works for me in `main`, it leads to https://github.com/dotnet/interactive/blob/main/docs/NotebookswithJupyter.md when clicking from the repo's README
