### ISSUE TITLE
Are polygot notebooks supported in jupyter/mybinder?

### ISSUE THREAD

**Issue by JonTheTurnip** [dotnet/interactive#1447]
Hi there,

Hopefully a very quick question.

I thought I'd try creating a notebook that includes both c# and f# cells, and then publish this to binder using the dockerfile from this repo.

It all works well for the c# cells but not for the f# cells.  It makes me think that perhaps polygots are not yet supported in jupyter/mybinder?

Apologies if this is an obvious question, but it's all new to me.  If needed, my repo is here...

https://github.com/JonTheTurnip/dot-net-notebooks

I also tried nbviewer with a dotnet interactive notebook and that did not work, assume that's expected behaviour at this time?

Cheers

Jon

**Comment by jonsequitur** [comment]
Polyglot notebooks are supported in Jupyter, MyBinder, etc. using magic commands, e.g.

```
#!csharp

Console.WriteLine("C#!");

#!fsharp

"F#!" |> Console.WriteLine

```

**Comment by JonTheTurnip** [comment]
Ok, thanks.  I created the notebook in VS Code and selected the cell language from the drop down option on the cell border.

Are you saying that in order for the notebook to work in Jupyter then I need to explicitly write the magic commands inside the cell?

Thanks for your help :)

**Comment by colombod** [comment]
> Ok, thanks. I created the notebook in VS Code and selected the cell language from the drop down option on the cell border.
> 
> Are you saying that in order for the notebook to work in Jupyter then I need to explicitly write the magic commands inside the cell?
> 
> Thanks for your help :)

Let me do some test, if the notebook has the cell metadata and Jupyter lab sends it with the request we honour it.

**Comment by colombod** [comment]
in this version of jupyter lab
![image](https://user-images.githubusercontent.com/375556/123660797-dee9f500-d82b-11eb-8ad5-753c8743f9a6.png)
I can run your notebook without any problem and the cell language is honoured

**Comment by jonsequitur** [comment]
> Are you saying that in order for the notebook to work in Jupyter then I need to explicitly write the magic commands inside the cell?

In versions of Jupyter that don't honor the cell metadata, then you can always fall back to using the magic commands.

**Comment by JonTheTurnip** [comment]
@colombod @jonsequitur  thanks for the info on this, much appreciated.

Going forward, I'll try JupyterLab instead.

In the meantime, I've tried the explicit magic commands and like you say, it works fine.
