### ISSUE TITLE
[EXTERNAL] Markdown cells do not render HTML

### ISSUE THREAD

**Issue by Treit** [dotnet/interactive#1455]
### Describe the bug
Using HTML tags in markdown cells with .NET Interactive notebooks does not render.

## .NET Interactive Version
Version: 1.0.230903+1a272ef3782d6e88b6d36ebd648fb1882da0a530
Build date: 2021-06-28T20:51:38.7685995Z

- OS
    - [x] Windows 11 (build 22000.51)
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
This animation shows the issue:

![vscode1](https://user-images.githubusercontent.com/8271812/123875179-11f4bd00-d8ee-11eb-9864-ffdd7d18f1b3.gif)

**Comment by jonsequitur** [comment]
I'm not able to repro this one.

It's a VS Code issue in any case. Here was the original issue filed there: https://github.com/microsoft/vscode/issues/111355

**Comment by Treit** [comment]
I have tested this just now on the current "Visual Studio Code - Insiders" build and it does not reproduce. It appears it may be an issue that has been fixed in the Insiders build but the bug is not yet fixed in the mainline VS Code builds.

**Comment by Treit** [comment]
Given that this seems to be a VSCode issue that appears fixed in newer VSCode instances, I think we can close this one.
