### ISSUE TITLE
Can't install extension using .vsix offline

### ISSUE THREAD

**Issue by dennisl68-castra** [dotnet/interactive#1458]
### Describe the bug
When trying to install ms-dotnettools.dotnet-interactive-vscode-1.0.2325011.vsix using `Install from VSIX...`,
I get the error

~~~~
Unable to install extension 'ms-dotnettools.dotnet-interactive-vscode' as it is not compatible with VS Code '1.57.1'.
~~~~

Trying to install the Jupyter Notebook extension gives the same error.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
  N/A
* At the command line, run `dotnet interactive --version`.
  N/A

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [X] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/49750419/123947197-69536580-d9a0-11eb-886c-e9837a14cd8f.png)

**Comment by brettfo** [comment]
The version of the extension you tried to install is only for insiders.  The latest package that'll install on stable is 1.0.2309030.

If it helps in the future, all of our extension version numbers look like `1.0.xxxxxx0` or `1.0.xxxxxx1`; the ones that end in `0` are for stable VS Code, the ones that end in `1` are for Insiders.
