### ISSUE TITLE
F# package added notification appears in the wrong cell and is missing version number

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#146]
When adding a package in F#, the notification doesn't appear in the correct cell and the version isn't indicated:

![image](https://user-images.githubusercontent.com/547415/74091109-c9263500-4a68-11ea-9fc4-bb737a02f036.png)

Version: 1.0.110703+800c860427197c5988ea3448c98fc35f38a9793d

**Comment by KevinRansom** [comment]
This is fixed in master.

![image](https://user-images.githubusercontent.com/5175830/78193970-b0b31500-7430-11ea-9ede-e93d55562582.png)
