### ISSUE TITLE
Stable versions not available at Visual Studio Marketplace for manual download

### ISSUE THREAD

**Issue by dennisl68-castra** [dotnet/interactive#1460]
The version of the extension you tried to install is only for insiders.  The latest package that'll install on stable is 1.0.2309030.

If it helps in the future, all of our extension version numbers look like `1.0.xxxxxx0` or `1.0.xxxxxx1`; the ones that end in `0` are for stable VS Code, the ones that end in `1` are for Insiders.

_Originally posted by @brettfo in https://github.com/dotnet/interactive/issues/1458#issuecomment-871647063_

![image](https://user-images.githubusercontent.com/49750419/124019002-ca9f2700-d9e8-11eb-971e-e9aded068b5e.png)

**Comment by brettfo** [comment]
I've updated the release [here](https://github.com/dotnet/interactive/releases/tag/1.0.2309030) to have the downloadable vsix.

**Comment by dennisl68-castra** [comment]
@brettfo What's the average release cycle for the stable releases?

**Comment by brettfo** [comment]
We release at the same time that VS Code does (maybe a few hours later), which is usually the first week of the month, commonly on a Wednesday or Thursday.  Near the end of the month there will usually be a pinned issue at https://github.com/microsoft/vscode/issues titled `<month> <year> Endgame`.  E.g., the current one is titled `June 2021 Endgame` at microsoft/vscode#127394.  That has a check list that they use leading up to publishing a new version of VS Code.
