### ISSUE TITLE
When opening a previously save .ipynb the cell results are blank?

### ISSUE THREAD

**Issue by iancoetzer** [dotnet/interactive#1462]
### Describe the bug
Hi, when I create a new .NET interactive .ipynb workbook that returns some records from a SQL database table the results disappear when I save and re-open the workbook.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
**1.0.230903**

- OS
    - [ X ] Windows 10
    -
 - Frontend
    - [ X ] Visual Studio Code 
    
### Screenshots
**image 1**
![i1](https://user-images.githubusercontent.com/7976311/124168409-62fae180-daa5-11eb-8177-533064655be5.png)

**image 2**
![i2](https://user-images.githubusercontent.com/7976311/124168424-68f0c280-daa5-11eb-8dc4-9fb237edb2b1.png)

**Comment by jonsequitur** [comment]
Visualizations that require JavaScript to be evaluated aren't currently viewable without re-running the notebook.
