### ISSUE TITLE
Uninstallation problem

### ISSUE THREAD

**Issue by WilliamQue** [dotnet/interactive#1468]
### Describe the bug
After testing and uninstalling .net interactive notebooks in vscode, I reopened ipynb file from vscode explorer, the file was still opened by the uninstalled extension, rather than jupyter notebook once.

How to uninstall .net interactive notebooks completely?

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
v1.0.2356031

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
Does this still happen after you completely restart VS Code?

**Comment by WilliamQue** [comment]
> Does this still happen after you completely restart VS Code?

Yes, even if deleted some config folders and reinstalled vscode.

**Comment by jonsequitur** [comment]
> the file was still opened by the uninstalled extension

Can you elaborate on this and/or provide a screen shot?

**Comment by WilliamQue** [comment]
I uninstall all extensions, delete .vscode folder under C:\Users\xxx, and code folder under C:\Users\xxx\AppData\Roaming, and then re-install python extension, it seems to be OK, and ipynb file will be opened by jupyter directly.

Turn off sync first! 

Thank you! please faster your steps.

**Comment by jonsequitur** [comment]
You're welcome. 

Can this issue be closed?

**Comment by WilliamQue** [comment]
I close, thanks!
