### ISSUE TITLE
nuget loading messages are very invasive

### ISSUE THREAD

**Issue by colombod** [dotnet/interactive#1469]
### Describe the bug
Loading packages or connecting to mssql produces a very long and verbose output, also a lot of package names are repeated.
![image](https://user-images.githubusercontent.com/375556/124792295-c7ee8580-df44-11eb-9c97-b537b52c2a84.png)
![image](https://user-images.githubusercontent.com/375556/124792348-d63ca180-df44-11eb-888b-b6a492cc93e0.png)

### Please complete the following:

- OS
    - [X] Windows 10
    - [X] macOS
    - [X] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [X] Visual Studio Code Insiders
    - [ ] Other (please specify)

**Comment by colombod** [comment]
@KevinRansom we should change formatting and make it something that user can expand.

**Comment by jonsequitur** [comment]
We should also make it very clear what's new versus what was referenced previously.

**Comment by colombod** [comment]
The current change will only display what has been added, we will have a different gesture to see the list of all that has been installed

**Comment by jonsequitur** [comment]
This is still an issue in 1.0.235701.

![image](https://user-images.githubusercontent.com/547415/125147805-87c50980-e0e2-11eb-8a14-58abbfbf8054.png)

**Comment by colombod** [comment]
on first #r instruction it seems it is not able to understand that some of those packages where already loaded. @KevinRansom any ideas?
