### ISSUE TITLE
Ansi output not supported

### ISSUE THREAD

**Issue by DonJayamanne** [dotnet/interactive#1471]
The following cell doesn't work in Notebooks:
```csharp
Console.Write("\x1b[38;2;0;255;0m"); // set text color to green
Console.WriteLine("green");
Console.Write("\x1b[0m"); // reset colors
```

Basically any ANSI codes are not supported (because all output is treated as as plain text).

**Comment by jonsequitur** [comment]
![image](https://user-images.githubusercontent.com/547415/128542002-9724c844-f927-475a-ab6a-48684a99bdc1.png)
