### ISSUE TITLE
Unable to install nuget:Microsoft.DotNet.Interactive.SqlServer

### ISSUE THREAD

**Issue by DebtheDBA** [dotnet/interactive#1478]
### Describe the bug
I installed VS Code so I could learn how to set up .NET Interactive notebooks. I used the System Installer instead of the User Installer.

I installed dotnet-sdk-5.0.301-win-x64.exe as well as dotnet-runtime-5.0.7-win-x64.exe
I installed these extensions in VS Code, if this helps with set up issues:
NuGet Package Manager (1.1.6), 
.NET Interactive Notebooks (1.0.2351010), 
SQL Server (mssql) (1.10.1), 
Jupyter (2021.6.999662501)

When creating a .NET Notebook, as a jpynb file, I added a C# code cell and ran:
#r "nuget:Microsoft.DotNet.Interactive.SqlServer,*-*"

I got the following error:
Error: C:\Users\Deborah\AppData\Local\Temp\nuget\6260--159f7760-6286-4970-bea7-77ad5cb1ce35\Project.fsproj : error NU1100: Unable to resolve 'Microsoft.DotNet.Interactive.SqlServer (>= 0.0.0-0)' for 'net5.0'.
C:\Users\Deborah\AppData\Local\Temp\nuget\6260--159f7760-6286-4970-bea7-77ad5cb1ce35\Project.fsproj : error NU1100: Unable to resolve 'Microsoft.DotNet.Interactive.SqlServer (>= 0.0.0-0)' for 'net5.0/win-x64'.

When researching and reaching out for general help with the problem, it sounded like there may be a config setting with nuGet and it was recommended that I open an issue.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
(see below for screenshot)
.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.233002+bb8147548dcdc9c83212e3b3631aa2e0148a0547
Build date: 2021-07-05T23:00:52.1339606Z
https://github.com/dotnet/interactive

* At the command line, run `dotnet interactive --version`.

- OS
    - [X ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/20119319/124973346-69371380-dff9-11eb-87d1-495d04e83207.png)

**Comment by jonsequitur** [comment]
@DebtheDBA Are you still able to reproduce this bug?

**Comment by DebtheDBA** [comment]
Yes - I am still able to reproduce the problem.

**Comment by jonsequitur** [comment]
Could you try this?

```
#r "nuget: Microsoft.DotNet.Interactive.SqlServer, 1.0.0-beta.21357.1"
```

**Comment by DebtheDBA** [comment]
I'm still getting errors:
Error:
C:\Users\Deborah\AppData\Local\Temp\nuget\11680--5b4f614e-50f6-4ca8-a3a3-519529bd8cf6\Project.fsproj
: error NU1100: Unable to resolve 'Microsoft.DotNet.Interactive.SqlServer
(>= 1.0.0-beta.21357.1)' for 'net5.0'.
C:\Users\Deborah\AppData\Local\Temp\nuget\11680--5b4f614e-50f6-4ca8-a3a3-519529bd8cf6\Project.fsproj
: error NU1100: Unable to resolve 'Microsoft.DotNet.Interactive.SqlServer
(>= 1.0.0-beta.21357.1)' for 'net5.0/win-x64'.

In addition, I'm now having problems with SQL Notebooks in Azure Data
Studio where I can't use any kernel other than SQL. I'm getting this error:
Failed to change kernel. Kernel SQL will be used. Error was: Can't find
notebook manager for provider jupyter

All of this seemed to start after I tried to do the latest updates that the
tools were suggesting I do (PowerShell and Python). I'm wondering if there
was a bad python update somewhere?

Thanks for following up on this!
Deborah

**Comment by jonsequitur** [comment]
.NET Interactive doesn't depend on Python so that should be unrelated.

Can you share the results of running ` dotnet --info` in your terminal?

**Comment by DebtheDBA** [comment]
.NET SDK (reflecting any global.json):
 Version:   5.0.303
 Commit:    6409b42649

Here are the results of dotnet --info

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.303\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  3.1.412 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program
Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program
Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program
Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program
Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program
Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program
Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program
Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
