### ISSUE TITLE
Custom install location of jupyter kernel

### ISSUE THREAD

**Issue by MikaelUmaN** [dotnet/interactive#148]
**Is your feature request related to a problem? Please describe**

I use docker for my development and have an image that I like to add net kernels to.

Usually I mount a folder as the home folder of the user in order to get things like ssh keys and configs in the container while the image remains general. I imagine this is quite common.

While I can install dotnet where I like and dotnet interactive as well, it seems “dotnet interactive install jupyter” always picks the home folder.

Thus when I volume mount the .dotnet folder is overwritten and doesn’t show up.

**Describe the solution you'd like**

Cmd option to point to a path, e.g /opt/.dotnet

**Describe alternatives you've considered**

Various workarounds which are OK but are invasive to my colleagues that use the same image.

**Comment by colombod** [comment]
You might have to change the way jupyter looks up the folders for kernel specs. With the pr #337  you can specify where you want the kernel spec file installed, just make sure jupyter or jupyter lab can read from there
