### ISSUE TITLE
Python extension required although only using PowerShell when creating a new .ipynb

### ISSUE THREAD

**Issue by dennisl68-castra** [dotnet/interactive#1487]
### Describe the bug
When creating a new Notebook for use with PowerShell, an error is displayed requiring Python.
The error can be ignored.

1. Ctrl-Shift-P
2. .Net Interactive: Create new blank notebook
3. Create as .ipynb
4. PowerShell

The kernel is correclty set to .Net Interactive

Using the .dib extension doesn't produce the error message.

### Please complete the following:

.NET Interactive v1.0.2357010
Jupyter v2021.8.1013163132
VS Code
~~~~
Version: 1.58.0 (system setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.17763
~~~~

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/49750419/125209895-b205fb00-e28b-11eb-87b3-ff68b5c9809c.png)

**Comment by RandomFractals** [comment]
I ran into the same issue today.

Disabling Python in vscode, disables all Jupyter notebook extensions, including yours.

**Comment by brettfo** [comment]
This has been addressed.
