### ISSUE TITLE
Allow `/openNotebook` URI handler to better handle notebook types.

### ISSUE THREAD

**Issue by brettfo** [dotnet/interactive#1490]
Currently the `/openNotebook` URI handler simply looks at the end of the URI for either `.dib` or `.ipynb` to determine how to open the notebook.

A better solution would probably be this order:

1. If the URI query parameters contains `as=.dib` or `as=.ipynb`, use that.  This is similar to how the `/newNotebook` URI handler works.
2. If (1) didn't produce anything, read the mime type from the response object; something like `application/x-notebook-dib` or `application/x-notebook-ipynb`, etc.
3. If (1) and (2) didn't produce anything, then fall back to the current behavior of looking at the end of the URI.

**Comment by RandomFractals** [comment]
@brettfo I don't know if 1. is needed. You can get file extension from Uri.

what's the full Uri pattern for opening .net notebook via `vscode://` file scheme?
