### ISSUE TITLE
nteract filters do not capture cells shortcut (a, d, etc)

### ISSUE THREAD

**Issue by marckruzik** [dotnet/interactive#1494]
### Describe the bug
I am running the basic example with nteract.
https://github.com/dotnet/interactive/blob/main/samples/ExtensionLab/ExtensionLab-nteract.ipynb

In the nteract output, when I am trying to use the filter, it writes down the keys I am typing, but the notebook captures those keys as well as shortcuts.
So when I am typing a key like "a", it is both written in the filter and it activates the notebook shortcut ("a" = create a new cell). Same goes for other shorcuts and shortcuts combinations, such as "d d".

Here is my exact code:
```
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json"
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"

#r "nuget:Microsoft.DotNet.Interactive.ExtensionLab,*-*"
```

```
 var data = new[]
            {
                new {Type="orange", Price=1.2},
                new {Type="apple" , Price=1.3},
                new {Type="grape" , Price=1.4}
            };
```

`data`

`data.ExploreWithNteract().Display();`

### Please complete the following:

**Which version of .NET Interactive are you using?**

Version: 1.0.235701+3881a96164de75fca84f5f11027f3606b7878044
Build date: 2021-07-18T15:05:14.4777930Z

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots

![nteract_filter_problem](https://user-images.githubusercontent.com/51711029/126082733-cb51623a-207a-4b09-a5ab-9c2afaf48960.gif)

**Comment by brettfo** [comment]
@rebornix This appears to be an issue in general when an output cell contains an `<input>` element.

**Comment by marckruzik** [comment]
I read that "nteractDataExplorer and SandDanddance are no longer part of the core product" (see ![#2545](https://github.com/dotnet/interactive/issues/2545#issuecomment-1358132320)).

Besides, I did some tests following instructions from the related post, and see that this bug is no longer present.

So I close my issue.
