### ISSUE TITLE
Autocomplete Support

### ISSUE THREAD

**Issue by jingle1000** [dotnet/interactive#15]
I am unable to utilize the benefits of static typing due to the lack of autocomplete and go-to definition functionality.

Use Cases:
![image](https://user-images.githubusercontent.com/11929724/71328292-f6337e00-24e2-11ea-8d30-a63b3c192262.png)
When inside a function/class initializer, "shift + tab" should show what parameters/overloads the function/class accepts.
![image](https://user-images.githubusercontent.com/11929724/71328320-575b5180-24e3-11ea-97f9-a30f68963131.png)
An object's properties should have autocomplete as well when you call "." on them. Pressing "tab" inside a Jupyter notebook shows the objects available methods/properties.

**Comment by MikaelUmaN** [comment]
Auto-complete seems to be added now (see attached). But still missing function documentation using "shift+tab" pattern. This is really fundamental for adoption I would say. One thing that makes me use jupyter notebooks for python over Vs Code is the superior autocomplete support and documentation available in jupyter notebook, whereas vs code struggles.

<img width="225" alt="intellisense" src="https://user-images.githubusercontent.com/1746060/74084723-fb886000-4a71-11ea-94cd-c76c73193f69.PNG">

**Comment by dcuccia** [comment]
Learned here that [Tab] displays method/property names, but per @MikaelUmaN 's comment, this is far from the Intellisense experience we know and love. Is there hope to bring this to Jupyter Lab?

**Comment by GF-Huang** [comment]
If could not get intellisense like VS, I would rather use python. Come on!

**Comment by jonsequitur** [comment]
It's coming.

**Comment by jonsequitur** [comment]
Step 1: VS Code support: #355.

(We'll be bringing this to Jupyter as well but we're starting with VS Code because its rich language services model is particularly useful in guiding the design.)

**Comment by GF-Huang** [comment]
Great, when will it release to VS Code Extensions?

**Comment by dcuccia** [comment]
Per @LadyNaggaga's post [here](https://github.com/dotnet/interactive/issues/179#issuecomment-638483756) I just tried out the latest bits, which are great. #355 (merged) suggests that completions are enabled - is that supposed to be true for the current impl? Neither dot nor space working for me.

![image](https://user-images.githubusercontent.com/479617/83817877-bd472a00-a67a-11ea-9f04-b1e77d800b95.png)

**Comment by jonsequitur** [comment]
The triggers are different in VS Code. Completions will often trigger automatically, or ctrl-space will explicitly request them.

![image](https://user-images.githubusercontent.com/547415/83830179-5b49ed00-a699-11ea-8d77-077b529c0d52.png)

**Comment by dcuccia** [comment]
Aha, didn't try Ctrl-Space, thanks! Taking 5-10 seconds for the autocomplete at the moment. Not triggering automatically. Looking forward to watching this as it matures!

**Comment by kMutagene** [comment]
I really think this project is a big step for .NET in datascience, very good job so far! Just reporting in here that I currently cant get autocomplete suggestions for F#:

VSCode: 
![image](https://user-images.githubusercontent.com/21338071/84044150-783b3480-a9a7-11ea-96a6-2474dc03cdde.png)

Jupyter:
![image](https://user-images.githubusercontent.com/21338071/84044182-838e6000-a9a7-11ea-9fff-23f880de2520.png)

C# works just fine.

**Comment by GF-Huang** [comment]
> The triggers are different in VS Code. Completions will often trigger automatically, or ctrl-space will explicitly request them.
> 
> ![image](https://user-images.githubusercontent.com/547415/83830179-5b49ed00-a699-11ea-8d77-077b529c0d52.png)

How about parameter suggestions? How to trigger it?

**Comment by jonsequitur** [comment]
@GF-Huang I think you're asking about #728.
