### ISSUE TITLE
Help using the #!mermaid extension

### ISSUE THREAD

**Issue by dburriss** [dotnet/interactive#1504]
Version: 1.0.235701+3881a96164de75fca84f5f11027f3606b7878044
Build date: 2021-07-15T09:59:27.7276102Z

I am trying to use `#!mermaid` extension but I get no output when following the instructions given after install.

What I have tried:
1. Installed extension with `#r "nuget: Microsoft.DotNet.Interactive.ExtensionLab,*-*"`
2. Created a new block:

```mermaid
#!mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts prevail!
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
```
3. Tried running the block as Javascript, Html, C#, and every other language kernel

My expectation was that the above would render an output cell with the mermaid image.

How do I render the mermaid image?
Any examples or docs on how to get this working would be appreciated.

**Comment by colombod** [comment]
I have copied the markdown from this issue and used in a notebook with success
![image](https://user-images.githubusercontent.com/375556/126992578-b8be4792-5303-4fbe-8369-f7d30acdd2d9.png)

I am using the extensionlab version 1.0.0-beta.21357.1 which is the latest available on nuget.org.

I also attach the notebook, could you try this one?
[mermaid_test.zip](https://github.com/dotnet/interactive/files/6878364/mermaid_test.zip)

**Comment by dburriss** [comment]
Interesting.

I tried again and it did not work.

Then changing from `#r "nuget: Microsoft.DotNet.Interactive.ExtensionLab,*-*"` to `#r "nuget: Microsoft.DotNet.Interactive.ExtensionLab, 1.0.0-beta.21357.1"` the `#!mermaid` command now works.

When I change back, it continues to work. Starting on a different notebook where it also did not work but not changing the nuget ref to explicitly have the version, it works.

So I cannot reproduce (well I might be able to by cleaning my global package cache?) but closing.
