### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by Redayoub-lang** [dotnet/interactive#1507]
- Issue Type: `Bug`
- Extension Name: `dotnet-interactive-vscode`
- Extension Version: `1.0.2357010`
- OS Version: `Windows_NT ia32 10.0.19042`
- VS Code version: `1.58.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jonsequitur** [comment]
Are you still able to repro this? If so, please include some additional details and reopen the issue.

Thanks.
