### ISSUE TITLE
Execute C# code from custom extension when it gets loaded

### ISSUE THREAD

**Issue by profix898** [dotnet/interactive#1511]
I'm currently writing an IKernelExtension in C#. I have the implementation logic done, but I'm looking for a way to execute some C# code at the time my extension gets loaded. This would be very helpful for settings up the notebook, for example important some namespace using statements.

I already tried several things:
Inside the ```OnLoadAsync``` method of _IKernelExtension_, I put the following variants to inject my code:

1. ```kernel.SubmitCodeAsync("using MyNamespace;");```
2. ```var kernelCSharp = (CSharpKernel) kernel.FindKernel("csharp");  kernelCSharp.SubmitCodeAsync("using MyNamespace;");```
3. ```kernel.DeferCommand(new SubmitCode("using MyNamespace;"));```
4. ```kernel.DeferCommand(new SubmitCode("using MyNamespace;", "csharp"));```
5. ```kernel.DeferCommand(new SubmitCode("using MyNamespace;", "dotnet-interactive.//csharp"));```

None of the above makes the namespaces available in the interactive notebook. If I execute the same code at the top/beginning of the notebook file, it works as expected.
I found issue #1378 (which is not about custom extensions): it made me try the DeferCommand method, but that doesnt seem to work either.

Any suggestions? Anyone having the same problem?

**Comment by jonsequitur** [comment]
Most of those options should work, with 2 probably being the one I'd recommend.

To help out more I'd need to see more of what you're doing. Do you have code code you can share?

And is your extension code getting called? The code looks like it should work so the issue might be in how it's being packaged.

**Comment by profix898** [comment]
Thanks for your guidance. I can confirm that everything works as expected for a simple demo project. I didnt test all variants, but 2) certainly works fine.

However, I'm still having issues in a more complex project which involves a dependency hierarchy with multiple IKernelExtensions. In this case, my extension depends on XPlot.Plotly.Interactive. I tried to isolate the problem by building my extension package once and including it in an interactive notebook several times. Code execution works approx. every 1 in 3-5 times. Although I can see that the extension gets loaded every time (prints a message on load).

I'm on summer vacation for the next two week. I will try to pinpoint the problem then and ideally build a demo project. But at this point, it's very difficult to reproduce consistently.

(Closing issue until I can provide more details or reproduce. Thanks anyway.)
