### ISSUE TITLE
Markdown cell: No renderer found for "text/plain"

### ISSUE THREAD

**Issue by BrianL-STCU** [dotnet/interactive#1513]
### Describe the bug

When I ✔ "Stop editing" a Markdown cell in the VSCode .NET Interactive Notebook extension,
it gives me the error "No renderer found for 'text/plain' a".

### Please complete the following:

**Which version of .NET Interactive are you using?**

Version: 1.0.235701+3881a96164de75fca84f5f11027f3606b7878044
Build date: 2021-07-29T15:08:07.9870694Z

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [X] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/20843057/127533193-1d66eefc-8514-45d5-ad93-4b6e4144483a.png)

**Comment by jonsequitur** [comment]
I haven't been able to reproduce this. Are you still able to, and if so, could you provide more details or a large screen shot?

Thanks.

**Comment by BrianL-STCU** [comment]
I can't repro anymore either.
