### ISSUE TITLE
Add an event for nuget restore

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/interactive#1519]
The nuget restore command generates display events and individual package load events but would benefit from events indicating that restore is happening and completed.

The advantages are:
1. Auto logging of events
2. Enables hosts of remote kernels to report and log package management information, because events flow.
3. Hosts that listen for the events can customize the way they display dependencies.

PackageImportEvent

Contains:
- Requested Sources
- Requested Packages
    - Package Type E.g. nuget
    - Package Name
    - Package Version
- Resolved Sources
- Set of Resolved Packages
    - Package Type E.g. nuget
    - Package Name
    - Package Version

**Comment by jonsequitur** [comment]
There is a `PackageAdded` event which contains information about the just-loaded package.

We've discussed adding a new command and event for inspecting environment information, which would provide information about which kernels are loaded, available magic commands, variables, runtime information, package sources, and loaded packages.
