### ISSUE TITLE
#I produces output when it wasn't specifically requested

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/interactive#1521]
In the following session, the source c:\Temp was specifically requested in the first cell and not in the second
Both cells produce display output listing the source.

![image](https://user-images.githubusercontent.com/5175830/127713983-ca5b22e0-ef0d-4609-bebe-50fb6790527b.png)

For packages we now only produce requested output for specifically requested, I.e submitted packages for package load display.

**Comment by brettfo** [comment]
Will be re-doing this experience.
