### ISSUE TITLE
Get JS kernel variable in C#/F#

### ISSUE THREAD

**Issue by PawelStadnicki** [dotnet/interactive#1526]
This may be a silly question and the requested feature exists but I can only find an example where C# variable is read from JS.

How to read JS variable in C# kernel ?

**Comment by jonsequitur** [comment]
Right now this isn't directly supported, though I can imagine a few hacky workarounds.

We're planning on adding commands and events for retrieving remote variable states, which should make this straightforward programmatically, and then we'll extend `#!share` to include cross-process sharing.

**Comment by PawelStadnicki** [comment]
I could accept dirty hack or workaround for the time being, please :)

**Comment by PawelStadnicki** [comment]
Meantime I did most crazy workaround you can imagine: ,I'm sending js variable value to Redis cache and fetch it back in F#...

**Comment by jonsequitur** [comment]
I can imagine some pretty crazy workarounds...

I think one thing that could work with the tools already in the box is to send a command from the C# kernel to the JavaScript kernel that sends a command back to the C# kernel. I might give this a try to see if it actually works...

Longer-term, there will be a straightforward command for this, as well as support via `#!share` the same it currently works between C#, F#, and PowerShell.
