### ISSUE TITLE
Can't open existing .dib file in interactive mode or save new one

### ISSUE THREAD

**Issue by v-tsymbalistyi** [dotnet/interactive#1547]
### Describe the bug
I am able to create new notebook file and run some code. But I can't save.
It says:
 "Failed to save 'Untitled-1': File name path/Untitled-1.txt is not supported by .NET Interactive Notebooks.

Please make sure the file name matches following patterns:
"
And it does not list any patterns. I tried a bunch of different extensions and names including a.dib and still got an error.

Also if I open existing .dib notebook via Ctrl-Shift-P > .Net Interactive: Open Notebook it just opens markup text. Not in interactive mode at all.

The only message in "Runtime Status" of the extension is "Notebook type 'dotnet-interactive' already used"

.NET Interactive Notebooks Extension v1.0.2409020

dotnet --info output (shortened):
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  2.1.519 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  ...
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  ...
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  ...
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  ...
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  ...
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  ...
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  ...
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  ...
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

I failed to find similar issue. Please let me know I there is something I could do.

**Comment by jonsequitur** [comment]
@brettfo Any ideas here?

**Comment by brettfo** [comment]
@v-tsymbalistyi Can you add a screenshot of this behavior?  It looks like something is overriding the default notebook extension of `.dib` to `.txt`, and that's likely where the issue is coming from.
