### ISSUE TITLE
Interpolation of shared variables into magic commands

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#1553]
Magic commands should support parameterization using shared variables.

(Example APIs are for discussion purposes.)

For example:

```
#!connect mssql --connection-string ${csharp:myConnectionString}
```

In this example, a variable called `myConnectionString` would be accessed from the `csharp` kernel and interpolated into the magic command.

**Comment by asmith-octopus** [comment]
Are there currently any options that allow for us to use a connection string stored as an environment variable, such as setting up the connection in a C# cell without a magic?

**Comment by ColinKrist** [comment]
ack - I really need this to get buy-in from my team before we start using this more. We don't like storing db connections in the notebooks for dbs that don't use windows creds

Here's a sample I was trying to write that would use KeyVault where I thought this would have had interpolation support out of the box:
![image](https://user-images.githubusercontent.com/27971797/158482138-694998aa-f465-46cf-be87-3fa2dc43afdb.png)
