### ISSUE TITLE
.NET kernel installation failed with error: Could not find jupyter kernelspec module

### ISSUE THREAD

**Issue by romancerny** [dotnet/interactive#157]
https://devblogs.microsoft.com/dotnet/net-interactive-is-here-net-notebooks-preview-2/#comment-4582

Above link instructs to: "Next, in an ordinary console, install the dotnet interactive global tool:"
`> dotnet tool install --global Microsoft.dotnet-interactive`

By ordinary console I understood Win 10 cmd. After running following command tool installed without errors and confirmed that it was installed successfully.

`> dotnet tool install --global Microsoft.dotnet-interactive --version 1.0.110520`

Following the next step: "Install the .NET kernel by running the following within your Anaconda Prompt:"

`> dotnet interactive jupyter install`

Returns following error. Below are the details of my command execution:

`(base) C:\Users\roman.cerny>jupyter kernelspec list`
Available kernels:
python3 C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\share\jupyter\kernels\python3

`(base) C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\share>dotnet interactive jupyter install`
.NET kernel installation failed with error: Could not find jupyter kernelspec module

The same happens even after restarting my PC

Please advise

Thank you,
Roman

**Comment by romancerny** [comment]
Thank you @jonsequitur , would there be any ETA for this bug fix?

**Comment by colombod** [comment]
PR #337 should address the issue. If the kernelspec module is not found the setup uses the path as indicated in jupyter docs. It is also possible to specify a path at install time
