### ISSUE TITLE
Broken markdown cells in .dib notebooks

### ISSUE THREAD

**Issue by Zeroto** [dotnet/interactive#1576]
### Describe the bug
It seems that yesterday the .net interactive tool updated causing markdown blocks to not be recognized. After loading a .dib file it shows the markdown cells as code cells with `#!markdown` as the first line.

### Steps to reproduce:
1. Create new .dib notebook file
2. Add a markdown cell and enter some text
3. Save the notebook
4. Close and reopen the notebook. The markdown cell is now parsed as a code cell with `#!markdown` as the first line.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

![image](https://user-images.githubusercontent.com/3375059/132269087-f35e3409-e37a-4a9a-9c53-c4f9765bb339.png)

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

**Comment by Ryan-Palmer-CIT** [comment]
I just opened a notebook, .NET Interactive updated and everything broke. As you say, the code and markdown aren't respecting the section markers.

**Comment by Ryan-Palmer-CIT** [comment]
I also just tried rolling back, that didn't work! Bah.

**Comment by Ryan-Palmer-CIT** [comment]
Interestingly, if I create a new notebook, it works fine until I save it, then it instantly breaks.

**Comment by StanislavSeregin** [comment]
I have exactly the same problem. Before launching, I have to repartition the cells to make it work. After reopening, everything is reset again and does not work (

**Comment by Ryan-Palmer-CIT** [comment]
Yeah I just found that if I start a new workbook, the top markdown cell gets saved as code. If change it back to markdown, and clear the #!markdown tag, it works. The underlying file doesn't seem to change though, so weird.

**Comment by brettfo** [comment]
We just published extension version 1.0.2459010 which addresses this issue.
