### ISSUE TITLE
Visual Studio Code's "Jupyter: Variables" view does not display any C# variables

### ISSUE THREAD

**Issue by ArthurFaisman** [dotnet/interactive#1581]
### Describe the bug

Visual Studio Code's "Jupyter: Variables" view does not display any C# variables. See screenshot below

### Please complete the following:

**Which version of .NET Interactive are you using?** 
Version: 1.0.240403+56a0e392fba305af06e72ce7dec885b2b6722c00
Build date: 2021-09-07T20:19:53.1655074Z

- OS
    - [X ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/1471056/132739694-34b5632f-837d-44d6-9d12-7789e2cbcb76.png)

**Comment by thielj** [comment]
Same with PowerShell.

**Comment by jonsequitur** [comment]
We're working with VS Code to enable this feature. I believe it currently only works for Python.

**Comment by jonsequitur** [comment]
.NET Interactive now has its own separate variable explorer. 

<img width="923" alt="image" src="https://user-images.githubusercontent.com/547415/189967158-d94db2ab-92e4-4c1f-ba83-e5efa3c1e040.png">
