### ISSUE TITLE
PowerShell kernel is adding blank lines to all the output

### ISSUE THREAD

**Issue by Jaykul** [dotnet/interactive#159]
#### PowerShell kernel adds blank lines

- [x] .NET Jupyter Notebook 

Every output has two line breaks added to it.

Note that this happens even with `-nonewline` so if I `Write-Host "Hello" -NoNewLine; Write-Host "World"` instead of ending up with "Hello World" on one line, they're actually separated by a blank line. In fact, it happens to every output, including things that are just being output through the formatter:

![image](https://user-images.githubusercontent.com/192942/74247904-c9b30b80-4cb4-11ea-806d-c2af1d865dff.png)

#### Please complete the following:
 - OS
    - [x] Windows 10
 - Frontend
    - [x] nteract

**Comment by daxian-dbw** [comment]
Right. The C# kernel obviously handles the output correctly:

<img width="557" alt="Screen Shot 2020-02-13 at 10 59 59 PM" src="https://user-images.githubusercontent.com/127450/74508731-9a6aed00-4eb4-11ea-8eac-417519f8d426.png">

We will look into it and get it addressed.
