### ISSUE TITLE
All notebook output in VSCode displaying as  "[object Object]" shortly after file opens

### ISSUE THREAD

**Issue by jhoneill** [dotnet/interactive#1592]
### Describe the bug
When a file is loaded output is briefly display and then replaced with the text `[object Object]`

This doesn't seem to happen with a dummy notebook with 1 cell, but with 2 or more it happens for me on multiple machines and even if I remove all my settings  

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
Version: 1.0.245901+0512fe0a05f5a99419a543463ee68233a3c60371

Build date: 2021-09-09T23:54:08.3484654Z

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/16209593/132939773-b604968a-60cf-40a1-9bd6-37e1deaa5242.png)

**Comment by jhoneill** [comment]
Additional  this only appears to impact the "polyglot" .NET interactive kernel. If I switch to the .NET (PowerShell) kernel things are OK, and immediately I switch to the .NET interactive it's [object Object] all the way down (obviously it's the noun but it reads like something is raising an objection like a new kind of error
If  switch kernels back to mono-lingual .NET (PowerShell) I then get `Failed to save 'dummy.ipynb': The "input" argument must be an instance of ArrayBuffer or ArrayBufferView. Received an instance of Object`  if I try to save the file.

**Comment by jonsequitur** [comment]
Could you provide a few screen shots including the larger VS Code UI? I'm not clear about what you mean by the "polyglot" versus "mono-lingual" kernel.

**Comment by Lawlzee** [comment]
Here are some repro steps:
1. using VS Code with this version:
![image](https://user-images.githubusercontent.com/15711142/133715342-48218374-d027-41aa-8075-98e312920ee8.png)
2. Create a ipynb notebook
3. Run this command: `#r nuget:Microsoft.DotNet.Interactive.SqlServer,*-*`
4. Close VS Code
5. Restart VS Code
6. The output looks like this now:
![image](https://user-images.githubusercontent.com/15711142/133715417-84ba547a-186e-4967-bb77-35e3e3752b54.png)

**Comment by jhoneill** [comment]
@jonsequitur    I thought the multi-language kernal ".Net Interactive" was called "polyglot" by other people. Here's the .net powerShell kernel - cells are PowerShell or Markdown 
 
![image](https://user-images.githubusercontent.com/16209593/133755929-06a773ac-21da-4e31-a63a-017ccb5a5b29.png)

Looking at the version this is the version which was installed into Jupyter months ago so did an update,  so its now
Version: 1.0.245901+0512fe0a05f5a99419a543463ee68233a3c60371
Build date: 2021-09-17T09:33:17.1229059Z
No change in behaviour but I notice that **.NET interactive wants to "sieze" notebooks written for this kernel and convert them to the .NET Interactive kernel**  which breaks them. 

Switch kernels and the cells can be PowerShell / C# / F# etc
![image](https://user-images.githubusercontent.com/16209593/133757480-974fefcc-5fe6-46ac-a8c9-7032f1fcb835.png)

If I re-run about I get
Version: 1.0.246201+da749355d416da20e634e5c80073b92356b57e0e
Build date: 2021-09-13T18:09:40.2398727Z

Oddly this is a later version number but an earlier date.
