### ISSUE TITLE
When building ...\src\Microsoft.DotNet.Interactive.Js\dist is not found

### ISSUE THREAD

**Issue by hahoyer** [dotnet/interactive#1612]
Pulled the repo, executed ensure-symlinks, opened the sln file with visual studio 2019.
When building dotnet-interactive with visual studio 2019 it fails with 
`1>CSC : error CS1566: Error reading resource 'Microsoft.DotNet.Interactive.App.resources.dotnet-interactive.js' -- 'Could not find a part of the path 'A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Js\dist\dotnet-interactive.js'.'
`

**Comment by jonsequitur** [comment]
You'll also need to run `npm i` as indicated in the developer guide. Turns out this is needed regardless of whether you're planning to build the VS Code extension. We'll update the docs.

https://github.com/dotnet/interactive/blob/main/DEVELOPER-GUIDE.md#build-and-test

**Comment by jonsequitur** [comment]
@brettfo

**Comment by hahoyer** [comment]
The developer guide says "Run npm i in the <REPO-ROOT>/src/dotnet-interactive-vscode/ directory.", but there is no package.json.
Did you mean dotnet-interactive-vscode-npm? But after executing npm i here the error is still there. 
Btw, the guide talks about code insiders. I want to use it with Visual Studio (19).

**Comment by jonsequitur** [comment]
You only need to use VS Code to work directly on the VS Code extension. You can use VS 2019 for the majority of the codebase. The JavaScript bits that need to be built are the ones that are in Microsoft.DotNet.Interactive.Js (for packaging into the `dotnet-interactive` tool) as well as the ones references by ExtensionLab.csproj. But the normal build **_should_** build them. 

Were there other errors earlier in your build?

**Comment by hahoyer** [comment]
No:

Build started...
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Telemetry\Microsoft.DotNet.Interactive.Telemetry.csproj (in 322 ms).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Formatting\Microsoft.DotNet.Interactive.Formatting.csproj (in 395 ms).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.NetStandard20\Microsoft.DotNet.Interactive.Netstandard20.csproj (in 726 ms).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive\Microsoft.DotNet.Interactive.csproj (in 1,09 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.FSharp\Microsoft.DotNet.Interactive.FSharp.fsproj (in 1,13 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Telemetry.Tests\Microsoft.DotNet.Interactive.Telemetry.Tests.csproj (in 1,15 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.PackageManagement\Microsoft.DotNet.Interactive.PackageManagement.csproj (in 1,19 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.AspNetCore\Microsoft.DotNet.Interactive.AspNetCore.csproj (in 1,29 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Http\Microsoft.DotNet.Interactive.Http.csproj (in 1,12 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.CSharp\Microsoft.DotNet.Interactive.CSharp.csproj (in 1,57 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.ExtensionLab.Tests\Microsoft.DotNet.Interactive.ExtensionLab.Tests.csproj (in 1,35 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Documents\Microsoft.DotNet.Interactive.Documents.csproj (in 98 ms).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.PowerShell\Microsoft.DotNet.Interactive.PowerShell.csproj (in 2,23 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.VSCode\Microsoft.DotNet.Interactive.VSCode.csproj (in 2,27 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Formatting.Tests\Microsoft.DotNet.Interactive.Formatting.Tests.csproj (in 730 ms).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.FSharp.Tests\Microsoft.DotNet.Interactive.FSharp.Tests.fsproj (in 1,08 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Jupyter\Microsoft.DotNet.Interactive.Jupyter.csproj (in 2,39 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.PowerShell.Tests\Microsoft.DotNet.Interactive.PowerShell.Tests.csproj (in 2,5 sec).
Restored A:\develop\Training\interactive\src\dotnet-interactive.Profiler\dotnet-interactive.Profiler.csproj (in 2,58 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.ExtensionLab\Microsoft.DotNet.Interactive.ExtensionLab.csproj (in 1,02 sec).
Restored A:\develop\Training\interactive\src\interface-generator\interface-generator.csproj (in 1,46 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Tests\Microsoft.DotNet.Interactive.Tests.csproj (in 2,72 sec).
Restored A:\develop\Training\interactive\src\dotnet-interactive\dotnet-interactive.csproj (in 2,7 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.CSharp.Tests\Microsoft.DotNet.Interactive.CSharp.Tests.csproj (in 2,71 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.SqlServer.Tests\Microsoft.DotNet.Interactive.SqlServer.Tests.csproj (in 2,77 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Jupyter.Tests\Microsoft.DotNet.Interactive.Jupyter.Tests.csproj (in 2,87 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.SqlServer\Microsoft.DotNet.Interactive.SqlServer.csproj (in 2,87 sec).
Restored A:\develop\Training\interactive\src\dotnet-interactive.Tests\dotnet-interactive.Tests.csproj (in 2,18 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Documents.Tests\Microsoft.DotNet.Interactive.Documents.Tests.csproj (in 1,56 sec).
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Kql\Microsoft.DotNet.Interactive.Kql.csproj (in 1,9 sec).
1>------ Build started: Project: Microsoft.DotNet.Interactive.Formatting, Configuration: Debug Any CPU ------
2>------ Build started: Project: Microsoft.DotNet.Interactive.Documents, Configuration: Debug Any CPU ------
3>------ Build started: Project: Microsoft.DotNet.Interactive.Telemetry, Configuration: Debug Any CPU ------
Restored A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Kql.Tests\Microsoft.DotNet.Interactive.Kql.Tests.csproj (in 2,04 sec).
3>Microsoft.DotNet.Interactive.Telemetry -> A:\develop\Training\interactive\artifacts\bin\Microsoft.DotNet.Interactive.Telemetry\Debug\net5.0\Microsoft.DotNet.Interactive.Telemetry.dll
2>Microsoft.DotNet.Interactive.Documents -> A:\develop\Training\interactive\artifacts\bin\Microsoft.DotNet.Interactive.Documents\Debug\netstandard2.0\Microsoft.DotNet.Interactive.Documents.dll
1>Microsoft.DotNet.Interactive.Formatting -> A:\develop\Training\interactive\artifacts\bin\Microsoft.DotNet.Interactive.Formatting\Debug\netstandard2.0\Microsoft.DotNet.Interactive.Formatting.dll
4>------ Build started: Project: Microsoft.DotNet.Interactive, Configuration: Debug Any CPU ------
4>Microsoft.DotNet.Interactive -> A:\develop\Training\interactive\artifacts\bin\Microsoft.DotNet.Interactive\Debug\netstandard2.1\Microsoft.DotNet.Interactive.dll
5>------ Build started: Project: Microsoft.DotNet.Interactive.PackageManagement, Configuration: Debug Any CPU ------
6>------ Build started: Project: Microsoft.DotNet.Interactive.PowerShell, Configuration: Debug Any CPU ------
7>------ Build started: Project: Microsoft.DotNet.Interactive.Http, Configuration: Debug Any CPU ------
7>Microsoft.DotNet.Interactive.Http -> A:\develop\Training\interactive\artifacts\bin\Microsoft.DotNet.Interactive.Http\Debug\net5.0\Microsoft.DotNet.Interactive.Http.dll
5>Microsoft.DotNet.Interactive.PackageManagement -> A:\develop\Training\interactive\artifacts\bin\Microsoft.DotNet.Interactive.PackageManagement\Debug\netstandard2.1\Microsoft.DotNet.Interactive.PackageManagement.dll
8>------ Build started: Project: Microsoft.DotNet.Interactive.CSharp, Configuration: Debug Any CPU ------
9>------ Build started: Project: Microsoft.DotNet.Interactive.FSharp, Configuration: Debug Any CPU ------
6>Microsoft.DotNet.Interactive.PowerShell -> A:\develop\Training\interactive\artifacts\bin\Microsoft.DotNet.Interactive.PowerShell\Debug\net5.0\Microsoft.DotNet.Interactive.PowerShell.dll
8>Microsoft.DotNet.Interactive.CSharp -> A:\develop\Training\interactive\artifacts\bin\Microsoft.DotNet.Interactive.CSharp\Debug\netstandard2.1\Microsoft.DotNet.Interactive.CSharp.dll
10>------ Build started: Project: Microsoft.DotNet.Interactive.AspNetCore, Configuration: Debug Any CPU ------
10>Microsoft.DotNet.Interactive.AspNetCore -> A:\develop\Training\interactive\artifacts\bin\Microsoft.DotNet.Interactive.AspNetCore\Debug\net5.0\Microsoft.DotNet.Interactive.AspNetCore.dll
9>Microsoft.DotNet.Interactive.FSharp -> A:\develop\Training\interactive\artifacts\bin\Microsoft.DotNet.Interactive.FSharp\Debug\net5.0\Microsoft.DotNet.Interactive.FSharp.dll
11>------ Build started: Project: Microsoft.DotNet.Interactive.Jupyter, Configuration: Debug Any CPU ------
12>------ Build started: Project: Microsoft.DotNet.Interactive.VSCode, Configuration: Debug Any CPU ------
12>Microsoft.DotNet.Interactive.VSCode -> A:\develop\Training\interactive\artifacts\bin\Microsoft.DotNet.Interactive.VSCode\Debug\net5.0\Microsoft.DotNet.Interactive.VSCode.dll
11>Microsoft.DotNet.Interactive.Jupyter -> A:\develop\Training\interactive\artifacts\bin\Microsoft.DotNet.Interactive.Jupyter\Debug\net5.0\Microsoft.DotNet.Interactive.Jupyter.dll
13>------ Build started: Project: dotnet-interactive, Configuration: Debug Any CPU ------
13>Zipping directory "A:\develop\Training\interactive\artifacts\obj\dotnet-interactive\Debug\net5.0\dotnetKernel" to "A:\develop\Training\interactive\artifacts\obj\dotnet-interactive\Debug\net5.0\dotnetKernel.zip".
13>CSC : error CS1566: Error reading resource 'Microsoft.DotNet.Interactive.App.resources.dotnet-interactive.js' -- 'Could not find a part of the path 'A:\develop\Training\interactive\src\Microsoft.DotNet.Interactive.Js\dist\dotnet-interactive.js'.'
13>Done building project "dotnet-interactive.csproj" -- FAILED.
========== Build: 12 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by brettfo** [comment]
@hahoyer Our build has a lot of moving parts (more than I'd like, really) so the only truly supported way to build is to run `ensure-symlinks`, followed by `build.cmd`.  Only then can the .sln be opened in VS.  I'll work on updating our documentation.

**Comment by GeorgeS2019** [comment]
There is no Microsoft.DotNet.Interactive.Js directory

**Comment by GeorgeS2019** [comment]
`ensure-symlinks` unfortunately does now work with an exFAT  formated drive :-(

`The device does not support symbolic links`

**Comment by GeorgeS2019** [comment]
> There is no Microsoft.DotNet.Interactive.Js directory
> `ensure-symlinks` unfortunately does now work with an exFAT formated drive

Once I git clone in non exFAT drive, I could 

```
ensure-symlinks
dotnet build
```

**Comment by jonsequitur** [comment]
I don't think making the build work without symlink support is something the dev team can prioritize. Is there any additional work to be done here or can we close this?

**Comment by GeorgeS2019** [comment]
`DEVELOPER-GUIDE.md` has been [updated](https://github.com/dotnet/interactive/issues/2128#issuecomment-1182039997)

From my side, it is fine to close it.
