### ISSUE TITLE
Notebook cell does not run after selecting kernel

### ISSUE THREAD

**Issue by misolori** [dotnet/interactive#1627]
### Describe the bug
Originally filed in https://github.com/microsoft/vscode/issues/129652

After installing the .NET Interactive notebook for the first time and .NET Interactive is finished installing, I attempted to run a cell. The notebook then asked me to select a kernel, and I chose .NET Interactive, and then the notebook did nothing. I had to push "run" again for it to actually run. I'd expect for this to automatically run after selecting the kernel.

### Please complete the following:

**Which version of .NET Interactive are you using?** 
1.0.250101+54a43fc43a67677d935256b24c6bf334fb8dafec

- OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [x] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots

@ 00:58 is when I attempt to re-run the cell

https://user-images.githubusercontent.com/35271042/135929628-21320177-a40a-4350-9976-9e121aebc7a3.mp4

**Comment by colombod** [comment]
Not sure what is happening, are you referring to the fact that on hitting run button you get a prompt to select a kernel and then the cell is not executed until you actually press again the run button?
