### ISSUE TITLE
[F#] Arithmetic operation (*) gets greyed out like a comment

### ISSUE THREAD

**Issue by GustavoFenilli** [dotnet/interactive#1629]
### Describe the bug
When piping using the operation (*) `x |> (*) y`, the end of *) gets greyed out as it was a comment.

### Please complete the following:

**Which version of .NET Interactive are you using?**

Version: 1.0.246201+da749355d416da20e634e5c80073b92356b57e0e
Build date: 2021-09-12T07:21:44.0000000Z

- OS
    - [x] Windows 10
    - [ ] macOS
    - [x] Linux: WSL2 Debian
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/14954720/135942342-8a75f8b3-3e7a-477b-bf22-bf022895d743.png)

**Comment by jonsequitur** [comment]
This is an issue with VC Code's built-in F# grammar.
