### ISSUE TITLE
The first notebook opened in VSCode fails to detect .NET interactive kernel type

### ISSUE THREAD

**Issue by jhoneill** [dotnet/interactive#1655]
### Describe the bug
When VS Code starts, if you open an existing .Net interactive  ipynb file VSCode briefly displays "Python 3" and then "Select Kernel" . And the cells are displayed with their language but without  (.Net Interactive) following the language name 
After you select the correct Kernel, everything works correctly for that notebook. 
Opening another notebook, or closing all notebooks and then re-opening one results in those notebooks being opened correctly. Correct behaviour continues until you next open VS Code. 
 

### Please complete the following:

**Which version of .NET Interactive are you using?** 
**Version:** 1.0.250604+e99bd250539a64e828b44cb9ad9353eeda9b5bc1     
**Build date:** 2021-10-12T06:41:06.2516566Z

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
We think this might be a performance issue, at least in the cases we've been able to repro. If you wait a while, does the kernel selector change on its own to .NET Interactive?

**Comment by jhoneill** [comment]
@jonsequitur this no longer occurs on my system. IIRC it wasn't changing for minutes, but whatever the cause it is now working properly. If I see it again I'll investigate and come back but I'll close this issue
