### ISSUE TITLE
How to pass big objects between js kernel and c# kernel

### ISSUE THREAD

**Issue by PawelStadnicki** [dotnet/interactive#1658]
if I understand correctly there must be some HTTP limit while sharing data between kernels.
In particular I cannot send bigger json data than ~100 items. 
Running vscode is there a way to enforce other transport layer that works with that ?
I guess that with js we must stick to HTTP nevertheless ...

**Comment by jonsequitur** [comment]
There will be direct API support for this very soon, which won't require HTTP. The values will go over commands and events.

Watch this space: #1631

**Comment by PawelStadnicki** [comment]
Great! Is this something that also will make work  JS Kernel in Codespaces?
