### ISSUE TITLE
Install error - The specified framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found

### ISSUE THREAD

**Issue by dullroar** [dotnet/interactive#166]
#### Describe the bug
Tried to install following instructions. Installed on dotnet 3.1, resulting in:

```bash
> dotnet --version
3.1.101
```
Looking in apt:

- dotnet-runtime-3.1 is at version 3.1.1-1
- dotnet-sdk-3.1 is at version 3.1.101-1
- aspnetcore-runtime-3.1 is at version 3.1.1-1.

However, when I then try:

```bash
> dotnet interactive jupyter instal
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      3.0.0-preview6.19307.2 at [/home/lehmer/dotnet/shared/Microsoft.AspNetCore.App]
```
#### Please complete the following:
 - OS
    - [ ] Windows 10
    - [ ] macOS
    - [x] Linux (Linux Mint 19.3)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Safari
 - Frontend
    - [ ] Jupyter notebook
    - [ ] Jupyter lab
    - [ ] nteract

**Comment by jonsequitur** [comment]
Could you provide the output of the `dotnet --info` command?

**Comment by dullroar** [comment]
```bash
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  19.3
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by floriwanna** [comment]
Have you find any solution for this error?

**Comment by dullroar** [comment]
I figured this out. I had a dotnet folder in my home directory that was conflicting with the global install for some reason. I did an `rm -rf dotnet` and then I could install it into Jupyter.

**Comment by YashDjsonDookun** [comment]
hi, i'm getting the following issue while trying a basic asp web app. I added the dotnet --info for reference. is there any fix? I don't have the conflicting dotnet folder in my home directory issue that @dullroar suggested :/

'It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=arcolinux-x64'



`dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.107
 Commit:    617a3e03f4

Runtime Environment:
 OS Name:     arcolinux
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.107/

Host (useful for support):
  Version: 3.1.7
  Commit:  6997f78ba5

.NET Core SDKs installed:
  3.1.107 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
`

**Comment by jonsequitur** [comment]
Can you try installing the latest .NET Core 3.1 SDK?

**Comment by YashDjsonDookun** [comment]
Hi @jonsequitur , thank you for your reply.

installing the latest SDK didn't work on the spot for some reasons.. I still had the same error.

HOWEVER, i went on and completely removed any dotnet related files on my machine and did a clean install via the 'install-script' and it seems to be working now. Thanks again.
