### ISSUE TITLE
KQL Kernel doesn't handle empty lines in cells

### ISSUE THREAD

**Issue by Charles-Gagnon** [dotnet/interactive#1662]
### Describe the bug

When executing a cell with a blank line in it something seems to go wrong with sending the query to the backend and it errors out. 

e.g. 

```
#!kql-mydatabase
let x = "Hello world!";
let y = 10;

print x, y;
```

fails. This works just fine in Data Explorer though. 

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

Latest from main

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/28519865/137405417-b6800c19-7124-4f3a-bdc0-ac7bbb35cd50.png)

**Comment by Charles-Gagnon** [comment]
@JustinMDotNet FYI

**Comment by JustinMDotNet** [comment]
Looks like this happens in ADS as well. I'll look into solving this on the Kusto Tool Service side which will require updating the ToolsService version in .NET Interactive Notebooks.

![image](https://user-images.githubusercontent.com/63619224/137546061-dddba89c-6353-4674-bd13-1c8df6bafa2f.png)

**Comment by colombod** [comment]
Is this addressed?

**Comment by Charles-Gagnon** [comment]
@JustinMDotNet 

I haven't seen anything about this in the tools service repo so I don't believe it has been.

**Comment by JustinMDotNet** [comment]
Sorry for not responding to this sooner. This is actually part of the syntax for Kusto. I verified this issue exists in Kusto Explorer.

![image](https://user-images.githubusercontent.com/63619224/139787196-b0d244a2-2881-46ef-a434-ea99ac817e63.png)

**Comment by Charles-Gagnon** [comment]
Oh huh, well that's weird. Could swear it worked for me when I tried it in data explorer earlier...ok well I don't understand why this behaves like this but guess we can close this as "working as intended"

**Comment by JustinMDotNet** [comment]
> Oh huh, well that's weird. Could swear it worked for me when I tried it in data explorer earlier...ok well I don't understand why this behaves like this but guess we can close this as "working as intended"

I thought so too :-\. Sorry for the confusion, I should've mentioned sooner.
