### ISSUE TITLE
Unable to use Tensors in Jupyter notebook due to loading errors

### ISSUE THREAD

**Issue by dasMulli** [dotnet/interactive#17]
#### Describe the bug

I'm currently trying to use the Jupyter kernel with ML.NET and the OnnxRuntime to prototype model inference based on pre-computed onnx models.
However I am unable to use System.Numerics.Tensors to create inputs to the model:

(EDIT - updated to minimal repro)
```csharp
#r "nuget:Microsoft.ML.OnnxRuntime,1.1.0"

using System.Numerics.Tensors;
var inputValues = new[]{12f, 10f, 17f, 5f};
var tInput = new DenseTensor<float>(inputValues.AsMemory(), new ReadOnlySpan<int>(new[]{4}));
```

errors with:
```
Unhandled Exception
Could not load file or assembly 'System.Numerics.Tensors, Version=0.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
   at Submission#23.<<Initialize>>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Submission#23.<Initialize>()
   at Submission#23.<Factory>(Object[] submissionArray)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

This apperently tries to load a reference assembly into the runtime.
/cc @eerhardt 

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [x] .NET Jupyter Notebook 
- [ ] online

#### What kind of error was it?
- [x] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge (Dev Channel)
    - [ ] Safari

**Comment by KevinRansom** [comment]
Thanks mate, closing this now.
