### ISSUE TITLE
Is dotnet interactive compatible with ARM architecture?

### ISSUE THREAD

**Issue by EverybodyKurts** [dotnet/interactive#1717]
**The package and version I'm asking about**: 

microsoft.dotnet-interactive      1.0.225503

### Question

Is dotnet interactive compatible on ARM architecture? Even after the release of dotnet 6, I still can't run dotnet interactive on my 2020 Macbook Air.

**Comment by colombod** [comment]
Can you share more? I have been running .NET Interactive with vscode on raspberry pi without issues.

**Comment by colombod** [comment]
what .NET ask do you have installed, can you run dotnet --list-sdks and paste the results?

**Comment by EverybodyKurts** [comment]
Hey Diego, here you go:

```
% dotnet --list-sdks
6.0.100-rc.2.21505.57 [/usr/local/share/dotnet/sdk]
6.0.100 [/usr/local/share/dotnet/sdk]
```

**Comment by colombod** [comment]
you need (at the moment) .net 5, we have not yet released .NET 6 version. You need to install .NET core 5 too if you want to run it today
