### ISSUE TITLE
Jupyter Lab error out in Windows Subsystem for Linux (WSL2).

### ISSUE THREAD

**Issue by MaximoTrinidad** [dotnet/interactive#172]
**Is your feature request related to a problem? Please describe.**
Yes! I'm getting an error when trying to run "jupyter lab" to run notebook in WSL.

I'm sure that this not available yet. But, it would be a *NICE* to have it working on WSL

```
PS C:\Windows\System32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.19559
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Windows\System32>
```
Windows 10 Insider
```
(OS Build 19559.1000)
```
WSL - 2
```
(base) maxt@earth:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
(base) maxt@earth:~$
```
Anaconda 2019.10
```
(base) maxt@earth:~$ conda info

     active environment : base
    active env location : /home/maxt/anaconda3
            shell level : 1
       user config file : /home/maxt/.condarc
 populated config files :
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages :
       base environment : /home/maxt/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/maxt/anaconda3/pkgs
                          /home/maxt/.conda/pkgs
       envs directories : /home/maxt/anaconda3/envs
                          /home/maxt/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/4.19.84-microsoft-standard ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

(base) maxt@earth:~$
```
![dotnet_wsl2_2020-02-14_17-51-38](https://user-images.githubusercontent.com/19892435/74575077-a8bc1600-4f53-11ea-922d-67b50d815b7b.png)

**Comment by henrybowers** [comment]
I'm wondering if this error is caused by dual Anaconda installations. I installed Anaconda for Windows 10, then upgraded to WSL2 release, then installed Anaconda for Ubuntu without uninstalling Anaconda for Windows. I get the same error as Maximo (above) when I run jupyter-lab in Ubuntu terminal (and powershell term and cmd term). Running jupyter-lab from anaconda shell is error-free.

**Comment by MaximoTrinidad** [comment]
@henrybowers 

You are probably right! I got dual Anaconda installed. 
Curious! What's the "conda info" difference between the two?  

I will update my environment and see if it help in any way. 
:)

**Comment by MaximoTrinidad** [comment]
@henrybowers 

Hum! I think the issue is more related to my chrome browser not been able to open from within WSL. 

Which browser are you using?
And, is it opening a Windows or Linux internet browser?

I will try a few more things and see where I get with it.

**Comment by MaximoTrinidad** [comment]
@henrybowers 

How did you fix the browser issue?  Or, what browser are you using? Windows or Linux internet browser?

I know that WSL doesn't include an internet browser, and I couldn't find any help about installing either Chrome nor Firefox browsers in WSL. They are all hard to implement. 

I even created the alias to point to Windows Chrome app, but I'm still getting the error.

At least I can copy/paste the Notebook URL to a Windows Chrome and it works!

![WSL_Error_2020-04-07_11-06-07](https://user-images.githubusercontent.com/19892435/78698158-e2642a00-78cf-11ea-943b-818bf611333c.png)

![WSL_WChrome_2020-04-07_11-06-07](https://user-images.githubusercontent.com/19892435/78698706-b7c6a100-78d0-11ea-8c3b-459d4fa6241e.png)


:)

**Comment by jonsel087** [comment]
@MaximiTrinidad - I don't know the answer, but I think you are on to something here. My WAG is that some port configuration needs to be done. For me, the notebook seems to work fine, but the server process logs an error on every click, leading me to believe it's not handling server callbacks well.

**Comment by henrybowers** [comment]
FWIW, I had to turn off jupyter authentication to get JupyterLab to start without errors. This was with  nodeJS installed and running `jupyter lab` (from ubuntu terminal). JupyterLab UI does not automatically open in browser. Instead I manually open [localhost](http://localhost:8888/lab) in a browser running on Windows10 (usually Chrome for me). To turn off authentication:

1. open jupyter_notebook_config.py file (found in ~/.jupyter dir with anaconda install in ubuntu)
2. turn off token requirement: `c.NotebookApp.token = ''`

Turning off authentication is NOT RECOMMENDED by JupyterLab authors. Since I am running a single-user, local-access-only instance, my security risk is very low.

**Comment by janreitz** [comment]
You can have jupyter notebook open the browser directly from wsl by disabling this option:

`c.NotebookApp.use_redirect_file = False`

By default, jupyter will try to open a redirect file with your browser. but the windows browser cannot find the wsl file path. This is where the file not found error comes from. This option let's you revert back to just opening the link in the browser.

**Comment by MaximoTrinidad** [comment]
@janreitz 

Damn!! This is it!!!!

Adding the line:
```
c.NotebookApp.use_redirect_file = False
```
Did the magic.

Thank You Very Much! 

👍
