### ISSUE TITLE
The .NET SDK version 5.0.400 is not sufficient.  The minimum required version is 6.0.

### ISSUE THREAD

**Issue by brettfo** [dotnet/interactive#1723]
(VS Code - Insiders) - When opening a notebook you may see the error message:

```
The .NET SDK version 5.0.400 is not sufficient.  The minimum required version is 6.0.
```

The extension now requires .NET 6.  To update your machine please:

1. Install the .NET SDK version 6.0.100 from [here](https://dotnet.microsoft.com/download/dotnet/6.0).
2. Restart VS Code - Insiders.

**Comment by wsmelton** [comment]
Small note the following readmes for the extensions with VS Code should be updated to note this update:

- [Insiders](https://github.com/dotnet/interactive/blob/main/src/dotnet-interactive-vscode/insiders/README.md)
- [Stable](https://github.com/dotnet/interactive/blob/main/src/dotnet-interactive-vscode/stable/README.md)
