### ISSUE TITLE
Error launch New interactive NoteBook

### ISSUE THREAD

**Issue by JM2K69** [dotnet/interactive#1729]
### Describe the bug
I install Visual Studio 2022 and After this i can't launch new netbook in vscode October version. I was not able to create anything.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`. 
![image](https://user-images.githubusercontent.com/17923944/141325555-b7f7762c-9e62-45d3-b4f9-4930ded0c57c.png)

- OS
    - [x] Windows 11

 - Frontend
    - [x] Jupyter Notebook
    - [ ] Jupyter Lab
    - [x] Visual Studio Code 
    - [ ] .NET interactive Notebook

### Screenshots
* The error in vsCode il like this

![image](https://user-images.githubusercontent.com/17923944/141318195-f5352b8a-75a5-47ef-a8c4-a00e85b5c1e8.png)
* SDK install
![image](https://user-images.githubusercontent.com/17923944/141318477-47417306-7db9-4b8f-8147-9c0151802d9a.png)
* .NET Interactive Notebooks version
![image](https://user-images.githubusercontent.com/17923944/141318828-4301b161-59f4-4266-a94a-51c332bde450.png)
* Environment Path
 ![image](https://user-images.githubusercontent.com/17923944/141319586-6be83d46-1e8f-4677-a83c-e2757fca37ef.png)

**Comment by colombod** [comment]
is this reproducing everytime? I have installed 2022 too (removed 2019) and updated vscode to matchign version. I don't get the extensionregistration error. Do you know if there are any additional step I can perform to try to reproduce this issue?

**Comment by JM2K69** [comment]
There isn't additional step. In CLI I try Dotnet interactive  -version I have a error I post screenshot tomorow.

**Comment by JM2K69** [comment]
I try this with no result 
![image](https://user-images.githubusercontent.com/17923944/141444979-59c93787-8250-484d-9fb0-121478649d88.png)

**Comment by halcwb** [comment]
I think this is the same as my issue #1775

**Comment by colombod** [comment]
Microsoft.dotnet-interactive isntalled like that i using the pacakge on nuget.org, that version is still Net 5.0 to install the latest build (the one insiders uses) look at this [documentation](https://github.com/dotnet/interactive/blob/main/docs/NotebookswithJupyter.md) and the way the global tool is installed is 
```
dotnet tool install -g --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" Microsoft.dotnet-interactive
```

**Comment by colombod** [comment]
How often do you pdate vscode? This seesm related to #1775

**Comment by JM2K69** [comment]
> Microsoft.dotnet-interactive isntalled like that i using the pacakge on nuget.org, that version is still Net 5.0 to install the latest build (the one insiders uses) look at this [documentation](https://github.com/dotnet/interactive/blob/main/docs/NotebookswithJupyter.md) and the way the global tool is installed is
> 
> ```
> dotnet tool install -g --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" Microsoft.dotnet-interactive
> ```

I can't run this command-line I have this error
![image](https://user-images.githubusercontent.com/17923944/142589061-aed44129-77c2-4de3-9ce2-5e45e059f2cb.png)
![image](https://user-images.githubusercontent.com/17923944/142589126-6c56d443-e97b-4189-86fc-957df13eea67.png)

**Comment by JM2K69** [comment]
> Microsoft.dotnet-interactive isntalled like that i using the pacakge on nuget.org, that version is still Net 5.0 to install the latest build (the one insiders uses) look at this [documentation](https://github.com/dotnet/interactive/blob/main/docs/NotebookswithJupyter.md) and the way the global tool is installed is
> 
> ```
> dotnet tool install -g --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" Microsoft.dotnet-interactive
> ```

I successful Install dotnet-interactive 
![image](https://user-images.githubusercontent.com/17923944/142590038-f3d5c6bc-9f75-4c9f-91ac-e2738c4cd691.png)

but I think there is an error wit environement path beacuse it don't work with  VSCode

**Comment by JM2K69** [comment]
I have only Jupyter Stdio notebook-parser and http command it's normal ?

**Comment by colombod** [comment]
the commands are fine, vscode uses teh stdio mode.

**Comment by colombod** [comment]
the other issue you quote is about the local storage in the user folder of vscode, to make sure I have all information
you are using VScode stable build, not insider.
Can you ensure is latest vesion of vscode?
Have you been upgrading vscode regulalry (it seems they change settings format and the upgrades would have addressed that unless the jump in version was too big)
Do you have any modified settings for .NET Interactive notebooks? 

Happy to jump on a call if you want to share screen.

**Comment by colombod** [comment]
Is this issue still happening for you?

**Comment by JM2K69** [comment]
Yes I'm using  always the lastest stable vscode I try to remove it completly and try to reinstall all extensions but always the same issue

**Comment by colombod** [comment]
have you tried (last and definitive) removing the cached settings?
they would be folders like 
`%appData%\Roaming\Code\User`
and 
`%appData%\Roaming\Code - Insiders\User`

@rebornix anything I am missing?

**Comment by JM2K69** [comment]
I clean ```%appData%\Roaming\Code``` and all subfolders and I have always the same error.

**Comment by JM2K69** [comment]
I think there is another issue in my environment path I have this : 
![image](https://user-images.githubusercontent.com/17923944/144220886-165209ce-748b-4d3a-bcf0-8cba9df76a4d.png)
In Windows terminal I have this 
![image](https://user-images.githubusercontent.com/17923944/144221023-8265a64e-0795-4998-99cf-d34a855e33c2.png)
I must be in the correct folder 
![image](https://user-images.githubusercontent.com/17923944/144221498-bbcb47da-0cda-464c-8d3d-ff22435de1ec.png)

**Comment by JM2K69** [comment]
I solved th issue $Env:path il all cmd or powershell I can use dotnet-interactive command

**Comment by colombod** [comment]
wow, sorry I could not be of concrete help. So you can now run with success?

**Comment by JM2K69** [comment]
No i can't create a New notebook.🤬

**Comment by colombod** [comment]
can we do a screen share? It is hard to understand the issue for me

**Comment by JM2K69** [comment]
![code](https://user-images.githubusercontent.com/17923944/144235919-19d79cf3-4f84-4058-a868-cf9d405fd758.gif)

**Comment by colombod** [comment]
what is in the output window? or the developer tool? Can you make it to a teams call?

**Comment by JM2K69** [comment]
I'm not available now for a call

**Comment by colombod** [comment]
when is convenient for you, let me know

**Comment by JM2K69** [comment]
I successflly install dotnet-interactive jupyter install
![image](https://user-images.githubusercontent.com/17923944/144237378-260cd7a2-8a24-48a9-be83-4f34491ca360.png)

**Comment by colombod** [comment]
Installing the global tool is to be supported in jupyter lab or notebook, that will require you  to also handle updates for .NET Interactive via hte command line.  I am trying to help you with the vscode issues, but i need to see the output view of the .NET Interactive diagnostics and if htere is any error showing hte the developer tool. do you know how to retrieve those informations? Still my offer to meet in a call and try to narrow down the problem stands.

**Comment by JM2K69** [comment]
I found 1 thing's the command line dotnet --info don't return SDK
![image](https://user-images.githubusercontent.com/17923944/144246368-b64b57f9-472a-4178-823c-342b499f5079.png)
but i have installed them
![image](https://user-images.githubusercontent.com/17923944/144246455-3e6130cb-a793-470f-994c-4004f2a50e50.png)

**Comment by JM2K69** [comment]
I found I need to move up in my Path C:\Program Files\dotnet\ and my SDK are detected and now it work's

**Comment by iainsproat** [comment]
I experienced a similar issue; I documented my steps to resolve here: https://github.com/dotnet/interactive/issues/1775#issuecomment-1013720312

**Comment by Mic-360** [comment]
> I found I need to move up in my Path C:\Program Files\dotnet\ and my SDK are detected and now it work's

how you solved this, can u tell a little more about it ? 
I'm using Windows !! VsCode insiders.

```
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22581
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by iSeiryu** [comment]
I'm on a Mac with an Intel CPU. It's been working for me just fine for months but today it started showing this
```shell
Command '.NET Interactive: Create new blank notebook' resulted in an error (command 'dotnet-interactive.newNotebook' not found)
```
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/129137/187950882-b752d7c5-fc1e-4cee-84e9-fdf8e6c50b41.png">

I already had .NET SDK 6.0.302 and went ahead and downloaded the latest. It did not solve the problem. Here is my current output:
```shell
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.400/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.302 [/usr/local/share/dotnet/sdk]
  6.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by iSeiryu** [comment]
I fixed it by running
```
dotnet tool install -g Microsoft.dotnet-interactive
```

I'd hope the VSCode extension would take care of it (as it did before, since I never had to run this command manually).

**Comment by ashwin759** [comment]
how to fix localhost9222 error in vs code . I have  installed the 2024 vs code I deleted the vs code and again I have installed it but its not working  I have checked at all coding platform even in github there is no solution can you fix this
