### ISSUE TITLE
Variable sharing between SQL cells and C#

### ISSUE THREAD

**Issue by LSTANCZYK** [dotnet/interactive#1735]
### Discussed in https://github.com/dotnet/interactive/discussions/1733

<div type='discussions-op-text'>

<sup>Originally posted by **LSTANCZYK** November 12, 2021</sup>
I am looking at `Variable sharing.ipynb`
Is it possible to take SQL cell result set (from SQL subkernel) and pass it to C# as a variable (say DataFrame or dynamic/Expando object)?
</div>

**Comment by colombod** [comment]
yes, it is possible to share in both directions.

To be able to share sql cell result you must give that result a name

```
#!sql-mydb --name myData
select ....
```

then in c#
```
#!share --from sql-mydb myData
myData[0].Display();
```

the variable myData is a colelction sicne you can perform more then one query in sql or kql cells. (same applies to kusto extension)

**Comment by teauxfu** [comment]
thanks for this! would be great to see such an example here on the docs 
https://github.com/dotnet/interactive/blob/main/docs/variable-sharing.md
