### ISSUE TITLE
Loading external JavaScript modules at runtime is not working

### ISSUE THREAD

**Issue by naramdash** [dotnet/interactive#1742]
**The package and version I'm asking about**: 

`vscode 1.62.2`
`vscode extension .net interactive notebook v1.0.2559020`

### Question

I just did copy and paste example code on [js overview doc](https://github.com/dotnet/interactive/blob/main/docs/javascript-overview.md#loading-external-javascript-modules-at-runtime),

but it is not working with error `Error: interactive.configureRequire is not a function`

![image](https://user-images.githubusercontent.com/24370799/141707827-a79e4b56-0028-4bc9-9d6c-68c2f3e96cff.png)

What else should I do?

**Comment by eosfor** [comment]
Hello @colombod , what should I do to make it work after this patch? I assume it was not yet released, right? so the extension was not updated.

**Comment by colombod** [comment]
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/375556/144009546-f3844409-56e6-487a-bfa6-6b3f70d5f768.png">

**Comment by eosfor** [comment]
Here is what i see in my freshly installed insiders

![image](https://user-images.githubusercontent.com/9363027/144117754-cf7d9807-4a33-473b-89a1-3d78a2d1fcd0.png)

**Comment by colombod** [comment]
for insiders at the moment we require .NET 6 sdk, how long since you last vscode insiders update?

**Comment by eosfor** [comment]
I just installed it. but perhaps I need to install  .NET 6 SDK. let me do it quickly

**Comment by eosfor** [comment]
![image](https://user-images.githubusercontent.com/9363027/144119962-3c6e8b64-c185-4f49-8d9b-cf66723d5311.png)

still the same. end even if I open a notebook, it does not see the .net interactive kernel

![image](https://user-images.githubusercontent.com/9363027/144120266-5f8acf45-1224-4a29-964c-16e3fba4bd56.png)

**Comment by eosfor** [comment]
These are the only packages there

![image](https://user-images.githubusercontent.com/9363027/144120421-e221c05a-c585-4e91-becb-ae1e29944d91.png)

**Comment by colombod** [comment]
can you try one thing,
bring up the command palette (CRTL+SHIFT+P on windows) and look for the command `Developer: Clear Notebook Editor Cache`
then close and reopen vscode insiders and try to reopen the notebook with the js loading. I am trying to see if this is an issue I saw before with stale vscode user settings that do not get clean up.

**Comment by colombod** [comment]
We found a bug, give us a few minutes, we are releasing a new version soon

**Comment by colombod** [comment]
This one : #1796

**Comment by eosfor** [comment]
oh, no, after all these manipulations like installing global .net interactive, + NET SDK 6 my normal vscode stuff stopped working. i can't even open notebooks there anymore :(
