### ISSUE TITLE
Item template did not install

### ISSUE THREAD

**Issue by mnagatos101** [dotnet/interactive#1767]
### Describe the bug
On my work laptop, I installed the extension.  When I try to add a new item to a C# console app, I don't see the notebook option for a new item.  On a customer dev machine I did the same thing and I do see the notebook item.  Not sure what's different.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
I am not able to open a notebook and the dotnet interactive command is not recognized from the command line.
* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [X] Other (please specify)  Visual Studio

### Screenshots
![Capture1](https://user-images.githubusercontent.com/35544902/142255571-546654fb-e647-4742-a891-1a342817493f.PNG)
![Capture](https://user-images.githubusercontent.com/35544902/142255577-188fd739-553f-469d-9efe-5cd88d362caf.PNG)
![Capture2](https://user-images.githubusercontent.com/35544902/142255579-5ef48e19-a52d-4e24-b662-c7d04e184aa8.PNG)

**Comment by JakeRadMSFT** [comment]
Can you try searching for it?

![image](https://user-images.githubusercontent.com/31937616/142260330-2607b5be-cae5-4162-9e89-4295ece41466.png)

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud have you ever seen this? Would clearing a cache help?

**Comment by LittleLittleCloud** [comment]
Maybe try clear VS cache and see if item template comes back? You can do this through opening command line in VS tool tab and run the following command

> devenv.exe /clearCache

**Comment by JakeRadMSFT** [comment]
@mnagatos101 did clearing the cache help resolve the issue?

**Comment by konst-sh** [comment]
I'm having the same issue on VS Community 2022 17.0.4. Notebook Editor is installed but no template/shortcut for notebook creation is available in the UI. VS installation repairing and cache cleaning didn't help.

**Comment by jonsequitur** [comment]
@mnagatos101 @konst-sh Are you still seeing this issue?

**Comment by konst-sh** [comment]
Yes, there are no shortcut for notebook creation still.

  
>Вторник, 12 апреля 2022, 20:20 +03:00 от Jon Sequeira ***@***.***>:
> 
> 
***@***.*** @konst-sh Are you still seeing this issue?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you were mentioned. Message ID:  <dotnet/interactive/issues/1767/1096991800 @ github . com> 
 
 
--
Константин Шириазданов

**Comment by brettfo** [comment]
The notebook experience is being consolidated in VS Code.
