### ISSUE TITLE
Do Not See nteract Rendering

### ISSUE THREAD

**Issue by DonJayamanne** [dotnet/interactive#1780]
Originally filled here https://github.com/microsoft/vscode-notebook-renderers/issues/79 by @Eddie-Hartman

Hello.

I followed this post https://devblogs.microsoft.com/dotnet/net-interactive-with-sql-net-notebooks-in-visual-studio-code/#querying-and-visualizing-data
and was able to query some data in my database. Unfortunately, it doesn't appear to be rendering with nteract as described.

>The results of the query are displayed using the nteract Data Explorer,providing a rich interactive filter and visualization experience where the user can explore their data in a number of ways.

Can anyone point me in the right direction here? I just see results as essentially an HTML table and the only other option is csv, but there appear to be no renderers available for that.

![image](https://user-images.githubusercontent.com/14089997/142567804-f2b713ff-b416-428e-907e-0dbaed84748d.png)

Thank you.

**Comment by colombod** [comment]
We are in the process of updating the docs, thank you for openign the issue. sql and kql extensions no longer import any of the advanced renderes so that users can use any additional addon (like [Data Table](https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-table)). To use nteract or sanddance there are a couple of steps.

I can show a workaround as we are defining the api for the explorers selection in queries.

All is the same but then you need to load the extension like this:

```csharp
#r "nuget: Microsoft.DotNet.Interactive.ExtensionLab, *-*"
```

Now there are 2 main approaches:

## 1 . Use variable sharing
in the sql/kql cell add `--name myResult` to store the statements result sets using the name `myResults`

<img width="798" alt="image" src="https://user-images.githubusercontent.com/375556/142848238-fe471081-b00f-4209-816b-2a7b935cdcc0.png">


Now you can share the `myResults` with `csharp kernel` with `#!share --from sql-adv myResults`.
In the csharp cell then
```csharp
using Microsoft.DotNet.Interactive.Formatting;

myResults[0].ExploreWithNteract().Display()
```

<img width="805" alt="image" src="https://user-images.githubusercontent.com/375556/142848708-ab3915dd-6a65-4669-8b93-5ca01e25eec8.png">

You might still have to pick up the right output mimetype / renderer
<img width="324" alt="image" src="https://user-images.githubusercontent.com/375556/142848819-8ddc0b6d-a982-4a86-bd40-62528137d2e6.png">

## 2 . Configure default explorer

As before load the extension, then we need to setup the eplorers
```csharp
using Microsoft.DotNet.Interactive;
using Microsoft.DotNet.Interactive.Formatting;
using Microsoft.DotNet.Interactive.Formatting.TabularData;

// register the data explorers for the data type TabularDataResource
DataExplorer.Register<TabularDataResource, Microsoft.DotNet.Interactive.ExtensionLab.NteractDataExplorer>();
DataExplorer.Register<TabularDataResource, Microsoft.DotNet.Interactive.ExtensionLab.SandDanceDataExplorer>();

// set the default data explorer to the NteractDataExplorer
DataExplorer.SetDefault<TabularDataResource, Microsoft.DotNet.Interactive.ExtensionLab.NteractDataExplorer>();
```

Now back to sql for a query and the default behaviour would be to use nteract
<img width="800" alt="image" src="https://user-images.githubusercontent.com/375556/142849624-260373a8-1e0c-465a-8532-a87f0664e429.png">


Or change it to SandDance:
```csharp
// set the default data explorer to the NteractDataExplorer
DataExplorer.SetDefault<TabularDataResource, Microsoft.DotNet.Interactive.ExtensionLab.SandDanceDataExplorer>();
```

<img width="807" alt="image" src="https://user-images.githubusercontent.com/375556/142849743-1a8dacd9-538d-477e-a33d-01e181a2e065.png">

**Comment by Eddie-Hartman** [comment]
@colombod I wanted to try and go through your steps, but I'm now having an entirely different issue.

After I run:
> #r "nuget:Microsoft.DotNet.Interactive.SqlServer,*-*"

I get this output:

> Installed Packages
> fsharp.compiler.service, 41.0.1
> fsharp.core, 6.0.1
> humanizer.core, 2.2.0
> messagepack, 2.2.85
> messagepack.annotations, 2.2.85
> microsoft.aspnetcore.html.abstractions, 2.2.0
> microsoft.azure.kusto.cloud.platform, 9.3.1
> microsoft.azure.kusto.data, 9.3.1
> microsoft.bcl.asyncinterfaces, 5.0.0
> microsoft.bcl.hashcode, 1.1.0
> microsoft.build.framework, 16.11.0
> microsoft.build.tasks.core, 16.11.0
> microsoft.build.utilities.core, 16.11.0
> microsoft.codeanalysis.analyzerutilities, 3.3.0
> microsoft.codeanalysis.common, 3.11.0
> microsoft.codeanalysis.csharp, 3.11.0
> microsoft.codeanalysis.csharp.features, 3.11.0
> microsoft.codeanalysis.csharp.scripting, 3.11.0
> microsoft.codeanalysis.csharp.workspaces, 3.11.0
> microsoft.codeanalysis.features, 3.11.0
> microsoft.codeanalysis.scripting.common, 3.11.0
> microsoft.codeanalysis.visualbasic, 3.11.0
> microsoft.codeanalysis.visualbasic.workspaces, 3.11.0
> microsoft.codeanalysis.workspaces.common, 3.11.0
> microsoft.data.sqlclient, 2.1.1
> microsoft.data.sqlclient.sni.runtime, 2.1.1
> microsoft.diasymreader, 1.3.0
> microsoft.dotnet.interactive, 1.0.0-beta.21559.2
> microsoft.dotnet.interactive.csharp, 1.0.0-beta.21559.2
> microsoft.dotnet.interactive.documents, 1.0.0-beta.21559.2
> microsoft.dotnet.interactive.formatting, 1.0.0-beta.21559.2
> microsoft.dotnet.interactive.packagemanagement, 1.0.0-beta.21559.2
> Microsoft.DotNet.Interactive.SqlServer, 1.0.0-beta.21559.2
> microsoft.entityframeworkcore, 3.1.8
> microsoft.entityframeworkcore.abstractions, 3.1.8
> microsoft.entityframeworkcore.relational, 3.1.8
> microsoft.entityframeworkcore.sqlserver, 3.1.8
> microsoft.extensions.caching.abstractions, 3.1.8
> microsoft.extensions.caching.memory, 3.1.8
> microsoft.extensions.configuration, 3.1.8
> microsoft.extensions.configuration.abstractions, 3.1.8
> microsoft.extensions.configuration.binder, 3.1.8
> microsoft.extensions.dependencyinjection, 3.1.8
> microsoft.extensions.dependencyinjection.abstractions, 3.1.8
> microsoft.extensions.logging, 3.1.8
> microsoft.extensions.logging.abstractions, 3.1.8
> microsoft.extensions.options, 3.1.8
> microsoft.extensions.primitives, 3.1.8
> microsoft.identity.client, 4.35.1
> microsoft.identity.client.extensions.msal, 2.18.9
> microsoft.identitymodel.jsonwebtokens, 6.8.0
> microsoft.identitymodel.logging, 6.8.0
> microsoft.identitymodel.protocols, 6.8.0
> microsoft.identitymodel.protocols.openidconnect, 6.8.0
> microsoft.identitymodel.tokens, 6.8.0
> microsoft.io.recyclablememorystream, 1.3.5
> microsoft.net.stringtools, 1.0.0
> microsoft.visualstudio.debugger.contracts, 16.10.0-beta.21214.1
> microsoft.visualstudio.threading, 16.9.60
> microsoft.visualstudio.validation, 16.8.33
> microsoft.win32.systemevents, 4.7.0
> nerdbank.streams, 2.6.81
> newtonsoft.json, 12.0.3
> nuget.frameworks, 5.11.0
> runtime.win-x64.native.microsoft.sqltoolsservice, 3.0.0-release.53
> streamjsonrpc, 2.8.28
> system.commandline, 2.0.0-beta1.21308.1
> system.commandline.rendering, 0.3.0-alpha.20427.1
> system.configuration.configurationmanager, 4.7.0
> system.diagnostics.diagnosticsource, 5.0.1
> system.drawing.common, 4.7.0
> system.identitymodel.tokens.jwt, 6.8.0
> system.io.pipelines, 5.0.1
> system.reactive, 5.0.0
> system.runtime.caching, 4.7.0
> system.security.cryptography.pkcs, 4.7.0
> system.security.cryptography.protecteddata, 4.7.0
> system.security.cryptography.xml, 4.7.0
> system.security.permissions, 4.7.0
> system.text.encodings.web, 5.0.1
> system.text.json, 5.0.2
> system.windows.extensions, 4.7.0
> 
> Error: System.TypeLoadException: Method 'CreateKernelAsync' in type 'Microsoft.DotNet.Interactive.SqlServer.ConnectMsSqlCommand' from assembly 'Microsoft.DotNet.Interactive.SqlServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
> at System.Reflection.RuntimeAssembly.GetExportedTypes()
> at System.Reflection.Assembly.get_ExportedTypes()
> at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembly(FileInfo assemblyFile, Kernel kernel, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 112
> at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembliesInDirectory(DirectoryInfo directory, Kernel kernel, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 74
> at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromDirectoryAsync(DirectoryInfo directory, Kernel kernel, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 47
> at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensionsFromDirectoryAsync(DirectoryInfo directory, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 320
> at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 167
> at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 70

And then when I try to connect in another cell:
> #!connect mssql --kernel-name DCDOT "Persist Security Info=False; Integrated Security=true; Initial Catalog=DCDOT; Server=localhost"

I get this error:
>Error: Required command was not provided.
Unrecognized command or argument 'mssql'
Unrecognized command or argument 'Persist Security Info=False; Integrated Security=true; Initial Catalog=DCDOT; Server=localhost'

**Comment by colombod** [comment]
are you using vscode or vscode insiders?

**Comment by Eddie-Hartman** [comment]
I'm guessing VSCode insiders would be like a preview build.

I'm just using regular VSCode. Version info:
![image](https://user-images.githubusercontent.com/14089997/142885210-d82d0b1f-b2ce-4a19-b475-b5875663b7f6.png)

I've updated and see that this resolved the above comment issue (I'm on a different machine and didn't realize it was so out of date). Sorry for the sidebar.

So it appears some progress has been made, but ran into another roadblock which I quickly resolved.

After updating, I had to restore the nuget packages again as expected, but I got an error when running
>#r "nuget: Microsoft.DotNet.Interactive.ExtensionLab, *-*"

saying that it was already installed. I'm aware that this is normal if you run the command more than once, but I had just copy-pasted it into a new cell block and therefore I should not have had it yet.

So OK. It should work then right? I tried to output and got a blank white screen. Weird. Closed VSCode and re-opened in, ran the whole notebook again and then the output worked fine.

So a few bumps along the road, but I eventually got there. Thanks for your help. Looking forward to the updated documentation to make this a bit smoother of a process.

**Comment by colombod** [comment]
<img width="289" alt="image" src="https://user-images.githubusercontent.com/375556/142896260-6cb39146-b3b5-4ff4-a551-1fcd145c9a4e.png">
<img width="562" alt="image" src="https://user-images.githubusercontent.com/375556/142896327-acd97a7c-d672-4b8b-87b3-0bcbafafe25d.png">

**Comment by Eddie-Hartman** [comment]
Sorry I know my wording was confusing. I am now up to date and it seems to be working well.

The screenshot I was showing was before I upgraded just to help explain the issue and resolution.

![image](https://user-images.githubusercontent.com/14089997/142897523-78393997-c395-4107-87a7-63cde8a10bc9.png)

Thanks again for your help and quick responses.

**Comment by colombod** [comment]
[test-data-exploring - stable.zip](https://github.com/dotnet/interactive/files/7582739/test-data-exploring.-.stable.zip)


CAn you try the attached file? You might have to change the connection strign and sql statement

**Comment by Eddie-Hartman** [comment]
We're still not on the same page. As of this comment: https://github.com/dotnet/interactive/issues/1780#issuecomment-975637900
I'm good. Everything is working. Thank you very much for all of your help. I genuinely appreciate it.

Leaving this issue open until the documentation is updated.

**Comment by colombod** [comment]
reloading packages is not supported, we are workign on ahving that behaviour to not give error if a user attempts to reloada version already loaded. But "overriding" package version is not supported
