### ISSUE TITLE
Support for running bash e.g. for AzureCLI 

### ISSUE THREAD

**Issue by bronthulke** [dotnet/interactive#1781]
**Is your feature request related to a problem? Please describe.**
I have a ton of bash scripts that I run for certain scenarios, especially for Azure CLI, for which a .NET Interactive Notebook would be super powerful.  I'd love to be able to hand them over to other team members including instructions (markdown), and even be able to force them to stop and review results before moving on to the next steps, etc.  

**Describe the solution you'd like**
It would be really helpful to have support of running bash commands in a .NET Interactive Notebook.

**Describe alternatives you've considered**
I've converted some of my scripts to PowerShell, e.g. for Azure, but there is some feature disparity between the Azure CLI and PowerShell, and plus some scripts would take a long time to convert to PowerShell.

**Comment by jonsequitur** [comment]
There's some discussion of this here: #465.

**Comment by bronthulke** [comment]
Ah thank you, I had a search for an existing request for this before posting, but somehow this other issue didn't come up! I'll close this ticket now.
