### ISSUE TITLE
Developer guide pack parameter is incorrect

### ISSUE THREAD

**Issue by Charles-Gagnon** [dotnet/interactive#1789]
In the developer guide it's [mentioned](https://github.com/dotnet/interactive/blob/main/DEVELOPER-GUIDE.md?plain=1#L137) running `build.[cmd|sh] --pack` to build and package the projects, but doing this now results in an error 

```
MSBUILD : error MSB1001: Unknown switch.
Switch: --pack
```

It looks like this was changed to just `-pack` recently (possibly in https://github.com/dotnet/interactive/pull/1757) so the guides should reflect this.

(I'm still seeing --pack used in a lot of other places though like https://github.com/dotnet/interactive/blob/main/eng/common/cibuild.sh#L16. Not sure what's going on there)

**Comment by Charles-Gagnon** [comment]
@brettfo Possibly because of your changes? --pack used to work for me

**Comment by brettfo** [comment]
The short answer is that all build arguments use a single dash on Windows (e.g., `-pack`) and a double dash on Linux/MacOS (e.g., `--pack`) and that part didn't change with my recent PR.  For instance, the `-pack` parameter ultimately flows through to [here](https://github.com/dotnet/interactive/blob/721c41c6aa9cab571fa855784b412545d8183d4d/eng/common/build.ps1#L19) and that's been unchanged.

Either way I've updated the developer guide to use `-pack` on Windows and `--pack` everywhere else.
