### ISSUE TITLE
VS Code Support

### ISSUE THREAD

**Issue by dcuccia** [dotnet/interactive#179]
I love the new support for [Jupyter notebook editing in VS Code](https://code.visualstudio.com/docs/python/jupyter-support). The tools get out of your way, and even support remote execution, bringing a powerful "backend" to a lightweight coding experience.

I followed the installation instructions for Interactive (described [here](https://github.com/dotnet/interactive/blob/master/docs/NotebooksLocalExperience.md) and [here](https://www.hanselman.com/blog/AnnouncingNETInteractiveTryNETIncludesNETNotebooksAndMore.aspx)), and can confirm that the C# support is working in Jupyter Lab.

However, after that install, I still could not see the C# language service recognized by the local Jupyter server instance when started. The same running service enumerated multiple available Python kernels.

Is there a "quick fix" to turn the C# language service on within the VS Code Jupyter plugin, or is this a deeper question regarding plugin tooling? If deeper, please consider this a feature request to bring Interactive to VS Code. Thanks!

**Comment by jonsequitur** [comment]
Most of the work to enable this will need to happen within VS Code, but we're definitely interested in making this work.

**Comment by dcuccia** [comment]
@jonsequitur thanks, that's great to hear. I'll find a place to cross-post on the VS Code side (unless that already exists).

**Comment by jonsequitur** [comment]
Getting underway: #355.

**Comment by jonsequitur** [comment]
More: #394, #396.

**Comment by LadyNaggaga** [comment]
Try it out: https://github.com/dotnet/interactive/#visual-studio-code
Early days

**Comment by dcuccia** [comment]
> Try it out: https://github.com/dotnet/interactive/#visual-studio-code
> Early days

@LadyNaggaga this is awesome! Thanks to the team for their work on this!!

**Comment by dcuccia** [comment]
#355 suggestions that completions are enabled - is that supposed to be true for the current impl? Neither dot nor space working for me. Couldn't find the ticket or on the new roadmaps - is this known?

![image](https://user-images.githubusercontent.com/479617/83817877-bd472a00-a67a-11ea-9f04-b1e77d800b95.png)
