### ISSUE TITLE
How do I display an SVG image in a notebook?

### ISSUE THREAD

**Issue by eosfor** [dotnet/interactive#1795]
**The package and version I'm asking about**: 
![image](https://user-images.githubusercontent.com/9363027/144007419-eba5e62c-ab0b-4c5e-8125-052a89fd53a4.png)

### Question
I have a ready to use svg file generated by graphviz. How do I display it?

**Comment by colombod** [comment]
Can you attach one file and show a snipept of code that you are using ? If you have a plain text file you can do something along these lines:
```
unsing System.IO;
var svg = File.ReadAllText("...");
svg.DisplayAs("text/html");
```

**Comment by eosfor** [comment]
Hi @colombod this works

```csharp
using System.IO;

var svg = File.ReadAllText("c:\\temp\\comms.svg");
svg.DisplayAs("text/html");
```

However, it would be cool if I could just do `c:\temp\comms.svg` in the PowerShell cell and get my image displayed:)
