### ISSUE TITLE
Nuget Package load fails due to a nuget source with invalid SSL certificate

### ISSUE THREAD

**Issue by camp-007** [dotnet/interactive#1802]
### Describe the bug
I've created a new C# `.ipynb` notebook and added a single cell with the following command:

```
#r "nuget: System.Text.Json"
```
Executing this cell fails with the message:

```
Error: C:\Program Files\dotnet\sdk\6.0.100\NuGet.targets(130,5): error : Unable to load the service index for source https://dotnet.myget.org/F/roslyn/api/v3/index.json. [C:\Users\myuser\AppData\Local\Temp\nuget\9156--609af78c-c33e-4937-8f5e-fd243440583c\Project.fsproj]
C:\Program Files\dotnet\sdk\6.0.100\NuGet.targets(130,5): error :   The SSL connection could not be established, see inner exception. [C:\Users\myuser\AppData\Local\Temp\nuget\9156--609af78c-c33e-4937-8f5e-fd243440583c\Project.fsproj]
C:\Program Files\dotnet\sdk\6.0.100\NuGet.targets(130,5): error :   The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch [C:\Users\myuser\AppData\Local\Temp\nuget\9156--609af78c-c33e-4937-8f5e-fd243440583c\Project.fsproj]
```

From what I can tell the .NET Interactive Notebook extension is generating an fsharp project file that always includes a nuget package source of `https://dotnet.myget.org/F/roslyn/api/v3/index.json`.  This `dotnet.myget.org` domain has an invalid SSL cert which is causing a nuget error on various nuget operations.

If I specify an explicit version number on the nuget package reference, I do not receive this error.  However, I always run into this same error message if I try adding a private nuget feed source and importing a package.  For example:

```
#i "nuget:https://pkgs.dev.azure.com/myazuredevopsaccount/_packaging/myazuredevopsfeed/nuget/v3/index.json"
#r "nuget: My.Private.Package, 1.0.0"
```

It seems any package operation that triggers nuget to evaluate all the sources will hit this error due to an invalid myget source.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
VS Code .NET Interactive Notebook extension v1.0.258004
.NET Interactive Version: 1.0.258004+3429f67626d2f15eec7d8f15a29215909284cb79
Build date: 2021-12-02T04:37:24.2359871Z

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
The Roslyn myget feed has been decommissioned. Do you have this in a nuget.config by any chance?

**Comment by camp-007** [comment]
Indeed. I assumed this was getting injected by the .net interactive notebook tooling for some reason because I have no recollection of ever using a myget feed for anything.  However `dotnet nuget list source` did in fact include this myget feed. I've never run into this causing any issues with other tooling I normally use, but nevertheless, this seems wrong.  After removing this source, everything is working as I'd expect.
