### ISSUE TITLE
`interactive.csharp` object is undefined

### ISSUE THREAD

**Issue by dweedul** [dotnet/interactive#1803]
### The Bug
The `interactive.csharp` object is always coming back as undefined.

I tried the simple instructions from the readme about sharing variables with javascript (see screenshot) and keep getting an error that indicates that `interactive.csharp` is undefined. I have opened all of the polyglot examples and see errors in those also.

It appears that the `notebookscope` object is also having problems for me.

I've tried this with both stable and insider VS Code.

### Environment

.Net Interactive
Version: 1.0.258004+3429f67626d2f15eec7d8f15a29215909284cb79
Build date: 2021-12-02T05:36:17.5600248Z

- OS
    - [x] Windows 10
 - Browser 
    - [x] Firefox
 - Frontend
    - [x] Visual Studio Code 
    - [x] Visual Studio Code Insiders

### Screenshots
![image](https://user-images.githubusercontent.com/781828/144372362-23e81f1f-8a53-4400-b5f7-fcbe09641f41.png)

**Comment by jonsequitur** [comment]
This is a deliberate breaking change to make things more consistent. The latest changes to the JavaScript kernel enable the use of `#!share` and no longer communicate directly over HTTP. 

<img width="538" alt="image" src="https://user-images.githubusercontent.com/547415/144467837-b5c835eb-7c30-47f0-976e-dbf510b3dd5b.png">

**Comment by dweedul** [comment]
Excellent! Thanks for the help. I thought that maybe I just wasn't finding the right bit of documentation.
