### ISSUE TITLE
Microsoft.DotNet.Interactive.Jupyter not referenced on session start

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#181]
On the first submission of even very innocent code to the C# kernel, the following error is displayed:

```console
(1,43): error CS0234: The type or namespace name 'Jupyter' does not exist in the namespace 'Microsoft.DotNet.Interactive' (are you missing an assembly reference?)
```

Subsequent submissions work correctly as long as the `Microsoft.DotNet.Interactive.Jupyter` namespace isn't referenced.

The issue is due to the following deferred submissions arriving in the wrong order at initialization:

```csharp
#r Microsoft.DotNet.Interactive.Jupyter.dll
using Microsoft.DotNet.Interactive.Jupyter;
```

**Comment by Cilyan** [comment]
Same here. As a temporary workaround, you can just create a new cell at the top of the notebook with an empty comment. This one cell will fail, but allows the rest of the notebook to be run smoothly when using "Run All".
