### ISSUE TITLE
Stopped working on VS Code for Mac since the migration to .NET 6 SDK has been completed

### ISSUE THREAD

**Issue by neminush** [dotnet/interactive#1813]
### Describe the bug
The following versions can be installed on VS Code for Mac, but do not works:
1.0.2606011
1.0.2606010
1.0.2602011
1.0.2602010
1.0.2601021

The new '1.0.2606011' version can't be installed because it's not compatible with VS Code '1.63.0'.

The last working version for VS Code for Mac is '1.0.246201'.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android

 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### System Software Overview:
  System Version:	macOS 11.6 (20G165)
  Kernel Version:	Darwin 20.6.0
  Boot Volume:	Macintosh
  Boot Mode:	Normal
  Computer Name:	Mac mini — 1 (2)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Visual Studio Code '1.63.0'

### Hardware Overview:
  Model Name:	Mac mini
  Model Identifier:	Macmini7,1
  Processor Name:	Dual-Core Intel Core i7
  Processor Speed:	3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

**Comment by neminush** [comment]
I can't create 'dib' file.
I can create 'ipynb' file, but my code in 'ipynb' file is not calculated.

**Comment by dcuccia** [comment]
I can repro a similar bug on my new Win11 machine with only .Net 6 installed: 

.Net Interactive `1.0.2462010` is the latest version that opens a UI when I select "Create a new .Net Interactive Notebook". Newer versions hang with the message "Activating Extensions..."

But even if a notebook (.dib or .ipynb) is created, I can't seem to execute any C# code - kernel execution hangs on a Hello World.

Tried installing the .Net 5 SDK, just in case, but that didn't help.

Repro'd on VS Code:

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

...and VS Code Insiders:

Version: 1.64.0-insider (user setup)
Commit: c6e58d126f6b5676242e32b34180b2a595f29b51
Date: 2022-01-14T05:19:33.429Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

What can I do to help track down? Should I create a separate ticket? I've grown so comfortable using .Net Interactive in my daily workflow, I'm at a loss for what to do!

**Comment by jonsequitur** [comment]
Are you still able to repro this bug?

**Comment by neminush** [comment]
@jonsequitur

The bug was due to the fact that the program does not know how to work with .NET 5 SDK and can't tell the user what it needs .NET 6 SDK.

After I installed the latest version of the .NET Interactive and installed the [.NET 6 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.101-macos-x64-installer), the problem disappeared.

**Comment by jonsequitur** [comment]
Thanks. We've made a recent improvement to the error message for this which will hopefully help people out of this situation in the future.
