### ISSUE TITLE
`notebookScope` not recognized in VS Code

### ISSUE THREAD

**Issue by fradav** [dotnet/interactive#1815]
### Describe the bug
`notebookScope` in javascript cells isn't recognized anymore inside VS Code. (*.dib and *.ipynb)

```plain
Error: notebookScope is not defined
```

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
1.0.260601+9d1ecd3c06ba93e59bfef3842d2660c08d9e2ce5
Build date: 2021-12-09T16:51:18.4618021Z

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by fradav** [comment]
Sorry didn't see https://github.com/dotnet/interactive/issues/1803 before

**Comment by fradav** [comment]
Reopened issue : I don't understand how we declare global (notebook-wise) variables like :

![image](https://user-images.githubusercontent.com/701587/145788973-5915411f-da41-4b8f-899f-f97d4da638dc.png)

**Comment by the-programmer** [comment]
I'm not 100% sure if it is the same issue (it looks similar enough) , however I would like to report it.

If I use the sample code here:
https://github.com/dotnet/interactive/blob/main/samples/notebooks/polyglot/COVID-19.ipynb

The javascript and html code generate the following message "Error: notebookScope is not defined".

**Comment by fradav** [comment]
My PR to the COVID notebook there : https://github.com/dotnet/interactive/pull/1823
It's a required change in the way kernels communicates. But my issue there is that without the notebookScope, we lose the ability to have functions "shared" across cells to access console.

**Comment by colombod** [comment]
Closing this but since we have open a more specific issue #1906
