### ISSUE TITLE
Kernel-to-client commands : how to make it works

### ISSUE THREAD

**Issue by JDiLenarda** [dotnet/interactive#1820]
**The package and version I'm asking about**: 
Version: 1.0.260601+9d1ecd3c06ba93e59bfef3842d2660c08d9e2ce5
Build date: 2021-12-06T19:06:20.0000000Z

Visual Studio Code 1.63.1 on macOS 11.6.1

### Question
It seems that the ["Kernel-to-client communication with client-side commands"](url)  doc is outdated, or at least #1803 makes me think so.

<img width="625" alt="Capture d’écran 2021-12-15 à 23 53 54" src="https://user-images.githubusercontent.com/41197638/146277391-63eae3d7-3e0d-4046-bafe-2241c5815718.png">

Please notice errors on cells 1, 4 and 5.

What's the current way to use this ?

**Comment by colombod** [comment]
Need to update a lot of things, this was a big change for vscode itnegration.
<img width="846" alt="image" src="https://user-images.githubusercontent.com/375556/146908163-02f237da-41fd-4925-b622-0834f783e826.png">

**Comment by JDiLenarda** [comment]
Thank you.

**Comment by PawelStadnicki** [comment]
this sample doesn't work for me,
I guess it is because registerCommandHandler doesn't exist on js kernel.

![image](https://user-images.githubusercontent.com/56049414/161557401-de2b39c3-ac22-46ef-bddd-57722912caf3.png)

**Comment by colombod** [comment]
I see it in the output of this
<img width="764" alt="image" src="https://user-images.githubusercontent.com/375556/161595477-1e311bae-4096-4c62-a207-9076d9acc948.png">

```javascript
const getMethods = (obj) => {
    let properties = new Set()
    let currentObj = obj
    do {
      Object.getOwnPropertyNames(currentObj).map(item => properties.add(item))
    } while ((currentObj = Object.getPrototypeOf(currentObj)))
    return [...properties.keys()].filter(item => typeof obj[item] === 'function')
  }

let methods = getMethods(kernel.root.findKernelByName("javascript"));
console.log(JSON.stringify( methods));
```

**Comment by JDiLenarda** [comment]
Something got broken with last version. 

In a JavaScript cell, the following code : `kernel.root.findKernelByName("javascript")` returns `Error: kernel.root.findKernelByName is not a function`
