### ISSUE TITLE
[Visual Studio] Default language is used for cells instead of specified one

### ISSUE THREAD

**Issue by xperiandri** [dotnet/interactive#1827]
### Describe the bug
If I want to use F# and I specify `#!fsharp` in each cell, then when I save and open a notebook `#!fsharp` disappears from cells but stays in a file and changes cell language. However, Visual Studio always executes cells with notebook default language but not with cell-specific.
So that I need to put `#!fsharp` back again which is terrible!!!

By the way, if I leave the first line of the cell blank but put `#!fsharp` on the second line it stays 😁 in the UI.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

![image](https://user-images.githubusercontent.com/2365592/146690982-57b9402c-c4dd-4ab3-8dd4-be58f4565f6b.png)

- OS
    - Windows 11
 - Frontend
    - Visual Studio

### Screenshots

![image](https://user-images.githubusercontent.com/2365592/146691008-11609302-e57f-4e9b-ac8d-6788e53bbc0a.png)

**Comment by JakeRadMSFT** [comment]
Thanks for the feedback! We're still in a Preview for ur Notebook Editor extension so not all functionality is available yet!

Language Selecting will be on our roadmap soon!

**Comment by xperiandri** [comment]
@JakeRadMSFT how to do that manually?
https://github.com/dotnet/interactive/discussions/1826

**Comment by JakeRadMSFT** [comment]
Sorry - No way to do it yet

**Comment by xperiandri** [comment]
@JakeRadMSFT any updates on the issue?

**Comment by claudiaregio** [comment]
Closing as support for notebooks in VS has been discontinued
