### ISSUE TITLE
[Visual Studio] Cyrillic path does not work even with Serbian Cyrillic system encoding

### ISSUE THREAD

**Issue by xperiandri** [dotnet/interactive#1828]
### Describe the bug
I try to read the file from the path that contains Cyrillic and Danish letters. All of them are displayed as invalid.
`C:\Users\Andrii\_____ Lægemiddel ______\Сайт групи - Документи\General\Data source sample`
Even the trick of switching from Ukrainian to Serbian Cyrillic for system-wide encoding does not help.
![image](https://user-images.githubusercontent.com/2365592/146691149-6ba0a252-22be-4ba3-9668-c89546a46278.png)

### Please complete the following:

![image](https://user-images.githubusercontent.com/2365592/146691167-95c95d01-f8ea-4169-94b1-d37aa5f87245.png)

- OS
    - Windows 11
 - Frontend
    - Visual Studio

### Screenshots

![image](https://user-images.githubusercontent.com/2365592/146691169-6996f256-0d5a-4a80-8948-b0c6730396db.png)

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud Can you investigate this one a bit? I'm not seeing where this encoding issue is being introduced.

My initial guesses were Text Buffer -> String, InteractiveCommand/KernelCommandEnvelope, or ServiceHub but I'm not seeing anything obvious.

**Comment by JakeRadMSFT** [comment]
Works in VS Code
![image](https://user-images.githubusercontent.com/31937616/146838157-922039a5-86bd-49b8-a9f5-c5f35bc40d94.png)


Doesn't work in VS
![image](https://user-images.githubusercontent.com/31937616/146838107-21209fa9-9645-48f5-b497-5f195369bff2.png)

**Comment by jonsequitur** [comment]
Thanks!
