### ISSUE TITLE
[Visual Studio] Notebook item template is not available in F# project

### ISSUE THREAD

**Issue by xperiandri** [dotnet/interactive#1829]
### Describe the bug
File\Add\New item... does not contain Notebook for F# projects

### Please complete the following:

![image](https://user-images.githubusercontent.com/2365592/146691167-95c95d01-f8ea-4169-94b1-d37aa5f87245.png)

- OS
    - Windows 11
 - Frontend
    - Visual Studio

### Screenshots

![image](https://user-images.githubusercontent.com/2365592/146691169-6996f256-0d5a-4a80-8948-b0c6730396db.png)

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! Good point - we've only added it to C# so far but we should add it to others.

**Comment by claudiaregio** [comment]
Closing as support for notebooks in VS has been discontinued
