### ISSUE TITLE
[Visual Studio] Tabs/Spaces setting is not preserved

### ISSUE THREAD

**Issue by xperiandri** [dotnet/interactive#1830]
### Describe the bug
Tabs are inserted into cells regardless of Visual Studio language setting which breaks F# code

### Please complete the following:

![image](https://user-images.githubusercontent.com/2365592/146691167-95c95d01-f8ea-4169-94b1-d37aa5f87245.png)

- OS
    - Windows 11
 - Frontend
    - Visual Studio

### Screenshots

![image](https://user-images.githubusercontent.com/2365592/146691169-6996f256-0d5a-4a80-8948-b0c6730396db.png)

**Comment by JakeRadMSFT** [comment]
Related: #1827 #1829

Thanks for reporting! We'll investigate why this is happening with the Editor.

**Comment by claudiaregio** [comment]
Closing as support for notebooks in VS has been discontinued
