### ISSUE TITLE
.Ipynb in VS Code has long delay after printing

### ISSUE THREAD

**Issue by jhoneill** [dotnet/interactive#1832]
### Describe the bug
It takes >6 seconds to return after printing <200 characters. 

### Please complete the following:
.NET Interactive    
© **2020** Microsoft Corporation    
Version: 1.0.260601+9d1ecd3c06ba93e59bfef3842d2660c08d9e2ce5    
Build date: **2021-12-18**T10:36:48.0565225Z    
 
- OS
    - [ ] Windows 11
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
Here is a trivial bit of powerShell
```PowerShell
#!time 
$sw = [System.Diagnostics.Stopwatch]::new()
$sw.Start()
1..90
"Elapsed ms:$($sw.ElapsedMilliseconds)"
$sw.stop()
```

![image](https://user-images.githubusercontent.com/16209593/147588973-9d2a28e7-3310-4568-a026-adcdbbece2aa.png)
It prints numbers 1 to 90 and gives the elapsed time by two methods the screen shot shows it took 6.4 seconds to return
![image](https://user-images.githubusercontent.com/16209593/147589282-550930c8-113f-403f-9921-a6509f97b499.png)

The messages above are printed after a very short time and most of the 6.4 seconds is waiting for the control to return
Changing the time from 90 to 900 the time is given almost but it took 2:33 , which is worse than 10x the time for 10x the data.  
![image](https://user-images.githubusercontent.com/16209593/147589669-a00b0ddb-2fd4-44df-ab64-4ddb9cc4c41a.png)

**Comment by Szeraax** [comment]
Of note, while you are waiting those two minutes, you can actually already run other cells. Its not LOCKED. 

See this other issue regarding it: https://github.com/dotnet/interactive/issues/730

**Comment by jonsequitur** [comment]
Just to note, this is not specific to PowerShell:

<img width="605" alt="image" src="https://user-images.githubusercontent.com/547415/147961560-73439b4c-71c6-4c1c-9a34-a936d1c99905.png">

It's also not specific to console output. The `Display` API exhibits the same problem.

**Comment by jhoneill** [comment]
@Szeraax  I've found the biggest problem is when I have a loop and an error - I had a typo and was doing something with a 5000 data set 5000 multi line errors caused the issue. and the I couldn't get control back in other cells, nor could I save my notebook I had to restart VS Code. 

 In the past I have thought I have seen variations of #730 in other places, but on closer examination it's been different. 

@jonsequitur  it seems to be the number of calls to  ` [Microsoft.DotNet.Interactive.Kernel]::display()`  that is the issue

Changing the number of calls with this   `for ($i = 1; $i -lt 10 ; $i++) {$null = [Microsoft.DotNet.Interactive.Kernel]::display("", 'text/plain')}`

backs up the chart @Szeraax posted on #730 

`dir -Recurse | out-string`  Outputs one large string and takes 0.1s ;  without the `out-string` the directory has 240 items and takes 20 seconds to output.

**Comment by eosfor** [comment]
Another example

```powershell
measure-command {get-process}
Get-Process
```

The first command was completed in just 11 milliseconds. But the whole cell does not stop even after 5 minutes. And there is no way to stop it. When you hit `stop` nothing happens.

![image](https://user-images.githubusercontent.com/9363027/153274881-42dad64b-bc79-42f7-ae6f-750f08e784dc.png)
