### ISSUE TITLE
markdown superscript and subscript

### ISSUE THREAD

**Issue by danielttran** [dotnet/interactive#1834]
### Describe the bug
The superscript and subscript don't seem to work.
For example: 

`x<sub>2</sub>`  should produce x<sub>2</sub>
`x<sup>2</sup>` should produce x<sup>2</sup>

Thank you,

**Comment by rebornix** [comment]
It's already working in latest VS Code Insiders

<img width="224" alt="image" src="https://user-images.githubusercontent.com/876920/156447985-5c4d728b-466e-44e1-8287-1ff6bdbdb0a8.png">
