### ISSUE TITLE
vscode: multi-cursor extension doesn't scroll the notebook

### ISSUE THREAD

**Issue by Spongman** [dotnet/interactive#1837]
### Describe the bug
in vscode editing c# .dib notebook. if the cell is tall, when using `editor.action.insertCursorBelow` (ctrl-alt-down) to extend the multi-cusros selection beyond the bottom of the visible area, the notebook doesn't scroll (like a normal vscode text editor window would).

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by rebornix** [comment]
Good catch, we don't listen to selection changes in a cell thus it won't scroll the outer notebook editor.

**Comment by rebornix** [comment]
This is already fixed.
