### ISSUE TITLE
ANSI sequences work for colours but not bold/italic, underline etc 

### ISSUE THREAD

**Issue by jhoneill** [dotnet/interactive#1839]
### Describe the bug
Ansi escape sequences   `[esc]` `]` 3x / 4x / 9x / 10x  `m` can be used for setting colours in a notebook.  (see #1471  and links for where this was added)
However  `[esc]` `]` x / 2x `m`  to turn on  Bold, Italic, underline, strike through, reverse  etc do not.  See the screen shot below 

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
.NET Interactive  
© 2020 Microsoft Corporation  
Version: 1.0.260601+9d1ecd3c06ba93e59bfef3842d2660c08d9e2ce5  
Build date: 2021-12-09T15:13:49.9229811Z  
https://github.com/dotnet/interactive  

- OS
    - [ ] Windows 11
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
 
![image](https://user-images.githubusercontent.com/16209593/148257035-192e2659-b38c-45ea-adfe-a8bab1db9145.png)

Notice that the red and blue foreground work correctly, the change of back grounds works correctly but the others do nothing.

**Comment by rebornix** [comment]
This will be fixed in next Insiders and April Stable of VS Code (upstream https://github.com/microsoft/vscode/issues/144275 )

**Comment by jhoneill** [comment]
@rebornix  Excellent. Thank you :-)
