### ISSUE TITLE
Can't declare namespace in notebook? 

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#1842]
### Describe the bug
Ran the following code in a Visual Studio C# Project and it worked fine. However when I tried to run it in a notebook, it did not work. 
This could just be me missing some info on C# and how it works but I'm not sure why this shouldn't work in a notebook 

```
using System; //Directives
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HelloWorld
{
    internal class Program
    {
        static void Main(string[] args)
        {

            int[] userAge = { 21, 35, 87 };
            for (int i = 0; i < userAge.Length; i++)
            {
                Console.WriteLine(userAge[i]);
            }
            
            Console.WriteLine(userAge.Length);
            Console.Read();

        }
    }
}
```

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
Ext: v1.0.2606011
![image](https://user-images.githubusercontent.com/19276747/148630624-e41ccabe-5acf-4416-bae5-f7a5b619d557.png)

- OS
    - [x] Windows 11
 - Frontend
    - [x] Visual Studio Code Insiders

### Screenshots

![image](https://user-images.githubusercontent.com/19276747/148630559-8a8716ed-5e4b-4291-afe3-bf8180eb5972.png)

**Comment by jonsequitur** [comment]
Namespace declarations aren't allowed in C# scripting, so this is expected.
