### ISSUE TITLE
I got an error "System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.22.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'"

### ISSUE THREAD

**Issue by won5572** [dotnet/interactive#1845]
### I can't connect mssql with .net interactive.

I wrote this code on the .net interactive notebook.

#r "nuget:Microsoft.DotNet.Interactive.SqlServer,*-*"
Installed Packages
Microsoft.DotNet.Interactive.SqlServer, 1.0.0-beta.21606.1

#r "nuget: Microsoft.EntityFrameworkCore.Design, 6.0.0"
Installed Packages
Microsoft.EntityFrameworkCore.Design, 6.0.0

#!connect mssql --create-dbcontext --kernel-name schEF "dbconnectString"
Scaffolding a DbContext and initializing an instance of it called schEF in the C# kernel.

Installed Packages
Humanizer, 2.8.26
humanizer.core, 2.8.26
Microsoft.EntityFrameworkCore.Design, 6.0.0
microsoft.entityframeworkcore.sqlserver, 6.0.0

Error: System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.22.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. 지정된 파일을 찾을 수 없습니다.
File name: 'Microsoft.Identity.Client, Version=4.22.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'
   at Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider..ctor(String applicationClientId)
   at Microsoft.Data.SqlClient.SqlAuthenticationProviderManager.SetDefaultAuthProviders(SqlAuthenticationProviderManager instance) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlAuthenticationProviderManager.cs:line 42
   at Microsoft.Data.SqlClient.SqlAuthenticationProviderManager..cctor() in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlAuthenticationProviderManager.NetCoreApp.cs:line 37

.NET interactive version
Version: 1.0.260601+9d1ecd3c06ba93e59bfef3842d2660c08d9e2ce5

- OS
    - [x] Windows 10
 - Browser 
    - [x] Chrome
 - Frontend
    - [x] Visual Studio Code 

![capture](https://user-images.githubusercontent.com/3466751/149077595-e8d57cc8-5a6d-4961-bbb6-3943339ebcba.PNG)
![capture1](https://user-images.githubusercontent.com/3466751/149078245-24d7393a-d730-4d32-9718-58fabcf817f1.PNG)
![capture2](https://user-images.githubusercontent.com/3466751/149078275-cf5db4cc-b930-4f54-92e0-88f3e03fe070.PNG)

**Comment by aurnoi1** [comment]
I have the same issue with the same exception.

Windows 10
Visual Studio Code
dotnet.interactive 1.0.0-beta.21606.1

![image](https://user-images.githubusercontent.com/11244735/151560085-2887f817-860e-45d2-bf4f-e6f0fa630d32.png)

**Comment by varon** [comment]
Same issue as well. Similar setups.

**Comment by colombod** [comment]
Fixed in current insider extension

**Comment by aurnoi1** [comment]
I confirm it works with the version insider vscode 1.66.0-insider and dotnet interactive v1.0.3172011.

I had to install the nuget Azure.Core.

#r "nuget:Microsoft.DotNet.Interactive.SqlServer,*-*"
#r "nuget:Microsoft.Identity.Client,*-*"
#r "nuget:Azure.Core,*-*"

Azure.Core, 1.23.0
Microsoft.DotNet.Interactive.SqlServer, 1.0.0-beta.22103.1
Microsoft.Identity.Client, 4.42.1

**Comment by colombod** [comment]
> I had to install the nuget Azure.Core.

you should not need to install the identity client to get the `--create-dbcontext` to work, 

I am not sure I understand your scenario.

to be clear when using insiders the latest version of the package (contain fixes) is only available on internal feed, today we will be releasing a new stable extension and all packages will; be available on nuget.org.

To use the internal feed add this line before importing nuget pakcages

```
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"
```

Then you can just do

```
#r "nuget:Microsoft.DotNet.Interactive.SqlServer, *-*"
```

and finally perform the connection with the `--create-dbcontext` option

**Comment by aurnoi1** [comment]
Thanks for the follow up @colombod. I have exactly repeated the same steps that show in my [previous post](https://github.com/dotnet/interactive/issues/1845#issuecomment-1024259655) with vscode 1.66.0-insider and dotnet interactive v1.0.3172011.

I understand now that by "insider" you meant the package insider and not the vscode insider version. Anyway, I will wait for the release of the official package.
