### ISSUE TITLE
Support Execution Count

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#1852]
Execution count does not show up in VS Code Notebook 
 - Frontend
    - [x] Visual Studio Code 
    - [x] Visual Studio Code Insiders

### Screenshots

![image](https://user-images.githubusercontent.com/19276747/149594728-70d23a8d-8f80-4c99-bcbd-913638607864.png)

**Comment by JakeRadMSFT** [comment]
When we fix this for VS Code ... lets work together to make sure that it allows the VS Extension to save Execution Count as well. (Please :) )

**Comment by zewditu** [comment]
Here is the related VS extension issue Jake mentioned above https://github.com/microsoft/VS-Notebook/issues/153

**Comment by claudiaregio** [comment]
Looks like this was dropped from March, could we roll it over into June?

**Comment by claudiaregio** [comment]
For reference: 
![image](https://user-images.githubusercontent.com/19276747/190755799-d0276066-3d76-48f1-ab9c-8a71e228ae7e.png)
