### ISSUE TITLE
VSCode can't parse two of the csharp 101 notebooks when using vscode:\\ protocol with ipynb

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/interactive#1861]
### Describe the bug
VSCode can't parse two of the csharp 101 notebooks when using vscode:\\ protocol with ipynb.

Can't open Notebook 2 and Notebook 9.

Notebook 2: https://tinyurl.com/csharp101-notebook02-ipynb
Notebook 9: https://tinyurl.com/csharp101-notebook09-ipynb

![image](https://user-images.githubusercontent.com/31937616/151059278-3443335f-128a-45a0-b196-d93ded358cc0.png)

Blocking: https://github.com/dotnet/csharp-notebooks/pull/11
### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [x] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by JakeRadMSFT** [comment]
Notes:
- The notebook were created in VS Code by opening DIB and using "save as" from command pallet.
- The notebooks work when opening directly.

I think it might be an encoding thing ... since the code path differs mainly by using a byte[] instead of loading from disk.
https://github.com/dotnet/interactive/blob/a2928fe1a604d152297d070fb398bd0883caa577/src/dotnet-interactive-vscode-common/src/extension.ts#L313

**Comment by brettfo** [comment]
The underlying issue is that the URLs are wrong.  Expanding the URL gives this:

```
vscode://ms-dotnettools.dotnet-interactive-vscode/openNotebook?url=https://raw.githubusercontent.com/dotnet/csharp-notebooks/main/csharp-101/02-The Basics of String.ipynb
```

But the `url` parameter is incorrect.  It should read:

``` diff
-...The Basics of String.ipynb
+...The Basics of Strings.ipynb
```

The difference being `String` (singular) vs `Strings` (plural).  So when the VS Code extension tries to fetch that url it gets the response:

```
404: Not Found
```

Which of course can't be parsed as JSON.

# However

In the case where we couldn't parse the notebook, the exception text should probably return what it actually tried to parse.
