### ISSUE TITLE
Part of markdown cell text cannot be selected in view mode in VS Code

### ISSUE THREAD

**Issue by AlexeiScherbakov** [dotnet/interactive#1864]
### Describe the bug
Part of markdown cell text cannot be selected in view mode in VS Code. When I try select part of markdown cell cursor converts to hand and only one way to select part of cell is switching to edit mode
In nteract I can select part of markdown cell normally, without switching to edit mode

### Please complete the following:

**Which version of .NET Interactive are you using?
Version: 1.0.260601+9d1ecd3c06ba93e59bfef3842d2660c08d9e2ce5
Build date: 2022-01-26T11:54:33.8365411Z

- OS
    - [*] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [*] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![изображение](https://user-images.githubusercontent.com/8665915/151161917-d2422f81-c93e-4482-b9ca-c2c511c3a509.png)

[sample.zip](https://github.com/dotnet/interactive/files/7941603/sample.zip)

**Comment by rebornix** [comment]
I think this one is already fixed in current Insiders. Will be available in next Stable build this week.
