### ISSUE TITLE
mermaid extension stopped working

### ISSUE THREAD

**Issue by eosfor** [dotnet/interactive#1898]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

	
.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.310301+a493554dbfb0097f7f070d7ae72dc2804cffae28
Build date: 2022-02-09T19:00:32.4008211Z
https://github.com/dotnet/interactive

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

Is this expected?

```
#r "nuget:Microsoft.DotNet.Interactive.ExtensionLab,*-*"
```

```
#!mermaid
flowchart LR
    data[minizinc data] --> pwsh[PowerShell Wrapper]
    model[minizinc model] --> pwsh[PowerShell Wrapper]
    pwsh -.calls.-> mz[minizinc.exe]
    mz --uses--> solver[solver GECODE]
    mz -.returns results.-> pwsh
    pwsh --parses and returns-->r[results]

    source["source servers details (CPU, RAM, Disks)"] -.-> data
    azureVM["Azure VM pricing and ACU"]  -.-> data
    azureDisk["Azure Disk prices"]  -.-> data
```

![image](https://user-images.githubusercontent.com/9363027/153561687-cfe6a401-108f-4fa7-845e-3ce40c871682.png)

**Comment by colombod** [comment]
Some extensions have been migrated out, for the mermaid you need the following
```
"nuget: mermaid.InteractiveExtension, *-*"
```

everything works as before.

**Comment by colombod** [comment]
Also there are few new features
<img width="432" alt="image" src="https://user-images.githubusercontent.com/375556/153638650-a2a06c70-1917-4bac-be71-e0df0d45989a.png">
