### ISSUE TITLE
F# JupyterLab DataFrame Example Doesn't Load

### ISSUE THREAD

**Issue by seth-ahca** [dotnet/interactive#19]
#### Describe the bug
The online F# DataFrame example doesn't load for me, and instead returns this error:

File Load Error for DataFrame-Getting Started.ipynb
Unreadable Notebook: /home/jovyan/Notebooks/fsharp/Samples/DataFrame-Getting Started.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')

It looks like the latest commit (fe9d31e, dotnet/try#700) to the file (NotebookExamples/fsharp/Samples/DataFrame-Getting Started.ipynb) may have broken the format. Line 73 ("let df = DataFrame([dateTimes; ints; strings]: DataFrameColumn list)\n",) should not have the trailing comma, I think.

Thank you.

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [ ] .NET Jupyter Notebook 
- [X] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [X] Other: JSON file doesn't load

#### Please complete the following:
 - OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Safari
    - [X] FireFox

**Comment by m0rphed** [comment]
`DataFrame-Getting Started.ipynb` seems to be partially broken again.
Get compile errors via *binder* and also locally: 
[some details via gist](https://gist.github.com/m0rphed/400b6d8c6a322e840a3c0a6ed3db6195)

dotnet SDK information (Ctlos = Arch Linux iso):
```
~ »  dotnet --info                                                         morphed@fish
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Ctlos
 OS Version:  net-1.0_20200407
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
