### ISSUE TITLE
ExploreWith Functions not Available

### ISSUE THREAD

**Issue by phage-nz** [dotnet/interactive#1902]
### Describe the bug
Since upgrading software and package versions, the ExploreWithNteract and ExploreWithSandDance functions don't appear to be available. Have they been renamed or shifted? Versions as follows:

.NET SDK: v6.0.102
VS Code: v1.64.2
.NET Interactive: v1.0.2606010
Jupyter: v2022.1.1001760686
SandDance for VS Code: v3.3.0
C#: v1.24.0

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ): v1.0.2606010

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Brave
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

My project:
![image](https://user-images.githubusercontent.com/18238564/153974826-8f3e2c7c-c548-4c80-b0aa-93019ccda35d.png)
![image](https://user-images.githubusercontent.com/18238564/153974920-23506cdc-024b-479e-90cf-73a23de0792a.png)
![image](https://user-images.githubusercontent.com/18238564/153974965-8f83bb7d-deaf-4583-9cea-7347ae953161.png)

Sample project:
![image](https://user-images.githubusercontent.com/18238564/153975031-072dee4a-95ce-4cd6-a6c6-95f767a79c62.png)

**Comment by jonsequitur** [comment]
These have been moved to separate packages:

https://www.nuget.org/packages/nteract.InteractiveExtension/
https://www.nuget.org/packages/SandDance.InteractiveExtension/

**Comment by phage-nz** [comment]
Excellent, thank you. This has resolved it:
```
#r "nuget:nteract.InteractiveExtension"
#r "nuget:SandDance.InteractiveExtension"
```
