### ISSUE TITLE
Markdown Cells are invisible at file open

### ISSUE THREAD

**Issue by FLAMINGxFURY** [dotnet/interactive#1905]
Issue Type: <b>Bug</b>

A markdown cell that is not on-screen at file launch will be invisible until one of the following actions are taken:
1. A different markdown cell is changed to the edit state
2. The lefthand pane is opened or closed
3. A code cell is executed

For this bug to occur, there must be a markdown cell below a code cell and the markdown cell must be offscreen. Upon scrolling down, the cell will be invisible and cannot be interacted with.

Before: 
![image](https://user-images.githubusercontent.com/25275552/154882492-21cf22c1-6d55-4b99-96d7-683dd952509e.png)

After: 
![image](https://user-images.githubusercontent.com/25275552/154882576-b284d5f9-85c0-478c-96c4-a191675210ca.png)

Extension version: 1.0.3103010
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (2.06GB free)|
|Process Argv|C:\\Users\\furye\\My Drive\\CSCI\\CAPSTONE\\Textbook Snippets\\Chapter 1 - Array and Array Algorithms\\1.1 .dib --crash-reporter-id 1d2b86b9-4020-41fd-9a0b-cb0342f5821d|
|Screen Reader|no|
|VM|44%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30438340
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
vscop841:30438915
dsvsc008:30440022
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vscaat:30438848

```

</details>

**Comment by rebornix** [comment]
We have fixes for this bug in Insiders now, which you can have a test once we release the new Stable this week.

**Comment by FLAMINGxFURY** [comment]
Thanks - will follow up at release.

**Comment by FLAMINGxFURY** [comment]
I've been working in notebooks today after the extension update, without any problem. If I find another case where this happens, I will reopen. Thank you!
