### ISSUE TITLE
Instructions for connecting to SQL/Kusto DB in ADS

### ISSUE THREAD

**Issue by Charles-Gagnon** [dotnet/interactive#1915]
Currently when you try to run a query in a SQL/Kusto cell that doesn't have a connection it prints a message like this : 

```
A SQL connection has not been established.

To connect to a database, first add the SQL extension package by running the following in a C# cell:

    #r "nuget:Microsoft.DotNet.Interactive.SqlServer,*-*"
```

But if the user does this they'll end up with other errors since the latest version of the package usually isn't going to work with the ADS version of the extension. The instructions should be updated to specify the exact version that users for the ADS version need to use.

**Comment by Charles-Gagnon** [comment]
Ok, with the correct version of the extension this doesn't seem to be an issue. The version it pulled worked correctly. But we should make sure that this isn't going to break in the future if newer versions of the sql/kusto extensions are released.

**Comment by jonsequitur** [comment]
Did you have NuGet configured to use an internal feed that might have a newer, incompatible version of the package?

**Comment by Charles-Gagnon** [comment]
Maybe - didn't really investigate that part of it when I had this issue. Given that I was able to get it working I'm not sure there's actually a bug here that customers would normally hit so I'm going to close this until we have a solid repro or issue to address.
