### ISSUE TITLE
How do I load classes from a local project?

### ISSUE THREAD

**Issue by rzippo** [dotnet/interactive#192]
I have seen examples using `#r "nuget:stuff"` but no example with a local library project.
I have tried `#r "/path/to/project"`, `#r "/path/to/project/project.csproj"`, `#r "/path/to/project/bin/[...]/project.dll"` but they all fail.

What am I doing wrong? And where should I find documentation for this tool?

**Comment by jonsequitur** [comment]
We don't currently support referencing a project file directly, but we're interested in supporting it.

You can do this in the meantime:

```
#!pwsh
dotnet build /path/to/project

#!csharp
#r /path/to/the/dll

// use the types in the library
```

**Comment by rzippo** [comment]
Does the path need to be absolute, or a relative one should work as well?

**Comment by jonsequitur** [comment]
Relative and absolute paths should both work.

**Comment by onionhammer** [comment]
@jonsequitur is there an issue tracking support for (something like) `#r "project: "` ?

**Comment by jonsequitur** [comment]
There is now: #890

**Comment by kubaszostak** [comment]
I'm not able to get it working... I would love to use <https://github.com/dotnet/interactive/issues/890> though.

![image](https://user-images.githubusercontent.com/4609437/160398358-41bc609b-02f3-4e73-a292-03188f899b4c.png)

**Comment by vzarytovskii** [comment]
> I'm not able to get it working... I would love to use #890 though.
> 
> ![image](https://user-images.githubusercontent.com/4609437/160398358-41bc609b-02f3-4e73-a292-03188f899b4c.png)

I think, full path to your project's dll should work.

**Comment by jonsequitur** [comment]
You can also do this in the C# kernel:

`#load "/path/to/the.dll"`

**Comment by kubaszostak** [comment]
This also doesn't work for me.

![image](https://user-images.githubusercontent.com/4609437/160459909-80f3edbd-9da0-4e86-80c2-9c9a98c2de40.png)

**Comment by jonsequitur** [comment]
Oh, sorry. `#load` is for source files. `#r` is for .dlls.

**Comment by kubaszostak** [comment]
Finally I managed to get it working (added assembly dll to '#r' directive):

```cs
#r "../ClassLibrary2/bin/Debug/ClassLibrary2.dll"
using ClassLibrary2;
Console.WriteLine(ClassLibrary2.Class1.Value);
```

**Comment by nczsl** [comment]
i very need to load local dll or  csproj but it is like many problem. some dll loading very long time and don't stop it.
i build my dll by vscode terminal ,and in net interactive notbooks ,by command #r load this dll. but the new added property is
not finded.

**Comment by brettfo** [comment]
Closing in favor of #890.
