### ISSUE TITLE
javscript not showing results if object

### ISSUE THREAD

**Issue by mika76** [dotnet/interactive#1950]
### Describe the bug
If you use javascript language, just ending the line with a variable does not show the result of that variable (like when using C#) - you have to use console.log.

Also, when you use console.log with an object, you get an error: "No renderer could be found for mimetype "application/json", but one might be available on the Marketplace."

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
```
Version: 1.0.317502+9c2a225c543085a04516cc4fc490919d5925ba87
Build date: 2022-03-25T20:43:44.0000000Z
```
- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [X] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![Screenshot 2022-03-31 at 10 39 06](https://user-images.githubusercontent.com/229311/161013931-f5e27026-212d-44af-9c55-dba307089902.png)

**Comment by jonsequitur** [comment]
We should consider having custom renderers built in for a few common scenarios like this.

But in the meantime, if you install a custom renderer, `console.log` of an object does work: 

<img width="377" alt="image" src="https://user-images.githubusercontent.com/547415/161161761-09f8d43c-8491-4b8f-bafb-7a998341ed36.png">

The one I'm using here is https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-table.

**Comment by jonsequitur** [comment]
Trailing expressions aren't supported like they are in C# and F# but you can get the same result using `return`:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/547415/161161977-43571803-138c-42ae-888c-3b4c0aa6906a.png">

Note I'm no longer using `const`. When referencing a variable across submissions, the `window` object is acting as your scope holder, so the above is equivalent to this:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/547415/161162051-7965bac6-e295-49e6-9610-f6c975e92150.png">

`let` and `const` declarations get hidden within a closure and can't be accessed from other cells. 

These are JavaScript language details that so far we haven't tinkered with, although the ergonomics might not be ideal.

**Comment by mika76** [comment]
> We should consider having custom renderers built in for a few common scenarios like this.

I think so - it's the first thing I tried just mostly because it's the most logical :smile:

> But in the meantime, if you install a custom renderer, `console.log` of an object does work:
> The one I'm using here is https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-table.

Thanks, this is great - I'll look into it - interesting that it shows a json result and not a data table - I guess the result might be hierarchical...

> Trailing expressions aren't supported like they are in C# and F# but you can get the same result using return:
> These are JavaScript language details that so far we haven't tinkered with, although the ergonomics might not be ideal.

Thanks for the `return` answer - it's easy enough and works well. But I think it would be awesome if it's the same as the C# way, purely out of consistency and logic (of course I have no idea how easy or hard that would be to implement)

One thing I was wondering, why can you only choose Javascript as a cell language but not as a notebook language? What is the difference?

Oh and also are there any plans to do Typescript?

(btw I just started playing with the notebook feature and am blown away with the usefulness - thank you guys so much for this!)

**Comment by colombod** [comment]
Issue has been fixed by vscode team. just update vscode
