### ISSUE TITLE
Notebooks in Visual Studio?

### ISSUE THREAD

**Issue by Regenhardt** [dotnet/interactive#1959]
### Question

Is it possible to use .NET Interactive Notebooks in Visual Studio (2022) and get the better IntelliSense? Kinda missing that in vscode when working with a new lib where I don't know the exact methods I'm gonna need yet.

**Comment by jonsequitur** [comment]
There is a [notebook editor in preview](https://marketplace.visualstudio.com/items?itemName=MLNET.notebook) but currently, the IntelliSense support is more mature in the VS Code extension.

Could you give an example of where you're expecting IntelliSense and not seeing it in VS Code? Could you also include a screen shot large enough to show which kernel you're using and what the cell-specific language is?

**Comment by Regenhardt** [comment]
Nice, will try the preview.

I was hoping to see the documentation of a method in intellisense.  
Visual Studio 2022 does this, example from a console application, displaying inputs and description:

![image](https://user-images.githubusercontent.com/10476293/162696780-376ec10a-ecf5-4e48-b275-4377a31d9bb0.png)

VSCode just shows autocomplete, but no documentation:

![image](https://user-images.githubusercontent.com/10476293/162696707-54c64818-4110-4b8f-a06f-1aab5418a18a.png)

**Comment by jonsequitur** [comment]
Like this?

<img width="695" alt="image" src="https://user-images.githubusercontent.com/547415/162758433-39deb9e4-b529-4d6d-9a41-e2f8a6327153.png">

Inline documentation is there in VS Code but it has a tendency to hide. If you're not seeing it, you can bring it up by hovering over one of the completion items and clicking the arrow that appears to the right:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/547415/162758776-986e72cb-ac96-4222-9da4-41ec9fe40055.png">

**Comment by rjra2611** [comment]
Hey @jonsequitur 

I'm using Jupyter Notebooks in VSCode and I have imported my modules but I'm unable to get inline documentation for the autocomplete suggestions. 

> you can bring it up by hovering over one of the completion items and clicking the arrow that appears to the right:

As you suggested, I tried hovering over the completion but I don't see any arrow icon appearing which I can click.


![image](https://github.com/dotnet/interactive/assets/28739120/b5ebd758-d847-45fe-85df-e1cfb29fb8d4)

![image](https://github.com/dotnet/interactive/assets/28739120/38ba9887-f752-471c-80dd-aec1798d54ca)
