### ISSUE TITLE
Shared byte[] variable becomes byte

### ISSUE THREAD

**Issue by Regenhardt** [dotnet/interactive#1960]
### Describe the bug

* Initialise a byte[] in a C# cell
* #!share that variable in an F# cell
* Variable is now a byte

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

Version: 1.0.317502+9c2a225c543085a04516cc4fc490919d5925ba87

Build date: 2022-04-05T08:19:21.2422480Z

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/10476293/162736295-2117ffa5-da0a-4653-b3d5-a9fbfe6a61a9.png)

**Comment by brettfo** [comment]
The bug is in how F# handles bound values.  It was fixed on the F# side in dotnet/fsharp#12606 and as soon as the next version of Visual Studio is released we'll be able to consume the updated packages here.
