### ISSUE TITLE
VS Code DIB files: "Create new blank notebook' resulted in an error (Notebook Editor creation failure for documenet [object Object])"

### ISSUE THREAD

**Issue by mikoskinen** [dotnet/interactive#1963]
### Describe the bug

No matter what I do I can't get the VS Code to work with DIB files with my Win 10 computer. .ipynb files work like they should but I can't create or open DIB-files because I always get the following error:

"Create new blank notebook' resulted in an error (Notebook Editor creation failure for documenet [object Object])"

![image](https://user-images.githubusercontent.com/143570/163104805-89b33c69-a603-4272-80e4-4b2ddb4eb658.png)

Note the typo in "documenet". Maybe that can help finding the correct spot from code.

I have tried to reinstall every extension multiple times and even uninstalled VS Code and installed it again. No luck. I'm only running the following extensions:

![image](https://user-images.githubusercontent.com/143570/163104961-72423652-bb1b-4007-bcc6-f370f01bc525.png)

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Version info:

dotnet-interactive --version
1.0.317502+9c2a225c543085a04516cc4fc490919d5925ba87

 dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

VS Code

Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19043

### Some additional info

Like I mentioned, ipynb files work:

![image](https://user-images.githubusercontent.com/143570/163105382-e5e7d5c3-0743-461e-849e-75dab2bf167b.png)

VS Code is installed using the installer from https://code.visualstudio.com/

**Comment by poychang** [comment]
I face the smae issue too. Now I just downgrade to v1.0.3103010 to use .dib files.

**Comment by jonsequitur** [comment]
This was most likely a point-in-time issue due to a VS Code API update. If you see it again, please feel free to reopen the bug and if you can, include output from the diagnostics and logging panes:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/547415/173641312-ad3e035c-ce22-477d-a972-afb57f31c436.png">

**Comment by dfinke** [comment]
Cool. TIL: mermaid was a magic command, and there is a diagnostic pane.

![image](https://user-images.githubusercontent.com/67258/173672214-6204c1f5-ef0e-412a-be5b-273a6d496983.png)

**Comment by jonsequitur** [comment]
Mermaid is also (implemented as) a kernel. It'll show up in the kernel picker soon.
