### ISSUE TITLE
Double line spacing in new notebooks in vscode

### ISSUE THREAD

**Issue by jhoneill** [dotnet/interactive#1964]
### Describe the bug
Output is double spaced -  I don't think this is a VS code issue because old notebooks render fine 

**Old notebook**
![image](https://user-images.githubusercontent.com/16209593/163136611-c9423d94-3456-48cb-9799-b674572d5c4d.png)

**New notebook**
<img width="432" alt="image" src="https://user-images.githubusercontent.com/16209593/163136571-0de750ff-a3f3-4321-8696-1b2c06b956e1.png">

### Please complete the following:

**Which version of .NET Interactive are you using?** Version: 1.0.317502+9c2a225c543085a04516cc4fc490919d5925ba87

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
See above

**Comment by jhoneill** [comment]
https://github.com/microsoft/vscode/pull/149842 

has been committed to fix this - it has gone into the latest code insiders and I have not yet had a chance to check it, but it looks like this issue will be closable soon :-)

**Comment by jonsequitur** [comment]
@brettfo

**Comment by jhoneill** [comment]
I've installed the latest code insiders and that has fixed the issue. Nasty strobe effect as if each line printed refreshed the page, but at least it is single spaced. Just need it to move to the stable release.
