### ISSUE TITLE
Migrate off of the concat text document API proposal

### ISSUE THREAD

**Issue by mjbvz** [dotnet/interactive#1966]
👋  Hi, I work on APIs for VS Code

The VS Code Dot Net Interactive notebooks extension currently has access to the `concatTextDocument` api proposal. We do not plan to finalize this proposal and instead would like to remove to simplify our code. See https://github.com/microsoft/vscode/issues/146781 for details

From a quick search through this repo, I don't think this extension is using `ConcatTextDocument` but please confirm this and let me know when we can safely remove Dot Net Interactive from the list of this api's consumers

**Comment by jonsequitur** [comment]
@brettfo Could you please confirm?

**Comment by brettfo** [comment]
Confirmed, we don't use the concat text document APIs.

@mjbvz you can remove us from the list.

**Comment by mjbvz** [comment]
Thanks for confirming! Will be removed in the next insiders build
