### ISSUE TITLE
How to Register Comm in Kernel?

### ISSUE THREAD

**Issue by AlirezaEiji191379** [dotnet/interactive#1970]
Hi!
I cloned your project and I realize that you add support for comm messages in Microsoft.DotNet.Interactive.Jupyter!
but i do not know how to register comm code in the kernel like the [IPython kernel](https://jupyter-notebook.readthedocs.io/en/stable/comms.html) from frontend!

could you please add documentation about that and explain it to me whether i can register comm in your project or not?

**Comment by AlirezaEiji191379** [comment]
#1506  
this is similar question

**Comment by AlirezaEiji191379** [comment]
does this project have some handlers for comm_open, comm_msg and comm_close message types according to [messaging in jupyter](https://jupyter-client.readthedocs.io/en/stable/messaging.html#custom-messages) ?

**Comment by brettfo** [comment]
Jupyter comms improvements are on the future roadmap.
