### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'getVariable') (interactive.csharp.getVariable())

### ISSUE THREAD

**Issue by andrerav** [dotnet/interactive#1975]
### Describe the bug
Run the following JavaScript example from the [docs](https://github.com/dotnet/interactive/blob/main/docs/javascript-overview.md):
![image](https://user-images.githubusercontent.com/3635018/164109679-c6af9d56-630a-40e4-8980-69471a26082b.png)
Expected: Example works.
Actual: Error: Cannot read properties of undefined (reading 'getVariable')
### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.317502+9c2a225c543085a04516cc4fc490919d5925ba87
Build date: 2022-04-19T21:48:04.4582881Z

- OS
    - [ ] Windows 11
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/3635018/164109792-57e958b2-6793-415e-a8ee-23d23a78660e.png)

**Comment by roberthusak** [comment]
As per https://github.com/dotnet/interactive/issues/1803#issuecomment-984816037 this seems to be the problem of outdated documentation, `#!share --from csharp x` should work.

**Comment by andrerav** [comment]
Thank you @roberthusak.
