### ISSUE TITLE
`.NET Interactive` from vscode extension vs `.NET (C#)` from `dotnet interactive jupyter install`

### ISSUE THREAD

**Issue by maxild** [dotnet/interactive#1987]
**The package and version I'm asking about**: 

```bash
$ dotnet interactive --version
1.0.317502+9c2a225c543085a04516cc4fc490919d5925ba87
```

`#!about` magic command output:

```
.NET Interactive

© 2020 Microsoft Corporation

Version: 1.0.317502+9c2a225c543085a04516cc4fc490919d5925ba87

Build date: 2022-03-25T20:43:44.0000000Z

https://github.com/dotnet/interactive
```

### Question

I have installed both the [vscode extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode) based kernel (called `.NET Interactive` in vscode) and the `dotnet-interactive tool based kernel`  (called `.NET C#` in vscode) seen by running

```bash
$ jupyter kernelspec list
Available kernels:
  .net-csharp        /home/maxfire/.local/share/jupyter/kernels/.net-csharp
  .net-fsharp        /home/maxfire/.local/share/jupyter/kernels/.net-fsharp
  .net-powershell    /home/maxfire/.local/share/jupyter/kernels/.net-powershell
  julia-1.7          /home/maxfire/.local/share/jupyter/kernels/julia-1.7
  python3            /home/maxfire/anaconda3/share/jupyter/kernels/python3
```

If I run the following C# script in a cell

```csharp
#r "nuget: System.CommandLine, 2.0.0-beta3.22222.1"

var root = new System.CommandLine.RootCommand("desc");
var command = new System.CommandLine.Command("name", "desc");

return (root.GetType().ToString(), command.ToString());
```

it fails in the `.NET Interactive` kernel 

```
Error: System.CommandLine version 2.0.0-beta3.22222.1 cannot be added because version 1.0.0.4 was added previously.
```

but it succeeds in the `.NET (C#)` kernel. 

Item1 | Item2
-- | --
System.CommandLine.RootCommand | Command: name

**Question**: What are the main differences between the two kernels?

**Comment by jonsequitur** [comment]
If you run `#!about` in VS Code and in Jupyter you'll most likely see different versions. They're both using the same `dotnet-interactive` tool but the VS Code extension manages its own installation of it, which at any given moment might be at a different version from the one you've installed globally that's used by Jupyter.

There are some small configuration differences but the goal is to make sure that notebooks that work in one frontend also work in the others.

What you're seeing with System.CommandLine is that since `dotnet-interactive` references it directly, you can't load a different version of it.

**Comment by maxild** [comment]
> There are some small configuration differences but the goal is to make sure that notebooks that work in one frontend also work in the others.

I am actually not using any of the traditional Jupyter clients/frontends (notebook and/or lab) -- although I could for the global tool installed kernels (I have jupyter and all the core packages installed; cf the `$ jupyter kernelspec list` command above). I am instead using the vscode client (that is in preview, I believe) in both examples above. I am not sure if this matter? But I guess that the `.NET Interactive` kernel is not using the jupyter/python based web server. And that the `.NET C#` kernel (on the other hand) is using the python (web-)based server.

Does this also explain why `System.CommandLine` is only loaded into the CLR when using the vscode managed (non jupyter/python based) installation?

**Comment by maxild** [comment]
These are my findings using `AssemblyLoadContext`:

`System.CommandLine` is only loaded in the first example...

### .NET Interactive

index | value
-- | --
0 | System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
1 | System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2 | Microsoft.DotNet.Interactive, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
3 | Microsoft.DotNet.Interactive.VSCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
4 | System.Linq, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

### .NET (C#)

index | value
-- | --
0 | System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
1 | Microsoft.DotNet.Interactive, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2 | Microsoft.DotNet.Interactive.Jupyter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
3 | System.Linq, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Comment by maxild** [comment]
This is probably unimportant to most people. 

I am just seeing a lot of options, after trying out .NET based notebooks: 

- kernel (this question)
- file formats (dib vs ipynb...confusing(!) for beginner)

Feel free to close
