### ISSUE TITLE
JS: `import` does not work

### ISSUE THREAD

**Issue by BananaAcid** [dotnet/interactive#1993]
### Describe the bug
One would expect `import` to work, as it is just default js by now.

It shows "Error: Cannot use import statement outside a module" ... but the root of a JS env should be module compatible.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

1.0.317502+9c2a225c543085a04516cc4fc490919d5925ba87

- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by colombod** [comment]
Thank you. We need to support ```type="module"``` attribute.

**Comment by BananaAcid** [comment]
Tried some ESM I created and host myself (a color conversion module, tried using an interactive document for teaching in school) . The jQuery module would probably be an example to target.

**Comment by colombod** [comment]
is there any other way you can achieve loading like emitting a script tag or using require to import the esm you need?

**Comment by BananaAcid** [comment]
Example code:
```js
// ref: https://github.com/BananaAcid/hex-and-rgba/blob/master/esm/index.mjs
import { hexToRgba } from 'https://rawcdn.githack.com/BananaAcid/hex-and-rgba/7b1c5056ade972c1fe94b549c01eff3a65597bd6/esm/index.mjs';

const [red,green,blue, alpha] = hexToRgba('#1B2B34cc');
console.log('colors:', [red,green,blue, alpha]);
```

Just the usual ES6 Modules stuff.

**Comment by colombod** [comment]
@rebornix

**Comment by colombod** [comment]
@rebornix is there any update on vscode side?

**Comment by colombod** [comment]
@rebornix we are using the new preloads api with es module exporting the activate contract. still this issue seems to be unresolved, how can the scenario be enabled?

**Comment by brettfo** [comment]
There's a slightly odd workaround that we found; it requires using an HTML cell for the `import` line (and assigning it to the `window` object) and in a separate JS cell running the actual code.

<img width="588" alt="image" src="https://user-images.githubusercontent.com/926281/210869300-b905271e-21e0-44c5-8ab4-53e819e013d3.png">

**Comment by colombod** [comment]
in pure js this is the way to use import
<img width="645" alt="image" src="https://user-images.githubusercontent.com/375556/211668477-9905de29-c024-4985-8e3f-a9776f514740.png">

this works too

**Comment by colombod** [comment]
interesting use of import  [here]( https://2ality.com/2019/10/eval-via-import.html)
