### ISSUE TITLE
Migrate off of the notebookEditorDecorationType API proposal

### ISSUE THREAD

**Issue by mjbvz** [dotnet/interactive#1994]
👋  Hi, I work on APIs for VS Code

The VS Code Dot Net Interactive notebooks extension currently has access to the `notebookEditorDecorationType ` api proposal. We do not plan to finalize this proposal and instead would like to remove to simplify our code. See https://github.com/microsoft/vscode/issues/146838 for details

From a quick search through this repo, I don't think this extension is using this api but please confirm this and let me know when we can safely remove Dot Net Interactive from the list of this api's consumers

**Comment by brettfo** [comment]
We're not using the `notebookEditorDecorationType` APIs and they can be safely removed.
