### ISSUE TITLE
Migrate off of the textDocumentNotebook API proposal

### ISSUE THREAD

**Issue by mjbvz** [dotnet/interactive#1995]
👋  Hi, I work on APIs for VS Code

The VS Code Dot Net Interactive notebooks extension currently has access to the `textDocumentNotebook` api proposal. We do not plan to finalize this proposal and instead would like to remove to simplify our code. See https://github.com/microsoft/vscode/issues/147414 for details

Can you please check to see if your extension is currently using this API. If it is, please look into migrating off of it so we can remove this API from our code

**Comment by brettfo** [comment]
We're not using the `textDocumentNotebook` APIs and they can be safely removed.
