### ISSUE TITLE
Variable sharing not working with powershell on MacOS

### ISSUE THREAD

**Issue by mika76** [dotnet/interactive#1996]
### Describe the bug
I put the following in a C# code block
```c#
var outputvar = "Something";
#!share --from csharp outputvar
```
and then this in a poweshell block
```powershell
$psval = "psv"
Write-Output "hi"
Write-Output $psval
Write-Output $outputvar
```

I get the result
```
hi
psv
```

*NOTE* value of $outputvar is missing
### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
> .NET Interactive
> Version: 1.0.317502+9c2a225c543085a04516cc4fc490919d5925ba87
> Build date: 2022-03-25T20:43:44.0000000Z

Powershell version 7.2.2

- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

<img width="1293" alt="Screenshot 2022-05-02 at 13 42 04" src="https://user-images.githubusercontent.com/229311/166228179-cfefd12f-b9dd-4e85-aa67-f9acf69bd85e.png">

**Comment by jonsequitur** [comment]
The `#!share` magic shares into a kernel, so you should use it within the PowerShell cell:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/547415/168934132-d4f82fb0-e311-4d2d-a9bc-2f2db3b76238.png">

Your first cell is trying to share a nonexistent variable. The fact that there's no error message for that is a bug.

**Comment by mika76** [comment]
Oh right! I see, and that works thanks.

Although I find it confusing - I guess maybe because the keyword is `share` so I assume I'm telling the cell to share _with_ other cells, not _from_ other cells 😊 

Thanks for your help.

**Comment by mika76** [comment]
@jonsequitur should I close this? (I ask because I notice you added the documentation tag)

**Comment by jonsequitur** [comment]
Feel free to close it. We'll use the documentation tag for later reference.

> Although I find it confusing - I guess maybe because the keyword is share so I assume I'm telling the cell to share with other cells, not from other cells 😊

Agreed! We're consider renaming it to something like `#!import` (and aliasing it for backwards compatibility.) Would that or another name make it clearer?

**Comment by mika76** [comment]
yeah maybe `#!import` makes more sense - at least the direction is a bit more clear. I do wonder if you might want to do something like `importvar` or `import-var` purely because the keyword `import` is so prevalent in programming and languages and people might get confused that it means importing a file or something. But I think it's way clearer than share anyway...
