### ISSUE TITLE
Can't run from vscode extension install.

### ISSUE THREAD

**Issue by nigelatdas** [dotnet/interactive#1999]
### Describe the bug
I'm trying to install the vscode extension. 
It says it installed and is enabled. 
I run create new blank notebook... I get `command 'dotnet-interactive.newNotebook' not found`.

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
(see images)

- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [x] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/91711992/166878275-c76f6410-5b3a-487b-91eb-e9222342bec4.png)
![image](https://user-images.githubusercontent.com/91711992/166878312-2477b2ab-2710-44fe-8ba6-01ef180babe5.png)

**Comment by brettfo** [comment]
My guess is that the dotnet SDK wasn't found.  Can you click View -> Output then set the drop down on the right to ".NET Interactive : diagnostics" and copy/paste the output here?

**Comment by nigelatdas** [comment]
```
Unable to determine the version of the .NET SDK.
STDOUT:

STDERR:


```
However...
![image](https://user-images.githubusercontent.com/91711992/167045610-4a801fe7-bc25-4d18-84b8-bb1281631f5c.png)
![image](https://user-images.githubusercontent.com/91711992/167045656-29a9efc8-bb96-4b75-a48d-e933706b89ae.png)

**Comment by nigelatdas** [comment]
![image](https://user-images.githubusercontent.com/91711992/167045726-f1bcc266-ba0d-4626-850d-d0e9ce2adf08.png)

**Comment by nigelatdas** [comment]
```

**Comment by jonsequitur** [comment]
Does this work if you run from a full install rather than from Snap?
