### ISSUE TITLE
Excess re-rendering causes waiting times after cell completion

### ISSUE THREAD

**Issue by Happypig375** [dotnet/interactive#2000]
### Describe the bug
```cs
for (var i = 0; i <= 100; i++) System.Console.WriteLine(i);
```
It is expected that such a small number of console writes would complete instantly. Indeed it does, however, excess re-rendering takes place immediately afterwards, costing additional seconds. This waiting time grows with the number of console writes, which is undesirable especially when used inside a loop.

It seems that a render function is called every time console output changes. It would probably be a lot faster if it buffered the output and just rendered it when the end of the cell is reached.

![image](https://user-images.githubusercontent.com/19922066/167149109-9e325afb-041f-497f-92e7-292128a83804.png)

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by bisen2** [comment]
For the solution of buffering output and only rendering at the end, it would probably need to be an opt-in feature to avoid breaking code that may rely on having output written before the cell is done:
```fs
printfn "Beginning long computation"
let result = longComputation()
printfn "Done"
```

Maybe a magic command would be a good way to say that you want a specific cell to only render once at the end?
