### ISSUE TITLE
Migrate off of notebookContentProvider VS Code API proposal

### ISSUE THREAD

**Issue by mjbvz** [dotnet/interactive#2004]
👋  Hi, I work on APIs for VS Code

The VS Code Dot Net Interactive notebooks extension currently has access to the `notebookContentProvider` api proposal. We currently do not plan to finalize this proposal and instead would like to remove to simplify our code. See https://github.com/microsoft/vscode/issues/147248 for details

Please let me know if your extension is currently using this API. If it is, please add some details about which parts of the API you are using so we can figure out how to migrate off of it

**Comment by jonsequitur** [comment]
@brettfo?

**Comment by brettfo** [comment]
We don't use these APIs and I've created #2017 that removes references to them.
