### ISSUE TITLE
[PowerShell] InvalidOperation: The property 'histfunc' cannot be found on this object

### ISSUE THREAD

**Issue by dfinke** [dotnet/interactive#201]
Using Chrome.

https://mybinder.org/v2/gh/dotnet/interactive/master?filepath=powershell%2FDocs

![image](https://user-images.githubusercontent.com/67258/75291743-cf4e3c80-57f0-11ea-9bf4-84bae58fe94a.png)

**Comment by daxian-dbw** [comment]
It works fine for me in mybinder

![image](https://user-images.githubusercontent.com/127450/75371866-63191a80-587c-11ea-83d1-590479cc345d.png)

Can you please share the environment (mybinder? local build (if so, what platform)?) and repro steps?

**Comment by dfinke** [comment]
That was the link Tyler tweeted yesterday. I'll try again.

**Comment by dfinke** [comment]
Sorry, it does work. I missed running one of the previous cells.
