### ISSUE TITLE
Visual Studio Notebooks: Tool tip obscures MD text.

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet/interactive#2010]
### Describe the bug
A small tool tip window pops up, partially obscuring the previous cell. See attached screenshot.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ): 1.0.310301

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] Interact
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [X] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![Screenshot 2022-05-13 094908](https://user-images.githubusercontent.com/1791495/168330999-1f1de948-e035-433c-a6ac-0ccb67f78e3f.png)

**Comment by zewditu** [comment]
@NiklasGustafsson  thanks we will take look

**Comment by claudiaregio** [comment]
Closing as support for notebooks in VS has been discontinued
