### ISSUE TITLE
Visual Studio Notebooks: newlines in string output are lost.

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet/interactive#2011]
### Describe the bug
When I run a cell that produces string output, and that output contains newline characters, the expected multiple lines are not shown.

I have attached screenshots of VS Code and VS formatting a multiple-line output of a TorchSharp tensor.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):1.0.310301

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] Interact
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [X] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![Screenshot 2022-05-13 101442](https://user-images.githubusercontent.com/1791495/168334939-80288f21-c1f1-4270-b04c-5a9752832545.png)
![Screenshot 2022-05-13 101356](https://user-images.githubusercontent.com/1791495/168334942-fec40a19-b89a-4df0-a34d-b5b97511a35a.png)

**Comment by zewditu** [comment]
Related with https://github.com/dotnet/interactive/issues/2012

**Comment by claudiaregio** [comment]
Closing as support for notebooks in VS has been discontinued
