### ISSUE TITLE
Long array shows up with additional blank lines.

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet/interactive#2012]
### Describe the bug
The formatting of a 'long[]' output from a cell differs from VS Code, with extra blank lines between each row.
### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [X] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)
![Screenshot 2022-05-13 102620](https://user-images.githubusercontent.com/1791495/168336407-c4b1c6aa-149a-4fb3-998d-c9093f11fed2.png)
![Screenshot 2022-05-13 102640](https://user-images.githubusercontent.com/1791495/168336410-0454a54f-a48b-4b28-91e9-551f786560b7.png)

**Comment by claudiaregio** [comment]
Closing as support for notebooks in VS has been discontinued
