### ISSUE TITLE
Allow WYSWYG while editing the markdown in the notebooks

### ISSUE THREAD

**Issue by tarekgh** [dotnet/interactive#2013]
When editing the markdown sections in the notebooks in VS, there is no way to visualize the markdown while editing it. Will be nice to add this feature as the one exists today in Visual Studio Code.

**Comment by zewditu** [comment]
@tarekgh  are you able to  add the screenshot of the feature in Vs code ?

**Comment by claudiaregio** [comment]
Closing as support for notebooks in VS has been discontinued
