### ISSUE TITLE
Mimic the VS Code cell manipulation UX

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet/interactive#2014]
### Describe the bug

Suggestion: VS Code has a number of cell-oriented commands on the right, near the corner of the cell. The menu is different depending on whether it's a code or markdown cell.

I suggest drawing inspiration from that UI in VS Notebooks, too.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [X] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![Screenshot 2022-05-13 104415](https://user-images.githubusercontent.com/1791495/168339102-4ec3d41d-bc54-4742-bba8-d7cbae4312ed.png)

**Comment by NiklasGustafsson** [comment]
Great! One minor, fit-and-finish detail: the spelling of 'Paste Cell' is wrong in that picture, and the items 'Copy cell', 'Cut cell', and 'Join With previous Cell' uses capitalization that is inconsistent with the rest of the menu.

**Comment by zewditu** [comment]
![image](https://user-images.githubusercontent.com/36615490/175179631-8c977c53-2b8a-4dcb-8820-48e309117fb3.png)

**Comment by claudiaregio** [comment]
Closing as support for notebooks in VS has been discontinued
