### ISSUE TITLE
Allow default settings for .ipynb vs. .dib and default setting for default new notebook language

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#2024]
When creating a new notebook through the command palette, a user always has to select whether they want to use the .ipynb format or the .dib format. 

Would be nice if there were a setting that allowed users to select a default file type such that they don't have to select every time they create a new notebook. For users who stick to one file type (my assumption is most do this), it would reduce the creation of notebooks by one click. 

### Currently: 
![image](https://user-images.githubusercontent.com/19276747/169624716-5c36d3db-e46f-42e3-9f52-5b2159eae8ae.png)
![image](https://user-images.githubusercontent.com/19276747/169624728-62df25cf-be9c-4a5e-880e-3b5608e69aa0.png)
![image](https://user-images.githubusercontent.com/19276747/169624741-0f48230a-aa30-400f-b052-b120bd30f272.png)

### With setting: 
![image](https://user-images.githubusercontent.com/19276747/169624716-5c36d3db-e46f-42e3-9f52-5b2159eae8ae.png)
![image](https://user-images.githubusercontent.com/19276747/169624741-0f48230a-aa30-400f-b052-b120bd30f272.png)

**Comment by jonsequitur** [comment]
The same would be useful for the default language.
