### ISSUE TITLE
Add variable explorer icon to toolbar 

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#2025]
Since we are shipping the variable explorer, let's add the icon to match that of Jupyter to maintain consistency across experiences + increase discoverability for our users. (+telemetry that shows us how often it's being opened through the toolbar icon) 

![image](https://user-images.githubusercontent.com/19276747/112914380-b2013700-90b0-11eb-81ac-160a668be954.png)

**Comment by jonsequitur** [comment]
Can you show an example of where this button would go?

**Comment by claudiaregio** [comment]
Python experience has it just to the left of Table of Contents icon

![image](https://user-images.githubusercontent.com/19276747/169632839-c0d40359-8262-49d4-b4c3-927d06adaa4b.png)
