### ISSUE TITLE
Variable explorer not working

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#2026]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

Version: 1.0.325601+1743a009db9b6b64e33146e1681731acc785a7cf

- OS
    - [x] Windows 11

 - Frontend
    - [x] Visual Studio Code 

### Steps to reproduce: 
1. Create new .NET interactive notebook
2. Assign variable to number and run 
3. Open terminal and open 

### Expectation
Value to be generated and show up in the variable explorer

### Screenshots
![image](https://user-images.githubusercontent.com/19276747/169628402-869a8c20-b91a-484a-9ee1-c14d9952bea0.png)

**Comment by jonsequitur** [comment]
I'm not able to reproduce this. Could you include a wider screenshot that shows the whole VS Code window?

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/169632899-7356dcf8-5299-4df5-976c-6c467843e5ab.png)

**Comment by jonsequitur** [comment]
It looks like you have a pending VS Code update (based on the badge on the gear icon in the lower left). Can you try restarting and seeing if that resolves it?

**Comment by claudiaregio** [comment]
Ah shoot how is that possible I had just updated before I did this! ok let me check

**Comment by claudiaregio** [comment]
ya love to see it

![image](https://user-images.githubusercontent.com/19276747/169663435-f9d4b595-06c5-4f64-ac07-e210311c17c3.png)

**Comment by claudiaregio** [comment]
Ok so i had to completely uninstall vs code and reinstall it but working now
