### ISSUE TITLE
Restart Kernel for C# notebooks

### ISSUE THREAD

**Issue by marckruzik** [dotnet/interactive#2032]
**Is your feature request related to a problem? Please describe.**
I'm working with C# notebooks (ipynb), and there are cases where I need to restart the C# Kernel.

**Describe the solution you'd like**
When working with Python I can restart the Python Kernel.
So when I am working with C#, I would like to be able to restart the C# Kernel.

**Describe alternatives you've considered**
Currently, I have to close and reopen VS Code each time I want to restart the C# Kernel.

**Comment by marckruzik** [comment]
I found by chance that there is a command to restart the current notebook's kernel.

![2022_05_27-19h11m25s-● notebook_csx_tests ipynb - Notebook_Converter_CSX - Visual Studio Code](https://user-images.githubusercontent.com/51711029/170754522-2f18f636-7376-4183-8fb4-ee7bf17f8108.png)

So the enhancement proposal would become the following:
Add a button to use the command "restart the current notebook's kernel". 
This button should be the same than the one we have when working with Python interactive:

![2022_05_27-19h13m47s-● notebook_csx_tests ipynb - Notebook_Converter_CSX - Visual Studio Code](https://user-images.githubusercontent.com/51711029/170756101-08f4f58f-4de3-45ca-99d3-825eec888f90.png)

**Comment by claudiaregio** [comment]
I think we should add this to achieve toolbar parity with Python, I don't think core will tackle the shared icon for a while.

**Comment by marckruzik** [comment]
Fixed by #2326.
