### ISSUE TITLE
Notebook specific methods such as display or HTML cannot be loaded from csx file

### ISSUE THREAD

**Issue by marckruzik** [dotnet/interactive#2033]
### Describe the bug
I am converting C# ipynb notebooks into csx files. Then those csx files are loaded into other notebooks with the #load directive. 

It works for the most part. But there are a few methods such as "display" and "HTML" which cause errors.
I tried adding references and using in the csx file, but I did not find any solution.

Is there a way to load a csx file containing a notebook specific method such as display or HTML?

Here is how to reproduce the problem:

In a script_display.csx file:
`display("display hello");`

In a C# notebook cell:
`#load "script_display.csx"`

Output of the C# notebook cell:
`Error: path\script_display.csx(5,5): error CS0103: The name 'display' does not exist in the current context`

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

1.0.317502+9c2a225c543085a04516cc4fc490919d5925ba87

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
There's some related discussion here: #322.

**Comment by marckruzik** [comment]
> There's some related discussion here: #322.

Thanks jonsequitur, this is the kind of plugin I was looking for.
