### ISSUE TITLE
Adopt the new vscode notebookWorkspaceEdit API proposal

### ISSUE THREAD

**Issue by mjbvz** [dotnet/interactive#2036]
👋  We're currently working to finalize VS Code apis for editing notebooks. As part of this work, we've deprecated the `notebookEditorEdit` API proposal and have replaced it with a [new `notebookWorkspaceEdit` proposal](https://github.com/microsoft/vscode/blob/18cf3d01ed22f7b35895a9b3c531048c835d4489/src/vscode-dts/vscode.proposed.notebookWorkspaceEdit.d.ts#L13)

This proposal should offer the same functionality as the old API, but expresses it differently. 

However before finalizing this new API, we'd like to hear your feedback about it. Please try migrating to the new `notebookWorkspaceEdit` API and let me know if you run into any problems or have any concerns

If everything looks good with the `notebookWorkspaceEdit` proposal, please go ahead and check in the migration to the new API so we can eventually remove the old, now deprecated `notebookEditorEdit` proposal 

See https://github.com/microsoft/vscode/issues/149181 for details

**Comment by brettfo** [comment]
The new APIs look good from our end.  @mjbvz what's the proposed timeline for the change in both insiders and stable?

**Comment by mjbvz** [comment]
`notebookWorkspaceEdit` is already in insiders and will be in VS Code 1.68

Once you've adopted it and are no longer using `notebookEditorEdit `, please let me know and I'll remove you from the list of `notebookEditorEdit` consumers

**Comment by brettfo** [comment]
I guess more interesting to us is when the new APIs will be in stable and how long the old APIs will be in insiders?  We build both stable and insiders versions of our extension from the same code, so we need to be able to compile (deprecation warnings are fine) and run against both.

**Comment by mjbvz** [comment]
The new apis will be in 1.68 which will ship next week. To ship using them, you'll need to update the min VS Code version in your extension to 1.68 as well

The old apis will be removed once they are no longer being used by any extensions (including dot net :))

**Comment by brettfo** [comment]
Excellent!  In that case, we'll stay on the old APIs until next week and as soon as stable 1.68 ships we'll immediately update to the new APIs and publish both versions of our extension.
