### ISSUE TITLE
Does this library not support remote PowerShell commands

### ISSUE THREAD

**Issue by wf-soft** [dotnet/interactive#2041]
I try to run a remote session and it will get an error

![image](https://user-images.githubusercontent.com/62228539/170850004-b482ab16-a655-447b-a31f-702644507239.png)

**Comment by jonsequitur** [comment]
@daxian-dbw Any thoughts on this?

**Comment by daxian-dbw** [comment]
Remoting is not supported in .NET Interactive because it depends on `BinaryFormatter` which is not allowed to be used in .NET Interactive. But the good news is we have removed this dependency in PowerShell 7.3-preview.4, so this will work once moved to PowerShell 7.3 by the end of this year.

**Comment by brettfo** [comment]
The PowerShell library has been updated to 7.3.0, can you give this a shot in the latest version?

**Comment by kfasick** [comment]
I can confirm working pwsh 7.3.3 Invoke-Command -ComputerName <ComputerName> -ScriptBlock {<ScriptBlock>} in Polyglot Notebooks v1.0.4152011 preview, code v1.76.0
Need anything specific to help waiting-on-feedback or Needs verification?
