### ISSUE TITLE
VS Code variable explorer doesn't know about all kernels

### ISSUE THREAD

**Issue by brettfo** [dotnet/interactive#2049]

**Comment by AbhitejJohn** [comment]
@brettfo : What kernels do we show today and what are we missing?

**Comment by brettfo** [comment]
We currently have a [hard-coded list](https://github.com/dotnet/interactive/blob/e1dee7bd7eaf9e2dc5e367b8267ee22b51091287/src/microsoft-dotnet-interactive/src/webview/kernelApiBootstrapper.ts#L47-L51) with only the well-known kernels, but our current work to update the JS APIs properly flows the `KernelInfoProduced` events so this list is properly dynamic.
