### ISSUE TITLE
If #r fails due to timeout then the cell will still fail until restarting the kernel

### ISSUE THREAD

**Issue by colombod** [dotnet/interactive#2051]
### Describe the bug
Loading a package using #r that times out will keep the error cached and won't let user re run the action without restating the kernel

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
<img width="343" alt="image" src="https://user-images.githubusercontent.com/375556/172475280-d33c56fb-03c2-4647-8f34-5bd557795d04.png">

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [X] Visual Studio Code Insiders
    - [X] Visual Studio
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
Does #2054 resolve this?

**Comment by colombod** [comment]
Only relative to timeout error, any other error will be cached and won't let the user perform the #r without restarting the kernel

**Comment by jonsequitur** [comment]
The issue is specific to a timeout. What other kinds of errors are we talking about?
