### ISSUE TITLE
 Import table from same Notebook

### ISSUE THREAD

**Issue by Ayanmullick** [dotnet/interactive#208]
**Is your feature request related to a problem? Please describe.**
As an Azure Architect, one of the notebook features that sounded most promising to me was the ability to put markdown documentation and PowerShell deployment automation script in one file. 

However, since there is no a way to reference a text block from a code block one would need to import a tabled set of parameter values from an external file.

**Describe the solution you'd like**
It'd be convenient if there was a way for one to populate a variable in a code block with content from a text block without having to use a second file. 
For eg. : How could one populate the `$Data` variable with the contents of the table in the text block without using another file in the notebook below? 
[https://github.com/Ayanmullick/test/blob/master/testfolder/test.ipynb](https://github.com/Ayanmullick/test/blob/master/testfolder/test.ipynb)

**Describe alternatives you've considered**
I considered `Import-CSV`, `Get-Content`, `ConvertFrom-Json` and `ConvertFrom-SourceTable`. However, [I couldn't figure out the value for the `-Path` parameter to point it to a text block in the same file.](https://stackoverflow.com/questions/60264332/import-table-from-same-notebook)

**Comment by jonsequitur** [comment]
You can pipe strings to `Out-Display` and specify a mime type, which should be more robust than parsing the `.ipynb` file.

![image](https://user-images.githubusercontent.com/547415/75587605-ac5b9c80-5a2b-11ea-8797-01eb69a94b02.png)

We're also working on some scenarios for sharing data between cells containing different languages. But `dotnet-interactive` is currently unaware of the contents of any Markdown cells.

**Comment by Ayanmullick** [comment]
@jonsequitur , My purpose of importing a markdown table to a PowerShell variable is so it can be consumed by other cmdlets not just `Out-Display`.

|Location| RG     | Name |
|--------|--------|------|
| EastUS | EastRG |EastVM|
| WestUS | WestRG |WestVM|


`$b=Import-Csv -Path <>  -Delimiter '|'`
`$b| Foreach-Object {New-AzVM -Location $PSItem.Location -ResourceGroupName $PSItem.RG -Name $PSItem.Name}`

Something like that.

**Comment by jonsequitur** [comment]
It seems like Jupyter Notebook and JupyterLab tend to treat Markdown cells as static presentation, not as something dynamic and programmable. There are extensions and other tricks to address using them more dynamically, but from what I found, they seem to rely on front-end details (leading to solutions that aren't portable across front-ends) or they involve parsing and understanding the JSON of `.ipynb` file, which is a Jupyter implementation detail I'd be hesitant to depend on. For example, an approach like the latter won't work as expected if you haven't saved the file.

Now, thinking out loud here, one possible approach that could work is to define a magic command that you use in a code cell, which outputs the rendered Markdown as well as captures a variable, something like this:

![image](https://user-images.githubusercontent.com/547415/78374983-03034b80-7581-11ea-905f-327825a803d4.png)

Thoughts?

**Comment by Ayanmullick** [comment]
Yes @jonsequitur , it'd be perfect if one could render and output to variable simultaneously. 

@TylerLeonhardt , I tried to read the notebook file and `ConvertFrom-Json`. But that could get messy for a large table for 30-40 VM implementation.

![image](https://user-images.githubusercontent.com/17693249/78380287-3ce04c00-7599-11ea-8dd9-78c3418c53bd.png)
