### ISSUE TITLE
Add Localization for the VS Code Extension

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#2093]
Work with the loc team to address localization of any UI we show in the extension including Variable Explorer. This is so we can be compliant.

**Comment by ocallesp** [comment]
Proposed module to handle localization [microsoft/vscode-nls: npm module to support externalization and localization of VSCode extensions. (github.com)](https://github.com/microsoft/vscode-nls)

**Comment by ocallesp** [comment]
For this, we need
- a list of localizable strings in both the Polyglot Notebooks and .NET Interactive
- a way for Polyglot Notebooks to tell dotnet-interactive what culture to use on startup

**Comment by ocallesp** [comment]
I having trouble debugging polyglot-notebooks-ui-components.

Based on a suggestion from @colombod, the localized column names for Variable Explorer should be passed somehow from polyglot-notebooks-vscode-insiders to polyglot-notebooks-ui-components.

**Comment by ocallesp** [comment]
Learning how to use Webview tools before making changes to the polyglot-notebook-ui-component
