### ISSUE TITLE
remove SubmitCode.SubmissionType

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#2095]

**Comment by AbhitejJohn** [comment]
This is known to affect our partners and hence would be good to address earlier so we don't break them after GA. It might also be good to get any feedback for any other changes that we'd need to incorporate as part of this.

**Comment by jonsequitur** [comment]
I confirmed that this is not being used in the Jupyter proxy work.

**Comment by AbhitejJohn** [comment]
Thanks Jon, could we move this out of the GA milestone in that case?
