### ISSUE TITLE
The global tool should have a way to get the latest daily build of the kernel

### ISSUE THREAD

**Issue by TravisEz13** [dotnet/interactive#210]
I'd like to self host the daily build of the kernel easily.

The global tool is great for getting the kernel, but I want some features that aren't in that build yet.

There should be either two global tools, one for daily and one for the stable build or a switch when you install the jupyter kernel to install the daily version.

**Comment by TravisEz13** [comment]
someone gave me these instructions:

```
dotnet tool install -g --add-source "https://dotnet.myget.org/F/dotnet-try/api/v3/index.json" Microsoft.dotnet-interactive


dotnet tool update -g --add-source "https://dotnet.myget.org/F/dotnet-try/api/v3/index.json" Microsoft.dotnet-interactive
```

**Comment by jonsequitur** [comment]
The example you have of the install from the MyGet feed is in effect our daily build. (It's actually rebuilt for every merged pull request.) The nuget.org version is arguably more stable, though since we're in preview it's also subject to change.

**Comment by TravisEz13** [comment]
agreed... this is similar to how it's done to get similar types of build is other products.  I'll close the issue.
