### ISSUE TITLE
Rename VS Code Extension PRIOR to removal from Preview

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#2100]
- [x] Extension name
- [ ] Update existing docs to use new name
    - [ ] Doing Data Science in Visual Studio Code
    - [x] old blog posts
    - [x] old youtube videos
- [x] Package name in package.json
- [x] VS Code extension icon
- [x] Command prefixes in command palette
    - [x] Also command ID prefix - shim old commands
- [x] config -- can we have a back compatibility shim and punt this to post-GA?
    - [x] JSON property names: We MIGHT be able to change this
    - [x] update display name in the ui
- [x] VS Code grammar and language IDs
- [x] Documentation text - mention Polyglot Notebooks at top of README so users know they're in the right place
- [x] Language/kernel pickers - remove the term .NET Interactive? does it need replacing at all?
- [x] VS Code bottom panel label
- [x] VS Code bottom panel output items: diagnostics and log channels
- [x] .ipynb metadata 
- [x] NuGet package tags
- [x] VS Marketplace extension tags

----

Do after GA

- [x] Folder names for - DO THIS LAST
    - [x] dotnet-interactive-vscode
    - [x] dotnet-interactive-vscodeinsiders
- [x] update dev container template

**Comment by AbhitejJohn** [comment]
The one remaining item "Doing data science in VS Code", I've added it in this docs issue - https://github.com/dotnet/interactive/issues/2078. We would likely cover that as part of the Python integration efforts.
