### ISSUE TITLE
Cancelling async operations in the cell

### ISSUE THREAD

**Issue by craigb** [dotnet/interactive#2115]
**The package and version I'm asking about**: 
.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.331401+f9a0736070089a9e182a96afc9c0142d2b81e5f5
Library version: 1.0.0-beta.22314.1+f9a0736070089a9e182a96afc9c0142d2b81e5f5
Build date: 2022-06-21T23:40:25.7409383Z
https://github.com/dotnet/interactive

### Question
Is there access to a cancellation token that's hooked up to the cancel button of the current cell? I have some dumb code that runs for a long time and won't let me cancel it.

**Comment by jonsequitur** [comment]
This should work, though I noticed in testing it that sometimes the `Console.WriteLine` isn't reached:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/547415/176338729-050bb6b1-db9a-48bb-9b0e-f27492fb2571.png">

**Comment by alienghub** [comment]
.NET Interactive
© 2020-2024 Microsoft Corporation
Version: 1.0.556801+2d9726b514498cd84403a1d5d13da3161c99eab2
Library version: 1.0.0-beta.24568.1+2d9726b514498cd84403a1d5d13da3161c99eab2
Build date: 2024-11-19T13:22:45.5291437Z
https://github.com/dotnet/interactive

```cs
using System.Threading.Tasks;
using Microsoft.DotNet.Interactive;

//initialize resources
Console.WriteLine("initialize");

var output = string.Empty.Display("text/plain");
var counter = 1;
while (!KernelInvocationContext.Current.CancellationToken.IsCancellationRequested)
{
    await Task.Delay(500, KernelInvocationContext.Current.CancellationToken);
    output.Update($"{counter++}");
}

//dispose of resources
Console.WriteLine("Dispose");
```

Dispose part is still not reached. How one should perform cleanup? If I don't cleanup, I have a lingering dotnet.exe process in the background, which stays even if i close vscode.
