### ISSUE TITLE
RequestKernelInfo hangs when sent to CompositeKernel within VS Code

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#2117]
![image](https://user-images.githubusercontent.com/547415/176488980-065d5ec0-1775-4170-b7d8-b28c4fd2b7c4.png)

**Comment by AbhitejJohn** [comment]
@jonsequitur : Trying to understand the impact of this - how often /when do we expect users to request kernel info?

**Comment by jonsequitur** [comment]
It's possibly going to be common in automation and extension scenarios. This was working at one point (when only the .NET-based kernels were handling this command) and I believe the root cause here is #2081.
