### ISSUE TITLE
When saving a new .ipynb, kernel reverts to Python

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#2125]
Steps to reproduce:

1. Create a new blank notebook, selecting the .ipynb option.
2. Run some code.
3. Save the file.
4. Note when the editor refreshes, the kernel selector shows Python and the run button is no longer responsive.
<img width="458" alt="image" src="https://user-images.githubusercontent.com/547415/176977793-ee0b2832-af39-4db4-9128-79280b10484d.png">

**Comment by claudiaregio** [comment]
+1 saw a user run into this today

**Comment by jonsequitur** [comment]
This appears to be fixed as of extension version 1.0.360602.
