### ISSUE TITLE
Missing folder and files

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/interactive#2128]
Further discussion [here](https://github.com/dotnet/interactive/issues/1612#issuecomment-1174494923)

The latest master has missing
- Utility folder
- dotnet-interactive.js
- dotnetKernel.zip

![image](https://user-images.githubusercontent.com/49812372/177230982-60b1b776-765c-4280-bfaf-2e5b31f80682.png)

**Comment by brettfo** [comment]
I suspect our build instructions are out of date.

Can you try following the steps in DEVELOPER-GUIDE.md from a clean machine and let us know which steps don't work or are otherwise wrong?  We can then update our instructions based on what we discover is incorrect.

**Comment by GeorgeS2019** [comment]
@brettfo 

The most critical **step 1** in Windows e.g. 10 or 11 is to git clone onto a drive that supports symbolic links.

Otherwise one would get when executing `ensure-symlinks`
`The device does not support symbolic links`

Once  `ensure-symlinks` is completed, then only run `build.cmd`

In summary, the critical step

1. Ensure using a drive thsupportsort symbolic links
2. run ensure-symlinks
3. run build.cmd

The above image most likely due to failure of doing step 1. Without step 1, step 2 will not run. Without step 2, step 3 (build.cmd) would end up errors

**Comment by brettfo** [comment]
I want to make sure I'm understanding the issue.  Did you run the `ensure-symlinks.ps1` script and saw the message `The device does not support symbolic links`?  If so, did you:

1. Run the script in an admin PowerShell?
2. Is the drive formatted as NTFS?  You mentioned in another post issues with an exFAT drive.  Only NTFS is supported.

**Comment by GeorgeS2019** [comment]
@brettfo  there is a need to advise users that the symbolic links script requires an NTFS drive.

**Comment by brettfo** [comment]
Thank you for the feedback, I've added a note to `DEVELOPER-GUIDE.md` that an NTFS-formatted drive is required in Windows.

Have you found any other places where our documentation is out-of-date?
