### ISSUE TITLE
How do I create an F# notebook in Visual Studio 2022?

### ISSUE THREAD

**Issue by nhirschey** [dotnet/interactive#2140]
**Is your feature request related to a problem? Please describe.**
I wanted to experiment with notebooks in visual studio 2022 rather than visual studio code. I tried to follow the directions on the [extension website](https://marketplace.visualstudio.com/items?itemName=MLNET.notebook) to add a new item to a solution.

I went to a poject and tried to add a file to my project via the right click menu. There was no option for adding the notebook to my project. However, if I click on a notebook link at the [c# ML.NET notebooks website](https://github.com/dotnet/csharp-notebooks) it opens in visual studio 2022 and can run.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/5226115/178582789-b026ce69-ac08-4058-9c75-37e15de96031.png">

**Describe the solution you'd like**
1. I would like to be able to add a notebook to my F# solution.
2. I would like to add a notebook to a folder without having to add it to a solution. Like via the "File > new > file" dialog.

**Describe alternatives you've considered**
Visual Studio code.

**System info**
Microsoft Visual Studio Community 2022
Version 17.2.0 Preview 1.0
VisualStudio.17.Preview/17.2.0-pre.1.0+32210.308
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

C# Tools   4.2.0-1.22108.11+a29b6ae89a8885856e4c55a0e92ba056e1530458
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22101.5+0cce0cbe615b0a944c7b95da646b0dd643f88758
Microsoft Visual F# Tools

**Comment by claudiaregio** [comment]
Closing as support for notebooks in VS has been discontinued
