### ISSUE TITLE
Swapping to another tab while creating an .ipynb file throws an error

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/interactive#2144]
VSCode version 1.70.0-insider
Interactive CI build 20220712.4 using dotnet-interactive-vscode-1.0.3362041.vsix

1. Start with an empty text file open in VSCode
2. `Ctrl+Shift+P` => ".NET Interactive: Create new blank notebook"
3. Select "Create as .ipynb"
4. Select "F#"
5. While it's creating, quickly navigate back to the text file tab.
Expected: The file creates without issues.
Actual: This error is thrown. Doesn't occur if you stay on the page.
                 
![image](https://user-images.githubusercontent.com/10537189/178845257-d5fbba38-433d-4e5c-9963-a14f0e066b62.png)

**Comment by brettfo** [comment]
Good find!  I've traced the issue to VS Code and filed microsoft/vscode#155778.

**Comment by brettfo** [comment]
External bug closed as won't fix.
