### ISSUE TITLE
Review uses of VS Code notebook API proposals

### ISSUE THREAD

**Issue by mjbvz** [dotnet/interactive#2150]
The Dotnet VS Code extension is currently listed as a customer of a number of api proposals related to notebooks. We are trying to either finalize or remove these APIs, so need an accurate understanding of which ones are really being used.

Please let me know if you are using each of the following proposals:

- `"notebookCellExecutionState"`
- `"notebookControllerKind"`
- `"notebookDebugOptions"`
- `"notebookLiveShare"`
- `"notebookMessaging"`
- `"notebookMime"`

 If you are not using a proposal, we will remove your extension as a consumer. If you are, I will keep you listed as a user and follow up later on what to do about each individual proposal

**Comment by brettfo** [comment]
@mjbvz I checked our usage of the proposed APIs and we're only using `notebookMessaging` and `notebookWorkspaceEdit`.  All others we don't use.

**Comment by mjbvz** [comment]
Great! I'll update the list of API proposal you use on our side too then
