### ISSUE TITLE
Can I use this with Python

### ISSUE THREAD

**Issue by MikeHillsNC** [dotnet/interactive#2151]
**The package and version I'm asking about**: 

### Question
Is it possible (yet) to use this with a jupyter notebook with Python ?

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact

x = np.linspace(0, 5*np.pi, 500)

@interact(w=(0, 10, .1), amp=(-4, 4, .1), phi=(0, 2*np.pi, 0.1))

def plot(w=1.0, amp=1, phi=0):
    y = amp*np.sin(w*x-phi)
    plt.plot(x,y)
    plt.ylim([-4,4])
    plt.show()

**Comment by claudiaregio** [comment]
Hi @MikeHillsNC, adding Python is something we are exploring. Could you help me understand what combination of languages you'd like to use with Python and what for?

**Comment by GeorgeS2019** [comment]
FYI @MikeHillsNC
- [PythonNET integration](https://github.com/dotnet/interactive/issues/2126)
- [PythonNET integration with .NET Interactive notebook ](https://github.com/pythonnet/pythonnet/issues/1851)

**Comment by brettfo** [comment]
Hi all! .NET Interactive has recently been working on Python and R integration! @claudiaregio is in search of volunteers who are willing to test out the experience in VS Code and give us feedback. It will require the signing of an NDA and filling out a feedback form. If you are interested in being one of the first to help shape this experience, please submit your email in this form and she will reach out with the instructions.

https://forms.office.com/r/UQchfQSGa5
