### ISSUE TITLE
[Telemetry] Language of cells on run

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#2154]
VS Code Specific: 
I'd like to be able to see the language of cells in the notebook in their **sequence** on run. (Assuming I can get the last run based on cell ID) 

For example, if someone has a notebook with the first cell as a SQL cell and the next 3 cells as C# cells, I'd like to see something like this stored in the telemetry when the notebook is saved: 
[SQL, C#, C#, C#]

**Comment by jonsequitur** [comment]
My proposal would be to capture the following information on each cell run:

* A cell ID
* A document ID
* The execution order
* The cell language
* Whether it executed successfully
* Execution time

**Comment by colombod** [comment]
If document ID is bound to the file name or something that is persistent when I close the document and then reopen it I would suggest we also capture a session ID that is tracking the lifespan of an open document.

**Comment by colombod** [comment]
Also ............ how about we are able to track source and destination languages for each use of #!share? that would draw a picture about the intentional interaction between languages.
