### ISSUE TITLE
Binder launched from repo does not have dotnet kernel

### ISSUE THREAD

**Issue by nathanjwtx** [dotnet/interactive#216]
#### Describe the bug
I created a Jupyter notebook localy via Anaconda and saved it to a Git repo. I created the launch binder icon as described in the readme but when I click it, it takes me to Binder that has no dotnet kernel.

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/nathanjwtx/Jupyter_Notebooks.git/master?urlpath=lab)

#### Did this error occur while using `dotnet interactive`?
- [ ] .NET Jupyter Notebook 

#### Screenshots
![image](https://user-images.githubusercontent.com/1558027/75631784-50c01900-5bbb-11ea-808a-fca1ff9b443f.png)

#### Please complete the following:
 - OS
    - [X ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ X] Chrome
    - [ ] Edge
    - [ ] Safari
 - Frontend
    - [ X] Jupyter notebook
    - [X ] Jupyter lab
    - [ ] nteract

**Comment by jonsequitur** [comment]
You can see the steps we take to run in Binder by looking at the Dockerfile in our repo: https://github.com/dotnet/interactive/blob/master/Dockerfile

**Comment by nathanjwtx** [comment]
Does that mean it will only work from a docker container?

**Comment by jonsequitur** [comment]
Binder provisions the container based on your Dockerfile.

**Comment by nathanjwtx** [comment]
Sorry, maybe i didn't phrase that correctly. In order to use Binder i need a dockerfile and/or container? Is that correct?

**Comment by colombod** [comment]
@nathanjwtx to use .NET interactive kernels in binder you need to use a docker file. We have [documentation](https://github.com/dotnet/interactive/blob/master/docs/CreateBinder.md) for the process of sharing notebooks via binder using the docker file
