### ISSUE TITLE
Unable to install extension 'ms-dotnetttools.dotnet-interactive-vscode' as it is not compatible with VS Code 1.69.2

### ISSUE THREAD

**Issue by JonTheTurnip** [dotnet/interactive#2172]
### Describe the bug
I'm unable to uninstall the .net interactive extension on my work laptop, I get an error saying "Command 'Extensions: Install from VSIX..' resulted in an error (Unable to install extension 'ms-dotnetttools.dotnet-interactive-vscode' as it is not compatible with VS Code 1.69.2.)"

Note that I'm able to install the extension without issue on my home laptop which is also running vs code 1.69.2.  I suspect it's a work laptop problem, but would helpful to understand what a work around might be.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [ x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![Snag_6efa445](https://user-images.githubusercontent.com/10959562/181288946-5f39208d-f4fc-4884-be89-f186afea0fce.png)

**Comment by jonsequitur** [comment]
Are  you still seeing this issue?

**Comment by JonTheTurnip** [comment]
hi, just checked, the issue has gone now, not sure if this is connected to your suggestion or that fact the network team have made some new exceptions.  Anyway great to be using interactive notebooks again, keep up the good work!
