### ISSUE TITLE
Hide the 'index' column in a dataframe/table?

### ISSUE THREAD

**Issue by boyedarat** [dotnet/interactive#2181]
**The package and version I'm asking about**: 
![image](https://user-images.githubusercontent.com/22816484/182201574-9000085a-9eec-4a4f-b5c5-acf81026c70e.png)

### Question
How do I hide the *index* column in the output below?
![image](https://user-images.githubusercontent.com/22816484/182202029-b0a43732-eee1-4542-a63d-56ba3d1680bd.png)

**Comment by jonsequitur** [comment]
Currently, the only way to do this is to [register a custom formatter](https://github.com/dotnet/interactive/blob/main/docs/formatting.md) that generates the HTML table. It's fairly simple to do this for a specific type and a bit more involved to change this for all `IEnumerable` types. 

A couple of relevant pieces of code:

https://github.com/dotnet/interactive/blob/a206f434beda79e25b9e8efed63ba0121515fbb1/src/Microsoft.DotNet.Interactive.Formatting/Html.cs#L212-L220

https://github.com/dotnet/interactive/blob/main/src/Microsoft.DotNet.Interactive.Formatting/HtmlFormatter%7BT%7D.cs#L110-L294

**Comment by boyedarat** [comment]
@jonsequitur Would it possible to just remove *index* altogether before sending it to Display()?

I would like to selectively view the *index* in the output. Creating a custom formatter for all possible types that would output a table would be more cumbersome. I also found out that I can't create formatters for Measure types.

**Comment by jonsequitur** [comment]
>  I also found out that I can't create formatters for Measure types.

Can you provide a code sample of what you're trying to do?
