### ISSUE TITLE
Minimum PowerShell Host Version Error

### ISSUE THREAD

**Issue by stvpwrs** [dotnet/interactive#2198]
When trying to run a script with the `Microsoft.Xrm.Data.Powershell` module I get the following error:

`The current PowerShell host is: '.NET Interactive Host' (version 0.0.1). The module 'C:\Users\...\Documents\PowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.8.14\Microsoft.Xrm.Data.Powershell.psd1' requires a minimum PowerShell host version of '1.0' to run.`

I'm not sure if this is an issue with how this module is checking the PowerShell version or something unexpected with the new .NET Interactive Host.

**Comment by jonsequitur** [comment]
Could you provide example code that reproduces this issue?

Thanks.

**Comment by stvpwrs** [comment]
The following code will produce the error.

```
$forMicrosoftXrmDataPowershell = @{
    Force           = $true
    Name            = 'Microsoft.Xrm.Data.Powershell'
    RequiredVersion = '2.8.14'
}
Import-Module @forMicrosoftXrmDataPowershell
```

```
Import-Module: 
Line |
   6 |  Import-Module @forMicrosoftXrmDataPowershell
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The current PowerShell host is: '.NET Interactive Host' (version 0.0.1).
```

**Comment by daxian-dbw** [comment]
The module manifest of `Microsoft.Xrm.Data.Powershell` defines `PowerShellHostVersion = '1.0'`, and that means it requires the host to be version `1.0`. But the .NET Interactive Host is currently v0.0.1. A quick fix would be to simply change it to 1.0.0, at https://github.com/dotnet/interactive/blob/main/src/Microsoft.DotNet.Interactive.PowerShell/Host/PSKernelHost.cs#L25.

**Comment by jonsequitur** [comment]
Does that change any behaviors of the host?

**Comment by daxian-dbw** [comment]
I don't think so. That version was chosen probably just to reflect it was new work. However, changing the version itself may not solve all the problems -- this module depends on the host version being 1.0, but there could be other modules depending on a higher version of the host -- those modules were targeting PowerShell console (thus the PowerShell host) and ideally should remove that key from the module manifest file unless it really depends on the PowerShell host.
