### ISSUE TITLE
Error launch New interactive NoteBook

### ISSUE THREAD

**Issue by Shahid-Roofi-Khan** [dotnet/interactive#2207]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/65172780/185414310-aea9a1f0-20e6-4cd5-94e1-a1f9ed11920a.png)

I have latest as of today, VSCode, and latest dotnet-interactive. 

There are two issues with same description but those are not the only reason issue happens, i did all mentioned in them.

https://github.com/dotnet/interactive/issues/1729     (this points to path to SDKs and some other minors things, still addressing that won't solve the issue)

https://github.com/dotnet/interactive/issues/1775    (this points to other techniques but doing them also won't solve this issue as i have latest everything (except that windows is not 11, its windows 10)

**Comment by jonsequitur** [comment]
Could you provide the versions of the extension and VS Code you have installed?

**Comment by brettfo** [comment]
Related, issue #2206 will track future work to make scenarios like this easier to diagnose.
