### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AndersonGabrielSilva** [dotnet/interactive#2212]
- Issue Type: `Performance`
- Extension Name: `dotnet-interactive-vscode`
- Extension Version: `1.0.3405010`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.70.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/ANDERS~1/AppData/Local/Temp/ms-dotnettools.dotnet-interactive-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jonsequitur** [comment]
Can you provide a more detailed repro?

Thanks.
