### ISSUE TITLE
#r nuget error "Value cannot be null. (Parameter 'path1')"

### ISSUE THREAD

**Issue by jmlane** [dotnet/interactive#2213]
### Describe the bug
Hello. I'm trying to load public NuGet packages in my F# interactive notebooks:
```dni
#r "nuget: Fuchu, 1,1.0"
```

I'm getting the following error for the cell containing the nuget directive:
> Error: c:\program files\dotnet\sdk\6.0.101\NuGet.targets(564,5): error : Value cannot be null. (Parameter 'path1') [C:\Users\jmlane\.packagemanagement\nuget\Projects\2008--b2087166-1f52-442d-a7cd-e1b30cd5ae8d\Project.fsproj]

These exact notebooks had been working as recently as a couple of weeks ago. I can't figure out what may have changed to cause this error.

I can restore the requested package and build the equivalent code in an F# project, so my issue is most likely related to my VS Code .NET Interactive notebook extension or some relevant configuration.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- Version: 1.0.341901+846a87324b4b21ee09299c42ed2f55f77a2831fa
- Library version: 1.0.0-beta.22419.1+846a87324b4b21ee09299c42ed2f55f77a2831fa

- OS
    - [x] Windows 10
 - Frontend
    - [x] Visual Studio Code Insiders

### Screenshots
N/A.

**Comment by jonsequitur** [comment]
The error message is pretty unhelpful but the example code isn't valid because of the comma in the package version. Try this:

```
#r "nuget: Fuchu, 1.1.0"
```

**Comment by jmlane** [comment]
I apologize, that comma in the version was a typo that didn't exist in my notebook; it was a period as is required.

Regardless, my issue seems to have resolved itself as of version 1.0.342603+f031fa8d3ab59b0f907be8896bca22d2fc447a1a.

Thank you for the help!
