### ISSUE TITLE
jupyter doesn't work in .net 6.0, doesn't work after install 3.1

### ISSUE THREAD

**Issue by anirugu** [dotnet/interactive#2269]
https://github.com/dotnet/try/issues/1033
https://github.com/dotnet/sdk/issues/27976

**Comment by jonsequitur** [comment]
Can you provide more details on how to reproduce the problem? What installation steps have you followed and what is the output of `dotnet --info`? 

Thanks.

**Comment by jonsequitur** [comment]
Jupyter functionality was moved from `dotnet-try` to `dotnet-interactive`.

Please follow the installation instructions here: https://github.com/dotnet/interactive
