### ISSUE TITLE
Notebooks HTML: Setting the background-color property on html changes the whole notebook

### ISSUE THREAD

**Issue by burkeholland** [dotnet/interactive#2279]
### Describe the bug
If you set the `background-color` for the `html` tag, it changes the background for the whole notebook.

```
<style>
  html {
    background-color: white;
  }
</style>
```

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [ x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ x] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

https://user-images.githubusercontent.com/686963/191589817-ad8f0a94-bca2-493f-8c3a-5695627d7965.mp4

**Comment by IanMatthewHuff** [comment]
Created https://github.com/microsoft/vscode/issues/161515 for tracking this issue in core.
