### ISSUE TITLE
Empty .ipnyb files modified by .NET Interactive are saved as C#, regardless of content

### ISSUE THREAD

**Issue by K8-and-a-half-1000** [dotnet/interactive#2289]
Reproduction steps:

In VS Code, with .NET Interactive installed:
- create an empty file, give it a .ipynb extension
- open the file and add a code cell, by default C#
- change the cell language to e.g. PowerShell
- save the file

If you open the file in a text editor, in the metadata section, you'll get:

```
"metadata": {
  "language_info": {
   "name": "csharp"
  },
  "orig_nbformat": 4
 }
```

This makes no sense. ^
At this point we have no data stored, just a single empty cell with "language": "pwsh"
If you actually add some sample PowerShell code, and then save, the metadata becomes:

```
 "metadata": {
  "kernelspec": {
   "display_name": ".NET (C#)",
   "language": "C#",
   "name": ".net-csharp"
  },
  "language_info": {
   "file_extension": ".cs",
   "mimetype": "text/x-csharp",
   "name": "C#",
   "pygments_lexer": "csharp",
   "version": "9.0"
  },
  "orig_nbformat": 4
 }
```

.. which is worse.
At this point, you are basically expecting polyglot support for everything that works with .ipynb files, which is silly.
Please align the notebook metadata with the cell language, and don't hard-code C# as the default.

**Comment by wsmelton** [comment]
It seems to also happen after picking the default language with cells created in that language using it, and then removing them all will cause it to revert back to C#.

1. Create new Polyglot notebook
2. Set default language to PowerShell (or whatever)
3. Add specified language cells
4. Remove them all
5. Next code cell created will default to C#

**Comment by jonsequitur** [comment]
This has been fixed.
