### ISSUE TITLE
How to Share from PowerShell to Javascript?

### ISSUE THREAD

**Issue by ScriptPup** [dotnet/interactive#2300]
**The package and version I'm asking about**: 
![image](https://user-images.githubusercontent.com/6163646/192804230-c1f89d6b-351d-4cd0-91ae-3d9fedb9a344.png)

### Question
How do I share variables from PowerShell to Javascript? All of the documentation uses C# and F# as the example. I assumed it would work similarly, but I cannot get it to work.

I know it should be possible since these [enhancement] tagged issues are closed:
- https://github.com/dotnet/interactive/issues/1648
- https://github.com/dotnet/interactive/issues/1551

But there doesn't seem to be any documentation on how to share between the PowerShell kernel and Javascript kernel.

When I try to just use the `#!share` magic in the same way as I would for C# or F#, it doesn't work.

![image](https://user-images.githubusercontent.com/6163646/192827684-f2676143-192a-491d-b1d0-a296df658879.png)

**Comment by dfinke** [comment]
I used `pwsh` worked. Did try just `test` in the js cell. Changed to the `console.log`, and then it double printed.

![image](https://user-images.githubusercontent.com/67258/192833622-947bbdac-a9ed-49e1-9938-14651bf64ef8.png)

**Comment by ScriptPup** [comment]
Thanks @dfinke! Looking at your screenshot helped solve it. I didn't realize that the `!#share` magic is language specific. None of the documents I read (unless I just overlooked it) mentioned that. Using the UI to select the language works, as does running the `#!share` magic after using a language selection magic.

![image](https://user-images.githubusercontent.com/6163646/192846648-c81e32f8-1ed6-4f4b-8aa4-95e184138667.png)

Thanks again for the assistance, closing this out.
