### ISSUE TITLE
unexpected javascript objects in variable explorer

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#2314]
## Steps to reproduce 
connected to local instance of sql adventureworks using #!connect command 

## Expected behavior
No variables in the variable explorer

## Actual behavior
![image](https://user-images.githubusercontent.com/19276747/193713556-85c2d367-feeb-48f6-8228-e7d8bc1c8afd.png)

**Comment by colombod** [comment]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/375556/193913573-e49d7c96-8058-495e-ada5-48963c84a3d9.png">

Doesn't happen in current insider build
