### ISSUE TITLE
.NET Interactive not showing as kernel anymore

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#2328]
In the polyglot notebook version of the extension, the kernel is not showing as .NET Interactive

![image](https://user-images.githubusercontent.com/19276747/194450906-379b9746-30fd-400e-a261-7fca24f9b60c.png)

Ext Version: v1.0.3477031

**Comment by claudiaregio** [comment]
@colombod

**Comment by colombod** [comment]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/375556/194535109-40159a54-8c1a-49b7-9a9a-947a7cd3f75c.png">

is this what is expected? @jonsequitur,. @brettfo  what do you think? this is the controller name.
