### ISSUE TITLE
Is it possible to render a mermaid chart from a string generated by another kernel?

### ISSUE THREAD

**Issue by nhirschey** [dotnet/interactive#2334]
**The package and version I'm asking about**: 
- Version: 1.0.345202+1f7cb23c53cee7fedf47418a0b0321090034af16
- Library version: 1.0.0-beta.22452.2+1f7cb23c53cee7fedf47418a0b0321090034af16
- Build date: 2022-09-12T17:28:08.1433523Z

### Question
I would like to generate a mermaid graph using code and then render it. Is this possible?

I tried using variable sharing, sharing an F# string to mermaid but that did not work.

![image](https://user-images.githubusercontent.com/5226115/194712346-eccf92eb-9c7a-4507-a26b-dc5937f147c0.png)

**Comment by jonsequitur** [comment]
You can do this by sending a command to another subkernel:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/547415/194919378-95065be3-ad55-4263-8349-cc6ef50b10d4.png">

**Comment by nhirschey** [comment]
Wonderful, thank you!
