### ISSUE TITLE
make this project independent. I want to use it independently Net C # interactive plug-in

### ISSUE THREAD

**Issue by nczsl** [dotnet/interactive#2345]
Make this project independent. I want to use it independently Net C # interactive plug-in. However, the current situation is to install plug-ins on vscode NET Interactive Notebooks needs to rely on 'jupyter', while 'jupyter' plug-ins need to rely on 'python' plug-ins, so they are bound together. I don't need to install Python plug-ins at all. I hate to install anything in Python on the machine because I don't need it. So I want to uninstall all Python plug-ins on vscode without affecting their use.

**Comment by colombod** [comment]
@DonJayamanne, @rebornix do you have any suggestions?

**Comment by DonJayamanne** [comment]
based on my understanding this extension doesn't need the jupyter extension at all, probably might need the render extension, apart from that i don't see why I've would need to install the jupyter extension.

if there's a dependency on jupyter extension, I'd check why that is there, and if there's no direct user of any jupyter extension api, then i think we can remove any such dependencies

**Comment by colombod** [comment]
.NET interactive depends on jupyter but it seems the user is reporting python extension installed too or maybe just been prompted to install themDr Diego Colombo PhDOn 17 Oct 2022, at 10:20, Don Jayamanne ***@***.***> wrote:﻿
based on my understanding this extension doesn't need the jupyter extension at all, probably might need the render extension, apart from that i don't see why I've would need to install the jupyter extension.
if there's a dependency on jupyter extension, I'd check why that is there, and if there's no direct user of any jupyter extension api, then i think we can remove any such dependencies

**Comment by brettfo** [comment]
we depend on the jupyter extension for ipynb file handling
