### ISSUE TITLE
can't load local dll when #!pwsh dotnet build csproj 

### ISSUE THREAD

**Issue by nczsl** [dotnet/interactive#2349]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [ x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ x] Chrome
    - [ x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

my needs is research local csproj ,so need load  local dll by #r command into net interactive notebooks. but when i use #!pwsh dotnet build xxx.csproj  after sucessed this process and then i use #r xxx.dll , first is can, but is update source code changed some place, and redo this process, will recived error, at the #!pwsh command excute time, the error message is：
"Files\dotnet\sdk\6.0.402\Microsoft.Common.CurrentVersion.targets(4632,5): warning MSB3026: 无法将“obj\Debug\net6.0\Synario.Util.dll”复制到“bin\Debug\net6.0\Synario.Util.dll”。1000 毫秒后将开始第 1 次重试。The process cannot access the file"
...
And repeated this error message many times

**Comment by jonsequitur** [comment]
Could you provide a more detailed way to reproduce the issue, e.g. an example notebook?

**Comment by nczsl** [comment]
if not use '#!pwsh dotnet build xxx.dll'command in 'net interactive notebooks' but use dotnet build xxx.dll in vscode pwsh terminal,the problem is still appear， when at least second time after update source code, change some place in the source code.
at pwsh terminal and  use command 'dotnet ... xxx.dll' then appear this problem,

**Comment by nczsl** [comment]
I try to reproduce the error process as follows:
1，create or open some *.ipynb file in vscode use '.net interactive notbooks' plugin
2, #r "local_xxx.dll"  // this dll is local machine not from nuget source,ok.
3, use some test sentence like is   "xx.some_property" and press key : ctrl+enter ,then show correct results!
4, find the xxx.dll source code ,change some place ,for example , change property name from xx.some_property update to
xx.some_property111, and  save  and excute command 'dotnet build ... xxx.dll' in vscode termial ,
and this time recived many time wram message  say meanings'.... File locked by ". NET Host (14556)" ...'

**Comment by jonsequitur** [comment]
It sounds like the `dotnet-interactive` process is holding onto the .dll and preventing the build from overwriting it. In VS Code, if you restart the kernel, it should allow you to rebuild the project. You can do this by opening the command palette and running the command `.NET Interactive: Restart the current notebook's kernel`. You'll need to rerun the notebook cells afterward.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/547415/195877791-f2070b5b-c3e5-4d49-84b1-d13189690006.png">

**Comment by nczsl** [comment]
yes, but not very easy to use.

**Comment by Dzeneralen** [comment]
Is restarting the Kernel between every update the way to go when developing extensions? In that case, are there any ways to restart the kernel programatically from a cell?

**Comment by jonsequitur** [comment]
There's no way to programmatically restart the kernel.
