### ISSUE TITLE
Unrecognized magic command for #!share

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/interactive#2366]
### Describe the bug
#!share is unrecognized when executing cell. 

Repro Steps:
Install latest interactive vsix (insiders) on vscode with .NET 6 (etc).
Download this repro and open its folder and the NotebookTestScript in VSCode.
Execute the following cells with the titles "Execute the next two cells" and "Execute the next cell. After execution, the outpute immediately above this should read:"

Expected: All 3 cells should display the appropriate results as described in the test script.
Actual: The 3rd cell fails with the following errors
Error: Unrecognized command or argument '#!share'.
Unrecognized command or argument '--from'.
Unrecognized command or argument 'csharp'.
Unrecognized command or argument 'x'.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - Windows 10

 - Browser 
    - Edge

 - Frontend
    - Jupyter Notebook
    - Visual Studio Code Insiders

### Screenshots
![image](https://user-images.githubusercontent.com/10537189/196799462-a3085431-7de9-4c03-8cff-82430c98bdbe.png)

**Comment by mattscheffer** [comment]
When "#!share --from csharp x " is executed in the last cell from the notebook test script, it works fine so I don't know why it is failing in the above cell.

**Comment by colombod** [comment]
it is added to the jskernel proxy at this line
