### ISSUE TITLE
Encountered many times The run time of net interactive notebook cannot be terminated. It will run always

### ISSUE THREAD

**Issue by nczsl** [dotnet/interactive#2372]
### Describe the bug
Compared with unit test method, in terms of research and learning Net interactive notebook has advantages, because in unit testing, when the code changes, it will be recompiled, which is a waste of time. And Net interactive notebook does not and can maintain context, but its performance is poor at present. For example, it is slower when displaying help prompts. If a cell makes an error during operation, it may not stop automatically, even if the user wants to stop it manually. I hope these fatal problems can be improved. It has seriously affected people's desire to use it Net interactive notebook.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by brettfo** [comment]
> If a cell makes an error during operation, it may not stop automatically

Can you give an example of a cell you were running when this happened?
