### ISSUE TITLE
I hope it is as easy to use as python jupyter

### ISSUE THREAD

**Issue by nczsl** [dotnet/interactive#2373]
. net interactive notebook helps development The. net technology ecological environment and the support of C # and other languages provide a good choice for those who want to use Jupyter. I think it is important to use C # on jupyter. But at present, compared with native python jupyter, it is still too difficult to use. It is stuck, and it is slow to open and run. I hope that the performance and reliability can be further improved, and various bugs can be solved, Make it as easy to use as python jupyter

**Comment by nczsl** [comment]
Let. net interactive notebook only focus on using C # to separate support for other languages, so as to respond to needs more quickly, improve quality, and use experience. Now because multilingual support is mixed together, this tool will become extremely cumbersome and difficult to use. I think. net interactive notebook should focus on building C # into a jupyter notebook for C #, which is of great significance to the development of C # ecology. Quality, speed and reliability are key

**Comment by claudiaregio** [comment]
@nczsl Could you provide some more details on what you are experiencing when you say "It is stuck, and it is slow to open and run"? Could you provide screen recordings of the performance issues you are seeing or would you be willing to share the notebook you are trying to run?

**Comment by claudiaregio** [comment]
@GF-Huang The original issue was too broad for us to take action and received no additional information which is why it was closed. 

Could you please open a new issue with the content you've provided here so we can address the intellisense specific issue in our next meeting? Thanks!

**Comment by GF-Huang** [comment]
> @GF-Huang The original issue was too broad for us to take action and received no additional information which is why it was closed.
> 
> Could you please open a new issue with the content you've provided here so we can address the intellisense specific issue in our next meeting? Thanks!

I hope my new issue will not be closed and tagged by duplicate.
