### ISSUE TITLE
Variable viewer should not show values from kernels that have not been activated

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#2384]
Currently, the variable view sends `RequestValueInfos` and `RequestValue` commands to every known kernel, causing them to initialize even though in most cases most of these kernels will not be used. This is an unnecessary performance hit in terms of both memory and message channel chattiness. It also means that the variable view always shows PowerShell values even if the user hasn't been using PowerShell.

We should look for an approach where we only send these requests to kernels after they have been activated by some user action. One example might be to only add kernels to the list of kernels we want to poll for values once we've seen a `CommandSucceeded` event from that kernel command was a `SubmitCode` or `SendValue`, which are good indicators of user interaction.

**Comment by brettfo** [comment]
We can (and should) also cache a notebook's visible variables.  Currently the content of the variable explorer is invalidated on active notebook change, but in that case we should just restore a cache and _only_ invalidate on `CommandSucceded`, etc.
