### ISSUE TITLE
was not expecting to see password content in variable explorer

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#2387]
When entering a value using @password: in the notebook and opening the variable explorer, the values of the password were displayed here. I was not expecting to see this stored here and seems like a security issue if someone is recording or sharing screen?

**Comment by brettfo** [comment]
We should see what Jupyter does in the password scenario, too.

**Comment by jonsequitur** [comment]
We have an existing `PasswordString` type could potentially be used to prevent the output from being displayed if e.g. `Kernel.GetPasswordAsync` returned it instead of `string`.
