### ISSUE TITLE
hitting share button in variable explorer adds cell to very end of notebook instead of after cell in focus

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#2393]
When sharing a variable by clicking on the icon in the variable explorer, the cell should be added under the cell in focus (either in command or edit mode) instead of the end of the notebook. (unless the user has focus on the last cell of the notebook)

**Comment by jonsequitur** [comment]
This is a specific manifestation of a more general issue with `SendEditableCode`, so closing this in favor of #2878.
