### ISSUE TITLE
VS Code extension tool check should be `===` not `>=`

### ISSUE THREAD

**Issue by brettfo** [dotnet/interactive#2398]
When the extension is installing the backing tool, the comparison should be `===` not `>=`; i.e., ensure _exact_ version match.

**Comment by AbhitejJohn** [comment]
@brettfo : What is the impact of this? Would this only affect customers installing a private vsix in certain niche scenarios?

**Comment by brettfo** [comment]
That's what initially led to the discovery of this, but it's also an issue if somebody rolls back their extension to a previous version.
