### ISSUE TITLE
explicitly handle `ErrorProduced` event type in `InteractiveClient.Execute`

### ISSUE THREAD

**Issue by brettfo** [dotnet/interactive#2415]
[This switch statement](https://github.com/dotnet/interactive/blob/d8d2990c6830b948525d558ab46849b8c88e0877/src/dotnet-interactive-vscode-common/src/interactiveClient.ts#L157) needs to be expanded to handle `ErrorProducedType` and to pass the error through `this.config.createErrorOutput(...)`.

**Comment by colombod** [comment]
we put this in??
