### ISSUE TITLE
no error when attempting to share variable that doesnt exist

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#2436]
When sharing a variable from SQL to Python, there is no error when you try to share a variable that doesn't exist 

Ex. titanic_df2 does not exist in this notebook
![image](https://user-images.githubusercontent.com/19276747/200135667-89c79bbc-5d17-4ba5-b3a9-8f415bc4c092.png)

**Comment by jonsequitur** [comment]
I believe this was fixed. @colombod, was this merged?

**Comment by colombod** [comment]
Is working for other kernels
<img width="515" alt="image" src="https://user-images.githubusercontent.com/375556/200185051-d7bdde2a-0e65-46be-8bf6-117ed76b71ac.png">

need to check the sql / kql behaviour
