### ISSUE TITLE
variable explorer shows value in .NET instead of target language

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#2452]
![image](https://user-images.githubusercontent.com/19276747/200648096-f883ab3d-f668-4c90-9dc3-651d99b5fdd1.png)

Ex. For python variable, i should see dataframe the same way I would in Python notebook

**Comment by claudiaregio** [comment]
This is what it looks like in a Python Jupyter notebooks today 

![image](https://user-images.githubusercontent.com/19276747/200649640-9c1359ca-8de6-4d6c-b62c-73c99070ba5c.png)

**Comment by jonsequitur** [comment]
We might consider adding string properties e.g. `KernelValueInfo.DisplayValue` and `KernelValueInfo.DisplayType` so that remote kernels can populate these independent of local formatting configurations.

**Comment by jonsequitur** [comment]
The core issue here has been resolved, though a Python-specific implementation might still be needed.

<img width="493" alt="image" src="https://user-images.githubusercontent.com/547415/218530921-56c7f44a-e050-40f4-b5b1-4e7d38390bb8.png">
