### ISSUE TITLE
[PowerShell] Need to revisit the 'TryGetVariable' implementation

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/interactive#246]
The current `TryGetVariable` code needs to be revisited to have a more complete implementation:
- Properties added by PowerShell ETS should work
- @jonsequitur mentioned that it's possible `TryGetVariable` gets called while `HandleCodeSubmit` or `HandleRequestCompletion` are running, so there could be a race condition
- maybe more? not familiar with how `TryGetVariable` works with `HttpAPI` yet.

**Comment by TylerLeonhardt** [comment]
> Properties added by PowerShell ETS should work

If we know that the result can be a dead object that's going to JavaScript, we could run the contents through `ConvertTo-Json`. This will keep all the properties.

However, I know that this API is also being used to get variables and bring them into C# so for that case, we want them to still be live objects.

**Comment by TylerLeonhardt** [comment]
> @jonsequitur mentioned that it's possible TryGetVariable gets called while HandleCodeSubmit or HandleRequestCompletion are running, so there could be a race condition

I think it might be worth wrapping the `_pwsh` in a semaphore... in doing so, we should have a `CancellationToken` cancel `TryGetVariable` if it's waiting for a certain period of time.

**Comment by jonsequitur** [comment]
The HTTP layer sits on top of all of this but the underlying APIs deal with the objects directly and are unaware of any serialization.

**Comment by jonsequitur** [comment]
Ah, I see. `TryGetVariable` allows specifying a type. I suppose we could enable requesting it as `PSObject` in which case it would not be unwrapped. That could then be the default when calling via the `VariableRouter`, i.e. when we know it's going to be serialized and sent over HTTP.
