### ISSUE TITLE
When to support. net7

### ISSUE THREAD

**Issue by nczsl** [dotnet/interactive#2460]
When to support. net7

**Comment by sanme98** [comment]
Ya, when it will support .Net 7?
```
string rawString = """
"Testing"
""";
rawString.Display();
```
Error: (1,20): error CS8652: The feature 'raw string literals' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.

I have installed .Net 7 and changed `dotnet-interactive.minimumDotNetSdkVersion` to 7.0 already, but still get the same result.

**Comment by onionhammer** [comment]
I would also love to know this.. currently unable to reference my projects in .net 7 from notebooks.

**Comment by brettfo** [comment]
There are really two separate questions being asked here.

1. **When is .NET 7 support coming?**  We're just finishing that work up right now and hope to have an extension published for VS Code - Insiders soon with this.

2. **When is C# 11 support coming?**  C# 11 support is what adds support for triple-quoted strings.  We're first going to finish up the .NET 7 support, then from there we can look at updating to support C# 11.

Unfortunately I can't give an estimate on when either of these will be done, but we are hoping to get them in soon.

**Comment by nycdotnet** [comment]
Thank you. Due to `"""` strings, I'm more excited for C# 11 than .NET 7 honestly.  Much appreciated for your work on this.
