### ISSUE TITLE
NU1101: Unable to find package

### ISSUE THREAD

**Issue by Agazoth** [dotnet/interactive#2461]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

- OS
    - [x ] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/15127301/201513582-7a8d249e-c2d2-4c10-9f2e-b58ec032aee3.png)

I am not able to get any nuget packages to work on C# Polyglot notebooks. I'm running notebooks successfully on my other machine, but I cannot figure out, why it's not working on this one.

I tried removing all .Net versions and reinstalling 6.0. I tried removing VS Code and reinstalling, I have tried removing all extensions and reinstalling, I have installed dotnet interactive tools globally, I have rebooted countless times, but I still get the same error.

I need a hint to what to try next.

**Comment by Agazoth** [comment]
Hmm. I deleted ```FSharp.Core.6.0.7``` from ```C:\Program Files\dotnet\sdk\6.0.403\FSharp\library-packs```, rebooted the PC and now it works.

**Comment by jonsequitur** [comment]
The syntax in the screen shot is incorrect. This should work: 

```c#
#r "nuget:azure.storage.blobs,*-*"
```

or: 

```c#
#r "nuget:azure.storage.blobs,7.0.0"
```
