### ISSUE TITLE
Polyglot Rebrand Feedback

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/interactive#2465]
Hey All!
I'm finding the rebrand a bit confusing since .NET Interactive seems to still exist? Do we have a good landing page to differentiate .NET Interactive and Polyglot Notebooks?

My suggestion would be to go all-in on Polyglot for all the related products for brand continuity 

- Polyglot Notebooks - Extension/Front End
- Polyglot Kernel or Polyglot Interactive  - Backend Kernel

- .NET SDK for Polyglot Notebook - .NET NuGets for extension writing and libraries for interacting with kernel.
- Python SDK for Polyglot Notebooks - Python libraries for extension writing and libraries for interacting with kernel.
- JS SDK for Polyglot Notebook - JS libraries for extension writing and libraries for interacting with kernel.

**Comment by JakeRadMSFT** [comment]
That will help a bit. The branding still seems to lack continuity though. 


<img width="868" alt="image" src="https://user-images.githubusercontent.com/31937616/202002042-67cdfcf1-4478-4750-9c2c-0c5abde48591.png">

In the Kernel/Language picker it just says both everywhere.

**Comment by jonsequitur** [comment]
They are two different layers. 

The .NET Interactive kernel can be used for things other than notebooks, e.g. `dotnet-repl` and other non-notebook form factors. 

Polyglot Notebooks can be used for non-.NET kernels (e.g our JavaScript kernel and potential future polyglot Jupyter kernels don't require .NET).

Do you think more closely aligning the naming would clarify or confuse these examples?

**Comment by JakeRadMSFT** [comment]
For me it's just confusing for ".NET Interactive" to exist as a public facing brand **after** a _rebrand_ to "Polyglot Notebooks".

### .NET Interactive is still

- The github repo https://github.com/dotnet/interactive
- In the language picker
- The nuget names https://www.nuget.org/packages/Microsoft.DotNet.Interactive/1.0.0-beta.22553.7
- The url for installing the extension https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode
- Everywhere inside of the Polyglot Notebooks extension

### Polyglot Notebooks is
- The name of the extension

It feels like a shallow rebrand and requires folks that are new to Notebooks to know the nuances of Notebooks and Kernels to get the difference.

Feel free to close out the issue if you all disagree and haven't heard similar feedback from others -- Just my 2 cents.

**Comment by JakeRadMSFT** [comment]
>  .NET Interactive kernel can be used for things other than notebooks, e.g. dotnet-repl and other non-notebook form factors.

Doesn't it also support more languages than just .NET? Isn't this the thing that makes Polyglot Notebooks ... Polyglot?

> Polyglot Notebooks can be used for non-.NET kernels (e.g. the JavaScript and HTML kernels as well as potential future polyglot Jupyter kernels don't require .NET).

Doesn't it still require .NET Interactive?

**Comment by jonsequitur** [comment]
The intent is not to rebrand .NET Interactive, which is a .NET-based technology that hosts .NET languages like C#, F#, and PowerShell. You can use it to create non-polyglot experiences. 

The protocol it uses is language-agnostic and enables polyglot experiences like Polyglot Notebooks. 

> It feels like a shallow rebrand and requires folks that are new to Notebooks to know the nuances of Notebooks and Kernels to get the difference.

Learning the difference between a notebook and a kernel is fairly important early on in learning Jupyter, I think.

>> .NET Interactive kernel can be used for things other than notebooks, e.g. dotnet-repl and other non-notebook form factors.

> Doesn't it also support more languages than just .NET? Isn't this the thing that makes Polyglot Notebooks ... Polyglot?

It doesn't support them directly and has no special knowledge of them. It supports them by proxying those behaviors to remote processes.

* JavaScript and HTML are proxied to browser-hosted kernels written in TypeScript.
* SQL and KQL are proxied to the SQLToolService executable.
* Python, R, etc. are proxies to Jupyter kernels.

>> Polyglot Notebooks can be used for non-.NET kernels (e.g. the JavaScript and HTML kernels as well as potential future polyglot Jupyter kernels don't require .NET).

> Doesn't it still require .NET Interactive?

The JavaScript and HTML kernels don't require .NET Interactive today. Though we haven't yet made them available standalone in Polyglot Notebooks, they can be loaded into a browser and used directly with no .NET in the picture. And Polyglot Notebooks will eventually work in browser-only mode with no server-side compute needed.

**Comment by JakeRadMSFT** [comment]
I think it's starting to make more sense then.

![image](https://user-images.githubusercontent.com/31937616/202014951-2edb83c2-0b49-4773-a1b1-607aac5aef2b.png)

What is the motivation for (Polyglot Notebooks) to be in the language picker for everything then?

**Comment by jonsequitur** [comment]
Each of the languages listed with `(Polyglot Notebook)` after it is actually a superset of the language, which allows e.g. C# **_and_** Polyglot Notebook magic commands.

The following isn't valid C# but it is valid in Polyglot Notebooks:

```C#
#!share --from fsharp someVariable
Console.WriteLine(someVariable);
```

**Comment by JakeRadMSFT** [comment]
I see - that's pretty nuanced!
