### ISSUE TITLE
PL/SQL

### ISSUE THREAD

**Issue by dhaanpaa-lab0** [dotnet/interactive#2474]
.net interactive notebooks

### Question
What would it take to add PL/SQL support to .net interactive?

**Comment by jonsequitur** [comment]
I'm not familiar enough with using PL/SQL to say for sure, but a minimal implementation can be quite simple.

Here's a sample SQLite subkernel: https://github.com/dotnet/interactive/blob/97a0651d15d6506bfe0a15dd5e74f8a29568eca4/src/Microsoft.DotNet.Interactive.ExtensionLab/SQLiteKernel.cs#L16

 That one doesn't support code completions or variable sharing. The support for T-SQL and KQL has those. The common implementation is here: 

https://github.com/dotnet/interactive/blob/7636b24de6e943b094a0562508caafb8d3b2b14d/src/Microsoft.DotNet.Interactive.SqlServer/ToolsServiceKernel.cs#L22

**Comment by dhaanpaa-lab0** [comment]
@jonsequitur Thank you so much. Here is a reference for oracle SQL. https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlqr/index.html , PL/SQL is oracles stored procedure language. What is involved in setting up a kernel development environment if you wanted to contribute?

**Comment by jonsequitur** [comment]
We have an extension mechanism so additional languages can be added using NuGet packages. There's an overview here: https://github.com/dotnet/interactive/blob/main/docs/extending-dotnet-interactive.md

Our SQL and KQL support uses this same mechanism.
