### ISSUE TITLE
Visual Studio 2022 Extension VSIX source Code for Notebook Extension you were Testing

### ISSUE THREAD

**Issue by SFC-Sarge** [dotnet/interactive#2475]
I was working on replacing/modifying my [LinqLanguageEditor2022 ](https://marketplace.visualstudio.com/items?itemName=DannyMcNaught.LinqLanguageEditor)extension to use Notebooks and would like to continue this project, can you provide me a link to the source code for you VSIX package for the Notebook extension you were testing for Visual Studio 2022 so that I will not have to start from scratch with your package and this will allow me to maintain and support the use of a notebook in my extension?

@SFC-Sarge @NotCoffee418 - Sorry that we haven't made it's deprecation clear. We'll work on messaging that to the community better.

The VS Notebook Extension was an experiment that didn't get as much adoption as we'd hoped.

I'd love to hear your feedback on the VS Notebook extension and on the VS Code Polyglot notebooks! VS Code has the best .NET Notebook experience with Polyglot Notebooks.

https://github.com/dotnet/interactive#visual-studio-code

I apologize again for the abrupt deprecation of the VS Extension and hope the VS Code experience meets your needs. If not, let us know!

**Comment by brettfo** [comment]
The code for the Visual Studio VSIX isn't open source and the path forward is going to be via the Polyglot Notebook extension (formerly .NET Interactive) for VS Code, which is this repo.

**Comment by SFC-Sarge** [comment]
@brettfo
I am willing to sign a NDA for the Visual Studio 2022 VSIX source code if that would help.
