### ISSUE TITLE
Extension bundled with nuget package no longer loading correctly

### ISSUE THREAD

**Issue by andrewheumann** [dotnet/interactive#2478]
### Describe the bug
A [library I work on](https://github.com/hypar-io/Elements) bundles with it an `extension.dib`, following the guidance in this document: https://github.com/dotnet/interactive/tree/5df931c08ec22bb0d01c8082e2339b80a17f4a30/samples/extensions/RandomNumber

We reference the bundled extension here: https://github.com/hypar-io/Elements/blob/ea629a7ec2d873cbf680298a6af69a00fd59ccbf/Elements/src/Elements.csproj#L60

Until recently, I would install the library in a notebook using `#r “nuget: Hypar.Elements, *-*“` and it would both install the package and import the extension. The `using`s from the `.dib` were automatically imported, I had access to the variables/methods defined, and custom `Formatter`s would be registered for me to use right away.

Recently, this stopped working in interactive notebooks in VS Code. I still receive the message `Loading extension script from /Users/andrewheumann/.nuget/packages/hypar.elements/1.4.0-alpha.2/interactive-extensions/dotnet/extension.dib`, and I can verify that that file exists. However, none of the `using`s are imported, and none of the variables / methods / `Formatter`s are available. [This video shows how this used to work.](https://youtu.be/73v9AOaKVvs)

Let me know if I’ve missed something about how this is supposed to work, or if this is the wrong place to report this issue.
### Please complete the following:
**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
Version: 1.0.355307+4cc71ae4e275fd80852b9c2faa317bc3a0033d2c
Library version: 1.0.0-beta.22553.7+4cc71ae4e275fd80852b9c2faa317bc3a0033d2c
Build date: 2022-11-04T02:20:42.0000000Z
- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [X] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser
    - [X] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)
### Screenshots
![image](https://user-images.githubusercontent.com/31935763/202472481-c21c593b-79af-4708-b9e1-f183073d919b.png)

**Comment by andrewheumann** [comment]
any update on this? this is still an issue as of 
```
Version: 1.0.360602+9bf026dabac44a6256a65168fa93dcb7e2edcca4
Library version: 1.0.0-beta.22606.2+9bf026dabac44a6256a65168fa93dcb7e2edcca4
Build date: 2022-12-20T17:11:54.7013002Z
```.  Are script-based extensions no longer supported?

**Comment by andrewheumann** [comment]
(For what it's worth, this isn't specific to us, the example also does not appear to work)
<img width="646" alt="image" src="https://user-images.githubusercontent.com/31935763/214113045-0923dfc0-e4c2-4590-82db-84553523694b.png">

**Comment by jonsequitur** [comment]
This is still supported and is the preferred approach, over embedding a DLL. 

I updated the ClockExtension sample and [docs](https://github.com/dotnet/interactive/blob/main/docs/extending-dotnet-interactive.md) the other day to favor this approach, in fact.

https://github.com/dotnet/interactive/blob/main/samples/extensions/ClockExtension.ipynb

There's one bug I hit during that process that most users won't hit but extension developers might. Late last year a cache was added to the `#r nuget` functionality. It improves performance by caching DLL paths but if you deleted the package from your NuGet cache, the `#r nuget` cache wouldn't get invalidated by the missing file. You can manually remove that cache by deleting everything under   `~\.packagemanagement\nuget`.

Please let me know if this works for you.

**Comment by andrewheumann** [comment]
deleted `~/.packagemanagement/nuget` and tried again, no dice:

![image](https://user-images.githubusercontent.com/31935763/214151642-bc1de842-8053-40bb-800b-fcd9967d9799.png)

**Comment by andrewheumann** [comment]
if I copy-paste the contents of that file (the extension.dib) into the notebook directly, everything works as expected. So it just seems like it's not loading the `extension.dib` at all

**Comment by jonsequitur** [comment]
It looks like the `#!markdown` element in the `.dib` threw it off. I was able to get the extension to load by removing it.

I'll look into why this is causing an issue. A workaround might be to remove it for the moment.

**Comment by jonsequitur** [comment]
This has been fixed. The fix is in Insiders and should be rolling out in Stable in the next couple of days.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/547415/215847584-a24c0890-e2c3-46a2-b272-741968dd2115.png">

**Comment by andrewheumann** [comment]
AMAZING!!!! thank you so much @jonsequitur
