### ISSUE TITLE
Is there a way I can check if notebook is using .net 6 or .net 7

### ISSUE THREAD

**Issue by anirugu** [dotnet/interactive#2496]
I create the .dib file and I am able to use them as expected. Is there a way I can verify if it's using .net 6 or .7 in c# using code?

**Comment by brettfo** [comment]
Unfortunately the answer to this is a little complicated.  The currently released version of the notebook tools is built against the .NET 6.0 runtime, but it will execute just fine on .NET 7, _however_ you won't be able to reference a .NET 7 assembly.

The version of the notebook tools in preview is built against .NET 7 and runs against that, too.

If you're looking purely at the runtime environment, you can execute this C# code in a cell to report the current runtime:

``` csharp
using System.Reflection;
using System.Runtime.Versioning;

Assembly.GetEntryAssembly()?.GetCustomAttribute<TargetFrameworkAttribute>()?.FrameworkName
```
