### ISSUE TITLE
How to construct connect mssql command with variable?

### ISSUE THREAD

**Issue by travisgan** [dotnet/interactive#2523]
NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.355307+4cc71ae4e275fd80852b9c2faa317bc3a0033d2c
Library version: 1.0.0-beta.22553.7+4cc71ae4e275fd80852b9c2faa317bc3a0033d2c
Build date: 2022-11-28T21:03:16.1596190Z

### Question
How to construct a magic connect command with variable? For example, 
#!value --name sqlserver
ServerA

#!share sqlserver --from value
string sqlconnstr = $"Server={sqlserver}; Initial Catalog=mydb; Persist Security Info=False; Integrated Security=true;";
#!connect mssql --kernel-name mydb sqlconnstr

This doesn't work. Expecting to have something similar as this,
#!connect mssql --kernel-name mydb "Server=ServerA; Initial Catalog=mydb; Persist Security Info=False; Integrated Security=true;"

**Comment by brettfo** [comment]
Values from other kernels can be inlined with the syntax `@kernelName:variableName` so in your scenario it could look something like this:

```
#!value --name sqlserver
ServerA
```

```
#!share sqlserver --from value
string sqlconnstr = $"Server={sqlserver}; ...";
```

```
#!connect mssql --kernel-name mydb @csharp:sqlconnstr
```

**Comment by travisgan** [comment]
That works. Thank you.

**Comment by o-o00o-o** [comment]
The AI's couldn't answer this and it doesn't seem to be in the docs, so perhaps worth covering this inline capability in a doc somewhere?

**Comment by jonsequitur** [comment]
There are docs for this here: https://github.com/dotnet/interactive/blob/main/docs/variable-sharing.md

Finding the rights docs isn't always easy of course. Any suggestions on what would have made these easier for you to find?
