### ISSUE TITLE
Using syntax when there is a diffrent between the nuget package name and the using

### ISSUE THREAD

**Issue by ilaykid** [dotnet/interactive#2533]
hey,
I'm trying to import a nuget package called BlingFire and when I'm trying to use the package I ran into the following exception:

```
#r "nuget:BlingFireNuget"
using BlingFire;
```
Error: (1,7): error CS0246: The type or namespace name 'BlingFire' could not be found (are you missing a using directive or an assembly reference?)

I wonder what syntax I should use to import this package with interactive dotnet.
thank you!

**Comment by brettfo** [comment]
.NET Interactive only supports NuGet packages that add assembly references (*.dll), but the `BlingFireNuget` package is purely a source-based package (e.g., it adds various files to your project), so there's nothing that could be referenced.

Adding a bunch of source files to .NET Interactive is currently out-of-scope, but if you wanted to use something like this in .NET Interactive you'd first have to build a local library with `BlingFireNuget` and then you could reference the build assembly like so:

```
#r "C:\path\to\BlingFireNugetProject\bin\Debug\BlingFireNugetProject.dll"
```
