### ISSUE TITLE
How to customize the Roslyn version used by the tool

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/interactive#2542]
**The package and version I'm asking about**: Polyglot Notebooks  v1.0.3553070 

### Question

I'd like to use a [nightly build](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-tools/NuGet/Microsoft.Net.Compilers.Toolset/overview/4.5.0-3.22601.3) of Roslyn with Jupyter Notebooks in order to test new versions of the compiler interactively. Is there any way I can make that happen? It would be nice if I could just point to a package with a setting or environment variable, but I don't mind doing slightly hacky stuff if necessary.

**Comment by brettfo** [comment]
We spoke with Rikki offline and have filed issue #2546 to address this.
