### ISSUE TITLE
SQL results not rendered with nteract data explorer

### ISSUE THREAD

**Issue by travisgan** [dotnet/interactive#2545]
.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.355307+4cc71ae4e275fd80852b9c2faa317bc3a0033d2c
Library version: 1.0.0-beta.22553.7+4cc71ae4e275fd80852b9c2faa317bc3a0033d2c
Build date: 2022-11-28T21:03:16.1596190Z
https://github.com/dotnet/interactive

When executing a sql query, the result is rendered in a plain table (like html table). For example,
#!sql-mydb 
select * from sys.databases

As opposed to multiple 'older' video showcase, the demo always shows that sql query rendered in nteract data explorer. 
https://youtu.be/938jBJ-tK3c?t=1134
https://youtu.be/m5d6pG_R05M?t=1186

At one point in the first video, @jonsequitur mentioned that by default sql result should be rendered with nteract data explorer. Not sure if anything has changed since then or is there anything additional need to be installed or configured to have the sql query result in a better/richer format (eg. nteract data explorer)?

**Comment by sasaendler** [comment]
Hi. 
I'm facing the same issue. "Change presentation" dialog on data result only offers text/plain as option. 
I couldn't find a nteract extension. What am I missing?

Running Polyglot Notebooks v1.0.3606020.

Best Regards.

**Comment by sasaendler** [comment]
@colombod Thank you for your great helpful response.

**Comment by travisgan** [comment]
@colombod thank you for the clarification. how do you exactly get to this data table view in your example? is that from nteract extension and how do you load that as default data explorer (instead of the sanddance example graphical view)?

![image](https://user-images.githubusercontent.com/5826790/210595323-9d9cc3ae-f8a7-45d3-9358-2196d609b3b4.png)
