### ISSUE TITLE
Import magic command displays errors for Markdown cells

### ISSUE THREAD

**Issue by marckruzik** [dotnet/interactive#2565]
### Describe the bug
When I use the import magic command to import a .dib notebook which contains a Markdown cell, the notebook displays an error instead of the output of the Markdown cell.

See this example to reproduce the bug:

![2022_12_13-12h06m28s-main_notebook dib - Advent_2022 - Visual Studio Code](https://user-images.githubusercontent.com/51711029/207301907-e6f92c3b-a32f-4004-9b44-9aff893be9c4.png)

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

Version: 1.0.355307+4cc71ae4e275fd80852b9c2faa317bc3a0033d2c

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by colombod** [comment]
Hi, I am working on this at #2569
