### ISSUE TITLE
F# Wrong Order of Assemblies / nuget packages loaded....

### ISSUE THREAD

**Issue by dhabe1982** [dotnet/interactive#26]
#### Describe the bug
I load all dependencies /nugetpackages at the top of the notebook file.
but i got errors that the typ is unkown.. 

when i try this in dotnet core under cli this working correctly..

i have also the little jupyter file attached.. it is easier to see the problem i think

[aarvark.zip](https://github.com/dotnet/try/files/3941892/aarvark.zip)

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [x ] .NET Jupyter Notebook 
- [ x] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x ] Other: input.fsx (18,8)-(22,10) typecheck error The type referenced through 'FShade.Imperative.Module' is defined in an assembly that is not referenced. You must add a reference to assembly 'FShade.Imperative'.

#### Screenshots
![error](https://user-images.githubusercontent.com/58706933/70476564-4409b880-1ad7-11ea-8767-82d84b354fb9.PNG)

#### Please complete the following:
 - OS
    - [ ] Windows 10
    - [ ] macOS
    - [x ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x ] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by KevinRansom** [comment]
This bug will be fixed when this F# PR : https://github.com/dotnet/fsharp/pull/8855 is merged, and inserted into interactive.

**Comment by KevinRansom** [comment]
This is fixed by: #

![image](https://user-images.githubusercontent.com/5175830/78192520-2ae19a80-742d-11ea-8187-13a05b873e4a.png)

**Comment by haraldsteinlechner** [comment]
hi there,

thanks for progress on this one. The original test case works now, but when referencing a bit more it seems rather weired again.

```
#r "nuget:FSharp.Data.Adaptive,0.0.25"
#r "nuget:Aardvark.Base,5.0.10"
#r "nuget:Aardvark.Base.Incremental,5.0.10"
#r "nuget:Aardvark.Base.FSharp,5.0.10"
#r "nuget:FShade.Core,5.0.3"
#r "nuget:FShade.GLSL,5.0.3"
#r "nuget:FShade,5.0.3"
#r "nuget:FShade.Imperative,5.0.3"
#r "nuget:Aardvark.Base.Rendering,5.0.6"
#r "nuget:Aardvark.Rendering.Vulkan,5.0.6"
#r "nuget:Aardvark.Application.Slim.GL,5.0.6"
#r "nuget:Aardvark.SceneGraph,5.0.6"
#r "nuget:Aardvark.SceneGraph.IO,5.0.6"
#r "nuget:Aardvark.Rendering.Text,5.0.6"
#r "nuget:FsPickler"
#r "nuget:FsPickler.Json"
#r "nuget:Suave"
```

with the same snippet (have it extra since in one cell the errors cannot be seen):
```
open System
open Aardvark.Base
open FShade

let a : FShade.Effect = Unchecked.defaultof<_>

open Aardvark.Base.Rendering

```

yields this error.
```

=============== S T A R T ==========================================
>>>> C:\Users\hs\.nuget\packages\aardvark.base.typeproviders\4.5.15\typeproviders\fsharp41\netstandard2.0\Aardvark.Base.TypeProviders.DesignTime.dll
>>>> C:\Users\hs\.nuget\packages\aardvark.base.typeproviders\4.5.15\lib\netstandard2.0\Aardvark.Base.TypeProviders.DesignTime.dll
Using: C:\Users\hs\.nuget\packages\aardvark.base.typeproviders\4.5.15\typeproviders\fsharp41\netstandard2.0\Aardvark.Base.TypeProviders.DesignTime.dll


Stopped due to error


input.fsx (2,6)-(2,19) typecheck error The type referenced through 'FSharp.Data.Adaptive.HashSet`1' is defined in an assembly that is not referenced. You must add a reference to assembly 'FSharp.Data.Adaptive'.
input.fsx (7,6)-(7,29) typecheck error The type referenced through 'FShade.Effect' is defined in an assembly that is not referenced. You must add a reference to assembly 'FShade.Core'.
```

indeed, this is the wrong typeproviders packge. let us specify:

```
#r "nuget:FSharp.Data.Adaptive,0.0.25"
#r "nuget:Aardvark.Base.TypeProviders,5.0.10" // mind this one
#r "nuget:Aardvark.Base,5.0.10"
#r "nuget:Aardvark.Base.Incremental,5.0.10"
#r "nuget:Aardvark.Base.FSharp,5.0.10"
#r "nuget:FShade.Core,5.0.3"
#r "nuget:FShade.GLSL,5.0.3"
#r "nuget:FShade,5.0.3"
#r "nuget:FShade.Imperative,5.0.3"
#r "nuget:Aardvark.Base.Rendering,5.0.6"
#r "nuget:Aardvark.Rendering.Vulkan,5.0.6"
#r "nuget:Aardvark.Application.Slim.GL,5.0.6"
#r "nuget:Aardvark.SceneGraph,5.0.6"
#r "nuget:Aardvark.SceneGraph.IO,5.0.6"
#r "nuget:Aardvark.Rendering.Text,5.0.6"
#r "nuget:FsPickler"
#r "nuget:FsPickler.Json"
#r "nuget:Suave"
```

and we are arriving with all installs failing:
```
Installing package FSharp.Data.Adaptive, version 0.0.25.failed!
Installing package Aardvark.Base.TypeProviders, version 5.0.10.failed!
Installing package Aardvark.Base, version 5.0.10.failed!
```

I dont see the error unfortunately. i can debug more in depth if needed.

In a c# notebook it works though.

Thanks again, bests, harald

**Comment by haraldsteinlechner** [comment]
i revisited this issue, error reporting is much better now, all works now :)
