### ISSUE TITLE
[PowerShell] Can no longer use Invoke-Command with PSSessions

### ISSUE THREAD

**Issue by wsmelton** [dotnet/interactive#260]
#### Describe the bug
I recently updated to the latest bits and found that my notebooks where I was remotely running code via `Invoke-Command` no longer works.
It now shows a message about support coming soon, which I don't understand because it was working before 😉 

> IHostSupportsInteractiveSession support is coming soon.

The example in the screenshot is utilizing the support for interactive credential. What worked with no issue previously was creating the credential object and passing that without interaction:

```powershell
$domainpwd = ConvertTo-SecureString -String 'mypassword' -AsPlainText -Force
$acctName = "lab\labadmin"
$domainCred = New-Object System.Management.Automation.PSCredential -ArgumentList $acctName,$domainpwd

$session = New-PSSession -VMName lab-sql-01 -Credential $domainCred
Invoke-Command -Session $session -ScriptBlock {"Test"}
```

#### Did this error occur while using `dotnet interactive`?
- [x] .NET Jupyter Notebook 

#### Screenshots

![image](https://user-images.githubusercontent.com/11204251/76338169-52c65e00-62c6-11ea-84d6-a0d6d232c2c7.png)

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Safari
 - Frontend
    - [ ] Jupyter notebook
    - [x] Jupyter lab
    - [ ] nteract

**Comment by TylerLeonhardt** [comment]
A fix is out for this now
