### ISSUE TITLE
Intellisense still slow

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/interactive#2606]
### Describe the bug
https://user-images.githubusercontent.com/4510984/211595063-8aa63ec1-a712-4d8e-ae0b-608981e53bc9.mp4

Refer: 
- https://github.com/dotnet/interactive/issues/2373#issuecomment-1370515985
- https://github.com/dotnet/interactive/issues/1391

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
```
.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.360602+9bf026dabac44a6256a65168fa93dcb7e2edcca4
Library version: 1.0.0-beta.22606.2+9bf026dabac44a6256a65168fa93dcb7e2edcca4
Build date: 2022-12-13T18:14:17.5227687Z
```

- VSCode
```
版本: 1.74.2 (user setup)
提交: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
日期: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
沙盒化: No
```
- OS
    - [x] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
- Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
- Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by reinux** [comment]
It's incredibly slow for me as well in F#.

**Comment by GF-Huang** [comment]
> It's incredibly slow for me as well in F#.

It's fast now in C#.

**Comment by jonsequitur** [comment]
I'm closing this because we have made some performance improvements. Performance work is always ongoing of course, so an issue like this is never exactly "fixed." But if the performance is annoyingly slow we definitely want to hear about it. 

Thanks!
