### ISSUE TITLE
variables created/saved in value kernel not showing up in variable explorer

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#2623]
VS Code Version: 1.74.3
Ext Version: v1.0.3611020
Tool Version: 1.0.360602+9bf026dabac44a6256a65168fa93dcb7e2edcca4

Steps to reproduce: 
1. Use value kernel + input to save a variable
2. Check variable explorer

**Comment by jonsequitur** [comment]
This has been fixed.

**Comment by jonsequitur** [comment]
<img width="493" alt="image" src="https://user-images.githubusercontent.com/547415/218530706-26479b1c-5221-4aa0-986f-beb3f9466cea.png">
