### ISSUE TITLE
Cannot resolve platform specific dll

### ISSUE THREAD

**Issue by colombod** [dotnet/interactive#264]
When importing a package like System.Device.Gpio,1.1.0-prerelease.20153.1 the packages are correctly resolved in dotnet run but dotnet interactive doesn't lookup the platform specific `.nuget\packages\system.device.gpio\1.1.0-prerelease.20153.1\lib\netstandard2.0`
but this is resolved
`System.Device.Gpio,1.1.0-prerelease.20153.1,/home/pi/.nuget/packages/system.device.gpio/1.1.0-prerelease.20153.1/lib/netstandard2.0/System.Device.Gpio.dll,,linux-arm`

**Comment by KevinRansom** [comment]
merged : https://github.com/dotnet/interactive/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc
