### ISSUE TITLE
Javascript cells cannot call javascript functions defined in other javascript cells

### ISSUE THREAD

**Issue by marckruzik** [dotnet/interactive#2643]
### Describe the bug
When I declare a javascript function in a cell, I cannot call it from another javascript cell.

I listed different cases:

* When a javascript function is defined in an html cell, it can be called from a javascript cell
* When a javascript function is defined in a javascript cell, **it cannot be called from another javascript cell**
* When a javascript function is defined in a javascript cell, it can be called from the same javascript cell

### Screenshots

![2023_01_24-20h19m36s-● exploration-20230124 dib - 2023_01_21-purity_exploration - Visual Studio Code](https://user-images.githubusercontent.com/51711029/214388250-f5967713-4ca8-4a9b-aa50-c4fa493f60d9.png)

### Dib Code

```
#!html

<script>
function js_function_in_html_cell() {
    console.log("hello from html cell");
}
</script>

#!javascript

js_function_in_html_cell();

#!javascript

function js_function_in_js_cell() {
    console.log("hello from js");
}

#!javascript

js_function_in_js_cell();

#!javascript

function js_function_in_same_cell() {
    console.log("hello from same cell");
}
js_function_in_same_cell();

```
### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
Version: 1.0.360602+9bf026dabac44a6256a65168fa93dcb7e2edcca4

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by colombod** [comment]
the js kernel is scoping those declarations to teh cell execution, right now for the function to be visible you would need to assign it to a global scope variable 
```
js_function_in_cell = () =>{
}```

**Comment by jonsequitur** [comment]
This is explained in more detail here: https://github.com/dotnet/interactive/blob/main/docs/javascript-overview.md
