### ISSUE TITLE
notebook files are considered modified a few seconds after opening

### ISSUE THREAD

**Issue by marckruzik** [dotnet/interactive#2646]
### Describe the bug
When I open a .dib file, it is considered non modified (that's normal).
But a few seconds later, the dib file is considered modified (with a little dot next to the file name on the tab). 

It causes me a lot of confusion, as I am working with several files, and I can never know if I modified them for real or not.

It looks like the modified state is caused at the same time than the loading of the bottom right part of the cell "csharp - C# Script"

### Screenshots

![2023_01_25-14h34m09s-● exploration-quickchart dib - 2023_01_21-purity_exploration - Visual Studio Cod](https://user-images.githubusercontent.com/51711029/214577109-d1969f64-bbf3-4059-a552-5774894e7908.png)

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
Version: 1.0.360602+9bf026dabac44a6256a65168fa93dcb7e2edcca4

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by kkoziarski** [comment]
I'm not sure if this is somehow related, but in recent insiders' version, metadata is changing constantly, `aliases` and `languageName` are changing places randomly, which makes git detecting changes, even if there was no change (manually) done in .dib file, only cell was run:

![image](https://user-images.githubusercontent.com/6848262/215694545-3544c2e8-82b2-4fb5-b13e-58996b0afc8c.png)

**Comment by jonsequitur** [comment]
@kkoziarski, I think this issue predated the addition of `.dib` metadata and also affects `.ipynb` files, but what you've found is definitely something we should also fix.

**Comment by colombod** [comment]
Some older notebooks will need to update metadata and will actually show as modified. But once saved this should not happen anymore.

**Comment by hwndmaster** [comment]
I still can reproduce this issue.

VS Code v1.91.1
Extension versions:
* ms-dotnettools.dotnet-interactive-vscode = v1.0.5229040
* ms-toolsai.jupyter = v2024.6.0
* ms-toolsai.jupyter-keymap = v1.1.2
* ms-toolsai.jupyter-renderers = v1.0.18

No updates are available at the moment and no special settings were applied to any of those extensions.

![Animation](https://github.com/user-attachments/assets/8e020372-2e55-4b4a-94bf-2f0b385091cd)

File content:
```
#!meta

{"kernelInfo":{"defaultKernelName":"csharp","items":[{"aliases":[],"name":"csharp"}]}}

#!csharp

# Test

blablabla
```

**Comment by marckruzik** [comment]
Hello @hwndmaster, about the behavior you are describing, I created another issue, which is still open: #3430
The issue here concerned all notebook files, but the one you are talking about concerns only dib files with a markdown cell.
