### ISSUE TITLE
[PowerShell] Tab completion doesn't work as expected for type name completion and static member completion

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/interactive#265]
#### Describe the bug

Tab completion for type name and static members are not work correctly.
For example,
- `[System.Man<tab>` will result out in `[System.System.Management` while the expected result is `[System.Management`;
- `[ConsoleCo<tab>]` results in `System.ConsoleColor]` while the expected result is `[System.ConsoleColor]`;
- `[ConsoleColor]::Blu` results in `Blue` while the expected result is `[ConsoleColor]::Blue`.

This is because currently there is no way to specify the `cursor_start` and `cursor_end` position to indicate the part of the original text that should be replaced by the completion results. The LSP work that is happening in dotnet-interactive will offer the infrastructural support, and we will have to put off the fix until that happens.

#### Did this error occur while using `dotnet interactive`?
- [x] .NET Jupyter Notebook 

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [x] macOS
    - [x] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [x] Edge
    - [x] Safari
 - Frontend
    - [x] Jupyter notebook
    - [x] Jupyter lab
    - [x] nteract

**Comment by TylerLeonhardt** [comment]
I believe there's nothing we can really do about this until we have a better frontend to use. Right @jonsequitur ?

I think the issue is still worth leaving opened because other users will find it and it's a very painful experience today.

**Comment by daxian-dbw** [comment]
`cursor_start` and `cursor_end` can be specified in the `CompletionReply` message, but currently the interactive kernel layer doesn't expose those two settings in the corresponding `KernelBaseEvent`. When constructing the `CompletionReply`, those 2 fields are calculated with some assumptions, which doesn't work with all PowerShell scenarios.

**Comment by TylerLeonhardt** [comment]
Thanks for the context @daxian-dbw! Yes that makes perfect sense.
