### ISSUE TITLE
Error when running the Binder demo

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/interactive#2659]
Hi, I'm trying to run the Binder demo [here](https://github.com/dotnet/interactive/blob/main/docs/NotebooksOnBinder.md).  
It never loads: I get a 404 error, Invalid build token, Failed to connect to event stream.  After a couple of page reloads I get  `500 Internal Server Error`.  I tried this same thing a few weeks ago and got the same errors.  I thought it was maybe having a bad day and I did not pursue it.
Tried using both Firefox and Chrome.

**Comment by jonsequitur** [comment]
We're no longer maintaining the Binder deployment as it was creating a significant maintenance drag on the repo and some of the Jupyter APIs are out of date with the VS Code-specific experience, particularly for JavaScript programmability.
