### ISSUE TITLE
HTML UI 

### ISSUE THREAD

**Issue by dgorti** [dotnet/interactive#2674]
I am looking for a way to present a simple UI to the user, an HTML form (checkboxes, radio buttons, input boxes etc). Data entered by the user should be available for use in the cells below.
I tried doing a simple input box, but the box would not let me type in. Some of the keystrokes are eaten by the notebook UI. For example, if I type 'a' in the input box, a new code cell is created.

It would be great to have a way to do a simple form to take user's input.

**Comment by jonsequitur** [comment]
You may be hitting #2020.

**Comment by colombod** [comment]
@rebornix

**Comment by PawelStadnicki** [comment]
I'm going to publish my work just after it is resolved

**Comment by PawelStadnicki** [comment]
Hi @brettfo , @colombod , @jonsequitur 
Is this going to be addressed before GA?
For me it is a crucial feature.
As a workaround I can just implement keyboard as a control like below, but it is not ideal:
![image](https://user-images.githubusercontent.com/56049414/220472708-dc5acf3b-3ea6-4a40-a819-40804066a078.png)

**Comment by colombod** [comment]
This is not on our side. Needs to be discussed with vscode

**Comment by PawelStadnicki** [comment]
Yes, I know it is vscode notebook API (keyboard shortcuts). I just thought it is still tracked here to some degree.

**Comment by rebornix** [comment]
@PawelStadnicki as @jonsequitur mentioned, an issue for VS Code repo will be very helpful and I'd like to how what keybindings are blocking your scenarios. Most of the time tweaking when clauses for keybindings can resolve the conflicts and we should probably make sure we have the when clauses updated in the core if it makes good sense. Thanks in advance!

**Comment by PawelStadnicki** [comment]
All single keyboard shortcuts break my notebooks:

![image](https://user-images.githubusercontent.com/56049414/221267554-88de9505-f077-4a73-80fa-674a69de166a.png)
**`!inputFocus`** _when clause_ doesn't work for cell output HTML.

When I type "S" in input, the Save dialog will appear. When I type "X", the cell output will be just deleted.
![image](https://user-images.githubusercontent.com/56049414/221268220-1afd5e08-ff0b-44dc-a20f-45669b91a574.png)

I know that the appropriate _when clause_ will solve it, but whatever the clause is, it should be turned on by default so users don't have to update keyboard preferences.

I can open the issue in VS Code.

**Comment by PawelStadnicki** [comment]
I created an [issue](https://github.com/microsoft/vscode/issues/175387) in VS Code repo.

**Comment by rebornix** [comment]
This issue should be fixed now via Jupyter Keymap 1.1.0. Please update the keymap extension and check if you can still reproduce.

**Comment by PawelStadnicki** [comment]
Cool :)
I updated the Visual Studio Code Insiders, and I can see the new when clause `!notebookOutputFocused.`
I wonder why it applies to everything except M and Y (screenshot).

![image](https://user-images.githubusercontent.com/56049414/221958665-d76ada6e-5e38-409b-a3f3-4c6e8adc3e0c.png)

**Comment by rebornix** [comment]
@PawelStadnicki that's an oversight, will prepare a fix for it, thanks for pointing that out!

**Comment by PawelStadnicki** [comment]
Uff, I thought it could have a deeper reason :)
Many thanks for this and the following fix, it makes my use case complete and ready to publish.

**Comment by rebornix** [comment]
I just realized M and Y are commands in VS Code. We will need a fix for VS Code, it will take longer for it to land in VS Code stable. For VS Code Insiders, you should be able to get the fix pretty soon (one day or two).

**Comment by PawelStadnicki** [comment]
I can see that in the latest insiders M & Y have the new clause `!notebookOutputFocues`
however, Polyglot Notebooks can't work with it:
**Extension is not compatible with Code 1.77.0-insider. Extension requires: 1.76.0-insider.**
