### ISSUE TITLE
Can't connect to Kusto 

### ISSUE THREAD

**Issue by dgorti** [dotnet/interactive#2681]
All good yesterday. Today I open an notebook and can't connect to Kusto. Tried this on 2 different machines.  Wondering what changed. Any pointers? 

`Error: System.InvalidOperationException: MicrosoftKustoServiceLayer failed to start properly. Exit code: 0.
 ---> StreamJsonRpc.ConnectionLostException: The JSON-RPC connection with the remote party was lost before the request could complete.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync(JsonRpcRequest request, Type expectedResultType, CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.DotNet.Interactive.SqlServer.ToolsServiceClient.ConnectAsync(ConnectParams connectParams)
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Interactive.SqlServer.ToolsServiceClient.ConnectAsync(ConnectParams connectParams)
   at Microsoft.DotNet.Interactive.Kql.ToolsServiceClientExtensions.ConnectAsync(ToolsServiceClient serviceClient, Uri ownerUri, KqlConnectionDetails kqlDetails)
   at Microsoft.DotNet.Interactive.Kql.MsKqlKernel.ConnectAsync()
   at Microsoft.DotNet.Interactive.Kql.KqlKernelConnector.CreateKernelAsync(String kernelName)
   at Microsoft.DotNet.Interactive.Kql.ConnectKqlCommand.ConnectKernelAsync(KernelInvocationContext context, InvocationContext commandLineContext)
   at Microsoft.DotNet.Interactive.CompositeKernel.<>c__DisplayClass26_0.<<AddKernelConnector>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 329`

**Comment by colombod** [comment]
@corivera can you spot anything?

@dgorti can you show the cell loading the kql extension and its output?

**Comment by dgorti** [comment]
![image](https://user-images.githubusercontent.com/28555053/216672629-b57f4d55-1fb5-4332-bb2e-cb27d0242da9.png)

**Comment by corivera** [comment]
We recently updated the underlying Kusto service, so maybe that's related.

@dgorti if you run the following command from a terminal, what versions to you get back for the kusto service tool? "dotnet tool list -g"

We also added an option to collect additional traces recently. From the same terminal, could you set the environment variable "DOTNET_KUSTOSERVICE_LOGFILE" to a path to a text file to store the traces? That will tell the Kusto service to output logs to that file. Launch VS Code from that same terminal and try the same set of instructions again. If any content shows up in that log file, then feel free to send it to my work email corivera@microsoft.com so I can take a look.

**Comment by corivera** [comment]
You can also run the service tool by itself as "MicrosoftKustoServiceLayer" from the terminal, which might give us some immediate console output if the logs are empty. Normally it shouldn't return any output, since it just waits for RPC calls from the client. You can cancel it with Ctrl+C after.

**Comment by dgorti** [comment]
![image](https://user-images.githubusercontent.com/28555053/216690752-a227b021-4143-46b3-ac93-de67982aa5e6.png)

Ran MicrosoftKustoServiceLayer on a prompt, did not see any output

Could not see any logs in the log file.

**Comment by corivera** [comment]
Looks like I didn't add a minimum version check when bumping the Kusto tool version, so if it was already previously installed it won't be updated. We added some additional launch arguments for that Kusto tool in the latest update of the Kusto kernel's nuget package, but the 1.0.0 version of the tool doesn't recognize those args and exits immediately with a help message that gets swallowed by the RPC stream causing that JSON RPC error above.

The workaround for this issue while we wait to push up a new nuget package is to manually update tool with the following commands:
dotnet tool uninstall -g microsoft.sqlserver.kustoservicelayer.tool
dotnet tool install -g microsoft.sqlserver.kustoservicelayer.tool --version 1.1.0

**Comment by blods** [comment]
Different error - but I have as yet been unable to connect with a URI like this, despite this being correct for ADX and Kusto.Explorer
![Untitled](https://user-images.githubusercontent.com/6963498/216736649-9b9aa376-a27f-4795-af7e-37741d184782.png)

**Comment by corivera** [comment]
@blods Looks like a different issue. Does that connection still work for you in Azure Data Studio? We use the same underlying Kusto service code there.

**Comment by blods** [comment]
Oh is it – Yeah we can get to those logs fine from Azure Data Explorer. I might be misunderstanding something though, on Data Explorer we it’s just the workspace ID, authentication types we give it – and we’re in.
We do use MFA and Data Explorer pops a browser Window for the sign in. Perhaps that’s it.

But yeah – that Cluster URI works in ADX browser and Kusto Explorer, and with the workspace ID in Data Explorer – just doesn’t work in polyglot.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by corivera** [comment]
Might have been some confusion there. Azure Data Studio is a separate product from Azure Data Explorer. It's a data-oriented fork of VS Code. More info here: https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio

To connect with Kusto you would install the Kusto extension from the Extensions tab in the sidebar, similar to vs code. Then open a connection using the "New Connection" option from the command palette (Ctrl+Shift+P). In the dialog that shows up, change the connection type to "Azure Data Explorer (Kusto)", enter your connection info, and then hit connect at the bottom.

If that also fails in Azure Data Studio, then that will let us know it's an underlying problem in the shared service code, rather thana bug in our Kusto notebook kernel here.

**Comment by blods** [comment]
OK got ya
So yes - the error also occurs in the Azure Data Studio when using the Kusto Extension.

I can use Azure Data Studios native ability and set the Connection type to 'Azure Monitor Logs' and use the workspace ID, but not Connection type 'Azure Data Explorer (Kusto)' with the cluster URI.

One or more errors occurred. ({"error":{"code":"MgmtCslFailedParsing","message":"ApiContractViolationError: management command parsing failed with error: SyntaxError: Expected \"(\", \"identity\", \"schema\", \"with\", or end of input but \"|\" found., Location: line 1, column ***@***.******@***.***":"ApiContractViolationError: management command parsing failed with error: SyntaxError: Expected \"(\", \"identity\", \"schema\", \"with\", or end of input but \"|\" found., Location: line 1, column ***@***.******@***.******@***.***":".show databases | top 1 by DatabaseName | project ***@***.******@***.******@***.***":true}})


________________________________

**Comment by corivera** [comment]
Got it. I'll take a look.

**Comment by brettfo** [comment]
In the next few days we'll publish a new version of the VS Code extension and packages that will have this fix.
