### ISSUE TITLE
Polyglot VSCode thinks F# notebooks generated by FSharp.Formatting are C# notebooks

### ISSUE THREAD

**Issue by nhirschey** [dotnet/interactive#2685]
### Describe the bug

1. This is probably the same issue as #2289, and it breaks all documentation notebooks previously created by F# Formatting.
2. For new F# notebooks, I can do a PR to update the F# Formatting library to generate F# notebooks with the metadata that the Polyglot notebooks extension wants. What metadata should we add?

Details follow:

The [F# Formatting Library](https://github.com/fsprojects/FSharp.Formatting) generates .NET interactive notebooks. The VSCode extension previously recognized the code cells as F#, but now the polyglot extension converts them to C#. As far as I can tell it's necessary to manually go through every cell and change it to F# (not practical). This breaks all documentation notebooks previously created by F# Formatting.

For example, the extension now thinks the F# code in [this notebook](https://fsprojects.github.io/FSharp.Data//library/CsvProvider.ipynb) from the [F# Data Library](https://github.com/fsprojects/FSharp.Data) is C# code:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/5226115/216729183-648c5c04-dde1-4c19-94aa-db21160720e7.png">

Regarding metadata ... A simple notebook generated by the F# formatting tool looks like this below in json and is what used to work with the old VSCode extension.

```json
        {
            "cells": [
          {
           "cell_type": "code",
           "metadata": {},
            "execution_count": 1, "outputs": [],
           "source": ["let x = 100\n"]
          }
,
          {
           "cell_type": "code",
           "metadata": {},
            "execution_count": 2, "outputs": [],
           "source": ["let y = 100\n"]
          }],
            "metadata": {
            "kernelspec": {"display_name": ".NET (F#)", "language": "F#", "name": ".net-fsharp"},
            "langauge_info": {
        "file_extension": ".fs",
        "mimetype": "text/x-fsharp",
        "name": "C#",
        "pygments_lexer": "fsharp",
        "version": "4.5"
        }
        },
            "nbformat": 4,
            "nbformat_minor": 1
        }
```

From experimentation, it looks like if we change `"metadata": {}` in code cells to what I have here then the cells are recognized as being F# code. Is this correct, is there anything else that you suggest?
```json
 "metadata": {
    "dotnet_interactive": {
     "language": "fsharp"
    },
    "polyglot_notebook": {
     "kernelName": "fsharp"
    }
   }
```

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

.NET Interactive
Version: 1.0.360602+9bf026dabac44a6256a65168fa93dcb7e2edcca4
Library version: 1.0.0-beta.22606.2+9bf026dabac44a6256a65168fa93dcb7e2edcca4
Build date: 2023-01-31T11:33:36.0115292Z

**Comment by brettfo** [comment]
@nhirschey adding the `polyglot_notebook` metadata is the "correct" way to enable this, and the `dotnet_interactive` key is a fallback for back-compat.

This situation, however, is interesting and something that should probably work.  The fix on our end will likely be to use the notebook's kernelspec language if the cell metadata isn't present.

**Comment by nhirschey** [comment]
@brettfo, thank you for making this fix so quickly! That's a real help to the F# community. Additionally, I will update the FSharp.Formatting tool so that it adds `polyglot_notebook` metadata to code cells in notebooks going forward.

@jonsequitur thank you, I was not aware. I'll keep that in mind. One of the F# formatting library's todo's is to allow generating documentation from a notebook, and your notebook parser could help with that.

Thanks!

**Comment by brettfo** [comment]
@nhirschey we published a new extension to our insiders channel, can you give it a shot to see if it fixes this issue?  You'll need to install [VS Code - Insiders](https://code.visualstudio.com/insiders/) and then install the extension like normal, it should automatically pick up the correct version, which should be 1.0.4108061.

**Comment by nhirschey** [comment]
@brettfo yes I checked docs from a few repos and it's fixed in the insiders version of VS Code. Thank you!
