### ISSUE TITLE
interactive.csharp.getVariable Property name is being changed

### ISSUE THREAD

**Issue by trmcnealy** [dotnet/interactive#269]
#### Describe the bug
When using interactive.csharp.getVariable, all the Property names are being changed to lower case.

If i use a Dictionary<string, object> or an type like:
```
public struct VegaViewData
{
    public string API  { get; set; }
    public double Day  { get; set; }
    public string Type { get; set; }
    public double Rate { get; set; }
}
```

the result is
```
api: "##-###-#####"​​​
day: 1​​​
rate: 280.51724137931035​​​
type: "Actual"​​​
Symbol(vega_id): 137048

```
I have to do this to fix it.
```
public struct VegaViewData
{
    [JsonProperty("API", NamingStrategyType = typeof(DefaultNamingStrategy))]
    public string API  { get; set; }
    [JsonProperty("Day", NamingStrategyType = typeof(DefaultNamingStrategy))]
    public double Day  { get; set; }
    [JsonProperty("Type", NamingStrategyType = typeof(DefaultNamingStrategy))]
    public string Type { get; set; }
    [JsonProperty("Rate", NamingStrategyType = typeof(DefaultNamingStrategy))]
    public double Rate { get; set; }
}
```

```
API: "##-###-#####"​​​
Day: 1​​​
Rate: 280.51724137931035​​​
Type: "Actual"​​​
Symbol(vega_id): 137048
```

#### Did this error occur while using dotnet interactive?
.NET Jupyter Notebook (microsoft.dotnet-interactive 1.0.115902)

#### Please complete the following:
 - OS
    - Windows 10
 - Browser 
    - Chrome & Edge
    - [ ] Safari
 - Frontend
    - Jupyter lab

**Comment by jonsequitur** [comment]
This is because we're using the same serializer settings that we use for other parts of the API, which is clearly unintuitive here.

So, related: How should we treat reference loops and other cases that might result in serialization errors?
