### ISSUE TITLE
Creating a blank new notebook doesn't work

### ISSUE THREAD

**Issue by pkese** [dotnet/interactive#2717]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [x] Linux (Please specify distro: `Ubuntu 22.04`)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code (`1.75.1`)
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

## Reproduction:

- open VS Code
- create a blank new notebook: `[Ctrl][Shift][p] + Polyglot notebook: create a blank new notebook`
- choose file type: `Create as .ipynb`
- choose language: C# (or any other)

Result
- Nothing works
- Notebook is started with Python kernel: ![image](https://user-images.githubusercontent.com/278492/218123301-faf48172-adf8-4fdb-8d16-ead750428b97.png)
- Developer tools are reporting bugs: ![image](https://user-images.githubusercontent.com/278492/218123174-a03ef932-635d-44fc-b4a7-2b618dd0e061.png)
- If I save that file and try to reopen it again, the same thing happens.

**Comment by pkese** [comment]
Here's the notebook that got created (I can't paste the .ipynb file into comment, so here's the content of the file):
```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "dotnet_interactive": {
     "language": "csharp"
    },
    "polyglot_notebook": {
     "kernelName": "csharp"
    }
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".NET (C#)",
   "language": "C#",
   "name": ".net-csharp"
  },
  "polyglot_notebook": {
   "kernelInfo": {
    "defaultKernelName": "csharp",
    "items": [
     {
      "aliases": [],
      "languageName": "csharp",
      "name": "csharp"
     }
    ]
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}```

**Comment by pkese** [comment]
Extension id is `ms-dotnettools.dotnet-interactive-vscode - v1.0.4102020`
Dotnet is `7.0.102`

**Comment by pkese** [comment]
I've noticed my version of extension is not the latest, so I downloaded .vsix file and tried to install it, but it failed to install.

```
> code --install-extension ms-dotnettools.dotnet-interactive-vscode-1.0.4109051.vsix 
Installing extensions...
(node:1317778) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Unable to install extension 'ms-dotnettools.dotnet-interactive-vscode' as it is not compatible with VS Code '1.75.1'.
Failed Installing Extensions: file:///home/pkese/Downloads/ms-dotnettools.dotnet-interactive-vscode-1.0.4109051.vsix
```

**Comment by pkese** [comment]
With `vscode-insiders` + `dotnet-interactive-vscode-1.0.4109051` everything appears to be working as expected.

**Comment by jonsequitur** [comment]
That's frustrating. Thanks for reporting. Is everything working now?

**Comment by pkese** [comment]
Interesting. :flushed:

Now it started working even in normal vscode (not just vscode-insiders).

That's the `!#about` (now that I can run it). Same version as before, but now it runs.
```
.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.410202+fce65bd557e21539f9eb0ba3f9c6a64300386c94
Library version: 1.0.0-beta.23102.2+fce65bd557e21539f9eb0ba3f9c6a64300386c94
Build date: 2023-02-03T01:38:36.0000000Z
https://github.com/dotnet/interactive
```
