### ISSUE TITLE
Journey sample not working due to Interactive.Extension.ImageSharp

### ISSUE THREAD

**Issue by marckruzik** [dotnet/interactive#2722]
### Describe the bug
I am trying to run the sample "Journey":

https://github.com/dotnet/interactive/tree/main/samples/notebooks/journey

The file [showcaseteacher.dib](https://github.com/dotnet/interactive/blob/main/samples/notebooks/journey/showcaseteacher.dib) starts by the following:
```
#r "nuget: Microsoft.DotNet.Interactive.Journey, *-*"
#r "nuget: Interactive.Extension.ImageSharp, *-*"
```

Which outputs:
```
**Installed Packages**
Interactive.Extension.ImageSharp, 1.0.36
Microsoft.DotNet.Interactive.Journey, 1.0.0-beta.23102.2

Loading extensions from `C:\Users\marck\.nuget\packages\interactive.extension.imagesharp\1.0.36\interactive-extensions\dotnet\Dotnet.Interactive.Extension.ImageSharp.dll`
Error: Failed to load kernel extension "KernelExtension" from assembly C:\Users\marck\.nuget\packages\interactive.extension.imagesharp\1.0.36\interactive-extensions\dotnet\Dotnet.Interactive.Extension.ImageSharp.dll
Error: Microsoft.DotNet.Interactive.KernelExtensionLoadException: Failure loading Kernel Extension
 ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.DotNet.Interactive.KernelCommandResult> Microsoft.DotNet.Interactive.KernelExtensions.SendAsync(Microsoft.DotNet.Interactive.Kernel, Microsoft.DotNet.Interactive.Commands.KernelCommand)'.
   at Dotnet.Interactive.Extension.ImageSharp.KernelExtension.OnLoadAsync(Kernel kernel)
   at Microsoft.DotNet.Interactive.PackageDirectoryExtensionLoader.LoadFromAssembly(Assembly assembly, Kernel kernel, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\PackageDirectoryExtensionLoader.cs:line 126
   --- End of inner exception stack trace ---
```

Is there a way to correct the journey sample so it will work? With a specific nuget version by example?
Or maybe the library Interactive.Extension needs to be updated? I see it's a repository from @colombod .

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
Version: 1.0.360602+9bf026dabac44a6256a65168fa93dcb7e2edcca4

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by colombod** [comment]
The bug seems to be in the image sharp library, will look at it asap. Can you open the issue over there?

**Comment by colombod** [comment]
Actually the issue is the notebook, the extension was rename to Image-Sharp.InteractiveExtension, I need to update the sample in the repo
