### ISSUE TITLE
HTML kernel name is duplicated in kernel picker: `html - html - HTML`

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#2723]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/547415/218526804-9bf4f1c2-db03-48ba-896b-7cec5eda9a09.png">

**Comment by ocallesp** [comment]
Hi @colombod , did you make a change for this issue ?

It seems that the behavior changed
![image](https://user-images.githubusercontent.com/510598/223173392-ca34cdb6-67a8-4a1c-aff0-9644646f2d45.png)

**Comment by colombod** [comment]
addressed with #2784
