### ISSUE TITLE
Kernel `vscode` should not appear in kernel picker

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#2724]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/547415/218527062-5ec1d7f8-c8eb-4d9c-b9f3-d8865e92afde.png">

**Comment by ocallesp** [comment]
I cannot repro this bug

![github-2723-cannot-repro](https://user-images.githubusercontent.com/510598/222249297-1b926895-29f0-4350-ae17-951c73e70870.gif)
