### ISSUE TITLE
splitting cell results in incorrect cell language

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#2762]
Steps to repro:

* Create a notebook with the default kernel of F#
* Create a cell and set the cell language to JavaScript
* Enter the following code into the cell:
  ```
  x = 1;
  console.log(x++);
  ```
* Put the cursor at the end of the first line.
* Trigger command `Notebook: Split cell`

Expected: 

* Two cells, both JavaScript

Actual: 

* Two cells, the first is JavaScript and the second is F#.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/547415/220477054-2968dca9-e711-4ca0-afb3-6c24403aa7c8.png">

Likely related: #2752

**Comment by AbhitejJohn** [comment]
Seems like a related issue to this [has been closed](https://github.com/dotnet/interactive/issues/2752#event-8653287294) perhaps by changes on the VS Code side. Does that mean this is addressed as well?

**Comment by jonsequitur** [comment]
This issue is still present.

**Comment by AbhitejJohn** [comment]
This has been addressed with https://github.com/dotnet/interactive/pull/2796
