### ISSUE TITLE
Add Docker Instructions

### ISSUE THREAD

**Issue by worldbeater** [dotnet/interactive#277]
**Is your feature request related to a problem? Please describe.**

Plenty of researches tends to run Jupiter Notebooks inside Docker containers. This allows folks to easily reproduce the results on different machines. Also, this makes the whole installation process much easier, as a user only has to type `docker build` and `docker run` to have the environment up and running.

**Describe  the solution you'd like**

The example of a `Dockerfile` and the related `Makefile` can be found in the [Keras](https://github.com/keras-team/keras) repo: https://github.com/keras-team/keras/tree/master/docker Those folks provide detailed instructions about how to use their library inside a Docker container with Jupiter Notebooks installed. A user only has to type `make notebook` and then immediately start their experiments.

Probably we could add docker-related instructions to the `How to Install .NET Interactive` section in readme https://github.com/dotnet/interactive#how-to-install-net-interactive Also, we could prebuild the docker image and upload it to [docker hub](https://hub.docker.com/).

Worth noting the [following line](https://github.com/keras-team/keras/blob/master/docker/Dockerfile#L79):
```Dockerfile
CMD jupyter notebook --port=8888 --ip=0.0.0.0
```

**Describe alternatives you've considered**

An alternative to Docker is [Vagrant](https://www.vagrantup.com/).

**Comment by colombod** [comment]
The command is already used as entry point docker run will just require you to map the port, then you can connect. is that working for you?

**Comment by worldbeater** [comment]
Thanks for sharing the `Dockerfile` and the samples! Can now confirm, that now the provided [samples and instructions](https://github.com/dotnet/interactive/blob/master/samples/docker-image/readme.md) work well. Further improvements could focus on providing a `Makefile` for Linux users, which could merge `build` and `run` docker commands into a single line e.g. `make notebook`, similar to https://github.com/keras-team/keras/blob/master/docker/Makefile#L24 However this is not as important. Thanks again!
