### ISSUE TITLE
'Detecting Kernels' never ends

### ISSUE THREAD

**Issue by ocallesp** [dotnet/interactive#2808]
### Describe the bug
Please provide as much information as you can.
Even if I uninstall and re-install this still says 'reload required'
![image](https://user-images.githubusercontent.com/510598/223631689-97f38394-11d1-45e7-a293-11433a39aae8.png)

![bug-not-loading-kernels](https://user-images.githubusercontent.com/510598/223631073-bda3c54a-9646-4de1-b6f4-16853ab6f9a3.gif)

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [X] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by AbhitejJohn** [comment]
Are we using Polyglot Notebooks kernel or is this Jupyter? I do not recognize the fly-out that pops up when you click on the "Detecting Kernels" message.

**Comment by ocallesp** [comment]
Something in the build was causing this issue.
