### ISSUE TITLE
Unable to retrieve data from SQL server

### ISSUE THREAD

**Issue by FCMTSoftware** [dotnet/interactive#2851]
### Describe the bug
I am trying to run SQL queries using the VS Code extension but keep on getting a exception when running the SQL statement. Tried with various databases and tables.

The exception is: 
Error: System.MissingMethodException: Method not found: 'Void Microsoft.DotNet.Interactive.Formatting.TabularData.TabularDataResource..ctor(Microsoft.DotNet.Interactive.Formatting.TabularData.TableSchema, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,System.Object>>>, System.String)'.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

Version: 1.0.360602+9bf026dabac44a6256a65168fa93dcb7e2edcca4
Library version: 1.0.0-beta.22606.2+9bf026dabac44a6256a65168fa93dcb7e2edcca4
Build date: 2023-03-20T09:25:45.2323986Z

- OS
    - [ ] Windows 11
    - [x ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/128373728/226319183-0647bd26-ff9a-4a6c-b3e1-340dd66bf08f.png)

**Comment by colombod** [comment]
can you run `#!about` and share the info?
this is what I am running (latest stable) 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/375556/226410232-9e74f1fc-a160-411a-b970-2853078ad078.png">


Then using latest mssql package from nuget (is the same you have)

![image](https://user-images.githubusercontent.com/375556/226410389-de86f66a-dd9f-4562-98d8-8023d3792543.png)

The mssl package on nuget org is built for the latest PolyglotNotebook extension

**Comment by FCMTSoftware** [comment]
This is the result from my #!about
![image](https://user-images.githubusercontent.com/128373728/226552754-cb6f3568-fa9a-458f-ba06-169bc9d961fa.png)

which seems to be an older version so I re-installed it and I still have the same version
