### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by mbrezu** [dotnet/interactive#2861]
### Describe the bug

Link https://github.com/dotnet/interactive/blob/main/src/dotnet-interactive/CommandLine/readme.md
(referred from https://github.com/dotnet/interactive/blob/main/docs/README.md) is dead.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
Thanks, @mbrezu! It's fixed. The updated link is here: https://github.com/dotnet/interactive/blob/main/docs/command-line-interface.md
