### ISSUE TITLE
Add a parameter for the environment name in the python connection string 

### ISSUE THREAD

**Issue by sharoncxu** [dotnet/interactive#2868]
**Is your feature request related to a problem? Please describe.**
Once users open VS Code from their anaconda command line, they cannot change it without closing VS Code, activating the right conda environment from the anaconda command line, and reopening VS Code

**Describe the solution you'd like**
With the addition of the parameter, users can switch between different environments after opening VS Code

**Comment by jonsequitur** [comment]
@sharoncxu Does this satisfy the requirement?

![Image](https://github.com/user-attachments/assets/33a12f3e-3354-44c9-80a0-6f3cf8f6ae52)

**Comment by sharoncxu** [comment]
@jonsequitur Yes it should! Let me test it out
