### ISSUE TITLE
Enable users to use python without opening VS Code from the anaconda command line

### ISSUE THREAD

**Issue by sharoncxu** [dotnet/interactive#2869]
**Is your feature request related to a problem? Please describe.**
I currently have to open VS Code from the anaconda command line to use python in polyglot notebooks which is quite tedious especially if I want to close and restart VS Code. It's also frustrating because I don't need to do this for any other language in polyglot notebooks nor any other file type.

**Describe the solution you'd like**
Enable python support by opening VS Code from the desktop

**Comment by shibbas** [comment]
Addressed with PR https://github.com/dotnet/interactive/pull/3184
