### ISSUE TITLE
NaN values are not properly sharable 

### ISSUE THREAD

**Issue by shibbas** [dotnet/interactive#2875]
### Describe the bug
Specifically when sharing NaN values where the EventEnvelope is used, the share or set results in an Error. See screenshot below for a repro. 

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/26466942/227383872-741e4be6-af2a-4c6c-a667-622a8cc9d4be.png)

**Comment by shibbas** [comment]
Basically, it's failing at the following step:
https://github.com/dotnet/interactive/blob/0de4474902dda125860622fd94d71481530727f1/src/Microsoft.DotNet.Interactive/Connection/KernelEventEnvelope.cs#L128

Because JsonDocument.Parse is failing to handle NaN values. E.g. run repro:

```csharp
using System.Text.Json;
var json = """{ "value" : NaN}""";
var element = JsonDocument.Parse(json).RootElement;
```

This is impacting the python value sharing as well. 

The Error returned is also not very informative, probably because this issue: https://github.com/dotnet/interactive/issues/2863

**Comment by jonsequitur** [comment]
What would be an appropriate value to deserialize to?

**Comment by shibbas** [comment]
> What would be an appropriate value to deserialize to?

Not sure if this is the correct way, but pandas.Dataframe.to_json converts them to nulls. https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html#pandas-dataframe-to-json
