### ISSUE TITLE
Upgrade to a 10.x version of Mermaid.js

### ISSUE THREAD

**Issue by IntegerMan** [dotnet/interactive#2899]
In trying to demo the Mermaid.js features of Polyglot Notebooks, I'm running into discrepancies between Polyglot Notebooks and the official Mermaid.js documentation, which seems to only reflect the current version (10.1.0 at the moment) instead of the configured version in `MermaidMarkdownFormatter.cs` of 9.1.7.

Because any invalid mermaid syntax causes a generic error display, this can lead to a frustrating user experience with mermaid code that matches the documentation and *should* work, but does not run on the version of mermaid that Polyglot uses. I've seen this particularly with `title` elements in various supported charts.

Additionally, using a more recent version of Mermaid gives us support for two new chart types:
- Mindmaps
- Timelines

I think both of these charts would demo well and help "wow" people at what's possible in Polyglot Notebooks and can personally see myself getting a lot of benefits out of Mindmaps in particular.

I'd like for us to upgrade from 9.1.7 to 10.1.0 or the latest stable version so we more accurately match the official documentation. This will reduce developer confusion and frustration and will enable a few more features. We also might want to consider a regular upgrade / update cadence for Mermaid.js in the future as this problem will likely recur.

**Comment by colombod** [comment]
Closing this issue as it is now available
