### ISSUE TITLE
Support running PowerShell code in a remote PSSession

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/interactive#290]
This issue is for tracking the implementation of `IHostSupportsInteractiveSession` members:
```c#
public bool IsRunspacePushed {.get; }
public Runspace Runspace { get; }
public void PopRunspace();
public void PushRunspace(Runspace runspace)
```
I looked into them more and think it's possible to support running code in a remote PSSession in the PowerShell kernel through the implementation of those members. The idea is to make `PushRunspace` and `PopRunspace` interact with the PowerShell kernel, in a similar way as what `Enter-AzShell` does (#286) -- set some state in the kernel and notify the kernel that subsequent code should be routed to the remote Runspace.

With this scenario and the Azure cloud shell integration, we will have 2 remote code run scenarios, which should give us enough references to design for a remote code run interface for the PowerShell kernel.

**Comment by brettfo** [comment]
Closing in favor of #2041.
