### ISSUE TITLE
Cannot #!import cs files

### ISSUE THREAD

**Issue by jsleep** [dotnet/interactive#2914]
### Describe the bug
Trying to use the semantic kernel project... The initial notebook has you import a relative path to a .cs file which is failing due to unrecognized extension...
Error: System.InvalidOperationException: Unrecognized extension for a notebook: .cs
   at Microsoft.DotNet.Interactive.Documents.InteractiveDocument.LoadAsync(FileInfo file, KernelInfoCollection kernelInfos) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.Documents\InteractiveDocument.cs:line 166
   at Microsoft.DotNet.Interactive.KernelExtensions.<>c__DisplayClass6_0`1.<<UseImportMagicCommand>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelExtensions.cs:line 98
--- End of stack trace from previous location ---

See screenshot below for further info.

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
Version: 1.0.360602+9bf026dabac44a6256a65168fa93dcb7e2edcca4

Library version: 1.0.0-beta.22606.2+9bf026dabac44a6256a65168fa93dcb7e2edcca4

Build date: 2023-04-12T20:59:31.6906037Z

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/6540938/231609579-427a6323-1129-493a-ba4b-15000daa5ea1.png)

**Comment by jonsequitur** [comment]
It looks like you're using a somewhat outdated version of Polyglot Notebooks. Can you check for any pending updates and try this again?

Some details on how to do this are here: https://github.com/dotnet/interactive/blob/main/docs/FAQ.md#troubleshooting

**Comment by jsleep** [comment]
Ah I thought I had the latest, but only once I installed the latest VSCode update, I saw updates available for Polyglot (as well as Jupyter) extensions and seems to properly import now. Thank you.
