### ISSUE TITLE
Polyglot Notebook: Using set for JavaScript doesn't work, but does work for C#

### ISSUE THREAD

**Issue by softchris** [dotnet/interactive#2944]
### Describe the bug

Using extension Polyglot Notebook in VS Code

When wanting the variable value from a previous cell, I should be able to retrieve it using `#!set`

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

## Actions to repeat

1. Create cell with JavaScript kernel
2. Give it the following content:

   ```javascript
   let jsname = "chris";
   jsname
   ```

1. Create another cell below with same kernel and give it the following content:

   ```javascript
   #!set --value @javascript:jsname --name jsname2

   console.log("Hello", jsname2);
   ```

   This renders "Hello null" 

   Note: works as intended using C#

## Screenshots

![Screenshot 2023-04-27 202541](https://user-images.githubusercontent.com/4598064/234972439-36c6603f-22ef-4ec7-af20-16b58ad86c33.png)

**Comment by colombod** [comment]
the problem is that for variables to be sharable from js they must be global declarations, the use of `var`, `let`, and `const` will cause them to be in the scope of the submission only. 

This code will work
```js
jsname = "chris";
jsname
```
```js
#!set --value @javascript:jsname --name jsname2

console.log("Hello", jsname2);
```
side by side case
<img width="378" alt="image" src="https://user-images.githubusercontent.com/375556/235110426-0d8b73fe-83ca-45ff-9b0d-88682cb221d6.png">

**Comment by softchris** [comment]
@colombod many thanks for this explanation
