### ISSUE TITLE
Polyglot Notebook: [DevExE2E][Regression] Fail to run F# code, with internal error "The thread is already executing the ControlledExecution.Run method."

### ISSUE THREAD

**Issue by v-hozha1** [dotnet/interactive#2945]
### Describe the bug
Using extension Polyglot Notebook in VS Code
[Regression] Fail to run F# code, with internal error "The thread is already executing the ControlledExecution.Run method."

**Note:** 
1.It's a regression issue. It doesn't repro on VSCode 1.77.3 + dotnet-interactive-vscode-1.0.4219021.vsix.
2.Repro VM: 172.16.195.186

**Steps:**
	1. Start with an empty text file open in VSCode
	2. Ctrl+Shift+P => ".NET Interactive: Create new blank notebook"
	3. Select "Create as .dib" ->Select "F#"
	4. In code, specify code: 1+1
	5. Execution cell

**Expected Results:**
Cell execution normally, with no error. 
![image](https://user-images.githubusercontent.com/100275240/235057223-62a55db8-8288-47cf-8438-a8a2c9215879.png)

**Actual Results:**
Fail to run F# code, with below internal error.
Error: input.fsx (1,1)-(1,1) interactive error internal error: The thread is already executing the ControlledExecution.Run method.
![image](https://user-images.githubusercontent.com/100275240/235057417-0ff4226d-7496-457d-8b5f-7fbb2e20d8c0.png)

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [√] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [√] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)
    
**Detailed Repro Build info:**  VSCode 1.77.3 + dotnet-interactive-vscode-1.0.4227011.vsix
VS Code Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

dotnet-interactive-vscode-1.0.4227011.vsix
build link: https://dev.azure.com/dnceng/internal/_build/results?buildId=2168897&view=artifacts&pathAsName=false&type=publishedArtifacts

sdk info: dotnet-sdk-7.0.203-win-x64.exe

**Comment by colombod** [comment]
This issue was addressed with pr #2953

**Comment by v-hozha1** [comment]
This issue has been fixed in VSCodeSetup-arm64-1.79.0-insider + dotnet-interactive-vscode-1.0.4259021.vsix.

Fixed screenshot:
![image](https://github.com/dotnet/interactive/assets/100275240/feb18ce0-3763-4114-84e9-01ad5a4a2947)
