### ISSUE TITLE
Polyglot Notebook: [DevExE2E] If unsaved and closing the .dib file, the execution errors still show in PROBLEMS page.

### ISSUE THREAD

**Issue by v-hozha1** [dotnet/interactive#2946]
### Describe the bug
Using extension Polyglot Notebook in VS Code
If unsaved and closing the .dib file, the execution errors still show in PROBLEMS page.

**Detailed Repro Build info:** VSCode 1.77.3 + dotnet-interactive-vscode-1.0.4227011.vsix
VS Code Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

dotnet-interactive-vscode-1.0.4227011.vsix
build link: https://dev.azure.com/dnceng/internal/_build/results?buildId=2168897&view=artifacts&pathAsName=false&type=publishedArtifacts

sdk info: dotnet-sdk-7.0.203-win-x64.exe

**Note:**
1.It's a not a regression issue. It also repro on VSCode 1.77.3 + dotnet-interactive-vscode-1.0.4219021.vsix.
2.Repro VM: 172.16.195.186

**Steps:**
1.  Start with an empty text file open in VSCode
2. Ctrl+Shift+P => "Polyglot Notebook: Create new blank notebook"
3. Select "Create as .dib" ->Select "F#"
4. In code, specify the incorrect code: prin("hello")
5. Execution cell
6. Close the created .dib file -> Don't save
7.Check the PROBLEMS page and double click the errors. 

**Expected Results:**
The errors should be disappeared in PROBLEMS page.

**Actual Results:**
If unsaved and closing the .dib file, the execution errors still show in PROBLEMS page.
![image](https://user-images.githubusercontent.com/100275240/235059185-1cbe7b22-b742-4b55-b21f-297c0b54acf5.png)

![Issue#5invalidateCode](https://user-images.githubusercontent.com/100275240/235058949-b53102ae-d083-43b9-8c78-d5ab04a221ef.gif)

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [√ ] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ √] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by colombod** [comment]
@rebornix do you have any suggestion?

**Comment by DonJayamanne** [comment]
In the component that is contributing the problems (diagnostic messages), you should be able to detect the file has been closed and then clear those problems
Thats what we used to do in Python extension as well, i.e. when notebook is closed, then clear the problems.

**Comment by DonJayamanne** [comment]
There are two APIs
* One for VS Code if not using a language server https://github.com/microsoft/vscode-jupyter/blob/refactorRemotes/src/standalone/intellisense/diagnosticsProvider.ts#L94
* If you are using a Language Server (that runs in a separte process), then the API will be different, basically listen to closed notebooks and return an empty list of diagnostics
@debonte might be able to help here

**Comment by debonte** [comment]
> If you are using a Language Server (that runs in a separte process), then the API will be different, basically listen to closed notebooks and return an empty list of diagnostics
@debonte might be able to help here

In Pylance we detect notebook closure via the [`notebookDocument/didClose`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#notebookDocument_didClose) LSP message (or [`textDocument/didClose`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didClose) for non-notebook documents). And then as part of our cleanup we send a [`textDocument/publishDiagnostics`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_publishDiagnostics) notification for each cell document with an empty `diagnostics` array.
