### ISSUE TITLE
May rough plan of work (2023)

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/interactive#2966]
- [x] #2885 @shyamnamboodiripad @jonsequitur 
- [x] #2967
- [x] #2965 @shyamnamboodiripad 
- [x] #2093 @ocalles @colombod
- [ ] #2854 @jonsequitur 
- [ ] #2855 @jonsequitur 
- [ ] #2078 
    - [ ] Plotting with Plotly
    - [ ] SQL
    - [ ] KQL
- [x] Cancellation & Scheduler efforts @jonsequitur @colombod 
- [ ] Fixing tests with Shibani @colombod 
- [x] #2946 @colombod 
------------------------ Stretch ----------------------
- [ ] #2631 @jonsequitur

**Comment by heartacker** [comment]
> @heartacker We put work into the monthly plan if we think we have capacity for it, plus some extra work that we see as higher priority, so we won't be able to get to this in May.
> 
> But if you're able to contribute, I'd be happy to help you put together a PR for it.

thank you, but I am not able to create PR because I can not code js/ts. I just know some c#
