### ISSUE TITLE
Create a command for adding a new cell or replacing the current code triggered from a kernel

### ISSUE THREAD

**Issue by shibbas** [dotnet/interactive#2971]
This is similar to [`get_ipython.set_next_input`.](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.interactiveshell.html#IPython.core.interactiveshell.InteractiveShell.set_next_input), but enable to create a code cell in any of the current languages. 

This allows the kernel to dynamically generate code in any language and add it to the notebook which would be helpful for generated code logics.

**Comment by jonsequitur** [comment]
This is partially supported today but needs some improvements.

![SendEditableCode](https://github.com/dotnet/interactive/assets/547415/ddd494aa-30e8-4fd6-9f1f-1af71c1994ca)

The limitations are:

* It can only add a cell, not edit an existing one.
* It always adds the cell at the end of the notebook. This probably isn't the right behavior when running a cell somewhere earlier in the notebook, and if the end of the notebook is scrolled out of view, then it's not apparent to the user that anything happened.

**Comment by jonsequitur** [comment]
Related: #2878.

**Comment by jonsequitur** [comment]
I'm going to close this issue. It's partially supported today via `SendEditableCode` as noted above. While this doesn't support replacing the content of an existing cell, the use case for that is less clear. A separate issue should be opened for that to expand on the use cases before we implement it.
