### ISSUE TITLE
Polyglot notebook stuck on Installing .NET Interactive version 1.0.425803...

### ISSUE THREAD

**Issue by SreeHarshaNelaturu** [dotnet/interactive#2984]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
1.0.425803+1db2979099d0272660e1497cae9b9af1238db42f
dotnet sdk 7.0.203 arm64
- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

I've installed, re-installed and tried everything possible on my end to ensure the right version of .NET SDK and dotnet-interactive is installed. Whenever I attempt to open a '.dib' file, it gives me the following error

![screenshot1](https://github.com/dotnet/interactive/assets/22708963/0b2b6698-e240-46bb-b788-06def4d7fb11)

And it remains in some sort of infinite download in the progress bar below like that never finishes.
![screenshot2](https://github.com/dotnet/interactive/assets/22708963/024f9ea8-840c-48a0-977e-b4b58d78fc03)

Both ```dotnet``` and ```dotnet interactive``` are in the path

I tried changing the version, modifying the required version to match the exact string provided by ```dotnet interactive --version``` to no avail.

My VSCode version is 1.78.2

Any help/suggestions in how to proceed to get this open/working would be great.

Thank you in advance!

**Comment by SreeHarshaNelaturu** [comment]
I'm not sure if its related -- but it finally worked after I installed Visual Studio Community and tried opening the .dib file, not sure if it was the remedy.

**Comment by prince-b-fg** [comment]
What help  me identify my issue was in the output window in vscode, select polyglot Notebook diagnosis from the drop down on the right. Mine ended up being because of authentication issues with a github source I added to my nuget package list. (Once I resolve that Ill update this thread with my out come
