### ISSUE TITLE
Refactor the VT100 sequence usage using 'System.CommandLine.Rendering'

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/interactive#299]
Refactor the PowerShell code to use `System.CommandLine.Rendering` for VT usage.
See the comment https://github.com/dotnet/interactive/pull/286#discussion_r394730068

**Comment by daxian-dbw** [comment]
@jonsequitur Can you please point me to the existing usage of `System.CommandLine.Rendering`? Thanks!

**Comment by jonsequitur** [comment]
Here's an example:

https://github.com/dotnet/interactive/blob/34b8d3ea6bf9dbae1135800c69d4549802a2b1e8/Microsoft.DotNet.Interactive/KernelExtensions.cs#L105-L111
