### ISSUE TITLE
Console.WriteLine appears to print previous calls to Console.WriteLine

### ISSUE THREAD

**Issue by istation-ed** [dotnet/interactive#3053]
### Describe the bug
Multiple Console.WriteLine calls are repeated as if each subsequent call prints the full stack.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ): v1.0.4313020

- OS
    - [x] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![image](https://github.com/dotnet/interactive/assets/98824731/3b523692-4821-4852-b456-c324c1060daf)

**Comment by jonsequitur** [comment]
I'm not able to reproduce this. Can you provide the complete code that was run leading up to this?

**Comment by istation-ed** [comment]
Hi Jon,

Thanks for looking into this.

I don't think it's the code that's creating the issue. I've zipped the file
and attached it to this email. I believe this started following the next
last update.

Thanks again,

--ed

[image: image.png]

**Comment by jonsequitur** [comment]
GitHub doesn't seem to include the attachment. Is the repro small enough to include the whole notebook in a screen shot?

**Comment by istation-ed** [comment]
Cell 1:
using System.Globalization;
using System.Text.RegularExpressions;

Cell 2:
Console.WriteLine(DateTime.Now.ToUniversalTime().ToString("O"));
Console.WriteLine(DateTime.UtcNow.ToString("O"));
Console.WriteLine(DateTime.UtcNow.ToString("s"));
Console.WriteLine(DateTime.UtcNow.ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffzzz",
CultureInfo.InvariantCulture));
string regexPattern =
@"^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$";

var timeString = DateTime.UtcNow.ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffzzz",
CultureInfo.InvariantCulture);
// sample from https://www.imsglobal.org/spec/lti-ags/v2p0#timestamp
Console.WriteLine("2017-04-16T18:54:36.736+00:00");
Console.WriteLine(timeString);
bool isMatch = Regex.IsMatch(timeString, regexPattern);
Console.WriteLine($"Match was {isMatch}");

Output:
2023-06-22T21:51:11.0987789Z
--
2023-06-22T21:51:11.0987789Z
2023-06-22T21:51:11.1014096Z
--
2023-06-22T21:51:11.0987789Z
2023-06-22T21:51:11.1014096Z
2023-06-22T21:51:11
--
2023-06-22T21:51:11.0987789Z
2023-06-22T21:51:11.1014096Z
2023-06-22T21:51:11
2023-06-22T21:51:11.101+00:00
--
2023-06-22T21:51:11.0987789Z
2023-06-22T21:51:11.1014096Z
2023-06-22T21:51:11
2023-06-22T21:51:11.101+00:00
2017-04-16T18:54:36.736+00:00
--
2023-06-22T21:51:11.0987789Z
2023-06-22T21:51:11.1014096Z
2023-06-22T21:51:11
2023-06-22T21:51:11.101+00:00
2017-04-16T18:54:36.736+00:00
2023-06-22T21:51:11.101+00:00
--
2023-06-22T21:51:11.0987789Z
2023-06-22T21:51:11.1014096Z
2023-06-22T21:51:11
2023-06-22T21:51:11.101+00:00
2017-04-16T18:54:36.736+00:00
2023-06-22T21:51:11.101+00:00
Match was True

I had to manually add the breaks above (--) to get it to look correct.

Again.. I don't think it has anything to do with the content. It's been
doing this on other notebooks.

Or do you have another email address I can send to?

Thanks,

--ed

**Comment by marckruzik** [comment]
I have the same problem.
.NET Interactive v1.0.4313020
VS Code v1.79.2

@istation-ed You can format your code (or output) using the "add code" button in the interface (with the `<>` icon). Paste your code, select it, and click on the "add code" button. You will see 3 characters looking like a simple quote before and after your code. You can check with the preview tab that everything looks ok.

**Comment by jonsequitur** [comment]
We still can't repro this. I tried it on a much slower machine where the cell execution took over 6 seconds and that didn't repro it.

Some other questions:

* Do you have multiple documents open at once?
* Do you have multiple panes open for the same document?
* Has the document been saved to disk?
* If so, which file extension was used?

**Comment by istation-ed** [comment]
I have several .md files open. Only a single doc active when working with
the .dib file. It's saved and on disk. After opening it up later..  same
issue.

Content of the .dib file below. Opened with sublime.

Thanks,

--ed

#!meta

{"kernelInfo":{"defaultKernelName":"csharp","items":[{"aliases":[],"name":"csharp"}]}}

#!csharp

using System.Globalization;
using System.Text.RegularExpressions;

#!csharp

Console.WriteLine(DateTime.Now.ToUniversalTime().ToString("O"));
Console.WriteLine(DateTime.UtcNow.ToString("O"));
Console.WriteLine(DateTime.UtcNow.ToString("s"));
Console.WriteLine(DateTime.UtcNow.ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffzzz",
CultureInfo.InvariantCulture));
string regexPattern =
@"^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$";

var timeString = DateTime.UtcNow.ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffzzz",
CultureInfo.InvariantCulture);
// sample from https://www.imsglobal.org/spec/lti-ags/v2p0#timestamp
Console.WriteLine("2017-04-16T18:54:36.736+00:00");
Console.WriteLine(timeString);
bool isMatch = Regex.IsMatch(timeString, regexPattern);
Console.WriteLine($"Match was {isMatch}");

**Comment by marckruzik** [comment]
I installed recently an extension which is causing the bug, this is Data Table Renderers.
https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-table
I uninstalled this extension and the bug disappeared.

**Comment by colombod** [comment]
interesting, I think that is probably because they register to many input types for rendering, including streams (stdio and stderr).

Would be worth opening the bug on the extension. Thank you very much for finding the root cause

**Comment by istation-ed** [comment]
Removing that Data Table works! Remember to restart!! :)

Thanks!

--ed
