### ISSUE TITLE
add support for Postgres

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#3056]
Add support for connecting Postgres subkernels via `#!connect`.

**Comment by NikiforovAll** [comment]
Hi @jonsequitur, any updates on this one?

**Comment by NikiforovAll** [comment]
Can I use it already?

Something like - `#!connect psql --kernel-name adventureworks \"{connectionString}\"`?

**Comment by jonsequitur** [comment]
I haven't published a package yet. I was going to give it a try before doing so.

Also, I missed this but would `#!connect postgres` make more sense?

**Comment by jonsequitur** [comment]
There should be packages available on the build feed here if you want to try it out: 

https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

**Comment by NikiforovAll** [comment]
> We haven't published a package on nuget.org yet. I was going to give it a try before doing so.
> 
> Also, I missed this but would `#!connect postgres` make more sense?

I think `psql` is OK because it resembles `psql` cli, kinda intuitive .

**Comment by luisquintanilla** [comment]
> > We haven't published a package on nuget.org yet. I was going to give it a try before doing so.
> > Also, I missed this but would `#!connect postgres` make more sense?
> 
> I think `psql` is OK because it resembles `psql` cli, kinda intuitive .

This is cool! Personally, since it's not using `psql` (or at least I didn't see it did from the PR), using `psql` might be confusing.

**Comment by jonsequitur** [comment]
I'm happy to make this change.

**Comment by NikiforovAll** [comment]
I'm wondering about syntax highlighting. Should we add it also?

**Comment by jonsequitur** [comment]
It would be nice to have. I would open another issue for that. It's a little complicated and our current solution isn't entirely satisfying.

**Comment by NikiforovAll** [comment]
Found a typo:

![Image](https://github.com/user-attachments/assets/36bda188-4bc3-4c6c-bca7-5c1d91d3a732)

**Comment by jonsequitur** [comment]
That should just work once you have a `TabularDataResource` or even just an `IEnumerable<T>`: https://github.com/colombod/dotnet-interactive-extension-lab/blob/7b8e09e82dfaa21b37688c4f3a5a292dc5cb47c3/src/SandDance.InteractiveExtension/ExploreExtensionsForSandDance.cs

Improving the ergonomics of getting data into those types could use some work in any case.
