### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Hoseinmj** [dotnet/interactive#3060]
Hi,

Can you provide us with an update on this topic ?

I use .NETFramework and cant use Kestrel, and I have the same problem. I need to identify my clients certificates as valid with the one stored on broker side.

Thanks for your feedback and code sample.

_Originally posted by @LouisCPro in https://github.com/dotnet/MQTTnet/issues/644#issuecomment-660201148_

**Comment by jonsequitur** [comment]
This appears to have been posted in the wrong repo.
