### ISSUE TITLE
Polyglot Notebooks extension should honor `FormattedValue.SuppressDisplay`

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#3079]
This property was added recently and isn't currently honored by the Polyglot Notebooks frontend.

The TypeScript definition should expose this property as optional, since it will very rarely be used.

**Comment by marckruzik** [comment]
It this a behavior close to the %%capture magic command (see #2570)?

**Comment by jonsequitur** [comment]
We're working out a design for that and they could be related, but I don't know that `#!capture` would rely on this feature. `SuppressDisplay` is intended just to suppress frontend display of some or all `FormattedValue` objects on a given event. The `FormattedValue` is still there and the events flow normally. It's there to allow kernels to return multiple formatted values when some are for UI while others are for data transfer across subkernels. 

`#!capture` (assuming we follow the spirit of the IPython `%%capture` magic) would prevent the events from flowing entirely, and optionally store them for later retrieval.

**Comment by marckruzik** [comment]
Thanks for the explanation!

**Comment by colombod** [comment]
I thought this line https://github.com/dotnet/interactive/blob/1a2a2d3c055bb5531bbba2c25cd77b7be994a861/src/polyglot-notebooks-vscode-common/src/interactiveClient.ts#L504 handles the suppression

**Comment by shyamnamboodiripad** [comment]
Yes, suppression is probably already handled - but it is cumbersome to have to always specify the parameter in the JavaScript API. I think we need a change in the code generation to make parameters that are optional in the C# API also optional on the JavaScript side somehow.
