### ISSUE TITLE
How do I get a table output?

### ISSUE THREAD

**Issue by mlaily** [dotnet/interactive#3085]
Following (I think) https://github.com/dotnet/interactive/pull/2671 (_change default HTML formatting to a tree layout rather than a table_), I can't find a way to get a simple table view of my data!

Instead, everything is foldable objects, even when the object is e.g. a simple record.

The only workaround I found is defining the html table manually with an html formatter as described in the `Formatting-outputs.ipynb` doc.

This is the output I get when I execute https://github.com/dotnet/interactive/blob/main/samples/notebooks/fsharp/Docs/Formatting-outputs.ipynb:

![image](https://github.com/dotnet/interactive/assets/1535823/57b930a2-ffc5-4da3-a14e-fd696e2c5cfe)

This is what I'm looking for:

![image](https://github.com/dotnet/interactive/assets/1535823/a971d0a8-776e-40f4-a9eb-4a73a6f2beaf)

### Question

How can I generate a table without resorting to manually crafting the html?

**Comment by jonsequitur** [comment]
We're planning to add an API for this. In the meantime there's a workaround described here: https://github.com/dotnet/interactive/discussions/3081#discussioncomment-6429156

**Comment by mlaily** [comment]
@jonsequitur ah thanks! Sorry I didn't see the discussion about this...
