### ISSUE TITLE
Take input from User in Polyglot

### ISSUE THREAD

**Issue by thekushalgaikwad** [dotnet/interactive#3101]
System: 
Windows 10
.NET 7

I want to take input from the user. what can I do? 
Program: Write a C# program in the notebook to get custom input from the user and test which datatype it is.
I am a beginner in C#.

![image](https://github.com/dotnet/interactive/assets/59055337/2b14fdb9-e1b3-427d-b34e-f5e20b54bb95)

**Comment by luisquintanilla** [comment]
Here's some documentation that can help here - https://github.com/dotnet/interactive/blob/main/docs/input-prompts.md
