### ISSUE TITLE
Closing and opening polyglot notebook in same VS Code session causes code to not be visible

### ISSUE THREAD

**Issue by wsmelton** [dotnet/interactive#3109]
### Describe the bug
1. Created a new Polyglot notebook (powershell)
2. Add a code cell
3. Run the code cell, output is visible
4. Close the notebook
5. Open it back up, code cell is not fully visible
6. Add new code cells or markdown and they full cell is not visible
7. Reload VS Code (insiders)
8. Open notebook again and code cell is visible again
9. Adding new cells then works as expected again too

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [x] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
Initial open of the notebook:

![image](https://github.com/dotnet/interactive/assets/11204251/c598796c-41f5-4efa-8de8-babceff8ec97)

In same VS Code Insiders session, close and reopen the notebook gives me this view:

![image](https://github.com/dotnet/interactive/assets/11204251/15f0622e-f3de-4a70-bb4b-e880f2ab5e95)

Code cell still executes though, and variables are seen populated:

![image](https://github.com/dotnet/interactive/assets/11204251/c10ad6f5-43ee-44b6-9f11-f63a56983f7f)

**Comment by jonsequitur** [comment]
This bug was caused by https://github.com/microsoft/vscode/issues/189109. A fix was made in Polyglot Notebooks to avoid the issue.
