### ISSUE TITLE
Jupyter Lab - Host getting stuck after executing Out-ConsoleGridView

### ISSUE THREAD

**Issue by MaximoTrinidad** [dotnet/interactive#311]
#### Describe the bug

Basically, executing the cmdlet Out-ConsoleGridView (OCGV) sends the results to where the Jupyter host is running.  

You can't use neither the "sec" key nor the OCGV "F9" key to clear it.

It will only execute the command once, then it get stuck.
Select .NET PowerShell notebook, and enter:
```
dir | ocgv
```
This works!

Enter a second command:
```
dir | select name | ocgv
```
At this time, .NET PowerShell stays "Busy" and won't process the command.

#### Did this error occur while using `dotnet interactive`?
- [PowerShell] .NET Jupyter Notebook 

#### Screenshots
(See attached Image)
![OCGV_01_2020-03-23_14-00-52](https://user-images.githubusercontent.com/19892435/77348945-aac28300-6d10-11ea-87b7-c4ba40bfcc0e.png)

#### Please complete the following:

Even after the update, I'm getting the same issue:
_Tool 'microsoft.dotnet-interactive' was successfully updated from version '1.0.116704' to version '1.0.117001'._

 - OS
    - [X] Windows 10
PS C:\Users\max_t> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
    - [ ] macOS
    - [X] Linux (Please specify distro) :
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Safari
 - Frontend
    - [ ] Jupyter notebook
    - [X] Jupyter lab
    - [ ] nteract

**Comment by TylerLeonhardt** [comment]
I don't see how we would be able to generically fix this. Even things like `vim` also cause the hang.

There isn't really a way AFAIK to signal to the executable that "this is not a real terminal"... the executable (or in your case, cmdlet `Out-ConsoleGridView`) needs to be smarter and say "am I being run in a real terminal".

Can you open this issue in https://github.com/PowerShell/GraphicalTools so we can get that fixed?

I think we should close this issue as "by-design"/"wont fix" since it's likely impossible.

**Comment by MaximoTrinidad** [comment]
Hi @TylerLeonhardt 

I'm just wondering if the ocgv would have the ability to use the "ESC" key instead of the long route of "F9" and click Yes to exit. Just something to think about.

I like the fact that I can use the ocgv in Notebook so I can save the image and paste it in the notebook file.

![OCGV_01_Jupyter_2020-03-24_13-17-18](https://user-images.githubusercontent.com/19892435/77456657-ea9d6f00-6dd1-11ea-9e3d-b5475d4c1c98.png)

It's a strange behavior... but, I would love to have it corrected! 
:)

**Comment by TylerLeonhardt** [comment]
We will be investigating an Out-GridView in Jupyter but we can't use Out-ConsoleGridView for this. It's a totally different technology stack.

**Comment by MaximoTrinidad** [comment]
Hey @TylerLeonhardt 

I forgot to mention.  I notice that the progress bar was displayed while doing an Install-Module. 

![ProgressBar_Jupyter_2020-03-19_19-28-57](https://user-images.githubusercontent.com/19892435/77474376-5ccf7d00-6ded-11ea-852c-e55c91b52373.png)

This is the reason why I try using the OCGV. 

:)

**Comment by TylerLeonhardt** [comment]
Understandable but progress and ocgv are rendered differently - progress is special cased to work in Jupyter.

Don't forget to open that issue in ocgv to protect against this.

**Comment by TylerLeonhardt** [comment]
I'm not really sure how .NET Interactive can get around this. It'd be the same behavior if you pop a GUI like with WPF or WinForms (or real `Out-GridView`). Considering the restart kernel is available to unblock users who get into that position, I think we can close this.

Plus, `Out-ConsoleGridView` has been fixed to warn you about running it in .NET Interactive.
