### ISSUE TITLE
Add HTTP as cell type

### ISSUE THREAD

**Issue by Regenhardt** [dotnet/interactive#3126]
**Is your feature request related to a problem? Please describe.**

I love how simple the .dib file is internally and now I'm bothered by how complicated it is to keep postman collections in sync with a dotnet solution and by how complicated the postman collection export is in a git diff.

**Describe the solution you'd like**

Add `.http` file functionality as a cell type to `.dib` files (don't know how the language/kernel would be called, I guess it's just plain HTTP because that's what the `.http` file contains?).

The result could either be rendered below the cell, or maybe we can find a way of putting it into a variable that contains the response as machine readable data for following cells (maybe `$return` for the last return value like C#, or `$0` like a browser console? This might be for another issue).

Variables of prior cells could be used in the `{{usualSyntax}}`, but in case of complex types it's complicated to choose what to do to convert it to a string that makes sense. Although I guess this could just be some [Object object] kind of broken as in this case a user can easily deconstruct the complex object to primitive objects in a prior cell.

**Describe alternatives you've considered**

Use C# in the `.dib` file to send requests but that is too much work compared to postman.

Use a dotnet test framework like MSTest to build E2E-Tests. This is quite complicated for quick iterations with the whole compilation and project structure and doesn't give me the same disconnect from the application where I can just call a webservice in the void and see what happens.

**Comment by jonsequitur** [comment]
Of possible interest: #3122.

You can get this functionality by installing the HTTP kernel from [this NuGet package](https://www.nuget.org/packages/Microsoft.DotNet.Interactive.HttpRequest). The linked PR and upcoming PRs in this area include a number of improvements to the experience. We're considering whether to make it one of the default kernels in the list out of the box.

**Comment by fravelgue** [comment]
Is it possible to get the HTTP response output in a variable too?

**Comment by jonsequitur** [comment]
Yes, that feature is coming.

**Comment by fravelgue** [comment]
@jonsequitur Do you know of any issue to follow up on?

**Comment by jonsequitur** [comment]
This is now supported but variable sharing isn't (yet). 

![image](https://github.com/dotnet/interactive/assets/547415/a0c03d06-e572-43df-a380-033455c8858d)

**Comment by frankenstein91** [comment]
@jonsequitur 
Are you able to fix https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode and remove HTTP Variable sharing?

**Comment by jonsequitur** [comment]
Variable sharing is intended to work for the HTTP kernel but there's a bug. (#3522)
