### ISSUE TITLE
.NET Editor will stack when use dynamic type variable and Console.WriteLine

### ISSUE THREAD

**Issue by gewarren** [dotnet/interactive#3134]
---
**Issue moved from MicrosoftDocs/feedback#3932**
- Please respond to @1234567Yang.

---

_From @1234567Yang on Wednesday, June 21, 2023 8:13:38 PM_

**Describe the bug**
.NET Editor will stack when use dynamic type variable and Console.WriteLine.
Example:
dynamic a = "1";
Console.WriteLine(a);

**To Reproduce**
1. Go to 'https://learn.microsoft.com/en-us/dotnet/csharp/how-to/parse-strings-using-split#code-try-0'
2. Open .NET Editor
3. Use both dynamic keyword and Console.WriteLine();
4. Click 'run'
5. See error

**Expected behavior**
The output will stack and continue loading.

**Screenshots**
![image](https://github.com/MicrosoftDocs/feedback/assets/113082249/a762511a-ee53-4eb6-a970-4d32022d2fcb)

**Desktop (please complete the following information):**
 - OS: Chromebook(Google Chrome OS Version 114.0.5735.119 (Official Build) (64-bit))
 - Browser: Chrome
 - Version 114.0.5735.119 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Not tested

**Additional context**
No.

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3932**
- Please respond to @jonsequitur.

---

_From @jonsequitur on Monday, August 14, 2023 6:25:41 PM_

dotnet/interactive is the appropriate repo for now. 

I'm guessing that `dynamic` doesn't work generally in the version of the Blazor WASM engine we're using. This may have been resolved in more recent versions of .NET's WASM support. If not, then dotnet/interactive will also not be the appropriate repo, but we can move it there and look into it.

**Comment by jonsequitur** [comment]
I can no longer repro this issue since the Try .NET update.
