### ISSUE TITLE
Command 'Polyglot Notebook: Create new blank notebook' resulted in an error

### ISSUE THREAD

**Issue by Robortor** [dotnet/interactive#3142]
### Describe the bug

- Having .NET SDK 7 already installed, I installed the Polyglot Notebook extension (v1.0.4403010) to VS Code (1.81.1).  

- When I try to create a new notebook from the **Command Palette:   Polyglot Notebook: Create new blank notebook, the Command 'Polyglot Notebook: Create new blank notebook' resulted in an error**

Polyglot Notebooks
v1.0.4403010

I closed VS Code, re-installed the .NET SDK and restarted VS Code,  alas, the error persisted.
 

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
- .NET Interactive
- © 2020 Microsoft Corporation
- Version: 1.0.350406+612aa40cba7d6a1f734272f71657a65561394752
- Library version: 1.0.0-beta.22504.6+612aa40cba7d6a1f734272f71657a65561394752
- Build date: 2022-10-15T09:10:39.8895914Z

- OS
    - [ ] Edition	Windows 10 Home
- Version	22H2
- Installed on	‎20/‎07/‎2020
- OS build	19045.3324
- Experience	Windows Feature Experience Pack 1000.19041.1000.0

 - Browser 
    - [ ] Edge
- Version 115.0.1901.203 (Official build) (64-bit)
    - [ ] Firefox 116.0.2 (32-bit)

 - Frontend
    - [ ] Jupyter Notebook (Anaconda 3, Python 3.7, 3.10)
    - [ ] Jupyter Lab
    - [ ] Visual Studio Code 
- Version: 1.81.1 (user setup)
- Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
- Date: 2023-08-09T22:22:42.175Z
- Electron: 22.3.18
- ElectronBuildId: 22689846
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0

- OS: Edition	Windows 10 Home Version 22H2   19045.3324
    - [ ] Visual Studio 2022, 2019, 2017

### Screenshots
![image](https://github.com/dotnet/interactive/assets/142629523/bf6b13bb-0c53-4012-bbdd-f106e19baeed)

### Workaround to get a Powershell interactive notebook (if Jupyter notebooks are working/Python is installed)
- read here: https://powershellisfun.com/2022/08/04/jupyter-notebooks-in-vscode-with-powershell-support/
- run: pip install powershell_kernel
- create a PS.ipynb
- set the interpreter/kernel to .NET (Powershell) for the respective code cells
- (the you can run the magic command successfully, though you don't need it anymore ;-) : In a notebook, run the `#!about` magic command.)

**Comment by jonsequitur** [comment]
This issue would be on the Polyglot Notebooks extension or VS Code end and would be unrelated to your .NET installation.

Do you have any pending VS Code or extension updates? These troubleshooting steps might help.

https://github.com/dotnet/interactive/blob/main/docs/FAQ.md#nothing-happens-when-running-a-cell

**Comment by Robortor** [comment]
Hi Jon
thanks for looking at this issue.

a) I am still unable to create a Polyglot notebook per Ctrl+Shift+p

b) I did have pending updates for c# extension, which I did update, alas to no avail (of course including closing and restarting VS Code).  That's why I kept searching for some kind of solution.  I eventually found the workaround I described at the end of my issue description.  Hence, I can create an .ipynb manually in which I am able to run c# code cells.

Best, Volker

**Comment by Robortor** [comment]
Actually, the workaround I found works for Powershell only.
Unable to select C# for a code cell.  When choosing Autodetect, the cell is set to C# but when run nothing happens <- in the manually created .ipynb.

(Still unable to create a new Polyglot notebook, which may wire up such that I may choose a C#/.Net kernel directly?)

Oh wait, if I select Jupyter first, C#.net may be offered upon clicking on Python in the code cell.  <- Weird,  very circumvent.  Will it still work in the next session?  Will I still remember next time?  There's got to be a direct way and still what about not being able to create a new Polyglot notebook?

**Comment by jonsequitur** [comment]
The workaround you posted is using a different kernel from .NET Interactive. 

> Oh wait, if I select Jupyter first, C#.net may be offered upon clicking on Python in the code cell. 

This will create a notebook targeting the Python kernel. 

When using the .NET Interactive kernel, you should see `.NET Interactive` in the upper right corner, which is the kernel selector for the notebook:

![image](https://github.com/dotnet/interactive/assets/547415/2a4af79d-7c53-4f7b-91e5-4ec9e9eb29cf)

Once you've created a Python notebook, are you able to click that kernel selector and select .NET Interactive by any chance?

**Comment by coosmiin** [comment]
I'm having the same issue. Just installed Polyglot Notebooks and I cannot create a new notebook:
![image](https://github.com/dotnet/interactive/assets/3222985/aa1e6f27-5d5e-4729-8679-5531d619f361)
And I also see this - it never ends:
![image](https://github.com/dotnet/interactive/assets/3222985/50ec36cc-2888-4265-ac81-77a9b22ce5ec)

**Comment by coosmiin** [comment]
In my case, the problem proved to be the nuget sources configured on my machine as explained here:
https://github.com/dotnet/interactive/issues/3233#issuecomment-1842657094

**Comment by balazs-ita-epam** [comment]
The issue still does exist with latest VS Code and .NET SDK 7 and 8. 
Please investigate.

**Comment by jonsequitur** [comment]
The .NET 9 SDK is now required. If you install .NET 9 and restart VS Code, do you still see the issue?

**Comment by balazs-ita-epam** [comment]
Yes, it does work with 9.

However, all the documentation of the exttension and MS Polyglott site recommends outdated information, .NET 7 and 8, see https://code.visualstudio.com/docs/languages/polyglot

MS should handle this, like "always the lates SDK@ or something...

Thanks anyway!

**Comment by HowardvanRooijen** [comment]
One of our devs hit this last week - he was surprised .NET 9 was the fix because of:

![Image](https://github.com/user-attachments/assets/3926476c-200b-428f-9a81-6b46c8be8846)

**Comment by jonsequitur** [comment]
Yeah, that confused a few people. That string change is basically just for error message documentation and probably shouldn't be present in settings at all, because changing it won't actually change which version of the .NET SDK .NET Interactive run on. 😕
