### ISSUE TITLE
Integration with JupyterHub (TLJH) Kernel always died (auto-restarting)

### ISSUE THREAD

**Issue by HoudayerPierre** [dotnet/interactive#318]
#### Describe the bug
Hello, I have a JupyterHub (TLJH) with JupyterLab installed, all behind a reverse HTTP/WebSocket proxy (python kernel works).
All Jupyter (C#, F# and powershell) kernels was installed and I can see them in the luncher tab.
If i open a notebook with a C# kernel the kernel seems to not start. If press the start button nothing is compiled and no output is shown.
After some time the kernel status is marked as autorestarting and a popup is shown.

#### Did this error occur while using `dotnet interactive`?
- [ ] .NET Jupyter Notebook 

#### Screenshots
![image](https://user-images.githubusercontent.com/12223438/77553312-f01fb580-6eb4-11ea-9334-da76fcac53fa.png)

![image](https://user-images.githubusercontent.com/12223438/77551701-f0b74c80-6eb2-11ea-94f7-a59a6480e6f8.png)

![image](https://user-images.githubusercontent.com/12223438/77553361-00379500-6eb5-11ea-8f89-9decea6feeaf.png)

#### Please complete the following:
 - OS
    - [ ] Windows 10
    - [ ] macOS
    - [X] Linux (Ubuntu 18.04)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome 80.0
    - [X] Firefox 74.0
    - [ ] Edge
    - [ ] Safari
 - Frontend
    - [X] Jupyter notebook
    - [X] Jupyter lab
    - [ ] nteract

**Comment by jonsequitur** [comment]
Does this still repro for you? Can you provide terminal output from `jupyter lab` when this happens?

**Comment by HoudayerPierre** [comment]
Yes it does.

I'm on Ubuntu 18.04.4 LTS (with JupyterHub TLJH) with JupyterLab Version 2.0.1

run `apt update && apt upgrade `
https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease

run : `journalctl -u jupyterhub -f`

```
mai 11 09:33:32 jupyterlab python3[956]: [I 2020-05-11 09:33:32.386 JupyterHub log:174] 200 GET /jupyterlab/hub/api/authorizations/token/[secret] (pitdu53@127.0.0.1) 186.25ms
mai 11 09:33:50 jupyterlab python3[956]: [I 2020-05-11 09:33:50.832 JupyterHub proxy:319] Checking routes
mai 11 09:33:51 jupyterlab python3[956]: [I 2020-05-11 09:33:51.499 JupyterHub log:174] 200 GET /jupyterlab/hub/api/users (cull-idle@127.0.0.1) 44.35ms
mai 11 09:34:51 jupyterlab python3[956]: [I 2020-05-11 09:34:51.551 JupyterHub log:174] 200 GET /jupyterlab/hub/api/users (cull-idle@127.0.0.1) 95.55ms
mai 11 09:35:51 jupyterlab python3[956]: [I 2020-05-11 09:35:51.590 JupyterHub log:174] 200 GET /jupyterlab/hub/api/users (cull-idle@127.0.0.1) 133.79ms
mai 11 09:36:53 jupyterlab python3[956]: [I 2020-05-11 09:36:53.471 JupyterHub log:174] 200 GET /jupyterlab/hub/api/users (cull-idle@127.0.0.1) 2009.04ms
mai 11 09:37:51 jupyterlab python3[956]: [I 2020-05-11 09:37:51.615 JupyterHub log:174] 200 GET /jupyterlab/hub/api/users (cull-idle@127.0.0.1) 159.29ms
mai 11 09:38:11 jupyterlab python3[956]: [I 2020-05-11 09:38:11.476 JupyterHub log:174] 200 POST /jupyterlab/hub/api/users/pitdu53/activity (pitdu53@127.0.0.1) 148.50ms
mai 11 09:38:50 jupyterlab python3[956]: [I 2020-05-11 09:38:50.833 JupyterHub proxy:319] Checking routes
mai 11 09:38:53 jupyterlab python3[956]: [I 2020-05-11 09:38:53.696 JupyterHub log:174] 200 GET /jupyterlab/hub/api/users (cull-idle@127.0.0.1) 2239.67ms
mai 11 09:39:51 jupyterlab python3[956]: [I 2020-05-11 09:39:51.889 JupyterHub log:174] 200 GET /jupyterlab/hub/api/users (cull-idle@127.0.0.1) 433.43ms
```

run : `journalctl -u jupyter-pitdu53`

```
mai 11 09:44:14 jupyterlab bash[8183]: [I 2020-05-11 09:44:14.204 SingleUserNotebookApp restarter:110] KernelRestarter: restarting kernel (1/5), new random ports
mai 11 09:44:14 jupyterlab bash[8183]: System.UnauthorizedAccessException: Access to the path '/home/jupyter-pitdu53/.dotnet/3.1.201.toolpath.sentinel' is denied.
mai 11 09:44:14 jupyterlab bash[8183]:  ---> System.IO.IOException: Permission denied
mai 11 09:44:14 jupyterlab bash[8183]:    --- End of inner exception stack trace ---
mai 11 09:44:14 jupyterlab bash[8183]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
mai 11 09:44:14 jupyterlab bash[8183]:    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
mai 11 09:44:14 jupyterlab bash[8183]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
mai 11 09:44:14 jupyterlab bash[8183]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
mai 11 09:44:14 jupyterlab bash[8183]:    at System.IO.File.Create(String path)
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.CreateEmptyFile(String path)
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Configurer.FileSystemExtensions.CreateIfNotExists(IFileSystem fileSystem, String filePath)
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Configurer.FileSentinel.Create()
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel as
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Cli.Program.Main(String[] args)
mai 11 09:44:14 jupyterlab bash[8183]: System.UnauthorizedAccessException: Access to the path '/home/jupyter-pitdu53/.dotnet/3.1.201.toolpath.sentinel' is denied.
mai 11 09:44:14 jupyterlab bash[8183]:  ---> System.IO.IOException: Permission denied
mai 11 09:44:14 jupyterlab bash[8183]:    --- End of inner exception stack trace ---
mai 11 09:44:14 jupyterlab bash[8183]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
mai 11 09:44:14 jupyterlab bash[8183]:    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
mai 11 09:44:14 jupyterlab bash[8183]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
mai 11 09:44:14 jupyterlab bash[8183]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
mai 11 09:44:14 jupyterlab bash[8183]:    at System.IO.File.Create(String path)
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.CreateEmptyFile(String path)
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Configurer.FileSystemExtensions.CreateIfNotExists(IFileSystem fileSystem, String filePath)
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Configurer.FileSentinel.Create()
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel as
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
mai 11 09:44:14 jupyterlab bash[8183]:    at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

The path /home/jupyter-pitdu53/.dotnet is under "chown -R 775" rights.

**Comment by jonsequitur** [comment]
Thanks, this is very helpful. 

The stack trace indicates that the error is happening in the telemetry setup, which creates a flag to keep track of whether we've sent install telemetry or you've opted out of telemetry reporting. A potential workaround (though it might fail for the same reason) would be to disable telemetry reporting by setting environment variable `DOTNET_TRY_CLI_TELEMETRY_OPTOUT` to `1`.

We should definitely avoid failing outright over this in any case. 

@wli3 @TIHan

**Comment by HoudayerPierre** [comment]
Hello,

I Have already set `DOTNET_CLI_TELEMETRY_OPTOUT="1"` in `/etc/environment` before.

Here is the content : 
```
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
GITLAB_URL="https://URL"
DOTNET_CLI_TELEMETRY_OPTOUT="1"
```

**Comment by TIHan** [comment]
@HoudayerPierre 

Another thing to try is setting this environment variable to "1":
`DOTNET_TRY_SKIP_FIRST_TIME_EXPERIENCE`

It's throwing on the first time user experience due to write permission to the .dotnet folder. That env variable should disable the first time experience, which is the welcome message about telemetry and an indication that any kind of permissions exist. This will also effectively disable telemetry as well.

**Comment by HoudayerPierre** [comment]
Hello,

I added this to `/etc/environment` like this :
`DOTNET_TRY_SKIP_FIRST_TIME_EXPERIENCE="1"`

But if i do in the console of jupyter : 
`printenv`
I dont see this environment variable.

If i do this same in the server console : 
```
echo $DOTNET_TRY_SKIP_FIRST_TIME_EXPERIENCE
1
```
So it's working in the server console. How did you add a environment variable in jupyter maybe it's here the problem.

**Comment by fockez** [comment]
I add DOTNET_TRY_SKIP_FIRST_TIME_EXPERIENCE="1" and set DOTNET_TRY_CLI_TELEMETRY_OPTOUT=1 in Dockerfile, the ENV at bottom of Dockerfile. But still get docker crash when using with JupyterHub

**Comment by wli3** [comment]
Could you try to set `DOTNET_CLI_HOME` to somewhere writable? Many functionality in .net core SDK require a disk space to write to.

**Comment by HoudayerPierre** [comment]
The problem is still here :(

**Comment by fockez** [comment]
No luck with the DOTNET_CLI_HOME, and every time it crashes, it cause all the other containers exit

**Comment by jonsequitur** [comment]
@HoudayerPierre Could you post the output of the following commands:

```console
> dotnet --info
> dotnet interactive --version
```

Thanks.

**Comment by HoudayerPierre** [comment]
Output from a jupyter terminal.

**The first one :** `> dotnet --info`
`SDK .NET Core (reflétant tous les global.json) :
 Version:   3.1.401
 Commit:    39d17847db

Environnement d'exécution :
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.401/

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  3.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download`

**The second one very interesting :** `> dotnet interactive --version`
`System.UnauthorizedAccessException: Access to the path '/home/jupyter-pitdu53/.dotnet/3.1.401.toolpath.sentinel' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.CreateEmptyFile(String path)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.CreateIfNotExists(IFileSystem fileSystem, String filePath)
   at Microsoft.DotNet.Configurer.FileSentinel.Create()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)`

**Comment by jonsequitur** [comment]
That is interesting!

@wli3 Does this ring any bells?

**Comment by wli3** [comment]
This is strange `3.1.401.toolpath.sentinel` should follow DOTNET_CLI_HOME

**Comment by HoudayerPierre** [comment]
Recently upgrade to `3.1.402-1`, using root in the server console : 
```
**root@jupyterlab:~# dotnet --info**
SDK .NET Core (reflétant tous les global.json) :
 Version:   3.1.402
 Commit:    9b5de826fd

Environnement d'exécution :
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download



**root@jupyterlab:~# dotnet interactive --version**

Bienvenue dans .NET Core 3.1 !
---------------------
Version du kit SDK : 3.1.402

----------------
Consultez la documentation : https://aka.ms/dotnet-docs
Signalez des problèmes et recherchez du code source sur GitHub : https://github.com/dotnet/core
Découvrez les nouveautés : https://aka.ms/dotnet-whats-new
Découvrez l'installation du certificat de développeur HTTPS : https://aka.ms/aspnet-core-https
Utilisez 'dotnet --help' pour voir les commandes disponibles, ou accédez à https://aka.ms/dotnet-cli-docs
Écrivez votre première application : https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
_Impossible d'effectuer l'exécution, car la commande ou le fichier spécifié est introuvable._
Raisons possibles :
  * Vous avez mal orthographié une commande dotnet intégrée.
  * Vous aviez l'intention d'exécuter un programme .NET Core, mais dotnet-interactive n'existe pas.
  * Vous aviez l'intention d'exécuter un outil global, mais l'exécutable portant le nom indiqué précédé de dotnet est introuvable dans le CHEMIN.
```
_Impossible d'effectuer l'exécution, car la commande ou le fichier spécifié est introuvable._
>> unable to run the command or file not found.

**Comment by jonsequitur** [comment]
If you run `dotnet tool list -g` what does it show?

**Comment by HoudayerPierre** [comment]
`(base) jupyter-pitdu53@jupyterlab:~$ dotnet tool list -g`
```
System.UnauthorizedAccessException: Access to the path '/home/jupyter-pitdu53/.dotnet/3.1.402.toolpath.sentinel' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.CreateEmptyFile(String path)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.CreateIfNotExists(IFileSystem fileSystem, String filePath)
   at Microsoft.DotNet.Configurer.FileSentinel.Create()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by piskernik** [comment]
I have a similar problem using the TLJH with dotnet interactive. Phyton works as expected. The kernel can not be started (and thus C# code cannot be executed). The access problem above is however not showing. Any ideas, what I can test in addition?
 
Result from `sudo journalctl -u jupyter-user -f`
```
[I 2020-11-08 19:01:30.877 SingleUserNotebookApp restarter:110] KernelRestarter: restarting kernel (4/5), new random ports
Could not execute because the specified command or file was not found.
Possible reasons for this include:
   * You misspelled a built-in dotnet command.
   * You intended to execute a .NET Core program, but dotnet-interactive does not exist.
   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[W 2020-11-08 19:01:33.890 SingleUserNotebookApp restarter:100] KernelRestarter: restart failed
```
Result from `jupyter kernelspec list`
```
Available kernels:
  python3               /opt/tljh/user/lib/python3.7/site-packages/ipykernel/resources
  .net-csharp           /home/jupyter-user/.local/share/jupyter/kernels/.net-csharp
  .net-fsharp           /home/jupyter-user/.local/share/jupyter/kernels/.net-fsharp
  .net-powershell       /home/jupyter-user/.local/share/jupyter/kernels/.net-powershell
  python-environment    /usr/local/share/jupyter/kernels/python-environment
```
Result from `dotnet tool list -g`
```
Package Id                        Version         Commands          
--------------------------------------------------------------------
microsoft.dotnet-interactive      1.0.148003      dotnet-interactive
```

Result from `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.403/

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Result from `dotnet interactive --version`
```
1.0.148003+8db7ff4b2bd09c703e7d5dc39d8adb9899d5e5c7
```

**Comment by jonsequitur** [comment]
Can you try again with the most recent version?

**Comment by piskernik** [comment]
All tools are the newest versions as of Nov. 8th 2020. I used `dotnet tool install -g --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" Microsoft.dotnet-interactive`. For the kernel spec I also gave the absolute path to dotnet, which didn't help. I also tried to turn on --verbose and the log-path, which didn't work either. Maybe the HTTP ports of the Traefik Proxy does not match (just guessing). At least the traefik log records a 504 Gateway timeout.

**Comment by HoudayerPierre** [comment]
Just ran `apt update && apt upgrade`.
`dotnet-sdk-3.1 (3.1.404-1)`
But no kernel start.

**Comment by jonsequitur** [comment]
@piskernik Can you run `dotnet-interactive` directly, e.g. `dotnet interactive --version`?

**Comment by piskernik** [comment]
I also updated dotnet to the most current version.
`dotnet interactive --version` works and results in `1.0.148003+8db7ff4b2bd09c703e7d5dc39d8adb9899d5e5c7`. So no new version available since Nov. 8th (in the feed I use, at least).
Just for completeness this is the log from traefik (removed IP Adress, address and username), Just scroll sideways to see everything.
```
heisenberg traefik[14605]: {"BackendAddr":"127.0.0.1:43877","BackendName":"backend__2Fuser_2Fpisker","BackendURL":{"Scheme":"http","Opaque":"","User":null,"Host":"127.0.0.1:43877","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"ClientAddr":"<REMOVED_BY_POSTER>:60410","ClientHost":"<REMOVED_BY_POSTER>","ClientPort":"60410","ClientUsername":"-","DownstreamContentSize":15,"DownstreamStatus":504,"DownstreamStatusLine":"504 Gateway Timeout","Duration":45000618636,"FrontendName":"frontend__2Fuser_2Fuser","OriginContentSize":15,"OriginDuration":45000503532,"OriginStatus":504,"OriginStatusLine":"504 Gateway Timeout","Overhead":115104,"RequestAddr":"<REMOVED_BY_POSTER>","RequestContentSize":0,"RequestCount":15617,"RequestHost":"<REMOVED_BY_POSTER>","RequestLine":"GET /user/user/api/kernels/92ed7b67-8b49-4403-9f3d-be136dcce124/channels?session_id=4dddecb0-60b4-4b09-8839-b8cc71d69eeb HTTP/1.1","RequestMethod":"GET","RequestPath":"/user/user/api/kernels/92ed7b67-8b49-4403-9f3d-be136dcce124/channels?session_id=4dddecb0-60b4-4b09-8839-b8cc71d69eeb","RequestPort":"-","RequestProtocol":"HTTP/1.1","RetryAttempts":0,"StartLocal":"2020-11-11T06:54:42.89812371+01:00","StartUTC":"2020-11-11T05:54:42.89812371Z","level":"info","msg":"","request_Cache-Control":"no-cache","request_Connection":"Upgrade","request_Cookie":"REDACTED","request_Origin":"https://<REMOVED_BY_POSTER>","request_Pragma":"no-cache","request_Sec-Websocket-Extensions":"x-webkit-deflate-frame","request_Sec-Websocket-Key":"lBqdi5XiDAjmfPSxX77kDg==","request_Sec-Websocket-Version":"13","request_Upgrade":"websocket","request_User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15","time":"2020-11-11T06:55:27+01:00"}
```
Here is the kernel.json (`--verbose` didn't help unfortunately).
```
{
  "argv": [
    "dotnet",
    "interactive",
    "jupyter",
    "--verbose",
    "--default-kernel",
    "csharp",
    "--http-port-range",
    "1000-3000",
    "{connection_file}"
  ],
  "display_name": ".NET (C#)",
  "language": "C#"
}
```
So the ports from traefik and the http-port-range do not match, but I'm not sure, if this is really the problem.

**Comment by jonsequitur** [comment]
A newer version was published a few days ago, though I think it's unlikely to fix the issue.

You can see additional logs by also setting the `--log-path` option in your command line args.

**Comment by jonsequitur** [comment]
A few other experiments to try:

* Change your `kernel.json` args from `"dotnet", "interactive"` to `"dotnet-interactive"`.

* Change your `kernel.json` args to use the fully-qualified path to `dotnet-interactive.exe`, e.g. `~/.dotnet/tools/dotnet-interactive.exe`

* Try installing `dotnet-interactive` to a different location using the `--tool-path` option. (I'm wondering if JupyterHub is lacking rights to the current install location, which might explain why it works fine when you start `dotnet-interactive` directly by JupyterHub doesn't find it.)

**Comment by piskernik** [comment]
I tried it also, however no log was generated. Somehow the kernel can start `dotnet` (hence the error message from dotnet) but not the `dotnet interactive` part. I also tried already to put in `dotnet-interactive`, but it didn't help unfortunately.

**Comment by jonsequitur** [comment]
FYI, not the difference in error messages:

![image](https://user-images.githubusercontent.com/547415/98830199-fab0a000-23ee-11eb-967c-c991958e949c.png)

Anyway this smells like a rights issue for JupyterHub.

**Comment by piskernik** [comment]
This worked for me:
Change your kernel.json args to use the fully-qualified path to dotnet-interactive.exe:
I used `/home/jupyter-user/.dotnet/tools/dotnet-interactive` with `user` as my username in Jupyter.

Thanks for your help!

**Comment by piskernik** [comment]
BTW: `.dotnet`, `tools` and `dotnet-interactive` are owned by and are in the group of `jupyter-user`.
Should it be root?

**Comment by wli3** [comment]
@piskernik root permission are not required. dotnet-interactive should have the access to `.dotnet`, and  `tools` directories
