### ISSUE TITLE
Polyglot Notebook: [DevExE2E] [Regression] The editor could not be opened due to an unexpected error with notebook editor type 'polyglot-notebook'.

### ISSUE THREAD

**Issue by v-hozha1** [dotnet/interactive#3181]
### Describe the bug
**Detailed Build info:**  **VSCodeSetup-x64-1.82.2 + dotnet-interactive-vscode-1.0.4468021.vsix + dotnet-sdk-7.0.401**
Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:51:09.788Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT arm64 10.0.22621

dotnet-interactive-vscode-1.0.4468021.vsix 
build link: https://dev.azure.com/dnceng/internal/_build/results?buildId=2270236&view=artifacts&pathAsName=false&type=publishedArtifacts

**Note:** It's a regression issue. It doesn't repro on - VSCodeSetup-x64-1.82.0 + dotnet-interactive-vscode-1.0.4461041.vsix .
It repro for both x64 and ARM64 VM.

**Steps:**
1. download file from https://github.com/dotnet/interactive/blob/main/NotebookTestScript.dib
2. Open the file in VSCode.

**Expected Results:**
The NotebookTestScript.dib file should be opened normally.

**Actual Results:**
The editor could not be opened due to an unexpected error: Cannot open resource with notebook editor type 'polyglot-notebook'.
![image](https://github.com/dotnet/interactive/assets/100275240/1840caca-6f3a-48dc-a955-def61ca016bd)

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [√] Windows 11
    - [√ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [√ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by AbhitejJohn** [comment]
@colombod : Do you have any thougths on why this could be broken?

**Comment by pkese** [comment]
I'm seeing the same error.
I went through Menu / Polyglot Notebook: Create New Blank Notebook / F# and when opening the notebook, I get the above error.

The notebook contains:
```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "dotnet_interactive": {
     "language": "fsharp"
    },
    "polyglot_notebook": {
     "kernelName": "fsharp"
    }
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".NET (F#)",
   "language": "F#",
   "name": ".net-fsharp"
  },
  "polyglot_notebook": {
   "kernelInfo": {
    "defaultKernelName": "fsharp",
    "items": [
     {
      "aliases": [],
      "languageName": "fsharp",
      "name": "fsharp"
     }
    ]
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

**Comment by jonsequitur** [comment]
I haven't been able to repro it. The fact that the "Installing..." might point to a race condition.

**Comment by v-hozha1** [comment]
I still encounter this issue on fresh VMs with today's new build.
VSCodeSetup-x64-1.82.2  https://code.visualstudio.com/download#
dotnet-interactive-vscode-1.0.4469041.vsix  https://dev.azure.com/dnceng/internal/_build/results?buildId=2271583&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by v-hozha1** [comment]
This issue doesn't repro on VSCodeSetup-x64-1.83.1 + dotnet-interactive-vscode-1.0.4514021.vsix.

Version: 1.83.1 (system setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.25398
