### ISSUE TITLE
Display input forms in the cell output

### ISSUE THREAD

**Issue by sharoncxu** [dotnet/interactive#3194]
Related to #992 
For all input forms where users have to enter multiple fields, display the form in the cell output

**User Scenario**
When the user runs the `#!connect `command to connect to a new kernel, any inputs will be displayed as a form in the cell output which they can enter values into and submit
![image](https://github.com/dotnet/interactive/assets/17832870/fa6bab02-18ea-4021-9e9b-6449d6ead019)

**Comment by jonsequitur** [comment]
Related: #35

**Comment by jonsequitur** [comment]
This work depends on #3567.
