### ISSUE TITLE
#r nuget loads unlisted packages

### ISSUE THREAD

**Issue by nhirschey** [dotnet/interactive#3204]
### Describe the bug

I did not expect that `#r "nuget: ..."` with an unqualified version to load unlisted packages. Does it make sense to load unlisted versions?

For example, the current maximum listed version of FSharp.Data.Fred is [0.1.0](https://www.nuget.org/packages/FSharp.Data.Fred/#versions-body-tab), but there is an unlisted version 1.0.0 that was accidentally published. It's unlisted, so I wouldn't expect `#r "nuget: FSharp.Data.Fred"` to load it. I'd expect it to load the maximum listed 0.1.0 version. But it loads 1.0 

### Please complete the following:

Version: 1.0.446104+34cc09c68f37568da9c8151ba5c51d264d0375d5

Library version: 1.0.0-beta.23461.4+34cc09c68f37568da9c8151ba5c51d264d0375d5

Build date: 2023-09-17T09:55:38.4483953Z

### Screenshots
![image](https://github.com/dotnet/interactive/assets/5226115/ef0f2b0a-0967-481e-bcdd-4e868c82b485)

**Comment by jonsequitur** [comment]
That is a bit surprising but I don't think this is something that .NET Interactive can control, as it's just running `dotnet restore` on a (hidden) project file using a package reference without a version specified. 

When a package is unlisted in NuGet it's hidden from search but can still be restored.

**Comment by nhirschey** [comment]
Ok, thanks for looking into it. 

It's a low probability edge case regardless. I'll close given it's not under your control.
