### ISSUE TITLE
Outdated info in VSCode extension readme

### ISSUE THREAD

**Issue by ShalokShalom** [dotnet/interactive#3208]
Hi :)

You did seem to have updated Python and R here at the Github README, as they are not marked as previews anymore. 

In the Extension description, it is still described as such: 

https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode

**Comment by crazy4pi314** [comment]
Are there any limitations still with the Python support or is that fully implemented?

**Comment by ShalokShalom** [comment]
It seems it has been fixed in the Marketplace description, so I assume yes.
