### ISSUE TITLE
'ms-dotnettools.dotnet-interactive-vscode' wants API proposa l 'languageConfigurationAutoClosingPairs' but that proposal DOES NOT EXIST

### ISSUE THREAD

**Issue by bpasero** [dotnet/interactive#3221]
Seeing this error when starting VS Code on Windows:

```
Via 'product.json#extensionEnabledApiProposals' extension 'ms-dotnettools.dotnet-interactive-vscode' wants API proposa
l 'languageConfigurationAutoClosingPairs' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (c
heck 'vscode.d.ts') or was abandoned.
```

**Comment by Oerroot** [comment]
This is my warning:

> `[warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-dotnettools.dotnet-interactive-vscode' wants API proposal 'languageConfigurationAutoClosingPairs' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
>  [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot-chat' wants API proposal 'terminalContextMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.`

I have no idea because i just uninstalled all the extentions

**Comment by EricYoung37** [comment]
Same here when trying to install an extension

**Comment by AbhitejJohn** [comment]
@colombod : Would this be addressed with our most recent release?

**Comment by colombod** [comment]
yes it was addressed in most recent release

**Comment by stevenh** [comment]
Still seeing this today, what should I check to ensure I'm on a release that fixes this?

**Comment by Kenan7** [comment]
same issue and I can't even find ms-dotnettools extensions in my extension folder

**Comment by colombod** [comment]
Is there a clear repro step? @rebornix can you help us with this issue?

**Comment by vgianferrari** [comment]
This same problem started to appear to me a few days ago after installing version 1.84.2 of 2023-11-09.
So it seems to be still an open problem...
