### ISSUE TITLE
Javascript hangs

### ISSUE THREAD

**Issue by bwong365** [dotnet/interactive#3245]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
Actually could not get the `#!about` command to work...
![image](https://github.com/dotnet/interactive/assets/42486090/3ac90e4c-4aa6-42b8-9808-14c7fea9469c)
Extension indicates v1.0.4509030. I have uninstalled and reinstalled it to check if my setup was faulty; no effect.

- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [x] macOS (Sonoma)
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
Javascript cells seem to hang infinitely. I have been able to get this cell to trigger maybe 1/10 times, with each time:
1. Restart VS Code
2. Create new blank Polyglot notebook
3. Add a JS cell, or use JS by default
4. Try to execute code in the JS cell

![image](https://github.com/dotnet/interactive/assets/42486090/87bf88b5-afce-4e7d-9deb-d1e9b2ef4e59)

I am able to reproduce this issue (and the one re: `!#about`) with Windows 11 via Parallels (completely fresh VSC install), and a machine running MacOS Ventura as well.

I am **unable** to reproduce either of the issues when running the previous release - `Version: 1.0.446104+34cc09c68f37568da9c8151ba5c51d264d0375d5`

**Comment by colombod** [comment]
New release done, js bug is address. will open one to track the `#!about`

**Comment by shyamnamboodiripad** [comment]
A fix for the above hang was merged in #3268 and a release with this fix was just released. Could you please confirm that this works now?

The `#!about` issue should also be fixed now (via #3252).

**Comment by shyamnamboodiripad** [comment]
Awesome - thanks much for confirming!
