### ISSUE TITLE
Polyglot Notebook: [DevExE2E][Regression] After stopping the cell, no variable is shown in POLYGLOT NOTEBOOK: VARIABLES page. 

### ISSUE THREAD

**Issue by v-hozha1** [dotnet/interactive#3261]
### Describe the bug
After stopping the cell, no variable is shown in POLYGLOT NOTEBOOK: VARIABLES page. 

**Note:** It's a regression issue. It doesn't repro on - VSCodeUserSetup-arm64-1.81.1 + dotnet-interactive-vscode-1.0.4454011.vsix + dotnet-sdk-7.0.400-win-x64.

**Detailed Repro Build info:**  _VSCodeSetup-x64-1.83.1 +dotnet-interactive-vscode-1.0.4514021.vsix+ dotnet-sdk-7.0.402-win-x64_

VS Code: https://update.code.visualstudio.com/1.83.1/win32-x64/stable
Version: 1.83.1 (system setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.25398

dotnet-interactive-vscode-1.0.4514021.vsix
Build link: https://dev.azure.com/dnceng/internal/_build/results?buildId=2291238&view=artifacts&pathAsName=false&type=publishedArtifacts

**Steps:**
1. Open the notebook from https://github.com/dotnet/interactive/blob/main/NotebookTestScript.dib.
2. Execute the 3rd scenario -> Stop the cell
    using System.Threading.Tasks;
using Microsoft.DotNet.Interactive;

var output = string.Empty.Display("text/plain");
var counter = 1;
while (!KernelInvocationContext.Current.CancellationToken.IsCancellationRequested)
{
    await Task.Delay(500, KernelInvocationContext.Current.CancellationToken);
    output.Update($"{counter++}");
}

**Expected Results:**
After stopping the cell, variables "output", "counter" should be shown in POLYGLOT NOTEBOOK: VARIABLES page.
![image](https://github.com/dotnet/interactive/assets/100275240/f9ff190a-4733-482c-8ecd-ff63c6c6e9a9)

**Actual Results:**
After stopping the cell, no variable is shown in POLYGLOT NOTEBOOK: VARIABLES page.
![image](https://github.com/dotnet/interactive/assets/100275240/1ce01c98-2708-468e-8910-1ee4bed39e8f)

### Please complete the following:
**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [√] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [√] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
I'm not able to repro this.

**Comment by v-hozha1** [comment]
I still repro this issue on VS Code 1.85.1 + dotnet-interactive-vscode-1.0.4611011.vsix + dotnet-sdk-8.0.100. 

![image](https://github.com/dotnet/interactive/assets/100275240/45d222cb-7130-45da-bdf7-2a22d5a18a4c)

**Comment by v-hozha1** [comment]
This issue doesn't repro on VS Code 1.93.1 + dotnet-interactive-vscode-1.0.5468011.vsix + dotnet-sdk-8.0.401-win-x64. Hence closing it.

![image](https://github.com/user-attachments/assets/ac9ed517-ab7e-4327-a9b1-7cff1ab30a41)
