### ISSUE TITLE
Can run a Code section once, but if changes are made it hangs when run again.

### ISSUE THREAD

**Issue by nat1craft** [dotnet/interactive#3264]
### Describe the bug
Similar to this issue but more specific: #3262 

1. `Create` a new notebook (.jpynb)
2. `Add` a code section (this example is JavaScript, but the same occurs for C#)
3. Add some valid logic to the code block

```
 x = 1;
console.log(x);
```

5. Click either `Run All` or `Run` (upper-left next to the Code block)
6. Note the code runs fine and output is visible
7. Do it again. Not necessary, but note it runs fine successive times. 
8. Make a change to the code block. Such as this new code (note the value changed)

```
 x = 2;
 console.log(x);
```

10. `Save` (or do not save) the document. The bug behavior is still the same.
11. Click either `Run All` or` Run` (upper-left next to the Code block) 
12. Note the block **seems** to run but actually "hangs" (shows the "running" animations) but never comes back to show the results.

Aside:
13. `Exit` out of VS Code
14. Re-run VS Code
15. Click either `Run All` or `Run` (upper-left next to the Code block)
16. The changed code actually runs fine (no error)... until you modify the code block again.

My Observations:
- This occurs every time (not an intermittent problem)
- Same behavior for JavaScript and C# code blocks (possibly other languages)
- The "hang" behavior doesn't ever stop or "eventually come back". 
- You have to exit out of VS Code completely and re-load VS Code to get the code block to run again

POLYGLOT Notebooks:  v1.0.4514020

VS CODE
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22635

- OS
    - [ ] Windows 11
 - Browser 
    - [ ] Chrome
    - [ ] Edge
 - Frontend
    - [ ] Visual Studio Code 

Running the block:

![block run](https://github.com/dotnet/interactive/assets/6864673/d0185466-2cca-45fb-bcc4-4b5960c6f731)

Successful Result:

![block run success](https://github.com/dotnet/interactive/assets/6864673/32f1f08d-aa69-432c-a00d-d4528a0b00e8)

Modified, Saved, and Run Again : Hangs
![block hang](https://github.com/dotnet/interactive/assets/6864673/e83231f8-8f98-462f-b4ff-f22fa3ecad6f)

**Comment by colombod** [comment]
A new release has been pushed out to address this, can you confirm ?

**Comment by nat1craft** [comment]
Sorry for the late reply. Seems to be fixed! Awesomesauce.
