### ISSUE TITLE
Custom Notebook Renderer Support in dib Files

### ISSUE THREAD

**Issue by AnWeber** [dotnet/interactive#3288]
**The package and version I'm asking about**: 
latest of today: 1.0.451701+e231cd6f4a395b6f74568c5ad95a15cbecb85cf2

### Question
I have written a custom renderer [httpbook-monacorenderer](https://github.com/AnWeber/httpbook-monacorenderer) for markdown output This is unfortunately used in dib files for displaying the markdown. I actually don't see any flaw and possibility in my definition of notebook renderer to prevent this. But with dib files it is not offered to me to change the output renderer either. How can I solve this problem?

```dib
#!meta

{"kernelInfo":{"defaultKernelName":"csharp","items":[{"aliases":[],"languageName":"csharp","name":"csharp"}]}}

#!markdown

## foo

```

![renderer_select](https://github.com/dotnet/interactive/assets/13434739/2b6da923-9936-430a-ac97-af46f351f683)

https://github.com/AnWeber/httpbook-monacorenderer/issues/8

**Comment by colombod** [comment]
console methods produce very specific mimetypes (stream) to use text/markdown create a  function that need to publish the a display event.

```js
printMarkDown = (a) => {
    let context = polyglotNotebooks.KernelInvocationContext.current;
    context.publish(new polyglotNotebooks.KernelEventEnvelope( 
        polyglotNotebooks.DisplayedValueProducedType, 
        { formattedValues: [ { mimeType: "text/markdown", value: a} ]},
        context.commandEnvelope));   
}
```

This is how it would work:


![Image](https://github.com/dotnet/interactive/assets/375556/3401b374-3e90-474b-8601-f9014ff1510f)

**Comment by AnWeber** [comment]
@colombod Unfortunately, that was not the question.. With the display in the ipynb I just wanted to show that my renderer supports `text/markdown`. My problem is that the renderer is used to render code cells in `dib` files, although it is defined as OutputRenderer (code cell is not output). Additionally, the [data property of NotebookCellOutputItem](https://github.com/microsoft/vscode/blob/519c8072f38520095d1636fa9cc1d70b18287002/src/vs/workbench/api/common/extHostTypes.ts#L3673) is not text/markdown as the mime actually pretends, which causes the renderer to display empty content.
For me, [the mime is supposed to describe the content of the data object](https://code.visualstudio.com/api/extension-guides/notebook#rich-output), and Polyglot Notebook doesn't take it too seriously here and does not hand over custom mime. Am I wrong there?

**Comment by colombod** [comment]
That object model is vscode notebook api, that is how cells and elements of the notebook UI are implemented. Polyglot Notebooks and .NET interactive do not do anything beyond producing events with formatted values and their mime type. 
The dib format is a text file format and doesn't store outputs.

**Comment by AnWeber** [comment]
@colombod thanks for your help
