### ISSUE TITLE
Issues once .net 8 is installed.

### ISSUE THREAD

**Issue by realparadyne** [dotnet/interactive#3339]
### Describe the bug
I have a simple script and it stops working once .net 8 is installed.  See screenshot below.

It is able to reference a nuget package and download it, getting the latest .net 8 version of it by default.

But then is unable to load the package.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
v1.0.4562010

- OS
    - [*] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [*] Linux (Ubuntu WSL 20.04)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [*] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

![image](https://github.com/dotnet/interactive/assets/2536830/78c33fbc-8685-4ff9-9069-969025b4a2b5)

**Comment by colombod** [comment]
With latest Polyglotnotebook extension I am not able to repro the issue

![Image](https://github.com/dotnet/interactive/assets/375556/b6301fec-5367-4080-83c7-0b05dd98e435)
