### ISSUE TITLE
Wont run under .NET 8

### ISSUE THREAD

**Issue by TheUdK** [dotnet/interactive#3343]
### Describe the bug
Notebook wont load under .NET 8 and is expecting .NET 7.

VS Code diagnostic output:
```shell
Tool 'microsoft.dotnet-interactive' (version '1.0.456201') was successfully installed. Entry is added to the manifest file /Users/hodm/Library/Application Support/Code/User/globalStorage/ms-dotnettools.dotnet-interactive-vscode/.config/dotnet-tools.json.
Started process 17730: dotnet tool run dotnet-interactive -- notebook-parser
process 17730 stderr: You must install or update .NET to run this application.

App: /Users/<user>/.nuget/packages/microsoft.dotnet-interactive/1.0.456201/tools/net7.0/any/Microsoft.DotNet.Interactive.App.dll
Architecture: arm64

process 17730 stderr: Framework: 'Microsoft.NETCore.App', version '7.0.0' (arm64)
.NET location: /opt/homebrew/Cellar/dotnet/8.0.0/libexec/

The following frameworks were found:
  8.0.0 at [/opt/homebrew/Cellar/dotnet/8.0.0/libexec/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=arm64&rid=osx-arm64&os=osx.13
```

Tried switching to pe-release. Under prerelease .NET interactive version wont install. Seems to be looking for a version that is not present on repo.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

.NET version: `8.0.100`
.NET Interactive version: `1.0.456201`

- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by kojo12228** [comment]
Upgrading to version `1.0.460602` does set the runtime to .NET 8, but breaks loading F# scripts and using new F# 8 features for me:

<img width="921" alt="image" src="https://github.com/dotnet/interactive/assets/36001967/885edb20-a546-4a6a-aee3-d6e59ab1fb9c">

When I try to `#load` a `.fsx` reference file that previously used to run in 3-6 seconds, it completely hangs (I assume for the same reason as above).

**Comment by kojo12228** [comment]
> When I try to `#load` a .fsx reference file that previously used to run in 3-6 seconds, it completely hangs (I assume for the same reason as above).

After removing new F# 8 language features and restarting both VSCode and kernel I was able to load the `reference.fsx` generated by Ionide. So I guess the internal FsAutoComplete needs to be updated.

**Comment by colombod** [comment]
@KevinRansom can we have a look at this? @vzarytovskii might need some help

**Comment by vzarytovskii** [comment]
That particular issue on screenshot above will be fixed in future versions of FCS.

**Comment by TheUdK** [comment]
> we released .NET8 support earlier this week, can you try?

Seems to work now with .NET8. Thanks
