### ISSUE TITLE
REPL console application

### ISSUE THREAD

**Issue by jbaron** [dotnet/interactive#335]
Often I want to try out quickly a few lines of C# code to interactively inspect the result of some library. Right now I could either start a notebook or a debug session in Visual Studio (Code).

But it seems most building blocks are already in place to **have a simple REPL application** (console app). IMHO would be a great addition to the current set of interactive tools. This would also support cases where people use interactively .Net over SSH or other terminal type of connections.

P.S Love the current set of interactive tooling, great addition for doing more discovery type of development often encountered in data science.

**Comment by jonsequitur** [comment]
This is built with .NET Interactive though isn't part of the product: https://github.com/jonsequitur/dotnet-repl.

Thoughts?

**Comment by jbaron** [comment]
Looks very nice indeed and seems to fit my needs, thanks!!!
