### ISSUE TITLE
Docs on .dbi

### ISSUE THREAD

**Issue by ShalokShalom** [dotnet/interactive#3378]
Hi :)

I think I can remind, that you had docs on dbi and its benefits to .ipynb, but I seem to be wrong about that. 

Maybe I missed it, but it seems not that easy to find. 
Even in the internet in general and also the AI doesnt know about it. 

Is dbi intended to by used by the general jupyter community, or is this only used within Microsoft?
Since it deserves a more prominent spot, in case you hope for adoption. 

Wonderful day

**Comment by jonsequitur** [comment]
I think you're referring to the .dib file extension. You can see more information about it here: https://github.com/dotnet/interactive/blob/main/docs/FAQ.md#whats-the-difference-between-a-dib-file-and-an-ipynb-file
