### ISSUE TITLE
System.Net.Http.Json not recognized

### ISSUE THREAD

**Issue by Expecho** [dotnet/interactive#3386]
### Describe the bug

After loading System.Net.Http.Json the assembly is not loaded:

    #r "nuget:System.Net.Http.Json"
    using System.Net.Http.Json;

results in 

> The type or namespace name 'Json' does not exist in the namespace 'System.Net.Http' (are you missing an assembly reference?)

This happened as soon as I installed the latest version of Polyglot Notebooks in VS code requiring .Net 8.

Seems the same as [this issue](https://github.com/dotnet/interactive/issues/1406)

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

![image](https://github.com/dotnet/interactive/assets/11960665/a425449c-465c-4604-b474-950663467071)

- OS
    - [x] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![image](https://github.com/dotnet/interactive/assets/11960665/7792c7c9-c479-4fc0-b225-9214e636ee98)

**Comment by rob-nice** [comment]
I've also experienced this issue.

My workaround was to downgrade the Polyglot notebook version to 1.0.456201 which worked as expected.

**Comment by mjamesharmon** [comment]
I'm seeing this issue as well.  I  wrote an extension method as a work around for `ReadFromJsonAsync`:

```csharp
public static async Task<T> ReadJsonAsync<T>(this HttpContent response  ){
			return await response.ReadAsStringAsync().
				ContinueWith<T>(s=>JsonSerializer.Deserialize<T>(s.Result));
		}
```

**Comment by yueyinqiu** [comment]
new news about this?

**Comment by jonsequitur** [comment]
This doesn't work because System.Text.Json.Http is a framework assembly. If you use `#r` without the `nuget` prefix it will work:

```csharp
#r "System.Net.Http.Json"
using System.Net.Http.Json;
```

**Comment by Expecho** [comment]
Thanks!
