### ISSUE TITLE
How to change the default data visualization way to the way which earlier version has?

### ISSUE THREAD

**Issue by ingted** [dotnet/interactive#3402]
### Question
Several months ago, with ```Polyglot Notebooks v1.0.3611020```
The tuple (or many other stuffs) would look like this:
![image](https://github.com/dotnet/interactive/assets/4289161/7d5728a5-1f9c-47c5-8a2a-f6f61f89a17c)

However it becomes looking like this with ```Polyglot Notebooks v1.0.5054021```

![image](https://github.com/dotnet/interactive/assets/4289161/89cca13e-f1ad-48cb-b507-2d217d5c8fdf)

How could we configure it to show stuffs in grid view instead of expandable list?

**Comment by jonsequitur** [comment]
For enumerable types, you can use the `DisplayTable` extension method. This isn't available for single instances but you can always wrap a single instance in an array to use it.

<img width="276" alt="image" src="https://github.com/dotnet/interactive/assets/547415/839119a8-9278-4907-b66c-6267f3d2c600">

**Comment by ingted** [comment]
Cool!! Thank you so much!!
