### ISSUE TITLE
Wrong intellisense on variable member [FSharp]

### ISSUE THREAD

**Issue by Dreambound131** [dotnet/interactive#346]
#### Describe the bug
While writing code inside cell is possible to call code completion with Tab key, but this feature doesn't work well with variables and instances members. Instead of showing accessible members it complete with a Note tag. If then you press tab again, this time you get initial set of code completion, still missing the variable's members.
I noticed this behaviour both on local kernel and online with Binder.
Locally I have tried both with jupyter and jupyter lab getting the same behaviour.
If it can help I think that IfSharp has a smooth working intellisense (although it only works on jupyter notebooks and not on Jupyter Lab)

#### Did this error occur while using `dotnet interactive`?
- [x] .NET Jupyter Notebook 

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari
 - Frontend
    - [x] Jupyter notebook
    - [x] Jupyter lab
    - [ ] nteract

**Comment by jonsequitur** [comment]
We've started working on improving Intellisense for all front-ends.

**Comment by colombod** [comment]
Addressed in PR #625
