### ISSUE TITLE
Opening dib file never loads

### ISSUE THREAD

**Issue by onionhammer** [dotnet/interactive#3507]
### Describe the bug
Woke up this morning, and for some reason dib files wont open; even brand new empty ones[

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
Cant run it because it wont load

- OS
    - [*] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [*] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [*] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

![image](https://github.com/dotnet/interactive/assets/969938/95e3b85a-c145-4591-ad33-ca8a76cde465)

![image](https://github.com/dotnet/interactive/assets/969938/93201bb3-4351-4053-8e7a-c994fb3ae151)

![image](https://github.com/dotnet/interactive/assets/969938/72db3893-3ae1-4e8a-a6d0-abb8e4e001ab)

![image](https://github.com/dotnet/interactive/assets/969938/2c3cd2ca-556d-4131-8086-0e001faaefb2)

**Comment by onionhammer** [comment]
This appears to conflict with dev drives

https://learn.microsoft.com/en-us/windows/dev-drive/#storing-package-cache-on-dev-drive

**Comment by onionhammer** [comment]
> Or are you only seeing the issue when using a dev drive?

I am. I switched the NUGET_PACKAGES  env var from the dev drive, and it started working again

**Comment by jonsequitur** [comment]
That's very likely a NuGet issue. You might verify that by seeing if the same package reference and NuGet path works for an ordinary project.

**Comment by onionhammer** [comment]
Everything else works; dotnet global tools all work, dotnet build/restore etc work, just .NET interactive doesn't (for me). Have you reproduced this?
