### ISSUE TITLE
Failed to install tool package ...

### ISSUE THREAD

**Issue by Calicedetabarnac** [dotnet/interactive#352]
#### Describe the bug
I'm trying to install Microsoft.dotnet-interactive tool but have this issue, I tried the following commands

>dotnet tool install --global Microsoft.dotnet-interactive
>dotnet tool install --global Microsoft.dotnet-interactive --version 1.0.110520
>dotnet tool install --global Microsoft.dotnet-interactive --version 1.0.115407
>dotnet tool install --global dotnet-interactive
>dotnet tool install --global dotnet-interactive --version 1.0.115407

Failed to install tool package 'microsoft.dotnet-interactive': Could not find a part of the path 'C:\\Users\\*\\.dotnet\\tools\\.store\\.stage\\10gaxnri.bop\\microsoft.dotnet-interactive'.
Tool 'microsoft.dotnet-interactive' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

Any idea?
Thank you

#### Did this error occur while using `dotnet interactive`?
- [x] .NET Jupyter Notebook 

#### Screenshots
N/A

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Safari
 - Frontend
    - [ ] Jupyter notebook
    - [ ] Jupyter lab
    - [ ] nteract

**Comment by wli3** [comment]
Is the error actually says `C:\Users*.dotnet` with a star in it (instead of you edited our your name)?

If so, the error might be caused by setting a non exists `DOTNET_CLI_HOME` or `USERPROFILE` environment variable

**Comment by Calicedetabarnac** [comment]
Hi,
No it's my name there, the path is good until 10gaxnri.bop where this folder is not created
Thank you

**Comment by jonsequitur** [comment]
The correct tool name to install is `Microsoft.dotnet-interactive`. Have you tried uninstalling that and also, if you previously installed it as `dotnet-interactive`, that as well?

**Comment by Calicedetabarnac** [comment]
Hi jonsequitur, non of the installed worked, I've just ran the uninstalled followed by the installed
> dotnet tool uninstall --global Microsoft.dotnet-interactive
    A tool with the package Id 'microsoft.dotnet-interactive' could not be found.
    
    Tools are uninstalled using their package Id which may be different
    from the tool name you use when calling the tool. You can find the tool names
    and the corresponding package Ids for installed tools using the command
    'dotnet tool list'.

> dotnet tool install --global Microsoft.dotnet-interactive
    Failed to install tool package 'microsoft.dotnet-interactive': Could not find a part of the path 'C:\Users\Bob\.dotnet\tools\.store\.stage\f5rj3bwr.h5d\microsoft.dotnet-interactive'.
    Tool 'microsoft.dotnet-interactive' failed to install. This failure may have been caused by:
    
    * You are attempting to install a preview release and did not use the --version option to specify the version.
    * A package by this name was found, but it was not a .NET Core tool.
    * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
    * You mistyped the name of the tool.
    
    For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by jonsequitur** [comment]
Did you try `dotnet tool uninstall --global dotnet-interactive`?

**Comment by Calicedetabarnac** [comment]
> Did you try `dotnet tool uninstall --global dotnet-interactive`?

> dotnet tool uninstall --global dotnet-interactive

A tool with the package Id 'dotnet-interactive' could not be found.

Tools are uninstalled using their package Id which may be different
from the tool name you use when calling the tool. You can find the tool names
and the corresponding package Ids for installed tools using the command
'dotnet tool list'.

**Comment by wli3** [comment]
@jonsequitur you move this issue to dotnet/sdk.

I did get several bug report have similar problem. But I could never repro it. I suspect something to do with antivirus scan or race condition on IO access

**Comment by wli3** [comment]
This issue was moved to dotnet/sdk#11459
