### ISSUE TITLE
Subscribe to an Observable.Timer, No output at all

### ISSUE THREAD

**Issue by hjy1210** [dotnet/interactive#3526]
**The package and version I'm asking about**: 
Polyglot Notebooks extension v1.0.5208010

### Question
Execute the cell with content:
```
using System.Reactive.Linq;
var timer = Observable.Timer(TimeSpan.FromSeconds(1));
timer.Subscribe(
    x=> Console.WriteLine($"get {x}"), 
    () => Console.WriteLine("completed"));
```
No ouput at all, only a check symbol appeared with message 1.3s, see image below.

![Polyglot_question](https://github.com/dotnet/interactive/assets/7498709/69379bdd-d1d0-4a4e-9883-715eee54d7a4)

**Comment by jonsequitur** [comment]
This is a little unintuitive but it's working as intended. What's happening is that the cell execution completes before the 1 second has elapsed, and kernel events from that cell execution longer get published.

You can see the output if you prevent the cell execution from completing so quickly:

![image](https://github.com/dotnet/interactive/assets/547415/2378f7b2-0558-492f-9d3e-bfe39fe00e91)

**Comment by hjy1210** [comment]
@jonsequitur 
Thanks a lot.

**Comment by jonsequitur** [comment]
@hjy1210 You're welcome!
