### ISSUE TITLE
Add support for DuckDB

### ISSUE THREAD

**Issue by rdjonsson** [dotnet/interactive#3560]
Since there seems to already be support for sqlite, something similar seems possible for DuckDB? Polyglot notebooks could really use DuckDB's great file I/O capabilities for data wrangling tasks. I may even try to add it myself, but only if someone with knowledge about the ins and outs of the codebase can tell me that it is straightforward.

**Comment by colombod** [comment]
Have a look at this repo : https://github.com/colombod/dotnet-interactive-extension-lab, this the duck db extension https://github.com/colombod/dotnet-interactive-extension-lab/tree/main/src/DuckDB.InteractiveExtension

**Comment by rdjonsson** [comment]
Thanks! I'll take a look, when I get some time!

**Comment by rdjonsson** [comment]
It works great! The documentation is sparse but everything you need to get it to work can be found in the example notebook.
https://github.com/colombod/dotnet-interactive-extension-lab/blob/main/samples/duckDb.dib

**Comment by jonsequitur** [comment]
I'm reopening this since the linked solution is being pulled into this repo and the package will be republished under a different name.

**Comment by jonsequitur** [comment]
The updated package name is `Microsoft.DotNet.Interactive.DuckDB`. It will be released to nuget.org with the next release of Polyglot Notebooks to VS Code stable.

**Comment by rynoV** [comment]
It seems the issue was trying to run the `#r "nuget: Microsoft.DotNet.Interactive.DuckDB, *-*"` in an F# block instead of a C# block, with a C# block it works thanks!
