### ISSUE TITLE
Problem for dotnet installation

### ISSUE THREAD

**Issue by Vanzinafan954** [dotnet/interactive#36]
I use Windows 7 and when I try to install dotnet interactive on my computer's ordinary console, this message shows up:

error NU1101: Il pacchetto dotnet-interactive non è stato trovato. Non esistono pacchetti con questo ID nelle origini: nuget.org
Non è stato possibile ripristinare il pacchetto dello strumento.
Non è stato possibile installare lo strumento 'dotnet-interactive'.  

What can I do ?

**Comment by jonsequitur** [comment]
Please reopen if there's still an issue.
