### ISSUE TITLE
Upgrade to Microsoft.ML, 1.5.0-preview2 causes Jupyter notebook to fail

### ISSUE THREAD

**Issue by CBrauer** [dotnet/interactive#361]
#### The following Screenshot shows the error messages:
![image](https://user-images.githubusercontent.com/1317234/80314092-18e0e680-87a4-11ea-9ab4-a4cca11e8571.png)

#### My environment is the following:
 - OS is Windows 10, build 18363.815
 - Browser is Edge 
- Frontend is Jupyter notebook

#### I have run the following commands:
```
>dotnet tool list -g
Package Id                        Version          Commands
---------------------------------------------------------------------
dotnet-try                        1.0.19553.4      dotnet-try
microsoft.dotnet-interactive      1.0.122501       dotnet-interactive
mlnet                             0.15.1           mlnet

>jupyter kernelspec list
Available kernels:
  .net-csharp        C:\Users\Charles\AppData\Roaming\jupyter\kernels\.net-csharp
  .net-fsharp        C:\Users\Charles\AppData\Roaming\jupyter\kernels\.net-fsharp
  .net-powershell    C:\Users\Charles\AppData\Roaming\jupyter\kernels\.net-powershell
  python3            H:\Anaconda3\share\jupyter\kernels\python3
  xpython            H:\Anaconda3\share\jupyter\kernels\xpython
```

Any help will be greatly appreciated.
Charles
`

**Comment by jonsequitur** [comment]
What version of `Microsoft.ML` were you using previously? Does it still work correctly with this version of `dotnet-interactive`?

**Comment by jonsequitur** [comment]
Ah, I think you're still pointing to the older `dotnet-try`-based Jupyter implementation.

Please try running this and see if that fixes it:

```console
> dotnet-interactive jupyter install
```

**Comment by CBrauer** [comment]
Hi Jon.
As you requested, I ran the following:
```
>dotnet-interactive jupyter install
Installing using jupyter kernelspec module.
Installed ".NET (C#)" kernel.
Installing using jupyter kernelspec module.
Installed ".NET (F#)" kernel.
Installing using jupyter kernelspec module.
Installed ".NET (PowerShell)" kernel.

>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

>
```

This brings up the questions:
  1. How can I remove the old versions.  They do not show up in the Control Panel Programs.
  2. How can I point to the latest release.

Charles

**Comment by CBrauer** [comment]
I got the notebook to work by doing the following steps:

1.  I used Control Panel to remove Visual Studio 2019, Preview 2.
2. I removed all .NET packages and SDK's,
3.  I rebooted my machine.
4.  I downloaded the latest Visual Studio 2019, Preview 2 and re-configured all the packages.
5.  I restarted Jupyter notebook, and I omitted the version number on the install cell:

![image](https://user-images.githubusercontent.com/1317234/80627480-d5d17e00-8a04-11ea-8293-e61b69d20599.png)

It worked, 

Charles

**Comment by jonsequitur** [comment]
`dotnet interactive jupyter install` writes (or overwrites) the `kernel.json` files that tell Jupyter how to launch the .NET kernels. It was needed this one time because the executable name changed from `dotnet-try` (which can still be used for interactive docs, as before) to `dotnet-interactive`. The latest versions of `dotnet-try` no longer include the Jupyter kernel feature.
