### ISSUE TITLE
Is there a way to tell .NET Interactive to use the system's powershell (which has extra modules installed)?

### ISSUE THREAD

**Issue by louien** [dotnet/interactive#3619]
**The package and version I'm asking about**: 

### Question

I use powershell to manage my cloud infrastructure. Usually I'll just install the az module on top of powershell and I can start using the az command. But with .NET Interactive, it comes with its own Powershell core that doesn't have the az module. Is there a way to tell .NET interactive to use my system's powershell? or is there any way to get the az commands working the notebooks?

**Comment by jonsequitur** [comment]
Assuming that I'm understanding correctly that you installed `az` in Windows PowerShell, you could probably create a Windows PowerShell session within the PowerShell 7 instance in .NET Interactive. 

The [recommendation](https://learn.microsoft.com/en-us/powershell/azure/install-azps-windows?view=azps-12.1.0&tabs=powershell&pivots=windows-psgallery) though is to use the Az PowerShell module with PowerShell 7.  

.NET Interactive's PowerShell kernel will load the current user's PowerShell profile so any configuration you do there will be available in every session.

**Comment by louien** [comment]
Thanks @jonsequitur that was spot on. After installing Powershell 7 and adding all the modules I need, .NET Interactive was able to load them in VSC and I was able to run the commands in the notebooks successfully.

Thank you.

**Comment by jonsequitur** [comment]
Quite welcome!
