### ISSUE TITLE
Unable to install package from private (Azure Artifacts) feed with #r

### ISSUE THREAD

**Issue by cthlo** [dotnet/interactive#3627]
### Describe the bug
```
Error: C:\.....\.packagemanagement\nuget\Projects\...\Project.fsproj: error NU1301: Unable to load the service index for source ..../index.json.
```
Hi,

I'm trying to use `#r` to install a nuget package from a private Azure Artifacts feed in my notebook.
But the above error is shown.
However, I am able to perform `nuget install` from a _pwsh_ cell in the same notebook no problem.
The creds are handled by `VstsCredentialProvider`. By any chance, it is not authenticated properly when using the magic command? How can I debug this?

Thank you!

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [x] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![image](https://github.com/user-attachments/assets/ea53fd76-423e-45ca-a52d-54a22d9011cd)

**Comment by jonsequitur** [comment]
Can you provide the code you're running and a screen shot?

**Comment by cthlo** [comment]
> Can you provide the code you're running and a screen shot?

Here's a screenshot of the cell and output:
![image](https://github.com/user-attachments/assets/50581295-1865-4063-8ef8-ccd8f88a3e58)

**Comment by jonsequitur** [comment]
Does the feed require authentication?

.NET Interactive doesn't provide any way to authenticate with a NuGet feed. If the feed requires authentication, the recommendation is to include a PAT in your nuget.config.

**Comment by cthlo** [comment]
> Does the feed require authentication?
> 
> .NET Interactive doesn't provide any way to authenticate with a NuGet feed. If the feed requires authentication, the recommendation is to include a PAT in your nuget.config.

Yes, it does. Our setup is handled by [VstsCredentialProvider](https://github.com/microsoft/artifacts-credprovider/blob/master/CredentialProvider.Microsoft/CredentialProviders/Vsts/VstsCredentialProvider.cs).

I'm able to install via `nuget install` in a _pwsh_ cell in the same notebook:
![image](https://github.com/user-attachments/assets/16021d07-5939-4337-a2c2-77e6e225b421)

Does `#r` interact with NuGet differently?

**Comment by jonsequitur** [comment]
`#r` performs a `dotnet restore`. It's not interactive, so if authentication is needed and no PAT is provided in nuget.config, it fails.

**Comment by cthlo** [comment]
> `#r` performs a `dotnet restore`. It's not interactive, so if authentication is needed and no PAT is provided in nuget.config, it fails.

I see. Thanks, Jon.
