### ISSUE TITLE
[VS Code Insiders] Cannot connect to SQL kernel

### ISSUE THREAD

**Issue by sharoncxu** [dotnet/interactive#3629]
Error message: "unrecognized name --kernel-name"

### Screenshots
![image](https://github.com/user-attachments/assets/9065b68e-5af4-4ff5-8f20-bbe482d6fa25)

**Comment by jonsequitur** [comment]
This is due to the latest extension packages not being available on nuget.org.

The workaround is to include the following in your notebook:

```
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"
```
