### ISSUE TITLE
[VS Code Insiders] Cannot do variable sharing to or from the python kernel

### ISSUE THREAD

**Issue by sharoncxu** [dotnet/interactive#3631]
### Screenshots
![image](https://github.com/user-attachments/assets/8783a997-f080-4793-ae2f-4cb9e7c9ba29)

The connection to python is working fine but variable sharing doesn't work. The variables also do not appear in the variable explorer.

**Comment by AbhitejJohn** [comment]
Needs to be tried again.

**Comment by jonsequitur** [comment]
Fixed.

![Image](https://github.com/user-attachments/assets/f9a0c54f-ba09-4dee-9451-ee3fe2a5a01d)
