### ISSUE TITLE
install --path is ignored

### ISSUE THREAD

**Issue by flcdrg** [dotnet/interactive#366]
#### Describe the bug
Anaconda defaults to installing kernels in %USERPROFILE%\Anaconda3\share\jupyter\kernels

`dotnet interactive jupyter install` fails because it is looking in the wrong directory

![image](https://user-images.githubusercontent.com/384747/80663089-2d89eb00-8ad2-11ea-887a-eb51d274a49d.png)

Trying to use the new `--path` parameter has no effect:

![image](https://user-images.githubusercontent.com/384747/80663131-48f4f600-8ad2-11ea-9de3-1805938ea050.png)

#### Did this error occur while using `dotnet interactive`?
- [ ] .NET Jupyter Notebook 

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Safari
 - Frontend
    - [ ] Jupyter notebook
    - [ ] Jupyter lab
    - [ ] nteract

**Comment by flcdrg** [comment]
Related to #157

**Comment by colombod** [comment]
Thank you for reporting this, look PR #367 
I think is addressing your issues

**Comment by flcdrg** [comment]
Ran a local build of master, and confirming I could do the install without error now
