### ISSUE TITLE
Delete or rename subkernel

### ISSUE THREAD

**Issue by tonidy** [dotnet/interactive#3668]
**The package and version I'm asking about**: 

```
.NET Interactive

© 2020 Microsoft Corporation

Version: 1.0.522904+cdfa48b2ea1a27dfe0f545c42a34fd3ec7119074

Library version: 1.0.0-beta.24229.4+cdfa48b2ea1a27dfe0f545c42a34fd3ec7119074

Build date: 2024-09-13T10:42:27.6738502Z
```

### Question

After running this command:

`#!connect jupyter --kernel-name pythonkernel --kernel-spec python3`

Add I cannot find to rename/delete the subkernel, so I got 2 python subkernels:

<img width="634" alt="image" src="https://github.com/user-attachments/assets/9f440434-30a0-48d9-abf1-1964b1e7eb46">

I’m not sure if this is a new feature or if I’ve just overlooked it.

**Comment by jonsequitur** [comment]
This is the intended design. Sometimes having multiple kernels of the same type is desirable, e.g. for different environments (in the case of Python) or different database connections (in the case of SQL).

There's currently no gesture for removing a subkernel other than restarting the whole kernel.

**Comment by tonidy** [comment]
> This is the intended design. Sometimes having multiple kernels of the same type is desirable, e.g. for different environments (in the case of Python) or different database connections (in the case of SQL).

That make senses, I understand now.

> There's currently no gesture for removing a subkernel other than restarting the whole kernel.

What do you mean by restarting the whole kernel? Is it `.NET Interactive` kernel? Or we can use this `restart`:
<img width="972" alt="image" src="https://github.com/user-attachments/assets/eb1d1749-e60a-4611-b038-56c86eca2ae2">
