### ISSUE TITLE
jupyter install is not installing

### ISSUE THREAD

**Issue by Jaykul** [dotnet/interactive#369]
#### Describe the bug
When I run `dotnet interactive jupyter install` I got the "The kernelspec path $C:\Users\jaykul\AppData\Roaming\jupyter\kernels does not exist" message, but after creating the folder, when I ran it again, all it did was make _more_ nested "kernels" folders:

#### Did this error occur while using `dotnet interactive`?
Trying to register the jupyter kernels

#### Screenshots

![image](https://user-images.githubusercontent.com/192942/80738934-afcedb00-8ae3-11ea-8232-a6f6e5436b15.png)

#### Please complete the following:
 - OS
    - [x] Windows 10

**Comment by colombod** [comment]
Addressing this in PR #367
