### ISSUE TITLE
Can't use using declaration but have to use block using statement

### ISSUE THREAD

**Issue by johngardner58work** [dotnet/interactive#3691]
This form of code _using var serilog = new Serilog.LoggerConfiguration();_  will complain about a missing ";"  but compiles fine in Visual Studio.   I have to change it to the statement block form: _using(var serilog = new Serilog.LoggerConfiguration()) {...}_  for it to work in interactive.   Since the declaration form is part of C# 12 shouldn't C# script support it also?

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

Version: 1.0.522904+cdfa48b2ea1a27dfe0f545c42a34fd3ec7119074

Library version: 1.0.0-beta.24229.4+cdfa48b2ea1a27dfe0f545c42a34fd3ec7119074

Build date: 2024-06-28T23:16:46.5517077Z
- OS
    - [ x] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ x] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [x ] Jupyter Lab
    - [ ] nteract
    - [x ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
Yes, this issue should be opened on the Roslyn repo.

**Comment by johngardner58work** [comment]
Thanks!
