### ISSUE TITLE
Polyglot Notebook: [DevExE2E][Regression]Fail to create Polyglot Notebook: Create new blank notebook (.dib ).

### ISSUE THREAD

**Issue by v-hongweiwei** [dotnet/interactive#3713]
**Describe the bug**
Fail to create Polyglot Notebook: Create new blank notebook (.dib ), throw error "Cannot read properties of undefined (reading 'kernelInfo')"

**Detailed Repro Build info:**
Detailed Repro Build info: VSCodeSetup-arm64-1.94.2 + dotnet-interactive-vscode-1.0.5511031.vsix
VSCode Link: https://code.visualstudio.com/download
Version: 1.94.2 (system setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT arm64 10.0.22631

dotnet-interactive-vscode-1.0.5511031.vsix
https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjU1ODU1Mi9hcnRpZmFjdE5hbWUvdnNjb2Rl0/content?format=file&subPath=%2Finsiders%2Fdotnet-interactive-vscode-1.0.5511031.vsix

sdk info: dotnet-sdk-8.0.403-win-arm64

**Note:**
1. It's a regression issue. It doesn't repro on VSCodeUserSetup-x64-1.93.1 + dotnet-interactive-vscode-1.0.5468011.vsix.
2. Not repro on create as .ipynb project.

**Steps:**
1. Ctrl+Shift+P => "Polyglot Notebook: Create new blank notebook"
2. Select "Create as .dib" ->Select "C#" or "F#"

**Expected Results:**
Creating .dib Polyglot Notebook should be done normally, with no error.
![Image](https://github.com/user-attachments/assets/3b50c21b-1427-4789-a001-e5c19b73f606)

**Actual Results:**
Fail to create Polyglot Notebook: Create new blank notebook (.dib ). 
![Image](https://github.com/user-attachments/assets/1bd4850a-3a58-47ef-b7a9-7beaaa111cbc)

[Window Title]
Visual Studio Code

[Main Instruction]
Command 'Polyglot Notebook: Create new blank notebook' resulted in an error

[Content]
Cannot read properties of undefined (reading 'kernelInfo')

[OK]
- OS
    - [√] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [√] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Screenshots**
![Image](https://github.com/user-attachments/assets/1f5eb967-4794-4fc9-af73-e719b00706a5)

**Comment by v-hozha1** [comment]
This issue also repros on windows x64 platform with build- VSCodeUserSetup-x64-1.94.2 + dotnet-interactive-vscode-1.0.5515021.vsix + dotnet-sdk-8.0.403-win-x64, not the specific issue on ARM machine.

**Comment by v-hozha1** [comment]
This issue doesn't repro on VSCodeSetup-x64-1.95.2 + dotnet-interactive-vscode-1.0.5562021.vsix.

![Image](https://github.com/user-attachments/assets/31453535-1830-4926-a146-ed6baacd4902)
