### ISSUE TITLE
Dll file reference leads to CS1025 error in latest release

### ISSUE THREAD

**Issue by dgpratt** [dotnet/interactive#3753]
### Describe the bug
I have a C# based notebook that prior to the latest update to the VS Code plugin was working fine. After the last plugin update (to v1.0.5530010, released on 2024-10-30, 12:24:40), it seems file (DLL) references cause an error (displayed in the cell output area):

> Error: (2,136): error CS1025: Single-line comment or end-of-line expected

To be clear, this is for references in the form:

`#r "C:\..\Example.dll"
`

Nuget references (e.g. `#r "nuget: Microsoft.Data.SqlClient"`) continue to work fine.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

Version: 1.0.553001+f0ec3826954ea1ab829b435418328e4aa8db58e2

Library version: 1.0.0-beta.24530.1+f0ec3826954ea1ab829b435418328e4aa8db58e2

Build date: 2024-11-06T19:03:33.2387602Z

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
I'm unable to reproduce this issue.

Are you able to get it to work with a different `.dll`? Can you provide additional information such as the exact code that's failing?

**Comment by konst-sh** [comment]
Confirming this, if in the same cell I have a few of #r directives for local .dll files it doesn't work anymore. If I split it into separate cells it still works. The issue seem to not appear for #r nuget directives.

**Comment by jonsequitur** [comment]
Can you provide code that reproduces the issue? I'm still unable to do so.

**Comment by konst-sh** [comment]
@jonsequitur this file and a pair of local dll's reproduces the issue for me, the dll's are just two random ones
[Polyglot notebook reference dll issue.zip](https://github.com/user-attachments/files/17744167/Polyglot.notebook.reference.dll.issue.zip)

**Comment by bdbai** [comment]
I’m also having this issue. I have a `main.ipynb` that references a `util.csx` using `#!import util.csx` syntax. Inside `util.csx`, it loads a few dlls like `#r "System.Net.Http.Json.dll"` and `#r "Microsoft.AspNetCore.WebUtilities.dll"`. When executing the main notebook, it shows the same error.

**Comment by konst-sh** [comment]
This cell was working before todays update of vs code polyglot extension

![Image](https://github.com/user-attachments/assets/ee96304a-aaac-4e71-ba23-300868926f51)

**Comment by konst-sh** [comment]
This kind of literal string for dll reference was working before todays udate in VS code polyglot extension. Now it doesn't stop executing cell. Only works @"" kind of string literals

![Image](https://github.com/user-attachments/assets/842462de-ca6c-44b3-a243-6539be44e363)

**Comment by jonsequitur** [comment]
@konst-sh Is that a C# cell or an F# cell?

**Comment by konst-sh** [comment]
@jonsequitur its F#
