### ISSUE TITLE
--create-dbcontext gives error: Microsoft.EntityFrameworkCore.SqlServer version 8.0.8 cannot be added because version 8.0.10 was added previously.

### ISSUE THREAD

**Issue by kemmis** [dotnet/interactive#3763]
### Describe the bug
Using Microsoft.DotNet.Interactive.SqlServer, version 1.0.0-beta.24563.1, when you use `--create-dbcontext` with `#!connect mssql` you will get 
**Error: Microsoft.EntityFrameworkCore.SqlServer version 8.0.8 cannot be added because version 8.0.10 was added previously.**

The EntityFrameworkCore packages in ConnectMsSqlDirective.cs need to be updated to match version in SqlServer.csproj.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [ X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![Image](https://github.com/user-attachments/assets/4b2f2507-5ef4-4593-81a3-86eeeb784972)

![Image](https://github.com/user-attachments/assets/fbe84ae1-53eb-45d4-bd28-cb215eeda6cd)

**Comment by jonsequitur** [comment]
Fixed by #3762.

**Comment by kemmis** [comment]
@jonsequitur Thanks for fixing this. Is there an ETA on when a new nuget package will get published?

**Comment by jonsequitur** [comment]
It should be available in the next hour.

**Comment by kemmis** [comment]
@jonsequitur using the latest package now give you: **Error: Microsoft.Identity.Client version 4.61.3 cannot be added because version 4.65.0 was added previously.**

**Comment by jonsequitur** [comment]
There's a fix on the way. (#3767)
