### ISSUE TITLE
Error: Microsoft.Identity.Client version 4.61.3 cannot be added because version 4.65.0 was added previously.

### ISSUE THREAD

**Issue by barnhouset09** [dotnet/interactive#3766]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

Getting this error when trying to scaffold a dbcontext with magic command:

```
#!connect mssql --create-dbcontext --kernel-name cadabraProdEF "Server=connection"
```
![Image](https://github.com/user-attachments/assets/7e7f4e84-80c0-4260-a830-409e34eda259)

I believe [this nuget package](https://github.com/dotnet/interactive/blob/8480c358329ae51b2fc32c676e5edf122458b267/src/Microsoft.DotNet.Interactive.SqlServer/Microsoft.DotNet.Interactive.SqlServer.csproj#L32) may need to be updated:

![Image](https://github.com/user-attachments/assets/b2ee7c2d-8708-43ba-9ba1-b66adedf11bd)

**Comment by jonsequitur** [comment]
An updated version of Polyglot Notebooks is now available with this fix.
