### ISSUE TITLE
Stay focused on current cell when **Esc** key is pressed

### ISSUE THREAD

**Issue by Bill-XU** [dotnet/interactive#3771]
**Is your feature request related to a problem? Please describe.**
When coding with assistants, I usually use **Esc** key to close the popup menu.
But when editing notebook, **Esc** key not only cl;oses the popups, but also move the focus outside of the cell which I was editing.
This is a bit annoying that I have to use mouse to put cursor into it again each time.

**Describe the solution you'd like**
Please change the behavior of **Esc** key when a cell is focused on, make the cell stay focused.

**Describe alternatives you've considered**
Sorry, don't know any alternatives, but I appreciate anybody helps give some ~
Thanks to all.

Bill

**Comment by jonsequitur** [comment]
This is controlled by VS Code and not Polyglot Notebooks. You can change this behavior by removing or changing the keyboard shortcut for `Notebook: Stop editing cell`.

**Comment by Bill-XU** [comment]
> This is controlled by VS Code and not Polyglot Notebooks. You can change this behavior by removing or changing the keyboard shortcut for `Notebook: Stop editing cell`.

@jonsequitur 
Thank you!

I found three shortcuts named "Notebook: Stop editing cell" in my settings.
One of them has the condition expression "notebookEditorFocused && notebookOutputFocused",
looks like the one caused unexpected behavior.
After removing it, **Esc** key behaves as I expected.

**Comment by jonsequitur** [comment]
@rebornix Is this behavior unexpected?
