### ISSUE TITLE
"KernelSpec python3 not found" when opening VS Code directly rather than from anaconda prompt

### ISSUE THREAD

**Issue by sharoncxu** [dotnet/interactive#3774]
### Describe the bug
Steps taken:
1. Opened VS Code directly from Start menu rather than from Anaconda prompt
2. Added --conda-env base parameter to connect command
3. Runs into error "KernelSpec python3 not found". See screenshot below.

Related to issue: https://github.com/dotnet/interactive/issues/2869

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [x] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![Image](https://github.com/user-attachments/assets/5f44bdef-9145-4653-9a75-611061b30a1f)

**Comment by jonsequitur** [comment]
Fixed by #3781.
