### ISSUE TITLE
Unable to restore NuGet packages in VS Code Polyglot Notebooks

### ISSUE THREAD

**Issue by NikiforovAll** [dotnet/interactive#3792]
### Describe the bug

Unable to restore a NuGet package. (global error, does not depend on package)

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
![Image](https://github.com/user-attachments/assets/36f36069-a632-49f8-827a-475c287772b2)

- OS
    - [X] Windows 11
 - Browser 
    - [X] Chrome
 - Frontend
    - [X] Visual Studio Code 

### Screenshots
![Image](https://github.com/user-attachments/assets/c2d8f185-305b-47c7-80a3-c543e3838021)

![Image](https://github.com/user-attachments/assets/20af18b6-d506-46ac-8f0b-379f6d69d390)

**Comment by jonsequitur** [comment]
Are you seeing an error message or does it just hang?

Have you checked for VS Code and extension updates and restarted VS Code?

**Comment by NikiforovAll** [comment]
I've reinstalled the vscode extensions and the issue is gone.  Thank you for the help
