### ISSUE TITLE
dotnet interactive graceful quit

### ISSUE THREAD

**Issue by colombod** [dotnet/interactive#385]
dotnet interactive should be able to terminate with exit code 0 if that is required by the application that owns it.

Different integrations could possibly have different enduser gestures to trigger such command.

The proposal consists in adding an api command that will initiate the shutdown of the dotnet interactive process with an exit code of 0

When ```Quit``` is issued dotnet interactive performs the dispose patterns so that kernels and any other component registered for disposal have the opportunity to clean up.

The handler of  the command prevents any other queued command from being executed and the context is completed, finally ```Environment.Exit(0)``` is done.

**Comment by suhsteve** [comment]
I like this idea of asking dotnet-interactive to try to shutdown gracefully.  In our extension we register a a disposable with the kernel and cleaning this up before shutting down would be greatly appreciated.

Having a separate command to shut down the kernel would also help in our extension scenario.  We add a middleware to the kernel and would not want the middleware run if a shutdown command is issued.  Currently we only run our middleware if the command is of type SubmitCode and having a separate command type to shutdown would help.

```csharp
kernelBase.AddMiddleware(async (command, context, next) =>
{
    if (command is SubmitCode)
...
```

**Comment by colombod** [comment]
@suhsteve do you think that disposable objects in code submission should have the opportunity to be involved with the disposal of kernels?

That would make sure that any user created resource is properly disposed when dotnet-interactive quits

**Comment by jonsequitur** [comment]
This makes very good sense.

**Comment by suhsteve** [comment]
I think it'd be a `nice to have` if it could do that as well.
