### ISSUE TITLE
simplify HTTP options

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#400]
As currently implemented (and described [here](https://github.com/dotnet/interactive/tree/master/src/dotnet-interactive/CommandLine)), the `--http-port` and `--http-port-range` options are mutually exclusive but in many cases both valid. 

It seems like we should be able to simplify this so that: 

* `--http-port` is never allowed for `dotnet interactive jupyter` 
* `--http-port-range` is never allowed for `dotnet interactive http`. 
* (Possibly) HTTP APIs can be disabled entirely when running `dotnet interactive stdio`.

Additionally, the port range for `dotnet interactive jupyter` should probably have a default value, so that the default Jupyter experience includes the ability to use the JavaScript variable sharing APIs.

**Comment by jonsequitur** [comment]
@brettfo @colombod Thoughts?

**Comment by colombod** [comment]
This design makes sense and reduces complexity for users
