### ISSUE TITLE
Integrate with Azure Notebooks

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/interactive#404]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Azure Notebooks currently supports F# with by using the IFSharp kernel. Replace that kernel with F# .NET Interactive and integrate C# and PowerShell kernels with Azure Notebooks. 

**Describe alternatives you've considered**
Provide Docker images users can self-host or can run in hosted environments. Currently that's how IFSharp works in Azure Notebooks, a container with an image that has IFSharp kernel installed is deployed.

**Comment by dsyme** [comment]
Closing this out, see https://docs.microsoft.com/en-us/azure/notebooks/

> On October 9, 2020 the Azure Notebooks public preview site will be retired and replaced with integrated services from Visual Studio, Azure, and GitHub. Learn about your options and Microsoft's other notebook experiences at https://notebooks.azure.com/Content/alternatives.html.
