### ISSUE TITLE
System.Data.SQLite doesn't work in notebook

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#41]
Here's what happens in a local notebook:

![image](https://user-images.githubusercontent.com/547415/68721396-0ca2fd00-0567-11ea-897f-0b5ce63eeef9.png)

Here's what happens in Binder:

![image](https://user-images.githubusercontent.com/547415/68721401-1462a180-0567-11ea-9208-07475aa01e30.png)

**Comment by KevinRansom** [comment]
Fixed by: https://github.com/dotnet/interactive/pull/239
