### ISSUE TITLE
When opening an .ipynb in VS Code, there are empty cells.

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#428]
Empty cells when opening an `.ipynb`. In the screen shot here, I opened `/samples/notebooks/Extensions.ipynb` and the notebook contains empty cells, though not missing code.

Version: 1.0.126511+f4313f53dc1b70447ef17c2116588ee27b6bac25

![image](https://user-images.githubusercontent.com/547415/82127798-2ff37280-976b-11ea-81e6-31fb87f5378c.png)

**Comment by colombod** [comment]
I propose not to open or auto convert `.ipynb` files but to have a gesture to import and export such file format. But the extension only works reading/writing our file format, so not to interfere and modify those notebooks without the user knowing or having a way to revert the changes.

**Comment by brettfo** [comment]
Due to language aliases (`#!pwsh` instead of `#!powershell`) and magic commands (`#!clock`) being misinterpreted.
