### ISSUE TITLE
[VS Code] .NET Interactive extension does not recognize installed NuGet packages 

### ISSUE THREAD

**Issue by lqdev** [dotnet/interactive#431]
### Describe the bug

Using the .NET Interactive VS Code extension, installation of NuGet package seems to work. However, when I use an `open` statement, it doesn't recognized the installed package.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/11130940/82230022-2dbf1e80-98f9-11ea-9494-4138cfe91574.png)

**Comment by colombod** [comment]
Fixed in latest release
