### ISSUE TITLE
add support for input and password gestures in VS Code notebooks

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#436]

**Comment by bfcamara** [comment]
Any ETA for this feature? Not being able to use `input` in VSCode .NET notebooks makes harder some experiences where we want to collect input from the user. Without this in VSCode, we still to use a classic jupyter server with the C# kernel (which already supports `input`).

**Comment by jonsequitur** [comment]
This is implemented and we've done a poor job of documenting it. 

The method is called `GetInputAsync` rather than the less .NET-ish `input`. 

Give this a try:

```cs
var value = await GetInputAsync("Put a prompt here", isPassword: true);

value
```

**Comment by bfcamara** [comment]
@jonsequitur Thank you. It works like a charm.
