### ISSUE TITLE
Unable to create .dotnet-interactive files in arbitrary places in VS Code Insiders

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/interactive#439]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
![image](https://user-images.githubusercontent.com/2546640/82259486-a8a02d80-9929-11ea-8ae4-889b367c260f.png)

* At the command line, run `dotnet interactive --version`.
1.0.116805+e82617b33d4652ef09b36a1d595ac15de434a939
* In VS Code Insider details
Version: 1.46.0-insider (user setup)
Commit: 6849775440496504e0677ffcf2a46d47ad9130f5
Date: 2020-05-15T05:30:56.857Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/2546640/82259275-49421d80-9929-11ea-8a7c-6184ab2ac343.png)

When trying to create a .dotnet-interactive file in arbitrary place in VS Code Insiders I get this the error above after, launching VS Code Insiders from the terminal using this command `code-insiders --enable-proposed-api ms-dotnettools.dotnet-interactive-vscode `

#### Workaround 
- I created a new folder  `notebooks` and navigate to it
- Launch VS Code Insiders like this `code-insiders --enable-proposed-api ms-dotnettools.dotnet-interactive-vscode .`  With a **.**
![image](https://user-images.githubusercontent.com/2546640/82256856-10a04500-9925-11ea-91fd-2ded7c8e10ef.png)
5. Inside notebooks created  `foo.dotnet-interactive`  then it worked 
![image](https://user-images.githubusercontent.com/2546640/82257512-2cf0b180-9926-11ea-9d33-820c97fca236.png)

**Comment by jonsequitur** [comment]
I believe this has been resolved. I've been opening files from anywhere and it works.

**Comment by LadyNaggaga** [comment]
I will go a head and close the issue.
