### ISSUE TITLE
Image in !#about is broken 

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/interactive#442]
.NET Logo image link in the !#about broken 
![image](https://user-images.githubusercontent.com/2546640/82274894-5d991100-994f-11ea-87ce-1113aa5fb99c.png)
![image](https://user-images.githubusercontent.com/2546640/82274910-6ee21d80-994f-11ea-9a3e-c393c3acec4c.png)

**Comment by jonsequitur** [comment]
This is a duplicate of #432.
