### ISSUE TITLE
unify #r nuget behavior between C# and F#

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#45]
The `#r nuget` behavior and capabilities are different between C# and F#, with F#'s features being more developed. C# currently only supports specifying package id and version. F# supports other parameters such as a package feed (`RestoreSources`). 

Unlike the current C# code, the F# semantics allow for multiple `#r nuget` statements to aggregate parameters, e.g.

```fsharp
#r "nuget:bl=true"
#r "nuget:RestoreSources=https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json"
#r "nuget:Microsoft.ML,version=1.4.0-preview"
#r "nuget:Microsoft.ML.AutoML"
#r "nuget:Microsoft.Data.DataFrame,version=0.1.1-e191008-1"
```

This behavior should be added to C#.

In terms of naming, parameter naming seems to draw from several sources in an inconsistent manner, e.g. in the example above `bl` is an MSBuild command line parameter, `RestoreSources` is an MSBuild property, `version` is shared with the `dotnet` CLI. We should consider making these consistent and hopefully more predictable and easier to remember.

**Comment by mswilson4040** [comment]
Any update on this? I'm also trying to get a private nuget feed working (package is in Azure DevOps) but no luck.

**Comment by KevinRansom** [comment]
Merged: https://github.com/dotnet/interactive/pull/239
