### ISSUE TITLE
Blank Xplot plots when running C# report via papermill

### ISSUE THREAD

**Issue by chriss2401** [dotnet/interactive#476]
### Describe the bug
Hi, I hope this is the right repo to report this.

When trying to run a c# report via papermill (v2) that contains a Xplot.Plotly bar plot, the resulting notebook has an empty plot (see image attached below). 

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
1.0.120301+734b46e7eb555cbae4e993d98efdc8e47a54ca39

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [x] Firefox
    - [ ] Safari
 - Frontend
    - [x] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
Plot when run inside jupyter notebook (top image) vs via papermill (lower image)
![image](https://user-images.githubusercontent.com/14329867/82997386-99df0800-a006-11ea-8763-015c4a0b978f.png)

![image](https://user-images.githubusercontent.com/14329867/82997495-bbd88a80-a006-11ea-8985-e27edba2c4ac.png)

**Comment by colombod** [comment]
Could you share with us the output file from papermill so we can see the content of the cell?

**Comment by chriss2401** [comment]
Here is a zip file with both input and output files.
[test_notebooks.zip](https://github.com/dotnet/interactive/files/4711116/test_notebooks.zip)

Additionally when i run the papermill command I get what seems like the output of the plot:

![image](https://user-images.githubusercontent.com/14329867/83407414-fa0fe880-a410-11ea-945c-665df50c5869.png)

**Comment by chriss2401** [comment]
@colombod any thoughts on this ? It seems that the plot is outputted in the console output instead of the jupyter notebook itself. Dunno if this is a `dotnet/interactive` or a `papermill` issue.

**Comment by colombod** [comment]
@chriss2401 the screenshot you have there shows the cell output containing the html + js required to render the plot on screen. Is there any indicator that prevents the notebook from rendering the code?

Sometimes when opening such notebook in juptyer lab / nootebook might display at the top a badge indicating the notebook is not trusted.

I see this when open in jupyter notebook :

![image](https://user-images.githubusercontent.com/375556/84178926-1e0ca300-aa7d-11ea-9fd1-d7c237cd4c35.png)

Then I click on the badge and change to trusted, so i see this

![image](https://user-images.githubusercontent.com/375556/84178981-3381cd00-aa7d-11ea-9803-bdfe4395aa87.png)

This is the documentation page about [trusted notebooks](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html#trusting-notebooks)

**Comment by chriss2401** [comment]
@colombod rookie mistake, thanks for taking the time to look into this. I'll generate the notebooks as trusted by default.

**Comment by colombod** [comment]
@chriss2401 Not a problem at all. Was interesting that only after investigation I realised that your original screenshot was pointing that out :). But now at least we also know the way to work with that!
