### ISSUE TITLE
Load a csx file from relative path into Jupyter Notebook doesn't work

### ISSUE THREAD

**Issue by dcostea** [dotnet/interactive#478]
I try to load a csx file into Jupyter Notebook and it throws the next error:
error CS1504: Source file 'Models.cs' could not be opened -- Could not find file.
The relative path doesn't work for #load directive, but the absolute path is ok.

E.g. Having a Jupyter notebook like this: C:/path/to/myNotebook.ipynb:
``#load "C:/path/to/file.csx" works``
``#load "file.csx" doesn't work``
``#load "./file.csx" doesn't work ``
``#load "../to/file.csx" doesn't work``

.NET Interactive 1.0.115407

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [x] Firefox
    - [ ] Safari
 - Frontend
    - [x] Jupyter Notebook
    - [x] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

**Comment by rspaulino** [comment]
I experience the same issue using
OS: macOS
Frontend: Visual Studio Code

**Comment by Benjol** [comment]
Windows 7, Firefox, Jupyter Lab.

**Comment by radobson61** [comment]
I encountered something similar on a Windows 10 machine.

C:\Users\Consultant\Work Stuff\DataAnalysis\MyNotebook.ipynb is where my notebook is.

I could only get the FQPN to work. 

None of the relative path options were working.

Get-Location returned 

C:\Users\Consultant\AppData\Local\Temp\bbc7dd9a-accd-402f-bd59-c1619d686d9f

its "seems" as if the Notebook is getting executed in that Temp folder, versus the folder where it lives.

**Comment by jonsequitur** [comment]
@radobson61 What version of `dotnet-interactive` are you using and what frontend (e.g. JupyterLab, VS Code, etc)?

**Comment by dcostea** [comment]
> @radobson61 What version of `dotnet-interactive` are you using and what frontend (e.g. JupyterLab, VS Code, etc)?

@jonsequitur , I can respond to my scenario: 

Jupyter Notebook
Version: 1.0.142601+586ab2f29818edea7c19c383874977fe5d0391fc
Build date: 2020-09-01T21:31:17.3494045Z

![Untitled](https://user-images.githubusercontent.com/15055082/93319894-ba7ada00-f810-11ea-8fe0-03fed36fb579.png)

**Comment by radobson61** [comment]
@jonsequitur  
dotnet-interactive --version     
    1.0.142601+586ab2f29818edea7c19c383874977fe5d0391fc

VSCode 
Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by Benjol** [comment]
1.0.145103+29ee905755d84cbd1f9952b9c16c2531f2e2a9df

Jupyter lab in Miniconda on Windows 7

**Comment by jonsequitur** [comment]
Sorry for the lack of clarity here. There are a few different things going on.

The lack of support for relative paths in `.csx` loading is a known bug that hasn't been fixed yet in any version of .NET Interactive. The issue there is that Roslyn scripting needs to be told what working directory to resolve relative to.

This, though, looks like an unrelated bug and surprised me:

> Get-Location returned
> C:\Users\Consultant\AppData\Local\Temp\bbc7dd9a-accd-402f-bd59-c1619d686d9f

PowerShell behaviors should be unrelated to `.csx` loading and it's not clear to me why the working directory got moved to that location. The working directory _should_ be folder where the notebook file is located, in VS Code. @radobson61, if you restart the notebook and run `Get-Location` before doing anything else, what path do you see?

Also, the version for VS Code will likely be different from the version of the globally-installed tool. The VS Code notebooks extension installs its own version of .NET Interactive. You can find its version by running `#!about`:

![image](https://user-images.githubusercontent.com/547415/93356671-54805980-f7f4-11ea-829d-52c7415e32bc.png)

**Comment by radobson61** [comment]
@jonsequitur 

The only change after a restart with the temp location.

C:\Users\Consultant\AppData\Local\Temp\b3e90375-e2b8-45ed-8003-d579cf75cf1b

 This includes closing and restarting VSCode

#!about 
Version: 1.0.142601+586ab2f29818edea7c19c383874977fe5d0391fc
Build date: 2020-09-09T14:18:07.6932204

**Comment by radobson61** [comment]
@jonsequitur for what its worth, that location on my C: drive is also where my OneDrive (Personal, not Business) is mapped to, so that location is synching.

**Comment by radobson61** [comment]
More update.

#!csharp
using System;
using System.IO; 

Console.Write(Directory.GetCurrentDirectory());

returns the same path at Get-Location

The location DOES NOT change when I close, then  reopen the file. 

The location DOES NOT change when I do a kernel restart in the notebook.

The location DOES change when I close VSCode.

**Comment by Spongman** [comment]
`File->Save As` to a different folder should also change the directory...

**Comment by strabu** [comment]
Hey guys,
I'm missing loading .csx-files in VSCode/.NET Interactive so much, because I can't push my Notebooks to git-repos or to Github.
The don't work for other people because they clone to different directories.

Here you'll find a notebook that describes 3 cases how I want to use it: https://github.com/strabu/dotnet-interactive-issue-repro

I guess I found a solution for this in Microsoft.DotNet.Interactive.CSharp/CSharpKernel.cs,
I've written a UnitTest and I'll try to send a pull-request for that.

**Comment by Acmion** [comment]
This is a very much needed feature. The current development experience suffers significantly from the lack of this feature.
