### ISSUE TITLE
Ignore namespace for loaded cs files in Jupyter Notebook

### ISSUE THREAD

**Issue by dcostea** [dotnet/interactive#479]
I tried to reuse the entities defined in a .NET solution into a Jupyter Notebook. The entities are part of a namespace in my solution, so I cannot remove the namespace without impacting the whole solution.

It would be great if the existing namespace is simply ignored when the file is loaded in Jupyter Notebook.

_MyNotebook.ipynb_
``#load "Person.cs"``

_Person.cs_
``namespace Entities`` 
``{``
``  public class Person { public string Name { get; set; } }``
``}``

**Comment by jonsequitur** [comment]
Related: https://github.com/dotnet/csharplang/issues/3117

**Comment by janschreieradac** [comment]
I know this is old, but I don't see how this is completed? I would still love this feature such they I can use a notebook next to an existing .net solution and not need to remove all namespaces. for me the obvious fix would be to simply ignore namespaces when using `#import`
