### ISSUE TITLE
#r doesn't work as expected with local libraries

### ISSUE THREAD

**Issue by mehmetakbulut** [dotnet/interactive#49]
#### Describe the bug
This issue has two parts, not sure if they are related:
1) Attempting to load a locally available library using #r with an absolute path fails partially. An error will be printed as if the #r command failed but namespace is available and types are usable if included with a `using` statement. Regardless, autocompletion of anything involving this local library doesn't work except when writing the `using` statement.
2) Attempting to load a locally available library using #r with a relative path fails completely. It will print out the standard file not found error. I'm not certain if this is intended to work so a clarification would be great. Without using an absolute path, certain (all?) system packaged libraries seem to be loadable just fine which makes me think there is some special handling concerning those.

Both issues are present in Jupyter Notebook, Lab and Console. Tried with various dlls that were either originally downloaded with nuget or built locally.

#### Did this error occur while using `dotnet try` or online?
- [X] `dotnet-try` (jupyter)
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [X] Other: Potential issue with .NET C# Kernel for Jupyter

#### Screenshots
No screenshots but:

Windows
```
#r "C:/Users/Mehmet/.nuget/packages/newtonsoft.json/12.0.2/lib/netstandard2.0/Newtonsoft.Json.dll"

Invalid: Command: #r C:/Users/Mehmet/.nuget/packages/newtonsoft.json/12.0.2/lib/netstandard2.0/Newtonsoft.Json.dll
```

Linux
```
#r "/home/mehmet/.nuget/packages/newtonsoft.json/12.0.2/lib/netstandard2.0/Newtonsoft.Json.dll"

Invalid: Command: #r /home/mehmet/.nuget/packages/newtonsoft.json/12.0.2/lib/netstandard2.0/Newtonsoft.Json.dll
```

#### Please complete the following:
 - OS
    - [X] Windows 10
    - [ ] macOS
    - [X] Linux (Ubuntu 18.04)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by Gimly** [comment]
@jonsequitur Could you copy your updated install instructions here ? Looks like the linked page doesn't exist and I'm experiencing the same issue as @bryanrcarlson. Thanks !

**Comment by jonsequitur** [comment]
I've updated the link: https://github.com/dotnet/interactive/blob/master/docs/NotebooksLocalExperience.md.
