### ISSUE TITLE
Expose default language setting for code cells in VS Code notebook to users

### ISSUE THREAD

**Issue by nasser** [dotnet/interactive#495]
**Is your feature request related to a problem? Please describe.**
Currently, every time I create a new code cell the language is C#. There does not seem to be a way to change this default. I do most of my work in F#, and I find myself changing the cell language manually for every new cell to F#, which is tedious. 

**Describe the solution you'd like**
I would like the ability to choose the default language for new code cells. Ideally this would be on a per-notebook level, but an editor-wide setting would work as well.

**Describe alternatives you've considered**
I currently have key bindings in place to trigger the `Notebook: Change Cell Language` command, but as stated above this is quite tedious.

**Comment by jonsequitur** [comment]
The current behavior is that new cells are created using the language of the previously-created cell. I believe this resolves this issue but please reopen if you feel like there's further improvement to be made.
