### ISSUE TITLE
Unable to open .dib on macOS

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#496]
Extension version is v1.0.127905

![image](https://user-images.githubusercontent.com/547415/83336288-03f5e800-a267-11ea-931d-40a47b08e9bb.png)

**Comment by Eskibear** [comment]
same for me when I was having a try. FYI as I have one more error message.

<img width="563" alt="Screen Shot 2020-06-04 at 12 53 59 PM" src="https://user-images.githubusercontent.com/2351748/83716510-b1e80480-a662-11ea-9761-9baed7f11b42.png">

**Comment by brettfo** [comment]
@jonsequitur Can you open Help -> Toggle Developer Tools to see what the console shows as the full error?  I don't have a Mac to test on.

**Comment by Eskibear** [comment]
@colombod it's 10.15 catalina. FYI

```
$> dotnet  --info
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  eb1d5ee318

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

**Comment by jonsequitur** [comment]
@Eskibear It looks like you need to install the .NET Core SDK. You only have the runtime.

The VS Code extension currently doesn't install the SDK for you.

**Comment by Eskibear** [comment]
Thanks. I’ll have a try with SDK.
Btw it would be much better if you do the check and provide more meaningful error message. 😄

**Comment by jonsequitur** [comment]
Agreed. We absolutely will once we figure out how to identify the issue automatically.

**Comment by jonsequitur** [comment]
@KevinRansom Can you repro?

**Comment by LadyNaggaga** [comment]
Same over here. My error message was little different 
![image](https://user-images.githubusercontent.com/2546640/84913788-e4452900-b088-11ea-8534-eff2c5db3748.png)
Mac OS : Catalina v 10.15.4

**Comment by jonsequitur** [comment]
I'm not longer able to repro this, as of v1.0.131506. Anyone else?

**Comment by colombod** [comment]
@Eskibear and @LadyNaggaga are you still able to repro this? Our PM is enquiring about it

**Comment by Eskibear** [comment]
not repro now.

**Comment by jonsequitur** [comment]
Thanks, @Eskibear!
