### ISSUE TITLE
Support rendering Google charts

### ISSUE THREAD

**Issue by cartermp** [dotnet/interactive#50]
XPlot also supports Google Charts: https://www.nuget.org/packages/XPlot.GoogleCharts/

However, when executed in the notebook they do not render. Given this code in an F# notebook:

```fsharp
#r "nuget: deedle"
#r "nuget: fsharp.data"
#r "nuget: XPlot.GoogleCharts"
#r "nuget: XPlot.GoogleCharts.Deedle"
    
open Deedle
open FSharp.Data
open XPlot.GoogleCharts
open XPlot.GoogleCharts.Deedle

let wb = WorldBankData.GetDataContext()
let cz = wb.Countries.``Czech Republic``.Indicators
let eu = wb.Countries.``European Union``.Indicators
let czforest = series cz.``Forest area (% of land area)``
let euforest = series eu.``Forest area (% of land area)``

[ czforest.[1990 .. 1993]; euforest.[1990 .. 1993] ]
|> Chart.Line
```

We get this output:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/6309070/68499080-51a4f780-0226-11ea-9b28-701cdcf6eab2.png">

**Comment by Odonno** [comment]
I downloaded the latest version of `XPlot.Plotly` and `XPlot.GoogleCharts` (3.0.1) but I still have the error you have in the output.

i don't why the error happened. I followed this example : https://fslab.org/XPlot/chart/google-calendar-chart.html

It is weird because the Pie chart works but the Calendar don't..

**Comment by jonsequitur** [comment]
We have special handling in place for XPlot.Plotly ([here](https://github.com/dotnet/interactive/blob/master/src/XPlot.DotNet.Interactive.KernelExtensions/PlotlyChartExtensions.cs)), which would have to be replicated for XPlot.GoogleCharts.

**Comment by iennacca** [comment]
Late to the game, but hitting this issue as well, and getting a 404 on the link for the Plotly special handling; anything new on this?

**Comment by jonsequitur** [comment]
The special handling for Plotly was removed a few months ago and moved to an extension package. Something like this would be needed for Xplot.GoogleCharts: 

* NuGet: https://www.nuget.org/packages/XPlot.Plotly.Interactive/
* Source: https://github.com/fslaborg/XPlot/tree/main/src/XPlot.Plotly.Interactive
