### ISSUE TITLE
Result dosn't get stored in dib File

### ISSUE THREAD

**Issue by PSTobiasMueller** [dotnet/interactive#500]
### Describe the bug
Maybe this isn't a bug. After watching the Videos from the PSCONF2020 i tried Notebook with Powershell by myself. I've installed the latest VSCode Insider Version, along with the latest .NET Interactive Notebooks. So far the notebook is working fine. i can use the different languages inside the notbook and when i'm execute them everything is working as expected. 

But shouldn't it be the point that the results my code generats get stored inside the notebook, so that when i reopen the Notebook, i should see the Result from the Code i've executed last?
But my .dib Notebook always starts empy (without the Result from the last run).

Is that expected? Does the Output only workling when i convert it to an ipynb File and start my Notebook with jupyter?

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
1.0.127902+f855f35ad60a01b915bf57c43250c7c399ac58bc

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
The `.dib` format doesn't store outputs, by design. This is still at the early stage and feedback is welcome. 

You can see more of the goals of the file format here: #467.

**Comment by jonsequitur** [comment]
I'm closing this issue as it's by design. 

There's additional discussion in #467. Please weigh in. 

Also, we've merged direct support for writing `.ipynb`, including outputs as you would expect, and without requiring a Jupyter installation.
