### ISSUE TITLE
.NET Interactive Preview 4  Goals 

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/interactive#508]
#### Release dates: TBD

Mark | Description 
--- | --- |
:thumbsup: |Complete |
:construction: | in progress |
:hand: | blocked item|
:mechanical_arm:	 | stretch goal|
:mag:| under discussion/investigation |
:large_blue_circle: |under discussion within team |
:thread: | Polishing up  |

#### Themes
- [Growing Tool support](https://github.com/dotnet/interactive/labels/Area-VS%20Code%20Extension) - Enabling VS Code  Insider Support 
- [Giving back to the Jupyter Ecosystem](https://github.com/dotnet/interactive/labels/Area-Jupyter)
- [Continued improvements to aquistion](https://github.com/dotnet/interactive/labels/Area-Installation)
- [Improve productivity](https://github.com/dotnet/interactive/labels/Area-Language%20Services)
- [.NET Interactive documentation](https://github.com/dotnet/interactive/tree/master/docs) 
- [.NET Interactive for makers](https://github.com/colombod/pi-top): As shown with pi-top[4]
- [.NET Interactive across products](https://github.com/CodeConversations/CodeConversations) 
- [Automation](https://github.com/dotnet/interactive/labels/Area-Automation)
- Performance 

### What's new 
- Embedding the proxy kernel - Beyond Notebooks
    - [Microsoft Teams](https://github.com/CodeConversations/CodeConversations) :mechanical_arm: :large_blue_circle	
    - PowerApps  :large_blue_circle:
    - Hardware :construction:
        - Plan to be private preview on [pi-top[4]](https://www.pi-top.com/products/pi-top-4)
    - Gaming :construction:
    - Webpage 
- Automation :construction:

**Comment by LadyNaggaga** [comment]
@jonsequitur Thoughts on moving these themes and workloads to post GA?

**Comment by jonsequitur** [comment]
I think it makes sense to clarify previews for the VS Code versus the core kernel capabilities.

**Comment by LadyNaggaga** [comment]
Good point and brings clarity.  I will split them up and add new tags to separate the kernel from tooling
