### ISSUE TITLE
Produce documentation for intellisense items

### ISSUE THREAD

**Issue by colombod** [dotnet/interactive#515]
Completion items in monaco can display documentation text for intellisense items.
Producing documentation text would be useful, specially for directives.

For directives the documentation provider should be able to provide text for the command and for all options / arguments.

The documentation provider should be extensible so that extensions developers can content authors can enrich and contextualise the content.

**Comment by jonsequitur** [comment]
Closing because we have language-specific duplicates: #626, #628.
