### ISSUE TITLE
Use LaTeX formatter when string has the LaTeX pattern

### ISSUE THREAD

**Issue by cartermp** [dotnet/interactive#53]
`$$ \begin{equation} \int_0^\infty \frac{x^3}{e^x-1}\,dx = \frac{\pi^4}{15} \label{eq:sample} \end{equation} $$` renders as this when executed as a markdown cell:

<img width="190" alt="image" src="https://user-images.githubusercontent.com/6309070/67987466-b048f080-fbea-11e9-9d83-6f64db3db376.png">

However, if I produce that same string as a string in an F# (or C#) cell, it renders the raw string.

I propose that when we see the `$$` at the beginning and end, we render the string as LaTeX instead.

This behavior could be perhaps opted out of with a magic command, `%%nolatex`.

**Comment by LadyNaggaga** [comment]
I believe @colombod  added this enhancement a few months ago.

**Comment by jonsequitur** [comment]
I think adding embedded DSLs, with the implications across languages, would make our parsing too complicated. I don't think this is practical to implement as described, though it's straightforward and composable with the existing formatters to do this via specialized types, e.g. https://github.com/dotnet/interactive/issues/878#issuecomment-726205471
