### ISSUE TITLE
Ability to load custom version of XPlot.Plotly

### ISSUE THREAD

**Issue by mscottford** [dotnet/interactive#534]
**Is your feature request related to a problem? Please describe.**
I've made a small change to XPlot.Plotly (see https://github.com/fslaborg/XPlot/pull/144), and I'd like to be able to load that version of the library into a Jupyter notebook so that I can use it to create a chart. In that pull request, I've added support for the `stackgroup` field on the `Graph.Scatter` class.

**Describe the solution you'd like**
I was expecting to be able to do something like this:

```
#i nuget:/Users/mscottford/src/corgibytes/XPlot/pkg
#r nuget:XPlot.Plotly,3.1.0-preview1-preview-LocalBuild
```

Which results in:
> Restore sources
> 
>     /Users/mscottford/src/corgibytes/XPlot/pkg
> 
> Installed package XPlot.Plotly version 3.1.0-preview1-preview-LocalBuild

But running this:

```csharp
new Graph.Scatter { stackgroup = "test" }
```

results in:

> `(1,21): error CS0117: 'Graph.Scatter' does not contain a definition for 'stackgroup'`

**Describe alternatives you've considered**
I tried to use reflection to see what version of XPlot.Plotly is loaded.

```csharp
typeof(Graph.Scatter).Assembly.ToString()
```

But that resulted in:

> `XPlot.Plotly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`

So I wonder if there's a shim between XPlot.Plotly that ships with dotnet-interactive which would need to be updated with the field that I added. I skimmed through the project source, and didn't find anything obvious (at least to me :smile:).

**Comment by jonsequitur** [comment]
This is probably because we ship with an XPlot.Plotly dependency already in place. We're planning to remove this and ask people to explicitly reference XPlot.Plotly using `#r nuget` which would make this sort of workflow easier at least for XPlot.Plotly.

Maybe @KevinRansom has some ideas?

In the meantime, building `dotnet-interactive` locally would work. If you want some pointers, let us know.

**Comment by mscottford** [comment]
Ooh! I’d really appreciate some pointers on how to set that up locally. I installed using the dotnet tool, that matters in what I need to change.

**Comment by jonsequitur** [comment]
This should work. I haven't tried it out. 

The basic stuff:

* Clone the dotnet/interactive repo
* Run the restore and build scripts in the root
* Open `dotnet-interactive.sln`

Then:

* Change this to a project reference to your local clone of `XPlot.Plotly`: https://github.com/dotnet/interactive/blob/master/src/XPlot.DotNet.Interactive.KernelExtensions/XPlot.DotNet.Interactive.KernelExtensions.csproj#L14
* Make your changes in `Xplot.Plotly` 
* Rebuild `dotnet-interactive.csproj`

To try out your changes in a notebook:

* This script is useful for rebuilding and reinstalling the tool: https://github.com/dotnet/interactive/blob/master/src/dotnet-interactive/build-and-install-dotnet-interactive.ps1, which is a decent approach for using your dev build in Jupyter.
* But that won't work in the VS Code extension, which uses its own install of `dotnet-interactive`. What I've been doing in that case is that I put this in my settings file (C:\Users\USERNAME\AppData\Roaming\Code - Insiders\User\settings.json): 

```json
{
    "dotnet-interactive.kernelTransportArgs": [  
        "dotnet",
        "C:\\dev\\interactive\\src\\dotnet-interactive\\bin\\Debug\\netcoreapp3.1\\Microsoft.DotNet.Interactive.App.dll",
        "stdio",
        "--http-port-range",
        "1000-3000",
        "--log-path",
        "c:\\temp\\"
    ]
}
```

Let us know if that helps.

**Comment by mscottford** [comment]
Thank you so much. I'll give this a go and report back.

**Comment by mscottford** [comment]
Going fairly well so far. A heads up that this [commit](https://github.com/fslaborg/XPlot/commit/1344082da0d3137ae450c4f97d804e0b89f43988#diff-2b5d8231f28ffb2e4fecb3ff22a555bb) is going to break any references to `XPlot.Plotly.Graph`, because it has been refactored out of the project. 

I suggest changing [PowerShellKernel:65](https://github.com/dotnet/interactive/blob/master/src/Microsoft.DotNet.Interactive.PowerShell/PowerShellKernel.cs#L65) to this (or something similar):

```
foreach (Type type in typeof(Trace).Assembly.GetTypes().Where(t => t.BaseType == typeof(Trace)))
```

That assumes that you all keep a direct dependency on XPlot.Plotly, and you want to add support to the version post `3.0.1`.

With that, I have everything building with one test failure that I _think_ is related to `XPlot.Plotly.Graph` going away. Now on to trying to get it to run in a notebook locally.

**Comment by mscottford** [comment]
That worked! I needed to modify the reinstall script (https://github.com/dotnet/interactive/blob/master/src/dotnet-interactive/build-and-install-dotnet-interactive.ps1) to join paths using `Join-Path`, since I'm running on macOS. But I was able to get the graph that I was looking for. 

This is a _huge_ help. Thank you _so_ much!

**Comment by jonsequitur** [comment]
You're welcome! Glad it helped.  

Would you like to PR your fixes?

**Comment by colombod** [comment]
@mscottford thank you for the feedback!

would love to merge a PR from you on this!

**Comment by mscottford** [comment]
@colombod I'm happy to. I'll send those in later this week. I'll do one for the change to the install script and another for the changes as a result of compiling against XPlot.Plotly vNext.

**Comment by colombod** [comment]
> @jonsequitur and @colombod I'm happy to submit a PR. I'll send those in later this week. I'll do one for the change to the install script and another for the changes as a result of compiling against XPlot.Plotly vNext.

Super amazing, what new feature would this light up? Very excited

**Comment by mscottford** [comment]
My apologies for sitting on this. I haven't forgotten about it.

> Super amazing, what new feature would this light up? Very excited

The next version of XPlot is very likely to have breaking changes, based on the current state of their default branch. One of my PRs will get started addressing those. I'm not sure what all's included in the vNext, but I added the ability to correctly generate stacked area charts, such as this: https://plotly.com/javascript/filled-area-plots/#stacked-area-chart.

My other PR is going to make it possible to run `build-and-install-dotnet-interactive.ps1` directly on macOS, because it'll use the correct path separator when joining paths together.

**Comment by jonsequitur** [comment]
Related, per my comment above: #582. 

@cartermp

**Comment by jonsequitur** [comment]
Xplot.Plotly integration is now provided by an external package, [Xplot.Plotly.Interactive](https://www.nuget.org/packages/XPlot.Plotly.Interactive/), which you can install in your notebook using the following:

```csharp
#r "nuget:xplot.plotly.interactive"
```
