### ISSUE TITLE
The first console output is not displayed when VS Code notebook is first started

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#537]
If the first command sent to the kernel writes console output, that console output is not displayed in VS Code. Rerunning the same cell will display the output. This can be reproduced in PowerShell and C#. I haven't been able to repro it in F# or in Jupyter.

**Comment by brettfo** [comment]
Can you attach your `.dib` file?  I'm seeing the expected output with the first execution being `Console.WriteLine(1234);`

**Comment by jonsequitur** [comment]
I can no longer repro the issue.
