### ISSUE TITLE
Timer is not reset when you create a new cell

### ISSUE THREAD

**Issue by alexandair** [dotnet/interactive#546]
### Describe the bug
Timer is not reset when you create a new cell. (see a screenshot)

**Which version of .NET Interactive are you using?**
.NET Interactive version 1.0.131505

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
<img width="314" alt="timer" src="https://user-images.githubusercontent.com/3135708/84753115-e347c500-afbe-11ea-8ad1-e9e7d7f11f7f.png">

**Comment by jonsequitur** [comment]
![issue-546](https://user-images.githubusercontent.com/547415/84837974-2a997a00-afee-11ea-9d30-665ab1175e8f.gif)

**Comment by brettfo** [comment]
Not something we have control over.  Migrated to microsoft/vscode#100339.
