### ISSUE TITLE
Allow a user to copy part of the cell's output

### ISSUE THREAD

**Issue by alexandair** [dotnet/interactive#547]
**Is your feature request related to a problem? Please describe.**
Right now it's possible to select text in the cell's output, but you cannot copy it to the clipboard.
Ctrl+C doesn't work. Right-click is unavailable.

When you use Enter-AzShell to connect to Azure Cloud Shell, you cannot copy the code for device-based login.

**Describe the solution you'd like**
Ctrl+C and right-click enable a user to copy text from the cell's output. Or, at least one of those methods will work.

**Comment by jonsequitur** [comment]
Is this happening in VS Code?

**Comment by alexandair** [comment]
@jonsequitur Yes, in VS Code. I couldn't find a way to copy device-based login code to clipboard.

**Comment by jonsequitur** [comment]
I've noticed this as well. @rebornix @brettfo Is this a known issue and do we know where the problem is?

**Comment by brettfo** [comment]
Looks like it's something beyond our control up at the VS Code Layer: microsoft/vscode#99398.

**Comment by alexandair** [comment]
@brettfo Interestingly, in Azure Data Studio's (which is a fork of Code) notebooks at least Ctrl+C is working.
