### ISSUE TITLE
Notebook taking a long time to run code

### ISSUE THREAD

**Issue by mizuniga** [dotnet/interactive#548]
### Describe the bug
Please provide as much information as you can.
On both Binder and VS Code, I had multiple instances where it would take anywhere from 5s to 60s to run code blocks. An example would be the import statements in the Housing sample provided where it took 60s to run the nuget install on VS Code and 17s to run it on Binder. The second time running the code block immediately after, VS Code took about 1.7s and Binder took about 5s

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
1.0.1311

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [x] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
![812da067-9915-4c46-bf61-1362f81d15c5](https://user-images.githubusercontent.com/63324229/84826715-367a4180-afd8-11ea-943d-a49619b29f42.jpg)

**Comment by colombod** [comment]
We have been doing some performance tuning work now I can see this performance

![image](https://user-images.githubusercontent.com/375556/88200776-846d0f80-cc3e-11ea-8c9d-0329729a84ef.png)

Have you updated to latest version lately, could you check if the performance issue is still there?

Note that performance of a cell that performs package loading can be affected by network state and local caching
