### ISSUE TITLE
Binder Dependencies folder doesn't exist

### ISSUE THREAD

**Issue by mizuniga** [dotnet/interactive#555]
### Describe the bug
Please provide as much information as you can.
In the CreateBinder.md file, it mentions that you can use the Dockerfile and Nuget.Config in the Binder Dependencies folder but when going into the Interactive repo, one cannot find that folder. Instead the files are located in interactive/samples/my binder

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
interactive repo
* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

- OS
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [x] Other (please specify)

**Comment by mizuniga** [comment]
@LadyNaggaga

**Comment by colombod** [comment]
Hi, look at this [folder](https://github.com/dotnet/interactive/tree/master/samples/my%20binder)

![image](https://user-images.githubusercontent.com/375556/85055706-e517b100-b195-11ea-9725-43ccc97132e9.png)

That is the files you need to use

**Comment by colombod** [comment]
The document is updated now
