### ISSUE TITLE
[EXTERNAL] VSCode keeps cell metadata from previous code block to new one

### ISSUE THREAD

**Issue by mizuniga** [dotnet/interactive#556]
### Describe the bug
Please provide as much information as you can.
When I was using Notebook on VSCode, I ran one of my code blocks and when given the output, I was also given the green check mark with the amount of time it took to run as expected. However, when I made a new code block beneath the one just run, the check mark with the amount of time copied over to the new code block even though there is no code

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
1.0.131105+4b51834efbfb21cfc9b2f83feaf1381d518b8443
* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/63324229/84960499-a3640900-b0b6-11ea-977b-213a5b6d03c9.png)

**Comment by mizuniga** [comment]
@LadyNaggaga

**Comment by jonsequitur** [comment]
This is a VS Code bug: https://github.com/microsoft/vscode/issues/100339

**Comment by colombod** [comment]
@brettfo what are your thoughts?

**Comment by brettfo** [comment]
Doesn't seem to repro anymore.
