### ISSUE TITLE
Differences in display logic online and local

### ISSUE THREAD

**Issue by BillWagner** [dotnet/interactive#557]
The issue is best observed on [this branch](https://github.com/BillWagner/try-samples/tree/linq-notebook)

I'm working on updating a LINQ tutorial to be more visual. This shows the effects of using LINQ methods to "shuffle" a deck of cards. After each shuffle, the deck is redisplayed.

There are major differences in the rendering depending on the environment:

- When I run locally in Jupyter Lab, the final cell updates the same space in the page to show how the cards are re-arranged in each shuffle. 
- At binder.org, in lab mode, the final cell runs to completion, but does not update the space above the cell.
- Locally in Jupyter notebook, the card display updates as a single column. Each shuffle is displayed.
- Online in notebook mode, the card display is a single column when the deck is first displayed. However, when the final cell executes, the display locations don't update.

### Please complete the following:

**Which version of .NET Interactive are you using?** 

Version: 1.0.131602+4499f850afa38e598630719e20ae0cb6a8898472
Build date: 2020-06-17T17:37:18.5307537Z

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [X] Jupyter Notebook
    - [X] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

This is the local version:

![image](https://user-images.githubusercontent.com/493969/85068802-0621d700-b181-11ea-884b-f9858211fee7.png)

**Comment by colombod** [comment]
@BillWagner can you post screenshots for the other scenarios?

**Comment by BillWagner** [comment]
Here's the notebook version at mybinder.org:  (All 52 cards are in a single column. And after running the last cell, the "number of shuffles" text still shows "0" shuffles):

<img width="938" alt="Screen Shot 2020-06-18 at 20 42 49" src="https://user-images.githubusercontent.com/493969/85084993-71c96b80-b1a4-11ea-9547-36136931fcd9.png">

**Comment by colombod** [comment]
are online and local all same version of jupyter and jupyter lab?

**Comment by BillWagner** [comment]
Online version:

> Version: 1.0.126104+2b7b465575ad2085df7dc7efea7a1e72afbbf380
> Build date: 2020-05-12T00:41:54.0000000Z

Local version:

> Version: 1.0.131602+4499f850afa38e598630719e20ae0cb6a8898472
> Build date: 2020-06-17T17:37:18.5307537Z

How do I get the online version updated? Is that in the dockerfile?

**Comment by colombod** [comment]
We can update the online tool no problem but I am asking about the jupyter lab and jupyter notebook version our code emits the xml the card formatter produces and the message is the same , the integration with the front end is done on the web page by the hosting code. I am trying to narrow down the differences that lead to such different behaviours

**Comment by colombod** [comment]
> Online version:
> 
> 
> 
> > Version: 1.0.126104+2b7b465575ad2085df7dc7efea7a1e72afbbf380
> 
> > Build date: 2020-05-12T00:41:54.0000000Z
> 
> 
> 
> Local version:
> 
> 
> 
> > Version: 1.0.131602+4499f850afa38e598630719e20ae0cb6a8898472
> 
> > Build date: 2020-06-17T17:37:18.5307537Z
> 
> 
> 
> How do I get the online version updated? Is that in the dockerfile?

Yes the online version is the one from the docket file in your repo

**Comment by BillWagner** [comment]
The local version of Jupyter lab is 1.1.4.
The local version of Jupyter notebook is 6.0.3

The online version of Jupyter lab is 2.1.3
The only version of Jupyter notebook is 6.0.3

**Comment by colombod** [comment]
can you se this in the docker file
```
FROM jupyter/base-notebook:latest

# Install .NET CLI dependencies

ARG NB_USER=jovyan
ARG NB_UID=1000
ENV USER ${NB_USER}
ENV NB_UID ${NB_UID}
ENV HOME /home/${NB_USER}

WORKDIR ${HOME}

USER root
RUN apt-get update
RUN apt-get install -y curl

ENV \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true \
    # Enable correct mode for dotnet watch (only mode supported in a container)
    DOTNET_USE_POLLING_FILE_WATCHER=true \
    # Skip extraction of XML docs - generally not useful within an image/container - helps performance
    NUGET_XMLDOC_MODE=skip \
    # Opt out of telemetry until after we install jupyter when building the image, this prevents caching of machine id
    DOTNET_TRY_CLI_TELEMETRY_OPTOUT=true

# Install .NET CLI dependencies
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libc6 \
        libgcc1 \
        libgssapi-krb5-2 \
        libicu66 \
        libssl1.1 \
        libstdc++6 \
        zlib1g \
    && rm -rf /var/lib/apt/lists/*

# Install .NET Core SDK
RUN dotnet_sdk_version=3.1.301 \
    && curl -SL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Sdk/$dotnet_sdk_version/dotnet-sdk-$dotnet_sdk_version-linux-x64.tar.gz \
    && dotnet_sha512='dd39931df438b8c1561f9a3bdb50f72372e29e5706d3fb4c490692f04a3d55f5acc0b46b8049bc7ea34dedba63c71b4c64c57032740cbea81eef1dce41929b4e' \
    && echo "$dotnet_sha512 dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -ozxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet \
    # Trigger first run experience by running arbitrary cmd
    && dotnet help
```

and then you keep going on copying notebooks and all ?

**Comment by colombod** [comment]
made this [PR](https://github.com/BillWagner/try-samples/pull/1)

**Comment by BillWagner** [comment]
I'll give this a try.

**Comment by BillWagner** [comment]
@colombod and I worked through a solution on Friday:

The problem is that any cell must be written to using `display(...)` to assign a variable in the same cell before using `location.Update()` to update the HTML.

The updated code is now in the original branch, and will be in this repo under `notebooks/LINQ/index.ipynb`

I'll close this.
