### ISSUE TITLE
Instructions in bug_report.md file are not accurate

### ISSUE THREAD

**Issue by alexandair** [dotnet/interactive#562]
```
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.
```
The first of these two ways to determine the version of the .NET Interactive tool is not valid for VS Code. VS Code extension install its own version of the tool and doesn't use the global tool.

Command palette in VS Code doesn't return the "Report installed version for .NET Interactive" command.

**Comment by alexandair** [comment]
@colombod Is this fixed?

**Comment by colombod** [comment]
That entry is fixed from what I can see the readme doesn't contain that url anymore
