### ISSUE TITLE
Bugs in tabular display of heterogeneous values (C#, F#), also other possible improvements

### ISSUE THREAD

**Issue by dsyme** [dotnet/interactive#569]
I'm running through the F# getting started notebook, it's great!

I noticed that a heterogeneous list of F# discriminated union values is printing incorrectly

```
type Shape =
    | Rectangle of width: float * length: float
    | Circle of radius: float
    | Prism of width: float * height: float * faces: int
    
let rect = Rectangle(length = 1.3, width = 10.0)
let circ = Circle (1.0)
let prism = Prism(width = 5.0, height = 2.0, faces = 3)
        
[prism; circ; rect]
```
gives this incorrect display:

![image](https://user-images.githubusercontent.com/7204669/85421808-c25a1380-b56c-11ea-8d08-9d3ad6c726b7.png)

Also they are printing with `Tag`, `IsXYZ` values.

For a heterogeneous collection of objects I guess I would expect to see something like this, where the properties have been collected, sorted alphabetically and empty values if the properties are not present?

|   Kind | faces  | height | length | radius |  width |
|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| Prism  | 3   |   2.0  |    |  |  5.0  |
| Rectangle |    |     | 1.3  |   | 10.0  |  
| Circle |    |     |  |  1.0 |   | 

Besides the bug, my questions are:

1. Can the F# kernel control this, if so could someone point me to the code?  Or is it generic for C# and C#?

2. What .NET metadata is the default printer using to choose columns and fill the values?

![image](https://user-images.githubusercontent.com/7204669/85420333-f7fdfd00-b56a-11ea-9699-00e7a761c820.png)

**Comment by dsyme** [comment]
Actually the printing is buggy for heterogeneous objects, e.g.

```
type Shape =
    | Rectangle of width: float * length: float
    | Circle of radius: float
    | Prism of width: float * height: float * faces: int
    
let rect = Rectangle(length = 1.3, width = 10.0)
let circ = Circle (1.0)
let prism = Prism(width = 5.0, height = 2.0, faces = 3)
        
[prism; circ; rect]
```
gives this incorrect display:


![image](https://user-images.githubusercontent.com/7204669/85421808-c25a1380-b56c-11ea-8d08-9d3ad6c726b7.png)

**Comment by colombod** [comment]
@dsyme the best way would be to provide a custom formatter, I would probably add something like UseFSharpTypesFormatters() to the [FSharpKernelExtensions.fs](https://github.com/dotnet/interactive/blob/adc3185cdf200ffe261217d8a33951f087d8cb6e/src/Microsoft.DotNet.Interactive.FSharp/FSharpKernelExtensions.fs#L18) file.

The function there should define formatter using the formatter api like we do for [xplot](https://github.com/dotnet/interactive/blob/adc3185cdf200ffe261217d8a33951f087d8cb6e/src/dotnet-interactive/KernelExtensions.cs#L81).

Finally use that in the composition [code](https://github.com/dotnet/interactive/blob/adc3185cdf200ffe261217d8a33951f087d8cb6e/src/dotnet-interactive/CommandLine/CommandLineParser.cs#L449)

**Comment by dsyme** [comment]
SO there are three issues 

1. the selection of properties for .NET objects

2. the printing of heterogeneous .NET objects (objects of different types) where the columns get mixed up 

3. the selection of properties to show for F# discriminated union values (we should also look at other F#-specific values)

Issues 2 is the most serious bug because it affects C# as well, see below

```
new object[] { System.DateTime.Now, "abc" }
```

gives this - note that the string has the "Date" column filled with its value??

![image](https://user-images.githubusercontent.com/7204669/85423552-bcfdc880-b56e-11ea-8e71-169265bb8d78.png)

With regard to (1) we just have a problem that way too many properties are being shown by default for basic values like Dates.  This will affect both C# and F# as shown by the Date example.

Ideally .NET types would just come with the metadata we need to give a good display.  As things stand we'll have to make use of good use of existing metadata and good heuristics I think 

But first bug (2) should be fixed.

**Comment by dsyme** [comment]
Here is another issue, it applies to F# at least:

```
type C() = 
    member x.P = failwith "fail"
```
then 
```
C()
```

The code tries to display the property `P` but some really strange exception happens
```

{ System.Exception: TargetSite: { System.Reflection.RuntimeMethodInfo: Name: get_P, DeclaringType: FSI_0007+C, ReflectedType: FSI_0007+C, MemberType: Method, MetadataToken: 100663307, Module: { System.Reflection.Emit.InternalModuleBuilder: MDStreamVersion: 131072, FullyQualifiedName: <In Memory Module>, ModuleVersionId: ec42a498-aeaf-4dff-9d8b-0f805b2dd666, MetadataToken: 1, ScopeName: RefEmit_InMemoryManifestModule, Name: <In Memory Module>, Assembly: { System.Reflection.Emit.InternalAssemblyBuilder: Location: { System.NotSupportedException: TargetSite: System.String get_Location(), StackTrace: at System.Reflection.Emit.InternalAssemblyBuilder.get_Location() at lambda_method(Closure , InternalAssemblyBuilder ) at Microsoft.DotNet.Interactive.Formatting.PlainTextFormatter.<>c__DisplayClass3_0`1.<CreateFormatDelegate>g__FormatObject\|1(T target, TextWriter writer) in ```

**Comment by jonsequitur** [comment]
Regarding the exception display, what's happening is it's displaying the exception that was caught while trying to evaluate `P`:

![image](https://user-images.githubusercontent.com/547415/86076939-e2437880-ba3f-11ea-8967-d395974b4e2a.png)

This is pretty hard to read. What sort of display would be more useful?
