### ISSUE TITLE
SqlClientFactory.Instance is null when using Microsoft.Data.SqlClient in Jupyter C# Kernel

### ISSUE THREAD

**Issue by aslotte** [dotnet/interactive#59]
#### Describe the bug
I attempted to load data from a SQL Server DB using the DatabaseLoader from a Jupyter Notebook.
I was first using System.Data.SqlClient as the ProviderFactory, but I got multiple re-direct issues in Jupyter. I moved to Microsoft.Data.SqlClient, which is supposed to work better with .NET Core and continued passed that issue. However, I instead run in to an issue where it says the provider factory is null.

#### Did this error occur while using `dotnet try` or online?
- [X] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [X] Other:

#### Screenshots
![image](https://user-images.githubusercontent.com/30201569/67637352-3ba34880-f8b0-11e9-8a65-db2b5e5d1702.png)

#### Please complete the following:
 - OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by KevinRansom** [comment]
@aslotte,

hi, I just tried to repro this with the latest master branch.  We have done a ton of work on the package management, and it seems as if this now works fine.

Please reopen this, if you are still having trouble with this.

Thanks

Kevin
![image](https://user-images.githubusercontent.com/5175830/78200547-df86b680-7443-11ea-9f19-f8c617f395df.png)

**Comment by devssharma** [comment]
I have facing issue with .net core 2.1 version, I am getting null of SqlClientFactory.Instance so that not able to register the System.Data.SqlClient data provider into factory. 

DbProviderFactories.RegisterFactory(
                "System.Data.SqlClient", SqlClientFactory.Instance);

In .net core 3.1 version it's working fine. but i need to use .net core 2.1
