### ISSUE TITLE
Using the .NET kernel with a Windows store installed python and jupyter is broken

### ISSUE THREAD

**Issue by rchiodo** [dotnet/interactive#612]
### Describe the bug
1. Install python from the windows store
1. Install jupyter using pip (important, make sure not other versions of jupyter are installed)
1. Install .net kernel
1. Run jupyter notebook and try to switch to a .net kernel.

This error will pop out:
[I 16:17:45.605 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
File does not exist: C:\Users\rchiodo.REDMOND\AppData\Roaming\jupyter\runtime\kernel-e62fdf2f-ca02-4611-b38d-a363a8cdff10.json

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
1.0.126302+9e8f007038a86132f72a94889d805be2a14addf2

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [x] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

I believe the root cause of this problem is this bug here:
https://bugs.python.org/issue41196

**Comment by rchiodo** [comment]
Python kernels don't seem to have this problem as they are using the same version of python as jupyter (which will find the appdata directory correctly)

**Comment by colombod** [comment]
I am not sure if I understood.

When you install the the .NET kernels using dotnet interactive jupyter install is it discovering the right paths?

Judging by the version you are using a .NET interactive from may, there was additional work done to discover install locations. can you install latest from myget feed?

**Comment by rchiodo** [comment]
Installing the kernels works fine. Running them doesn't. 

The error is in the file that jupyter passes to you on startup:
```C:\Users\rchiodo.REDMOND\AppData\Roaming\jupyter\runtime\kernel-e62fdf2f-ca02-4611-b38d-a363a8cdff10.json```

That is not the actual path with a Windows Store python. The Windows Store python is redirecting %APPDATA% to something like: 
```
C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Roaming\jupyter\runtime ...
```

**Comment by rchiodo** [comment]
This probably isn't something the .NET kernel should handle. 

Personally I think
- Jupyter needs to call 'os.path.realpath' on the file path before it passes it to you.
or
- Window store Python needs to stop redirecting the APPDATA folder.

**Comment by rchiodo** [comment]
Sorry @colombod when you said this:
> Judging by the version you are using a .NET interactive from may, there was additional work done to discover install locations. can you install latest from myget feed?

Did you also mean changes to handle the json file passed when starting up? As you guys explicitly handle the scenario where Jupyter's %APPDATA% folder is redirected?

I can try a newer version if that's the case.

**Comment by jonsequitur** [comment]
@rchiodo, our install heuristics changed about a month ago and the latest version may handle this better. Please give it a try and let us know if it works any better.

**Comment by rchiodo** [comment]
I tried 1.0.135401+21f25d9a0a88df33f395e94e88526fdacdd31989. Same results. I believe this is not an install issue. It's a runtime issue.

When starting a kernel, jupyter will launch the executable specified in the kernel.json. In this case (for me), this value is like so:

```
"resource_dir": "C:\\Users\\rchiodo.REDMOND\\AppData\\Roaming\\jupyter\\kernels\\.net-csharp",
      "spec": {
        "argv": [
          "dotnet",
          "interactive",
          "jupyter",
          "--default-kernel",
          "csharp",
          "--http-port-range",
          "1000-3000",
          "{connection_file}"
        ],
        "env": {},
        "display_name": ".NET (C#)",
        "language": "C#",
        "interrupt_mode": "signal",
        "metadata": {}
```

That works fine. The problem is the ```{connection_file}``` argument. Jupyter is sending this file here as the connection file argument.

```
C:\Users\rchiodo.REDMOND\AppData\Roaming\jupyter\runtime\kernel-641b5a38-230d-4842-9c6e-85dc6c44fa24.json
```

However, because jupyter is running from the 'store' python, that directory is actually this one:

```
"C:\Users\rchiodo.REDMOND\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Roaming\jupyter\runtime\kernel-641b5a38-230d-4842-9c6e-85dc6c44fa24.json"
```

Jupyter is not sending your kernel a path that it can find. 

For a python kernel, that file works because the python kernel is launched with the same store app as jupyter itself.

The root cause of this is the fact that Windows is redirecting writes to %APPDATA% to a different directory for store apps.

**Comment by jonsequitur** [comment]
Do you have a sense of why the file can't be read? Is it a permissions problem? As far as I know, .NET Interactive does nothing special with that file path. I wouldn't expect `%APPDATA%` being redirected to affect .NET Interactive in and of itself.

**Comment by rchiodo** [comment]
Sorry maybe this isn't clear. 

If you run this code in a python app (which is essentially what jupyter is doing to create the running/kernel.json that they pass to your kernel)

```
os.listdir(os.environ['APPDATA'])
```

you will get different results from a 'store' installed python versus a normal installed python.

The file path that Jupyter is passing you does not actually exist.

**Comment by rchiodo** [comment]
This all has to do with Windows redirecting writes to %APPDATA% when running in a store app. So under the covers, jupyter is doing something like so:

```
filePath = '%APPDATA%\Jupyter\Running\kernel.json'
writeRunningData(filePath)
runDotNetKernel(filePath)
```

That filePath is not the ```real``` file path. That's the crux of the problem. It's because Jupyter does not know the file has been redirected so they can't tell you about the real path.

**Comment by rchiodo** [comment]
And the default python kernel does not have this problem because the invalid path is findable by its python (well because it's running the same store python). 

So for a python kernel a path like this:

```
C:\Users\rchiodo.REDMOND\AppData\Roaming\jupyter\runtime\kernel-641b5a38-230d-4842-9c6e-85dc6c44fa24.json
```

will be resolved by Windows to this:

```
C:\Users\rchiodo.REDMOND\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Roaming\jupyter\runtime\kernel-641b5a38-230d-4842-9c6e-85dc6c44fa24.json
```

**Comment by colombod** [comment]
The question is then if any other kernels that are not the python one are actually working in your scenario. Have you tried to install kernels like Q# ?

**Comment by rchiodo** [comment]
No I haven't tried others, but they would have the same problem. 

In fact running 'jupyter notebook' has a problem as well.

It tries to send a file like so to the browser:
```
file:///C:/Users/Rich/AppData/Roaming/jupyter/runtime/nbserver-7004-open.html
```

That path is not readable by the browser as it's really 
```
file:///C:/Users/Rich/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/Roaming/jupyter/runtime/nbserver-7004-open.html
```

**Comment by rchiodo** [comment]
Seems this also fails with the Julia kernel. I'm going to submit a PR to Jupyter in order to fix it there.

**Comment by colombod** [comment]
Makes sense, thank you for your extensive testing!
