### ISSUE TITLE
Support spaces after `%%` in magic commands

### ISSUE THREAD

**Issue by cartermp** [dotnet/interactive#62]
You can specify magic commands without a space (e.g., `%%time`) without issue. But specifying it with a space yields an error in both C# and F#:

![image](https://user-images.githubusercontent.com/6309070/67710283-e84afc00-f97c-11e9-92fb-aa9d9a1a3530.png)

![image](https://user-images.githubusercontent.com/6309070/67710296-ec771980-f97c-11e9-9388-39f2aae20f70.png)

**Comment by colombod** [comment]
Closing this issue as the directive feature have changed
