### ISSUE TITLE
No completions for instances in F#

### ISSUE THREAD

**Issue by colombod** [dotnet/interactive#620]
### Describe the bug
Bug #607 is still present for F#

### Please complete the following:

**Which version of .NET Interactive are you using?** 
1.0.135702

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code
    - [ ] Other (please specify)

**Comment by brettfo** [comment]
Dependent on dotnet/fsharp#9644.
