### ISSUE TITLE
Hover text does not contain documentation (C#)

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#628]
![image](https://user-images.githubusercontent.com/547415/87064162-2f53e700-c1c4-11ea-9f67-100e9950a369.png)

**Comment by onionhammer** [comment]
Is this sort of intellisense also covered under this goal?

Where if as you type (as opposed to 'hover'), it should show the arguments and overloads of the method you're invoking?

![image](https://user-images.githubusercontent.com/969938/95661212-3d7f0f80-0af3-11eb-8263-879ffa9934b5.png)

**Comment by jonsequitur** [comment]
@onionhammer, what your screen shot shows is called signature help. We have a separate issue for that:  #728.
