### ISSUE TITLE
Drop `Microsoft` from namespaces in the programming model

### ISSUE THREAD

**Issue by dsyme** [dotnet/interactive#643]
I suggest that .NET Interactive simply drop `Microsoft` from the namespaces in the programming model.

Current: `Microsoft.DotNet.Interactive.*`
Suggestion: Just use just `DotNet.Interactive.*`.  

Why: 

1. The use of `Microsoft` for a namespace qualifier for neutral, open source, collaborative  .NET technologies and tooling is inappropriate in 2020.   THis is an open source technology, not a Microsoft proprietary technology.  

2. The use of `Microsoft` as a namespace qualifier on DLLs and namespaces is a long and ugly legacy of a rather unfortunate set of guidelines that got created long before .NET was open source tech. We should not be trapped by decisions that capture the mindset of 2001.  If necessary policies can change.

3. If any other company were contributing and making this tech as a .NET core technology we would not expect `Adobe.` or `Facebook` to go on the front.  

4. In the open source world the neutral technology is the primary qualifier in matters of naming.  Not the company.  That's now well-established practice across the industry.

5. I'm not sure of current "policy" (though it should change whatever it is), but there are now hundreds of examples where .NET is a neutral lead identifier, e.g. .NET is in `https://github.com/dotnet` and so on.

As background, we went around and around this for F#.  In the end the F# programming model uses just `FSharp.*` (though there is an unfortunate backward compat issue where the namespaces in the actual DLL use `Microsoft.FSharp`, though we would drop that if we could).  .NET has taken the same journey.   To repeat: in the open source world a neutral technology acts as the primary qualifier in matters of naming.

I personally think it's really essential to make this change to properly position .NET Interactive as a neutral, broad technology and also to stand up for what's right for the future of the .NET ecosystem)

If necessary we can get opinions from @richlander, @terrajobst and others?

**Comment by dsyme** [comment]
We really need to do this. This would look so much better than with the company prefix.

    open DotNet.Interactive.FSharp.FSharpPocketViewTags

**Comment by davidfowl** [comment]
Why does it even need DotNet.

**Comment by dsyme** [comment]
@davidfowl In my eyes the top namespace should be:

1. a neutral organisation moniker (DotNet for .NET Foundation matching "dotnet", `FSharp` for F# Foundation matching "fsharp")
2. a company (Microsoft) 
3. a technology (OxyPlot)

Using the name of the technology here would lead to "DotNetInteractive.*" 

Using the name of the organisation would lead to "DotNet.*"

Using the name of the company would lead to "Microsoft.*"
