### ISSUE TITLE
F# - Too many namespaces opened by default

### ISSUE THREAD

**Issue by dsyme** [dotnet/interactive#645]
I'm looking over the source for the F# kernel and I notice that `FSharpPocketViewTags` is opened by default, e.g. through this list in `UseDefaultFormatting`.  This brings into scope a swathe of HTML tags like `a` and `area`. 

We should not be doing this in the default programming model and it won't create a programming experience that will last the test of time, even if it marginally improves demos.  People won't know where these values are coming from or what they are for, and they might very easily collide with other programming models.  

In any case, F# basically already has its own point of view on default-opened namespaces for a programming model.  It's ok to add `FSharpKernelHelpers` to this but I would expect pretty much everything else to be explicitly opened.

For C# I think you should discuss with the C# designers - this is an issue for the basic concept of the C# scripting programming model and the defaults really impact on the reusability of script-like assets across different settings.

Here is the current list of explicit opens:

    // From UseDefaultNamespaces
    open System
    open System.Text
    open System.Threading.Tasks
    open System.Linq

    // From UseKernelHelpers
    open Microsoft.DotNet.Interactive.FSharp.FSharpKernelHelpers

    // From UseDefaultFormatting
    open Microsoft.AspNetCore.Html 
    open Microsoft.DotNet.Interactive.FSharp.FSharpPocketViewTags 
    open XPlot.Plotly
    open Microsoft.DotNet.Interactive.Formatting

Of these, I feel they categorise as follows:

##### Definitely not:

    open Microsoft.AspNetCore.Html 
    open Microsoft.DotNet.Interactive.FSharp.FSharpPocketViewTags 
    open XPlot.Plotly
    open Microsoft.DotNet.Interactive.Formatting

##### Probably not (for F# code)

    open System.Threading.Tasks
    open System.Linq

##### Probably ok (for F# code)

    open System
    open System.IO
    open System.Text

##### Definitely ok:

    open Microsoft.DotNet.Interactive.FSharp.FSharpKernelHelpers

**Comment by gbaydin** [comment]
> People won't know where these values are coming from or what they are for, and they might very easily collide with other programming models.

I can confirm. I've been confused about where the list of names I keep seeing in autocomplete come from.

**Comment by KevinRansom** [comment]
Don has already fixed this,

For F# the default namespaces are:
````
System
System.IO
System.Text
Microsoft.DotNet.Interactive.Formatting
````

For C# the default namespaces are:
````
System
System.IO
System.Text
Microsoft.DotNet.Interactive.Formatting
````
