### ISSUE TITLE
error NU1101: Unable to find package System.Collections.Generic. No packages exist with this id in source(s): nuget.org

### ISSUE THREAD

**Issue by praveenraghuvanshi** [dotnet/interactive#648]
### Describe the bug
Recently installed  dotnet-interactive and tried to install package 'System.Collections.Generic.' in jupyter notebook. It's giving error NU1101. Same cell execution for 'System' works. 

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.115407+d247e88f3f756abad4bd16b47cf8cde187aafabc
Build date: 2020-07-14T22:52:12.8236468Z
https://github.com/dotnet/interactive

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [x] Jupyter Notebook
    - [x] Jupyter Lab
    - [x] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/66641548/87484467-dec10b80-c653-11ea-8852-0df7e79f82b3.png)

**Comment by jonsequitur** [comment]
The `System` and `System.Collections.Generic` namespaces are already available and don't need to be referenced using `#r`.
