### ISSUE TITLE
.Net interactive Notebooks won't render correctly in the Azure DevOps Repository View

### ISSUE THREAD

**Issue by constantinhager** [dotnet/interactive#649]
### Describe the bug
If I create a .dib file in VSCode and push that to an Azure DevOps repository
the rendering of that format does not work.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
1.0.115407+d247e88f3f756abad4bd16b47cf8cde187aafabc

- OS
    - [ x ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ x ] Edge
    - [ x ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ x ] Other (please specify) Azure DevOps Repository View

### Screenshots
![grafik](https://user-images.githubusercontent.com/19409495/87710423-0c1dce80-c7a6-11ea-8850-2569f600dd09.png)

Am I missing something? Can I install an extension to make that work? Is It not implemented yet?

Thank you

**Comment by zyzhu** [comment]
I'm using this extension on Azure DevOps repo.
https://marketplace.visualstudio.com/items?itemName=ms-air-aiagility.ipynb-renderer

A guy from Microsoft developed it but didn't get too much traction.
https://github.com/Azure/ipynb-renderer

But it only supports previewing Python notebook. Maybe it's worthwhile to expand it to support other notebooks as well as dib file.

**Comment by jonsequitur** [comment]
@constantinhager In the .NET Interactive Notebooks extension for VS Code, you can export to .ipynb, and we're working on directly reading and writing .ipynb in VS Code. In order to not interfere with the existing VS Code Python support, we implemented the simple .dib format in the interim.

Do you have a preference of format and if so, what do you find useful about it?

**Comment by constantinhager** [comment]
OK. So the dib format is going away if you have 100 % compatibility with the .ipynb. Do I understand you correctly?
In that case I can convert to .ipynb. That can be rendered in Azure DevOps.
