### ISSUE TITLE
Enable copying of output

### ISSUE THREAD

**Issue by mjwsteenbergen** [dotnet/interactive#653]
**Is your feature request related to a problem? Please describe.**
Currently, in the vs-code extension, I am able to see the output. However, I am unable to copy the output to my clipboard.

**Describe the solution you'd like**
As a user, when I highlight text in the output and press Ctrl-c, I expect this text to be copied to my clipboard.

**Describe alternatives you've considered**
Going into the devtools and copying from there?

**Comment by jonsequitur** [comment]
This is a known VS Code issue: https://github.com/microsoft/vscode/issues/99398.

**Comment by jonsequitur** [comment]
Reopening for visibility until the VS Code issue is resolved.

**Comment by jonsequitur** [comment]
This is now working.
