### ISSUE TITLE
When does VSCode extension no longer need insiders version?

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/interactive#654]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want to use this without insiders version vscode.

**Comment by jonsequitur** [comment]
This will depend on the timeline for VS Code notebooks: https://code.visualstudio.com/api/extension-guides/notebook.

**Comment by claudiaregio** [comment]
The Polyglot Notebooks extension (formerly .NET Interactive Notebooks) is available in VS Code stable
