### ISSUE TITLE
My Binder does not detect C# Kernel

### ISSUE THREAD

**Issue by Expecho** [dotnet/interactive#655]
### Describe the bug
I created a C# notebook, copied the files from the [samples/my binder](https://github.com/dotnet/interactive/tree/master/samples/my%20binder) folder and followed the steps in the document "Share your notebooks on Binder" ([link](https://github.com/dotnet/interactive/blob/master/docs/CreateBinder.md)). Upon launch it tells me no C# Kernel is available. After that I tried using the Dockerfile and nuget.config from the root of this repo but it still does not work.

When I build and run the container manually on a local machine everything works fine.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [x] Jupyter Notebook
    - [x] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

### Reproduce
See [my repo](https://github.com/Expecho/DotNetInteractive)

**Comment by colombod** [comment]
I have followed the steps in the sample and create this [binder](https://mybinder.org/v2/gh/colombod/binder_test/master) using the repo you can access [here ](https://github.com/colombod/binder_test).

I just copied the files from the samples/my binder folder and added a notebook there.

![image](https://user-images.githubusercontent.com/375556/88088742-d0f31500-cb82-11ea-91ee-6a048fff264a.png)

and i have the following kernels available in jupyter

![image](https://user-images.githubusercontent.com/375556/88088810-e7996c00-cb82-11ea-974f-51c235649ebd.png)

Can you share you repo?

**Comment by Expecho** [comment]
Thanks for investigating @colombod . I did put a link to the repo at the bottom of the issue.

It is here: https://github.com/Expecho/DotNetInteractive

**Comment by colombod** [comment]
Your docker file is different from the one in our repo and I am using, did you see nay error / warning when you launched mybinder the first time? Could test using the same docker file I have in my binder_test repo?

**Comment by Expecho** [comment]
> Your docker file is different from the one in our repo and I am using, did you see nay error / warning when you launched mybinder the first time? Could test using the same docker file I have in my binder_test repo?

I've updated my docker file based on your version (I think that one is from the example in de .Net Interactive repo, but that didn't work for me) but it is still not working.

**Comment by colombod** [comment]
Don't know if binder is case sensitive in any way, the only difference I see is that my file is `Dockerfile` while your is `DOCKERFILE` but clearly binder is not using that docker file to build the image. As the server start is supposed to be set to use ~/notebooks as working directory.

My landing page will look like this
![image](https://user-images.githubusercontent.com/375556/88187824-ec1b5e80-cc2e-11ea-81d2-bceb0d48b457.png)

But with your binder instance I clearly land in ~/
![image](https://user-images.githubusercontent.com/375556/88187885-005f5b80-cc2f-11ea-87d0-254f5fa4aa79.png)

This is making me think that the docker file is not detected by the bonder tool, could you try address the casing?

**Comment by Expecho** [comment]
It is the casing! Changed the casing to match yours. Wow, did not expect that. Thanks for sorting this out and sorry for the inconvenience.
