### ISSUE TITLE
Missing /nbextensions/widgets/notebook/js/extension.js

### ISSUE THREAD

**Issue by darrenjrobinson** [dotnet/interactive#657]
### Describe the bug
#!javascript results in 404 GET /nbextensions/widgets/notebook/js/extension.js

### Please complete the following:

**Which version of .NET Interactive are you using?** 

```
Version: 1.0.136005+eb038ecb4877981ad1b17a7f6830868c0041aa11
Build date: 2020-07-10T18:53:44.0000000Z
```

![image](https://user-images.githubusercontent.com/384733/88121508-44d80080-cc09-11ea-9bd5-0c0d8a544c26.png)

- OS
    - [ ] Windows 10
    - [ ] macOS
    - [X ] Linux (Please specify distro) Ubuntu 18.04 LTS
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [X ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

```
You are using Jupyter notebook.

The version of the notebook server is: 5.7.8
The server is running on this version of Python:
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]
```

### Screenshots

![image](https://user-images.githubusercontent.com/384733/88121426-03dfec00-cc09-11ea-813b-205fb4375a0e.png)

![image](https://user-images.githubusercontent.com/384733/88121473-2245e780-cc09-11ea-9f8e-a1fe3226dd23.png)

**Comment by colombod** [comment]
I was able to execute it and use both promsie and async approach

![image](https://user-images.githubusercontent.com/375556/88186881-b9249b00-cc2d-11ea-8265-a7bfa0183f9a.png)


The only difference I have is the js code
```
#!js

(async () => {
    let output = document.getElementById("output");
    output.innerHTML = await interactive.pwsh.getVariable("hi");
})();
```

**Comment by darrenjrobinson** [comment]
It works for @jonsequitur too. But not for me. 
Only reason I can see is the error in the console

```
[W 21:25:47.058 NotebookApp] 404 GET /notebooks/work/undefinedresources/dotnet-interactive.js (172.17.0.1): No such file or directory: work/undefinedresources/dotnet-interactive.js
[W 21:25:47.059 NotebookApp] 404 GET /notebooks/work/undefinedresources/dotnet-interactive.js (172.17.0.1) 2.66ms referer=http://localhost:8888/notebooks/work/Untitled2.ipynb
```

**Comment by colombod** [comment]
one last thing to check is that I am on jupyter 6.03 and the error you are seeing is relate to require.js configuration. Is it possible for you to upgrade or that newer version

**Comment by darrenjrobinson** [comment]
I've updated to Jupyter 6.0.3 
![image](https://user-images.githubusercontent.com/384733/88241088-6fd75880-cccc-11ea-8122-a43b7166c43b.png)

Still no joy.
![image](https://user-images.githubusercontent.com/384733/88241153-a57c4180-cccc-11ea-8c20-04df6bc42940.png)

Same error in the console
![image](https://user-images.githubusercontent.com/384733/88241173-b3ca5d80-cccc-11ea-8f19-1c494e143298.png)

**Comment by darrenjrobinson** [comment]
Update.
I have it working on Windows. Here is my Windows Jupyter Env
![image](https://user-images.githubusercontent.com/384733/88492345-79730000-cfed-11ea-9ff2-d909ec463538.png)

![image](https://user-images.githubusercontent.com/384733/88492386-d53d8900-cfed-11ea-8d24-3a116b13ca9a.png)

However still no joy using Docker with a Linux Ubuntu 18.04 container. I've gone through and updated everything Jupyter related. Here is that Jupyter Env
![image](https://user-images.githubusercontent.com/384733/88492358-9dcedc80-cfed-11ea-91f9-2a89db6a4c05.png)

**Comment by colombod** [comment]
Hi, do you have the port mapping working? For that to work .NET Interactive needs to be reachable directly.

Loot at the documentation [here](https://github.com/dotnet/interactive/tree/master/samples/docker-image) to see command line examples

**Comment by darrenjrobinson** [comment]
Yes I have Port Mapping working. I've also tried reinstalling the nbextensions.

**Comment by colombod** [comment]
I was able to reproduce the bug

**Comment by colombod** [comment]
@darrenjrobinson we have just made a release and I also updated the docker file, your repro steps now seem to work correctly inside a docker container. Could you please test if your scenario is now addressed?

**Comment by darrenjrobinson** [comment]
Fantastic, thank you @colombod & @jonsequitur 

Success locally with JupyterLab using your sample Dockerfile
![image](https://user-images.githubusercontent.com/384733/89355594-1d9c2b80-d6ff-11ea-9df3-0af957ef7833.png)

However failing locally using Jupyter Notebook with my updated image for Interactive Build 1.0.140402 

![image](https://user-images.githubusercontent.com/384733/89356807-027eeb00-d702-11ea-81fc-2687856e673e.png)

Different error in the console

![image](https://user-images.githubusercontent.com/384733/89356852-29d5b800-d702-11ea-9210-f8ccb91af9b7.png)

Yes, I have incoming ports specified. Same as for what successfully works for Jupyter Lab.

**Comment by colombod** [comment]
does it work if you retry?

**Comment by colombod** [comment]
What do you see in chrome dev tools when you execute the cell?

This is a sequence of request that completes with success the kernel's http endpoint discovery
![image](https://user-images.githubusercontent.com/375556/89358508-71852100-d6bb-11ea-840e-1a21c56631f0.png)

**Comment by colombod** [comment]
Does it work if you split the powershell code submission from the html and js?

**Comment by darrenjrobinson** [comment]
No joy their either.

![image](https://user-images.githubusercontent.com/384733/89386652-b30dde80-d744-11ea-8c50-4ead80ba29e0.png)

Maybe missing a dependency. 
![image](https://user-images.githubusercontent.com/384733/89386729-d042ad00-d744-11ea-9693-d209fa1d59e8.png)

Some extra tracing showed I needed to update with the following and extend in the inbound ports to start at 1000. 

```
pip install ipywidgets
jupyter nbextension enable --py widgetsnbextension
pip install jupyter-require 
```

**Comment by colombod** [comment]
not sure, We have no installation of jupyter-require and the only other difference is that we target python 3 explicitly in our docker file.

can you show the docker file you are using ?

**Comment by darrenjrobinson** [comment]
AWESOME NEWS.
I took the reference Dockerfile from the updated examples.
I then modified it for a bunch of my requirements and Jupyter Notebook (over Jupyter Lab). 

![image](https://user-images.githubusercontent.com/384733/89592449-fc1e7980-d88f-11ea-9d16-e5dc57e8f9e7.png)

Success. 
Thanks for all your help @colombod 
This particular feature is extremely powerful. 🐱‍🏍

**Comment by colombod** [comment]
Thank you for your feedback, glad you have your scenario working.
