### ISSUE TITLE
notebook kernel stop the process when it calls "console.writeline" method.

### ISSUE THREAD

**Issue by mifmasterz** [dotnet/interactive#66]
#### Describe the bug
notebook kernel stops the process when it calls "console.writeline" method. This issue happens when I use ML.NET with Jupyter Notebook.  

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x] Other: (backend) code execution in notebook kernel is stop

#### Screenshots
if I run this cell, the code below the red line will not be executed, the process is just stop, but, If I remove the "Console.WriteLine" it will run smooth till the end of code
![image](https://user-images.githubusercontent.com/15245579/66688077-44d8c680-ecaf-11e9-8fb0-08f7cc07b161.png)

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [x] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
Please reopen if you're able to reproduce this issue.
