### ISSUE TITLE
display becomes unavailable after a kernel restart

### ISSUE THREAD

**Issue by pakrym** [dotnet/interactive#669]
### Describe the bug

1. Open a notebook
2. Use `display` method
3. Run "Restart current notebooks kernel" command
4. Try using `display` method

Expected: things work

Actual:
![image](https://user-images.githubusercontent.com/1697911/88566979-af16e980-cfeb-11ea-8e75-9c976e48e626.png)

Reopening the file helps.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

![image](https://user-images.githubusercontent.com/1697911/88566647-2b5cfd00-cfeb-11ea-8ecd-3bb7677360ba.png)

```
Version: 1.48.0-insider (user setup)
Commit: 731f9c25632dbbf01ee3a7892ad9d2791fe0260c
Date: 2020-07-24T05:57:10.466Z (3 days ago)
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

**Comment by colombod** [comment]
Running VS Code Insiders
![image](https://user-images.githubusercontent.com/375556/89298972-f4778e80-d65d-11ea-847c-92eb7cca05e3.png)

And .NET Interactive
![image](https://user-images.githubusercontent.com/375556/89299012-035e4100-d65e-11ea-8adf-db74a04cc6bf.png)


I wasn't able to reproduce the issue using the repro steps you provided, can you share your code or try with the latest extension?
