### ISSUE TITLE
XPlotly Choropleth plot not rendered properly in C#

### ISSUE THREAD

**Issue by praveenraghuvanshi** [dotnet/interactive#670]
### Describe the bug
In Jupyter notebook with C# kernel, while plotting a data with name of countries and alcohol consumption in a Choropleth plot, global world map is rendered with scale on right side, but data is not rendered as shown in the attached image.
I have tried to follow the F# implementation available at https://muehlhaus.github.io/FSharp.Plotly/choropleth-map.html

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.115407+d247e88f3f756abad4bd16b47cf8cde187aafabc
Build date: 2020-07-14T23:05:06.5944002Z
https://github.com/dotnet/interactive

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [x] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
- Image with outpout of Choropleth plot
- Xplotly-Choropleth-plot-csharp.ipynb notebook. I have attached it as a txt, please change extension to ipynb. Also , i have attached it as a pdf file for reference.

![image](https://user-images.githubusercontent.com/66641548/88639664-a7823e00-d0da-11ea-92c0-323b529b3e94.png)

[Xplotly-Choropleth-plot-csharp.txt](https://github.com/dotnet/interactive/files/4986960/Xplotly-Choropleth-plot-csharp.txt)

[Xplotly-Choropleth-plot-csharp.pdf](https://github.com/dotnet/interactive/files/4986985/Xplotly-Choropleth-plot-csharp.pdf)

**Comment by colombod** [comment]
You do not need to import the plotly package, is already present.
The error here is the way you set the ```locationmode```, according to the [documentation](https://plotly.com/javascript/reference/#choropleth-locationmode) you have to change your cell to

```csharp
var globalGeoPlot = Chart.Plot(
    new Graph.Choropleth()
    {
        locations = globalData.Keys,
        z = globalData.Values,
        locationmode = "country names"
    });
```

the result is 

![image](https://user-images.githubusercontent.com/375556/89042332-a7827800-d33e-11ea-9c2f-90651ff347be.png)

**Comment by praveenraghuvanshi** [comment]
Sorry my bad... It worked, Thank you!!!
Is there a Gitter channel where I could ask such small queries instead of logging an issue?

The issue can be closed!

**Comment by colombod** [comment]
@praveenraghuvanshi thank you for the suggestion, we just created the channel, you can see the badge on the readme
