### ISSUE TITLE
System.Runtime version 5.0.0.0 not found

### ISSUE THREAD

**Issue by unuunc** [dotnet/interactive#673]
### Describe the bug
1. I have few dll's which are generated from .net 5 preview version
2.I add reference to these dll

Now when I invoke function 

I get following error

====================================================================
Error: System .10.FileNotFoundException: Could not load file or assem bly 'System .Runtime, Version= 5.0.0.0, Culture= neutral, PublicKeyToken= b03f5f7f1 1 d50a3aI. 
The system cannot find the file specified. 
File name: 'System .Runtime, Version= 5.0.0.0, Culture= neutral, PublicKeyToken= b03f5f7f1 1 d50a3aI 
at Subm < 0.MoveNext0 
at System.Runtime.Com pilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) 
at Subm ission#5. < Initialize> 0 
at Subm ission#5. < Factory > (Object[] subm issionArray) 
at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubm issionsAsync[TResult](lm mutableArray'1 precedingExecutors, Func'2 currentExecutor, 
StrongBox'1 exceptionHolderOpt, Func'2 catchExceptionOpt, CancellationToken cancellationToken) 

====================================================================

Version : 1.0.137901
VSCODE Extension

**Comment by seesharprun** [comment]
I don't believe .NET 5 is supported yet per #663 

I validated this on my local machine (with .NET 5 preview 7 installed) by following these steps:

1. Run ``dotnet --version`` and observe the output:
    ```sh
    5.0.100-preview.7.20366.15
    ```
1. Run ``dotnet --list-sdks`` and observe the output:
    ```sh
    2.1.503 [c:\program files\dotnet\sdk]
    2.1.602 [c:\program files\dotnet\sdk]
    2.1.800 [c:\program files\dotnet\sdk]
    2.2.103 [c:\program files\dotnet\sdk]
    3.0.100 [c:\program files\dotnet\sdk]
    3.1.101 [c:\program files\dotnet\sdk]
    3.1.203 [c:\program files\dotnet\sdk]
    3.1.300-preview-015135 [c:\program files\dotnet\sdk]
    3.1.400-preview-015138 [c:\program files\dotnet\sdk]
    5.0.100-preview.7.20366.15 [c:\program files\dotnet\sdk]
    ```
1. Open a notebook and add the following C# code:
    ```csharp
    using Runtime = System.Runtime.InteropServices.RuntimeInformation;
    using static System.Console;

    WriteLine($"Running Version: {Runtime.FrameworkDescription}");
    ```
1. Run the notebook and observe the output:
    ```sh
    Running Version: .NET Core 3.1.4  
    ```

**Comment by colombod** [comment]
Hi @seesharprun we do not support yet .NET 5. At the moment we target .NET core LTS.

**Comment by jonsequitur** [comment]
Related: #869

**Comment by belumolinaisu** [comment]
> I don't believe .NET 5 is supported yet per #663
> 
> I validated this on my local machine (with .NET 5 preview 7 installed) by following these steps:
> 
> 1. Run `dotnet --version` and observe the output:
>    ```shell
>    5.0.100-preview.7.20366.15
>    ```
> 2. Run `dotnet --list-sdks` and observe the output:
>    ```shell
>    2.1.503 [c:\program files\dotnet\sdk]
>    2.1.602 [c:\program files\dotnet\sdk]
>    2.1.800 [c:\program files\dotnet\sdk]
>    2.2.103 [c:\program files\dotnet\sdk]
>    3.0.100 [c:\program files\dotnet\sdk]
>    3.1.101 [c:\program files\dotnet\sdk]
>    3.1.203 [c:\program files\dotnet\sdk]
>    3.1.300-preview-015135 [c:\program files\dotnet\sdk]
>    3.1.400-preview-015138 [c:\program files\dotnet\sdk]
>    5.0.100-preview.7.20366.15 [c:\program files\dotnet\sdk]
>    ```
> 3. Open a notebook and add the following C# code:
>    ```cs
>    using Runtime = System.Runtime.InteropServices.RuntimeInformation;
>    using static System.Console;
>    
>    WriteLine($"Running Version: {Runtime.FrameworkDescription}");
>    ```
> 4. Run the notebook and observe the output:
>    ```shell
>    Running Version: .NET Core 3.1.4  
>    ```

Sorry, but what is  **the notebook** and how could you run it?
