### ISSUE TITLE
Guestion: how to preprocess (modify) submitted code before it gets executed by C# kernel?

### ISSUE THREAD

**Issue by aleckravets** [dotnet/interactive#675]
I'm working with Jupyter notebooks and my code is not pure C#. So, before it gets executed I need to modify it to make it valid C# code. Is it possible to do using middleware. 
Or maybe there is a way of introducing my own kernel that would subclass the CSharpKernel? Is it possible at all? 
Please, help.

**Comment by colombod** [comment]
Hi, can you share an example of "non" correct c# you want  to preprocess?
