### ISSUE TITLE
C# `using` statement breaks syntax highlighting in VS Code notebook

### ISSUE THREAD

**Issue by loic-sharma** [dotnet/interactive#677]
### Describe the bug
Please provide as much information as you can.

### Please complete the following:

**Which version of .NET Interactive are you using?** : VS Code extension v1.0.138101

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/737941/89142932-b19ea500-d4fd-11ea-8547-91a1d1895b5c.png)

**Comment by brettfo** [comment]
We fall back to the default C# grammar and they have a known bug around top-level using blocks.  See dotnet/csharp-tmLanguage#126.

**Comment by Blealtan** [comment]
So it cannot make use of actual IntelliSense support from, like, OmniSharp?

**Comment by jonsequitur** [comment]
There are a number of differences that make it impractical to reuse an existing C# language server.

The C# scripting compilation model is quite different from the project-based model, and there are also language differences. In addition, .NET Interactive is polyglot, including at the cell level, and includes magic commands.
