### ISSUE TITLE
Move to a more standard style of HTML DSL for F# #689

### ISSUE THREAD

**Issue by dsyme** [dotnet/interactive#687]
I'd like us to review the F# FSharpPocketViewTags programming model (though the PocketView implementation can be used underneath)

The F# community have a fairly standard way of doing HTML DSLs, which is the same across many F# web programming technologies like Fable (client-side HTML) and Giraffe (server-side HTML).  Roughly speaking the end result is to always look like this

    div 
      [ ] 
      [ p [ todoStyle ] [ str item.Description ]
        button [ ClassName "button is-info"; dispatchToggle ] [ str toggleText ]
        divider
        button [ ClassName "button is-danger"; dispatchDelete ] [ str "Delete" ] ]

That is, each HTML element is `tag [...attributes...] [ ...content...]`

This is how we should be descrbing HTML in the F# .NET Interactive programming model.  It doesn't have to be precisely the same as every other HTML DSL in F# (nor share code) but this is the standard syntax in the community and the one we should be using for window dressing.  It's also very, very effective as a DSL syntax, I and others absolutely love using it, particularly because it jives so well with F# list expressions.

I'd also like to make sure the namespace is not open by default, see #645, and that the way of opening is fairly simple. Currently it is

    open Microsoft.DotNet.Interactive.FSharp.FSharpPocketViewTags

which is not great  - I'd like any of

    open FSharpPocketViewTags
    open PocketViewTags
    open HtmlTags

I'll experiment with options

**Comment by jonsequitur** [comment]
I think given that great HTML DSLs already exist in F#, we should remove the F# implementation of `PocketViewTags`. 

The C# version is likely to support extension authors more often than notebook users and there as well I agree we shouldn't open the namespace by default.

**Comment by dsyme** [comment]
> I think given that great HTML DSLs already exist in F#, we should remove the F# implementation of PocketViewTags.

At the moment my feeling is we should replace it by an implementation of an F# DSL that is surface syntax for PocketViewTags and conforms to the HTML element part of [Giraffe.ViewEngine](https://github.com/giraffe-fsharp/Giraffe.ViewEngine) exterior API. I'm trialling that right now.

I'm loathe to diverge on the actual HTML object because I suspect 
1. there's devil in the detail 
2. there may be c#-f# interop on this
3. Giraffe.ViewEngine is not yet something I'd  wouldn't want to take an actual dependency  on 

BTW here's an example of the code (compare the C# code with explicit use of ResizeArray due to lack of list expression syntax):

```
open Html

let register (df:DataFrame) (writer:TextWriter)
    let take = 20
    table [] [
      thead [] [
        th [] [i [ str "index"]]
        for c in df.Columns -> th [] [c.Name]
      ]
      tbody [] [
        for i in 0 .. min take (int df.Rows.Count - 1) do
          td [] [ object i ]
          for o in df.Rows.[int64 i] do
            td [] [ object o ]
      ]  ]
    |> writer.Write
Formatter<DataFrame>.Register( (fun df writer -> register df writer), mimeType = "text/html")

**Comment by dsyme** [comment]
DOne in #689
