### ISSUE TITLE
Evaluation leads to a default formatter registration, then user-defined formatters are ignored

### ISSUE THREAD

**Issue by dsyme** [dotnet/interactive#692]
Evaluation implicitly leads to a default formatter registration which then leads to user-defined formatters being ignored.  THis is very confusing.

0. Restart kernel

1. Evaluate `DayOfWeek.Monday`

2. Register a formatter for IComparable

3. Evaluate `DayOfWeek.Monday` again

Expected: The formatter for IComparable is invoked

Actual: the same formatting as step 1 is used

Compare with 

0. Restart kernel

1. Register a formatter for IComparable

2. Evaluate `DayOfWeek.Monday` again

In this case, the formatter for IComparable is invoked.  The fact that I've previously formatted a DayOfWeek value should be irrelevant.

The formatter architecture is very sniffy, it seems full of hidden state like this.  Somehow evaluation causes default formatters to be populated and then those take precedence of user-specified formatters.  

There should be a simple declarative spec like 

* "we run all registered user-defined formatters in sequence finding the first that matches, then run default formatters", or

* "we look at all user-defined formatters and select the one that is closest match by type hierarchy.  If none match we do the same with the default formatters"

I took a  look at the implementation and TBH I saw some code fragments that indicate these type-indexed tables get automatically populated by defaults which I assume that leads to this kind of problem.

**Comment by dsyme** [comment]
To be honest I'm finding myself just deeply confused about 

1. what the intended specification is for which formatter gets called when (given a set of user-specified formatters)

2. what the default formatters are

3. what the implementation bugs are with respect to the intended specification 

As context, what I'm trying to do is set up the default formatting of F# values to be acceptable for example F# programming.  

To be helpful, I'm going to try to write a min-spec of what I think the intended behaviour is (unless there is one already available?)

**Comment by dsyme** [comment]
Another bug: For formatting a simple value that has no formattable members (e.g. take `type X = A | B` then format `A`) then we end up calling
```
                return new HtmlFormatter<T>((value, writer) => writer.Write(value));
```

However this is just using `ToString()` on the vaue which is a string not HTML.  For example:

```
type X = 
    | A 
    | B 
    override x.ToString() = "<b>Bold</b>"
```
gives a situation where plaintext `ToString()` results get used as HTML:

![image](https://user-images.githubusercontent.com/7204669/89708794-1d579680-d972-11ea-9405-9d6a6c4fbe55.png)

I'll keep working through this and compiler a list of issues and make a set of fixes and tests

**Comment by dsyme** [comment]
Notes to self

### debugging

To debug, attach and set a breakpoint at `Microsoft.DotNet.Interactive.Kernel.display` and call it:

```
open Microsoft.DotNet.Interactive.Kernel

display(value, "text/plain")
```

### code notes

Why is this async?  

```
        public static Task<DisplayedValue> DisplayAsync(
            this KernelInvocationContext context,
            object value,
            string mimeType = null)
        {
            DisplayedValue result = Display(context, value, mimeType);
            return Task.FromResult(result);
        }
```

**Comment by dsyme** [comment]
Notes to self:

### Debugging

To debug, attach to `dotnet-interactive.exe` and set a breakpoint at `Microsoft.DotNet.Interactive.Kernel.display` and call it:

```
open Microsoft.DotNet.Interactive.Kernel

display(value, "text/plain")
```

### code notes

* Why is this async?  

```
        public static Task<DisplayedValue> DisplayAsync(
            this KernelInvocationContext context,
            object value,
            string mimeType = null)
        {
            DisplayedValue result = Display(context, value, mimeType);
            return Task.FromResult(result);
        }
```

* `PlainTextFormatter<_>.CreateForMembers` is never called except in tests

* Down the OO rabbit hole:  `FormatterSetBase.AddFormatterFactory`???

* In the following the `TypeIsAnonymous`, `TypeIsException`, `TypeIsValueTuple` look redundant as none of these categories of types are even IEnumerable, so the fourth condition always holds

            if (Formatter<T>.TypeIsAnonymous ||
                Formatter<T>.TypeIsException ||
                Formatter<T>.TypeIsValueTuple|| 
                !typeof(IEnumerable).IsAssignableFrom(typeof(T)))
            {
                return CreateForAllMembers(includeInternals);
            }

* PlainTextFormatter<>.CreateForAllMembers is mis-named, since it actually selected members using `GetMembersToFormat`

**Comment by jonsequitur** [comment]
> COMMENT: this is a very strange part of the spec - this means registering a printer for an abstract base class, interface or generic non-abstract base class has different consequences to a non-generic non-abstract base class. This also explains why registering an "obj" printer doesn't do anything (it only selects type obj)

This point of differentiation is fairly recent, based on user requests. Originally, the formatters were only useful for types that can be instantiated. These should ideally be differentiated more clearly to show the intention behind "registering" a formatter for interfaces, abstract types, and open generics, i.e. that it's an on-demand fallback to be used when no formatter has yet been registered. The aggressively specific name `RegisterLazilyForConcreteTypesOf` is the the start of a more explicit differentiation of these two use cases.

**Comment by jonsequitur** [comment]
> gives a situation where plaintext ToString() results get used as HTML:

This is a result of the fact that when nesting formatters, we currently fall back to `text/plain` but preferably we would fall back to some form of HTML fragment. The `text/html` formatters, which follow Python conventions for laying out tables, aren't appropriate for nesting.

**Comment by dsyme** [comment]
@jonsequitur Cool thanks for the details.

Perhaps we can talk about this 1:1 on Monday, but I think I'd recommend this simple spec for choosing relevant formatters (or at least put it forward as a strawman).

I don't think "concrete" or "abstract/interface" should be relevant, we should just use the type hierarchy (IsAssignableFrom, though also taking into account generic type formatters)

---------------------------

Strawman spec:

When formatting an object of some runtime type (GetType() = A), then determine the relevant mime type and formatter from the lists of user-registered mime types (Formatter.SetPreferredMimeTypeFor) and user-registered formatters (Formatter.Register) as follows:

1. If no mimeType is specified, determine one

   - Choose the most-specific user-registered mime type preference relevant to A

   - If none are relevant, then choose a default mime type.

2. Next, determine a formatter

   - Choose the most-specific user-registered formatter relevant to A

   - If none are relevant, then choose a default formatter (using the same rules with the built-in defaults).

3. Here "most specific" is in terms of the class and interface hierarchy.   In the event of an exact tie in ordering or some other conflict, more recently registered formatters and mimeTypes are preferred. Type-instantiations of generic types are preferred to generic formatters when their GenericTypeDefinition are the same

4. Internal tables of formatters are cleared each time a new formatter is registered.

5. The default sets of formatters for a mime type always include a formatter for `object`.

----------

This spec would mean the following.  Each seems natural to me from the user's perspective:

* If the user registers `text/plain` as the mime type for `object` then it is used as the mime type for everything (likewise any other mime type)

* If the user registers an `object` formatter, it is preferred over all other formatters except other user-defined formatters

* If the user registers a `DateTime` formatter (or any sealed type), it is preferred over all other formatters

* If the user registers `List<>` and `List<int>` formatters the `List<int>` formatter is preferred

* If the user registers a confusing conflicting mess of overlapping formatters incrementally, they should Formatters.Clear() or restart the kernel.
