### ISSUE TITLE
instructions for installing local build fail

### ISSUE THREAD

**Issue by dsyme** [dotnet/interactive#693]
I'm trying to follow these instructions from the README.MD

> To build and then install your developer build of the dotnet-interactive global tool, you can run the PowerShell script <REPO-ROOT>/src/dotnet-interactive/build-and-install-dotnet-interactive.ps1. This will uninstall any previous version of dotnet-interactive you might have installed.

However I get this

```
E:\GitHub\dsyme\interactive>powershell -File src/dotnet-interactive/build-and-install-dotnet-interactive.ps1
Join-Path : A positional parameter cannot be found that accepts argument 'interface-generator'.
At E:\GitHub\dsyme\interactive\src\dotnet-interactive\build-and-install-dotnet-interactive.ps1:7 char:16
+ ... net run -p (Join-Path -Path $thisDir ".." "interface-generator") --ou ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Join-Path], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
```

**Comment by dsyme** [comment]
I guess I might have some older version of powershell, though unhelpfully `powershell -?` doesn't show the version

After fixing the above to use `[System.IO.Path]::Combine` I get this:

```
The variable '$IsLinux' cannot be retrieved because it has not been set.
At E:\GitHub\dsyme\interactive\src\dotnet-interactive\build-and-install-dotnet-interactive.ps1:16 char:9
+     if ($IsLinux -or $IsMacOS) {
+         ~~~~~~~~
    + CategoryInfo          : InvalidOperation: (IsLinux:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : VariableIsUndefined
```

**Comment by dsyme** [comment]
OK it runs after I just remove the IsLinux conditional on my Windows machine

**Comment by jonsequitur** [comment]
I believe this is a Windows PowerShell versus PowerShell Core difference. It looks like the script assumes you're using the latter.

**Comment by dsyme** [comment]
> I believe this is a Windows PowerShell versus PowerShell Core difference. It looks like the script assumes you're using the latter.

Yup
