### ISSUE TITLE
Preserving linebreaks and whitespace in HTML formatting of leaf objects and strings

### ISSUE THREAD

**Issue by dsyme** [dotnet/interactive#697]
HTML Formatting hits objects at the leaves which it decides not to format.   When it does, it invokes plain text formatting and dumps the result encoded into the HTML without any tag

The problem with this is that all whitespacing and line breaks are lost from the results plain text formatting.  This is one root cause of a lot of poor formatting for tables involving complex data rendered as plaintext

Compare this:

![image](https://user-images.githubusercontent.com/7204669/89738426-4a8a6e80-da70-11ea-8f47-51668f2b7611.png)

and this, where i've adjusted the default to wrap a `pre` tag around the text for unknown objects.

![image](https://user-images.githubusercontent.com/7204669/89738542-6e01e900-da71-11ea-9a14-b689c49ba3fb.png)

There is a fundamental design decision here about whether we "trust" plain text formatting to produce good white-spacing.  I think we have to - at least from the F# perspective where we have a plaintext formatting story that does exactly this.    So i'd recommend this as the default for the F# kernel.  Maybe for C# too.

**Comment by dsyme** [comment]
I'm trialling adding a `HtmlFormatter.PreformatEmbeddedPlainText` setting set to true for F# by default

There are downsides of using preformatted - notably the styling uses a monospace font.  But for data-centric programming like we expect people to do in F# it's the right default.  Likely the right result in C# too but that's something we can discuss

**Comment by dsyme** [comment]
As an aside, the place where the decision to switch from HTML to plain text formatting is made is very subtle, it's on [this line](https://github.com/dotnet/interactive/blob/master/src/Microsoft.DotNet.Interactive.Formatting/HtmlFormatter%7BT%7D.cs#L204) where `td(r)` is embedding an arbitrary object which [ultimately gets formatted as plain text through this code here because a default argument of `"text/plain"` is used](https://github.com/dotnet/interactive/blob/master/src/Microsoft.DotNet.Interactive.Formatting/PocketView.cs#L217).  

The  decision to switch in to plain text is being made by the table formatting code, effectively formatting all column values as plaintext. I guess this is to avoid recursive tables - but at the moment, even values that have good, registered HTML renderers aren't being rendered as HTML in table columns.  

This seems an odd choice.  A better option would be to list tables as a "nesting limit=1" or "nesting limit = 2" type, and enforce that in the global loop, but otherwise render values in columns as HTML if possible, and plain text if not.

**Comment by dsyme** [comment]
Just a side note that 

1. top level strings with multi-line and whitespace also lose their whitespaceing in output. Indeed they are currently treated as raw HTML, because of this code.

            if (obj is string s)
            {
                writer.Write(s);
                return;
            }


2. string objects injected into the PocketView lose their whitespaceing and line breaks in output, but are at least encoded as HTML

                    case string s:
                        writer.Write(s.HtmlEncode());
                        break;

3. any formatter for strings is currently ignored (see (1) above).  We do currently have this formatter but it is unused:

                new HtmlFormatter<string>((s, writer) => writer.Write(span(s))),

   which puts a `span` around and then injects the string object into the PocketView, which uses rule (2) above.  This would be correctly encoded but lose whitespaceing

**Comment by dsyme** [comment]
By the way [this stackoverflow question is relevant](https://stackoverflow.com/questions/45326130/how-can-i-display-the-text-in-pre-tag-in-the-default-fonts-that-html-uses/45326306) - it allows us to use `pre` whitespace-preservation without opt-ing in to `pre` font defaults, which would perhaps make preserving whitespace and multi-line more palatable, separating it from the question of which fonts are used.

**Comment by dsyme** [comment]
OK @jonsequitur, so which of these do we use for these nested objects rendered as plain text?  

1. `<pre>...</pre>` 
2. `<pre style="white-space: pre; text-align: left">... </pre>` 
3. `<div style="white-space: pre; text-align: left">...</div>` 
4. `<div style="white-space: pre;">...</div>` 

The difference can be seen below in these four styles below, in the same order.  

![image](https://user-images.githubusercontent.com/7204669/89825055-f0f77200-db4b-11ea-94d8-5b40cefc1909.png)

Remember that as things stand what ever you choose applies to *all* objects rendered via plain text , which might potentially mean *all* values in all columns at the moment (though we will move to render more objects as HTML.

I'd recommend either (2) or (3).  

The advantage of (2) is that it makes it obvious "hey this got rendered via plain text! I'm using a monospace font!".  The disdvantage is that all columns rendered via plain text are left-justified.

The advantage of (3) is that that no monospace font is introduced. However multi-line things columns formatted via plaintext are right-justified by default which is a counter-intuitve way to render multi-line plain text.

We do have to choose one or other.  We could plausibly apply (2) for multi-line strings or strings with multiple whitespace characters in a row, though that could give an odd mix of results within the same column.  Maybe that's not too bad though.

**Comment by jonsequitur** [comment]
Considering that console output is also rendered as `"text/plain"`, a good deal of output is likely expecting to be able to use monospace fonts for layout, so I would vote for (3).

**Comment by dsyme** [comment]
> Considering that console output is also rendered as "text/plain", a good deal of output is likely expecting to be able to use monospace fonts for layout, so I would vote for (3).

Do you mean (2)  (corresponding to number 1 in the list above)

**Comment by dsyme** [comment]
> Considering that console output is also rendered as "text/plain", a good deal of output is likely expecting to be able to use monospace fonts for layout, so I would vote for (3).

So I need to check this - do you want with monospace or without?  And do you want left-justfied or right-justified?

**Comment by jonsequitur** [comment]
Sorry, yes, I meant (2). I would expect the same layout as one sees in the console (ideally colorized when we get there):

![image](https://user-images.githubusercontent.com/547415/89966316-b7823d80-dc03-11ea-876c-1080919c1da1.png)

But the fact that in case (0) the alignment defaults to right-aligned isn't something I expected, so I think I'm missing something.

> (BTW I'm quite concerned about a change to left-justified as many simple table outputs might suddenly become left-justified)

Do you have an example of where this might happen?
