### ISSUE TITLE
Subplots in Plotly?

### ISSUE THREAD

**Issue by dfinke** [dotnet/interactive#715]
Is there a way to create subplots?

https://plotly.com/python/subplots/

![image](https://user-images.githubusercontent.com/67258/90319823-d6394a80-df09-11ea-82cd-6572f10ddb2e.png)

**Comment by jonsequitur** [comment]
I'd check out the Xplot.Plotly documentation. I don't know if this is supported but I'm not an expert. @cartermp? 

Another option might be to use JavaScript and [variable sharing](https://github.com/dotnet/interactive/blob/master/docs/javascript-overview.md#accessing-kernel-data-from-client-side-javascript-code).

**Comment by cartermp** [comment]
There's currently no support for subplots where each plot is distinct. As in the example above, it's possible to have multiple traces in the same plot. It'd have to be added to XPlot or be accessed via variable sharing.

FYI it does appear that fsharp.plotly does support this: http://muehlhaus.github.io/FSharp.Plotly/multiple-charts.html

**Comment by dfinke** [comment]
Thank you
