### ISSUE TITLE
When reopening a notebook that had not been saved, VS Code does not restore its state

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#717]
### Describe the bug

When there are unsaved changes in VS Code notebook files and you close the app, there's no prompt to save, and unsaved changes are lost on reopen.

**Which version of .NET Interactive are you using?** 

1.0.141102+2d53d810e6558ec75694e4ceb7afc508d87841af

**Comment by jonsequitur** [comment]
I realized that this is a normal VS Code behavior. For example, if I run File > New File (Ctrl + N), type some text, and close VS Code, there's no save prompt. When I open VS Code again, that unsaved "file" is also reopened.

The .NET Interactive Notebooks extension doesn't do this though. So the real issue isn't the lack of a save prompt but the fact that my unsaved content isn't restored on reopen.

**Comment by Happypig375** [comment]
This issue has come back again.
![image](https://user-images.githubusercontent.com/19922066/133119920-71171837-80a9-4e8e-9f31-e6e5a1baafe7.png)

**Comment by brettfo** [comment]
@Happypig375 We just published a new version of the extension a few minutes ago and a quick test of this scenario on my machine had it working.  Can you give it another shot?  If it doesn't work for you I'd be interested in figuring out how our setups are different.
