### ISSUE TITLE
Files included with "Content Include" are searched for inside lib folder of nuget package.

### ISSUE THREAD

**Issue by chriss2401** [dotnet/interactive#741]
### Describe the bug
Hello,

I have created a jupyter notebook which calls a nuget, which contains some files (in this case pre-trained neural nets - .onnx files), and these files are included in the nuget using `Content include=...` and by adding a `.targets` file. All this works fine when I use the nuget in a C# app, since everything is simply "dumped" into the output folder.

But when I add the same nuget in a jupyter notebook and then call the same function in a cell, I get the following error : 

`Error message: Load model C:\Users\"PC-name"\.nuget\packages\"nuget-package-name"\"version"\lib\netstandard2.1\".onnx-file" failed. File doesn't exist`

AFAIK, contents are not added in the `lib` folder of a nuget, but in the `content` folder. Is there something I am missing here, or should I add my `.onnx` models in another way ? Thanks in advance

### Please complete the following:

**Which version of .NET Interactive are you using?**
1.0.142702

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [x] Firefox
    - [ ] Safari
 - Frontend
    - [x] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
Cannot share unfortunately, but I can try and reproduce the problem if needed in a minimal viable example.

**Comment by rspaulino** [comment]
@chriss2401 I don't know if this will work for you but I load my local build nuget into vscode using #i and the #r nuget search on the location I specific.

```
#i "/Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/artifacts/packages/Release/Shipping"
#r "nuget:Microsoft.DotNet.Interactive.ExtensionLab,1.0.0-beta.20426.1"
```

<img width="933" alt="Screen Shot 2020-09-02 at 12 03 54 PM" src="https://user-images.githubusercontent.com/378671/92007808-6520d200-ed14-11ea-80df-ffc5ec61eeba.png">

**Comment by jonsequitur** [comment]
What's the code that's trying to load the `.onnx` file from that path? I don't think I have the context to understand why this might behave differently in .NET Interactive versus a .NET app.

**Comment by brettfo** [comment]
There's no backing `.csproj` or `.fsproj` so `<Content Include="..." ... />` won't be handled at all.  If you need a file from the NuGet package you could do something like this:

``` csharp
var asmPath = Path.GetDirectory(typeof(SomeTypeFromThePackage).Assembly.Location);
var myAsset = Path.Combine(asmPath, "some-asset.png");
```
