### ISSUE TITLE
.dib notebook intellisense, tooltip, hovertext enhancements

### ISSUE THREAD

**Issue by rspaulino** [dotnet/interactive#746]
**Is your feature request related to a problem? Please describe.**
It would be great if vscode notebook .dib would follow the same approach to intellisense, tooltip, hovertext like at least vscode does, coming from VS and using vscode I always take a lazy approach and relay a lot on intellisense to pass value to parameters, etc. Right now using notebook for discovery isn't as fluent as it could be. I have to switch a lot between .dib and .cs just to get the intellisense when working with new API, etc.

I know it's a new project and maybe this is already on the backlog but just shining some light to it in case. 

I don't know the limitation of notebooks, to the extended if it's even possible but look that some if there already it's more polishing and enhancing it.

**Describe the solution you'd like**
**.cs**
<img width="714" alt="Screen Shot 2020-09-03 at 11 30 57 AM" src="https://user-images.githubusercontent.com/378671/92136767-6b798180-edda-11ea-8d7f-93428e62b82f.png">

<img width="685" alt="Screen Shot 2020-09-03 at 11 30 09 AM" src="https://user-images.githubusercontent.com/378671/92136702-53096700-edda-11ea-95fc-4ed87aa44ffa.png">

<img width="724" alt="Screen Shot 2020-09-03 at 11 33 39 AM" src="https://user-images.githubusercontent.com/378671/92136816-7c29f780-edda-11ea-9eee-d8c4b1ceb398.png">

**.dib**
<img width="727" alt="Screen Shot 2020-09-03 at 11 31 19 AM" src="https://user-images.githubusercontent.com/378671/92136844-85b35f80-edda-11ea-9585-0ffd3f6c70a1.png">

<img width="700" alt="Screen Shot 2020-09-03 at 11 30 34 AM" src="https://user-images.githubusercontent.com/378671/92136876-8cda6d80-edda-11ea-9ccc-a4f158cb3e4b.png">

**Comment by jonsequitur** [comment]
We do plan on making a number of these improvements: https://github.com/dotnet/interactive/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area-Language+Services%22

**Comment by rspaulino** [comment]
@jonsequitur thanks for the insight and awesome work big fan.
