### ISSUE TITLE
.NET Interactive Notebook + Visual Studio Code Insiders + GitHub Codespaces

### ISSUE THREAD

**Issue by seesharprun** [dotnet/interactive#749]
### Describe the bug

I'm trying to open a repository with a simple [*.dib](https://github.com/seesharprun/notebook-codespace-test/blob/master/test.dib) file. I have tested this notebook locally on my machine and it runs fine.

#### Repro steps

1. Go to [seesharprun/notebook-codespace-test/](https://github.com/seesharprun/notebook-codespace-test/) repo
1. Open the repo in GitHub Codespaces
1. Install the **.NET Interactive Notebooks** extension (I will automate this step later with a devcontainer 😃)
1. Run the notebook

I'm getting all sorts of weird results. Sometimes the notebook will flat-out not run at all. Sometimes the notebook will run and spin forever. I'm not sure if I am missing an obvious step.

### Please complete the following:

**Which version of .NET Interactive are you using?** Unsure, can't get magic command to work

- OS
    - [x] Windows 10
 - Browser 
    - [x] Edge
 - Frontend
    - [x] Other (GitHub Codespaces)
        > **Note**: GitHub Codespaces is running version 1.49.0-insider of Visual Studio Code

### Screenshots

- ![image](https://user-images.githubusercontent.com/5067401/92271420-c338eb00-eeb5-11ea-8cbd-ace8861b1439.png)
- ![image](https://user-images.githubusercontent.com/5067401/92269997-3d1ba500-eeb3-11ea-98a1-dcc110f3b93f.png)
- ![image](https://user-images.githubusercontent.com/5067401/92270056-5d4b6400-eeb3-11ea-83c0-065054fa266c.png)

**Comment by colombod** [comment]
The vscode insider version in code spaces is older than the current you are using locally. An api change in the latest vscode insider is making the current extension version incompatible with the code spaces. this should be resolved soon as code spaces catches up with the latest vscode insider. I would appreciate any feedback given also few changes we are making with pr #745 to improve the experience when running in code spaces.

**Comment by seesharprun** [comment]
Thanks for the insight. I'm trying to convince anyone in shouting range that we can use Notebooks as a great teaching tool for .NET. I'm already starting the process of building a devcontainer for [microsoftlearning/az-204-developingsolutionsformicrosoftazure](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure) and will wait for this issue to resolve.

One more question: How would I know this version is lagging behind the one I have installed locally. The about screen only says the build is ~3 days old compared to ~12 hours old for my local instance:

![image](https://user-images.githubusercontent.com/5067401/92276172-7c032800-eebe-11ea-9bcf-a8adfcd09601.png)

**Comment by colombod** [comment]
That is how I am tracking that at the moment, I asked the team to have an idea about their integration cycles. You should also join our gitter channel.

**Comment by seesharprun** [comment]
Thanks, I just joined the gitter.

**Comment by colombod** [comment]
This is from today
![image](https://user-images.githubusercontent.com/375556/94722650-80045780-034f-11eb-92d1-46576470795a.png)

**Comment by seesharprun** [comment]
I just tested this with my [favorite notebook](https://github.com/seesharprun/blobs-dotnet-notebook) and it works! I will need to add a .devcontainer to make sure it always install the correct extension and version of .NET Core.

We can close this issue for now and I will re-open if anything changes down the road.

![image](https://user-images.githubusercontent.com/5067401/94723694-2a1bb980-0327-11eb-8233-393fe1d6e2c8.png)
