### ISSUE TITLE
Unable to open 'dotnet.dib': fetch is not defined.

### ISSUE THREAD

**Issue by a531** [dotnet/interactive#752]
Issue Type: <b>Bug</b>

unable to open .net interactive notebook in visual studio code insiders, .netcore sdk and rutime installed and verified. Uininstalled and reinstalled .net interactive notebook extension in vs code insiders. I am able to open jupyter lab notebook in vs code insiders, and able to open .net interactive with jupyter lab in Chrome web browser.

Extension version: 1.0.145402
VS Code version: Code - Insiders 1.49.0-insider (e4256dd1a02339bb1d56647ecd9134bf38bc7c03, 2020-09-04T18:45:03.783Z)
OS version: Linux x64 5.4.48-06434-gd868196d13af

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/7a (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|2.71GB (2.69GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 5d0a5243-06e3-44fb-86ca-853bfee7c1b0|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details>

**Comment by colombod** [comment]
The pr #753 should address this issue.
