### ISSUE TITLE
[EXTERNAL] Changing cell type doesn't work

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#764]
If you create a cell in one language, then use the language switcher to choose a different language, the submission is still treated as the original language.

![image](https://user-images.githubusercontent.com/547415/92636957-0f58a680-f28d-11ea-81df-a3168ef53384.png)

**Comment by bobbydazzler** [comment]
Failing to execute FSharp for me. Also, a cell configured for FSharp when saved, closed, reopened, appears as a CSharp cell instead.

![01 FSharp in FSharp cell fails](https://user-images.githubusercontent.com/2190584/92958325-efc6a700-f461-11ea-85ab-f6c5c267b106.png)

It really thinks it's CSharp:

![02 CSharp in FSharp cell executes unexpectedly](https://user-images.githubusercontent.com/2190584/92958330-f2290100-f461-11ea-9899-c4a71804f015.png)

FSharp cell rendered as CSharp after save, close, open:

![03 After save close open language type has reset to CSharp](https://user-images.githubusercontent.com/2190584/92958561-564bc500-f462-11ea-8440-2003929d319d.png)
