### ISSUE TITLE
VS Code sometimes writes files incorrectly

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#766]
We're still looking for a stable repro for this but we've observed a few issues:

* Closing VS Code quickly after making a change _might_ cause recent changes to be lost.
* Using numerous Markdown cells and the split cell command _might_ cause cells to be written incorrectly.  
* Sometimes, `.dib` files _might_ be deleted from disk.

**Comment by brettfo** [comment]
Bullet point 2 possibly fixed by [this](https://github.com/microsoft/vscode/commit/59dcc5c9124ad82d15adc888013b2a861405d794) commit.  Once the next version of VS Code Insiders is out we can re-test this scenario.

**Comment by colombod** [comment]
today a new version has been released and I published an extension matching the changes, can we test this?
