### ISSUE TITLE
Cell inputs and outputs getting mixed up

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#771]
This behavior isn't consistent across notebooks but seems to be consistent for me when creating a new blank notebook.

![cell confusion bug](https://user-images.githubusercontent.com/547415/92769651-0bd92400-f34e-11ea-8817-a22774758511.gif)

**Comment by brettfo** [comment]
Possibly fixed by [this](https://github.com/microsoft/vscode/commit/59dcc5c9124ad82d15adc888013b2a861405d794) commit.  Once the next version of VS Code Insiders is out we can re-test this scenario.

**Comment by colombod** [comment]
With latest VSCode I cannot type any code in cell in a new untitled notebook see #782

**Comment by colombod** [comment]
Issue #782 has been fixed. I cannot reproduce this one any more
