### ISSUE TITLE
Opening .ipynb files fails with error "Cannot read property `rendererId` of undefined" 

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#775]
![image](https://user-images.githubusercontent.com/547415/92841872-b45fa600-f397-11ea-83bf-c48c81d8be99.png)

**Comment by brettfo** [comment]
Can you attach the notebook that caused this?  We don't have the string `rendererId` anywhere in our codebase.

**Comment by jonsequitur** [comment]
I'm no longer able to repro it.

**Comment by EverybodyKurts** [comment]
Here's a repo with a corrupted notebook:

https://github.com/EverybodyKurts/corrupted-dotnet-interactive-notebook/blob/main/clean-code-with-ces.ipynb
