### ISSUE TITLE
'Interrupt' button does not work

### ISSUE THREAD

**Issue by ndalchau** [dotnet/interactive#776]
## Bug

The interrupt button does not work, at least for the .NET F# kernel. This button is critical for anyone doing non-trivial calculations in notebooks. 

I'll tested this in two different ways, which leads to different outcomes, both of which are wrong.

## Binder (Jupyter Lab) | Windows 10 | Edge

Here is my very simple example:
![image](https://user-images.githubusercontent.com/7451485/92912313-9048a700-f421-11ea-953f-47408d7b61b9.png)

After started evaluation of the infinite loop of incrementing variable `y`, I clicked 'Interrupt'. Then tried to evaluate the subsequent cell, to inspect the previously evaluated variable `x`. It seems that instead of interrupting the evaluation of that cell, it has simply restarted the kernel. 

## Installation. Jupyter notebook | Windows 10 | Edge

To rule out the possibility that this is limited to the Binder example, I installed .Net interactive following the steps [here](https://github.com/dotnet/interactive/blob/main/docs/NotebooksLocalExperience.md). This time, clicking the interrupt button simply did nothing. Jupyter registered that I had clicked the button, but the cell appears to be evaluating still, and I cannot run the subsequent cell after clicking interrupt.

![image](https://user-images.githubusercontent.com/7451485/92911444-c9cce280-f420-11ea-96e5-c3d49f38ca4f.png)

**Comment by jonsequitur** [comment]
This is now supported at the kernel level and works in VS Code, so it should be fairly simple now to plumb this through for Jupyter as well. @colombod
