### ISSUE TITLE
New cell error "Cannot read property 'charAt' of undefined at"

### ISSUE THREAD

**Issue by radobson61** [dotnet/interactive#786]
### Describe the bug
When I click the plus sign to create a new cell in a workbook I get an error. The new cell isn't created and I see this error message in a larger than usual font. 

The error message survives a restart of the kernel. 

The error is gone after I restart VSCode.

The error is also gone after I save / close the file and re-open it.

Error Text follows:

TypeError: Cannot read property 'charAt' of undefined at 
  
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in div
    in div
    in div
    in div
    in t
    in h
    in t
    in div
    in div
    in div
    in t
    in main
    in div
    in t
    in h
    in f

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
Version: 1.0.142601+586ab2f29818edea7c19c383874977fe5d0391fc
Build date: 2020-09-09T14:18:07.6932204Z

- OS
    - [X ] Windows 10
 - Browser 
    - [X - default ] Chrome
    - [x] Edge
    - [x] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X ] Visual Studio Code
Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/7076485/93378578-40ebe780-f822-11ea-82e5-a7be13482dc2.png)

**Comment by jonsequitur** [comment]
This is coming from the Python extension, not .NET Interactive. If you have both extensions installed,  you can open the notebook in .NET Interactive using the command palette command `.NET Interactive: Open notebook`.
