### ISSUE TITLE
table data schema not rendering

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#787]
![image](https://user-images.githubusercontent.com/547415/93394786-98418600-f829-11ea-916b-e7beaea60acf.png)

`d.ToDisplayString("application/table-schema+json")` should produce a JSON output.

**Comment by colombod** [comment]
Closing the bug
![image](https://user-images.githubusercontent.com/375556/93543170-c4a4f180-f952-11ea-8ba7-59ab1114036d.png)
