### ISSUE TITLE
#r "nuget: in vscode squiggles 

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/interactive#788]
This seems wrong:

![image](https://user-images.githubusercontent.com/5175830/93423654-52a5ad00-f86b-11ea-813f-b01abe96bf4f.png)

**Comment by jonsequitur** [comment]
I don't repro this. It looks like it might gave been because of #764 which has been fixed.

Are you still seeing it?

**Comment by WhiteBlackGoose** [comment]
It also looks like `Area-VS Code` issue

**Comment by jonsequitur** [comment]
Does this still happen?

@WhiteBlackGoose This is really a language services bug. It doesn't show up in Jupyter Notebook or Jupyter Lab because we don't have diagnostics wired up to the editors there, but the behavior is driven by the kernel.
