### ISSUE TITLE
Unexpected Current Working Directory

### ISSUE THREAD

**Issue by Jose10go** [dotnet/interactive#824]
After create a new notebook, the C# expression System.Environment.CurrentDirectory is not returning notebook directory, instead is returning  AppData\Roaming\Code - Insiders\User\globalStorage\ms-dotnettools.dotnet-interactive-vscode

### Please complete the following:

**Which version of .NET Interactive are you using?** 
1.0.115407+d247e88f3f756abad4bd16b47cf8cde187aafabc

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

**Comment by Spongman** [comment]
yeah, this pretty much makes `#r "path/to/assembly.dll"` useless.

**Comment by jonsequitur** [comment]
Related: #478
