### ISSUE TITLE
add VS Code extension to the Data Science category in VS Code extension marketplace

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#825]
https://marketplace.visualstudio.com/search?target=VSCode&category=Data%20Science&sortBy=Installs

**Comment by RandomFractals** [comment]
I think yours is also a good candidate for Visualization & Notebooks categories vscode & marketplace teams added recently:

https://marketplace.visualstudio.com/search?target=VSCode&category=Visualization

https://marketplace.visualstudio.com/search?target=VSCode&category=Notebooks
