### ISSUE TITLE
Set default language?

### ISSUE THREAD

**Issue by isaacabraham** [dotnet/interactive#829]
Is is possible to set the default language for notebooks? It's a pain to constantly have to change it from C# Interactive to something else.

**Comment by jonsequitur** [comment]
Are you using VS Code? The kernel itself spins up with a default language but the VS Code extension is unaware of it. The initial cell defaults to C#, but if you change the language an add another cell, the new cell will be in the last language chosen. 

To improve this experience, we could do something like this:

* For creating a notebook, replace the existing **.NET Interactive: Create new blank notebook** palette command with three commands: **.NET Interactive: Create new blank notebook (F#)**, **.NET Interactive: Create new blank notebook (C#)**, and **.NET Interactive: Create new blank notebook (PowerShell)**. 
* When opening a notebook, read the `kernelspec` field back from the `.ipynb` and use that to establish the default (i.e. language of the next cell created) for the notebook.  

Thoughts?

@brettfo

**Comment by brettfo** [comment]
(Continuing the assumption that we're talking about VS Code.)

That's an interesting thought, I'll have to explore to see if that's something we can do (e.g., **.NET Interactive: Create new blank notebook (F#)**.  My initial thoughts are that we might be able to control the language of the first default cell via [this](https://github.com/dotnet/interactive/blob/1953ffe660c6b11b70a70657634b33af9a00060a/src/dotnet-interactive-vscode/src/vscode/notebookContentProvider.ts#L59).

**Comment by brettfo** [comment]
(Follow-up to above.)

I've verified that rearranging the order of [this](https://github.com/dotnet/interactive/blob/1953ffe660c6b11b70a70657634b33af9a00060a/src/dotnet-interactive-vscode/src/vscode/notebookContentProvider.ts#L59) list will make the first default cell the new top language.  With that having been discovered, I think it's worth adding to our backlog the new commands like @jonsequitur suggested.

**Comment by Jawz84** [comment]
This would be great to have, thanks for considering.

**Comment by WalternativE** [comment]
As an addition: this could become extremely useful after the recent changes which integrated the experience more tightly with the Jupyter VSCode extension. Right now it sets (and resets) the code cells pretty aggressively to `csharp` (like in the `metadata` properties of the `custom` block. This might be a bug but because of the default being `csharp` right now I have to be extremely cautious whenever I open a new notebook 😢

**Comment by michaelburgess-d** [comment]
bump -- I can't see feature being useful if it has this high friction to use it -- creating a cell and constantly having to change the language is a very poor experience.

**Comment by esteimanuel** [comment]
@isaacabraham this issue can be closed, because it has been resolved in #2712
