### ISSUE TITLE
Powershell C#/F# interop

### ISSUE THREAD

**Issue by PawelStadnicki** [dotnet/interactive#833]
I would like to have  the possibility to use/parse Azure CLI results in F#/C#.

In particular for the time being following statement generates json that I would like to reuse with other language:

```
$subs = az functionapp config appsettings list --name myresourcename --resource-group mygroup --subscriptionmysub
$subs
```

Unfortunately any approach to consume it in C#/F# cell doesn't work, including following:

```
#!value --name someJson
$subs
```

```
#!csharp
#!share someJson --from value
someJson // "subs" is printed
```

**Comment by jonsequitur** [comment]
You don't need to go through the `#!value` kernel if you already have a variable.

This works for me:

![image](https://user-images.githubusercontent.com/547415/95622804-11975780-0a29-11eb-8aea-ae6d77eac120.png)
