### ISSUE TITLE
Import custom magic function from nuget

### ISSUE THREAD

**Issue by rajivharris** [dotnet/interactive#844]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like dotnet interactive to support importing custom magic functions through nuget
```csharp
#r "nuget:CustomMagicFunctions"
#!magicfunction
```

**Describe alternatives you've considered**
No

**Comment by jonsequitur** [comment]
This is currently supported.

You can see a quickstart doc here: https://github.com/dotnet/interactive/blob/main/docs/extending-dotnet-interactive.md

Here are some samples: 

https://github.com/dotnet/interactive/tree/main/samples/extensions
https://github.com/dotnet/interactive/tree/main/src/Microsoft.DotNet.Interactive.ExtensionLab

**Comment by rajivharris** [comment]
Thanks @jonsequitur for the quick response!
