### ISSUE TITLE
[EXTERNAL] can't copy cell outputs

### ISSUE THREAD

**Issue by Spongman** [dotnet/interactive#862]
you can select the outputs, but `ctrl-c` is overridden to copy the cell contents. also the right-click menu is also overridden to cell-specific actins, even when you click on the outputs.

**Comment by jonsequitur** [comment]
I assume this is in VS Code? 

What version of the .NET Interactive Notebooks extension are you using?   

I'm not able to repro it using this version:

![image](https://user-images.githubusercontent.com/547415/97917897-0ffc3f00-1d0a-11eb-8e45-3e342213f1a2.png)

**Comment by doggy8088** [comment]
@jonsequitur I'm also expected to get a "Copy Cell Outputs" command. For now, there is only "Clear Cell Outputs".

![image](https://user-images.githubusercontent.com/88981/120010424-b645c400-c00f-11eb-828b-03320a6a9c26.png)

**Comment by jonsequitur** [comment]
@Spongman This was fixed a few months back in VS Code. It's not something that the .NET Interactive Notebook extension or .NET Interactive kernel controls, so I marked it as external.

@doggy8088 This menu is also provided by VS Code, not by .NET Interactive. You can copy the cell outputs by highlighting the output and pressing `Ctrl+C`. I haven't noticed a context menu item for copying them. I would suggest opening an issue at https://github.com/Microsoft/vscode if you think they should add it.
