### ISSUE TITLE
Set max rows for display helper

### ISSUE THREAD

**Issue by erichiller** [dotnet/interactive#867]
Currently `display()` maxes out at 20 rows, and then shows xxx count of rows remaining. It would be incredibly useful to be able to increase this at times, say 40, or even all.

Workarounds such as writing my own display-type function or calling display in a loop seem like less than stellar solutions, `display()` is already awesome, I'd just like to be and to see more than 20 rows sometimes.

Ideas for Implementation (off the cuff):
- JupyterLab setting (seems most elegant)
- global variable
- second optional param to `display` for configuration.

**Comment by jonsequitur** [comment]
This is configurable using the `Formatter` [APIs](https://github.com/dotnet/interactive/blob/main/docs/formatting.md#user-configuration-of-default-formatters).

![image](https://user-images.githubusercontent.com/547415/98485153-1d616f80-21c9-11eb-8e07-5d571b04d01d.png)

**Comment by erichiller** [comment]
This is *Great*! Thanks.

Mind if I add a small about, or just a link from the [display docs](https://github.com/dotnet/interactive/blob/main/docs/display-output-csharp.md) to the [Formatter APIs](https://github.com/dotnet/interactive/blob/main/docs/formatting.md#user-configuration-of-default-formatters)? It may help others with the same question.

**Comment by jonsequitur** [comment]
By all means, link to the docs. Thanks!
