### ISSUE TITLE
Consume .NET 5.0 SDK when RTM is available.

### ISSUE THREAD

**Issue by brettfo** [dotnet/interactive#869]
When the .NET 5.0 SDK RTM is publicly available, this repo should move to that.  This will likely be a 2 step process:

1. Update global.json with SDK version and get CI and signed builds to pass.
2. [optional] update `<TargetFramework>` values in appropriate projects to `net5.0`.
   - If this step is taken, the dotnet requirement checks for the VS Code extension should also be updated [here](https://github.com/dotnet/interactive/blob/e8365bba80d734dc3f9ec6bb0fd16890a3f151a4/src/dotnet-interactive-vscode/package.json#L113).

**Comment by akdor1154** [comment]
Maybe related to this.. is there any method for a user to specify framework version? I.e. currently it's 3.1.0 and I can't see any method to force it to 5.0.0, which I have installed. If this issue gets fixed, will it be set to 5.0.0, with no way to force 3.1.0?

**Comment by jonsequitur** [comment]
Currently there isn't but we'd like to enable this eventually.

**Comment by dhirschfeld** [comment]
I'd love to try this out with .NET5 which has just been released! :tada:
```
> .\dotnet-interactive.exe --help
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.0 at [C:\Miniconda\dotnet\shared\Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=win10-x64
```

**Comment by kurt-mueller-osumc** [comment]
Awesome, this is just awesome. I'm so excited y'all :).
