### ISSUE TITLE
Always copy FSharp.Core.xml on output

### ISSUE THREAD

**Issue by TIHan** [dotnet/interactive#871]
We should be copying FSharp.Core.xml when we build so we get the appropriate documentation in interactive.
Related: https://github.com/dotnet/sdk/issues/9498

**Comment by dsyme** [comment]
Duplicate of https://github.com/dotnet/interactive/issues/842?

**Comment by colombod** [comment]
@KevinRansom, @brettfo  is this now fixed?

**Comment by KevinRansom** [comment]
It's hard to say.

**Comment by KevinRansom** [comment]
Always copying it, created an issue for F# developers.  So I made it an opt in switch, I will go through the notebook solution and make sure that we enable it when necessary/

**Comment by jonsequitur** [comment]
Is the only way to solve the actual issue?
