### ISSUE TITLE
Microsoft.DotNet.Interactive.ExtensionLab depends on System.CommandLine version not present on nuget.org

### ISSUE THREAD

**Issue by sanchez** [dotnet/interactive#876]
### Describe the bug
Hi I am trying to follow along with the amazing showcase on dotnetconf right now of the use of SQL inside notebooks, however I am unable to run the following command: `#r "nuget:Microsoft.DotNet.Interactive.ExtensionLab"`

I get the following error in the output:
```
Installing package Microsoft.DotNet.Interactive.ExtensionLab.........
Error: C:\Users\dfitz\AppData\Local\Temp\nuget\7548--fbde0a9e-8cb9-4904-85a9-cfa3bcf198b6\Project.fsproj : error NU1103: Unable to find a stable package Microsoft.DotNet.Interactive.ExtensionLab with version (>= 0.0.0)
C:\Users\dfitz\AppData\Local\Temp\nuget\7548--fbde0a9e-8cb9-4904-85a9-cfa3bcf198b6\Project.fsproj : error NU1103: - Found 87 version(s) in https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json [ Nearest version: 1.0.0-beta.20561.1 ]
C:\Users\dfitz\AppData\Local\Temp\nuget\7548--fbde0a9e-8cb9-4904-85a9-cfa3bcf198b6\Project.fsproj : error NU1103: - Found 4 version(s) in nuget.org [ Nearest version: 1.0.0-beta.20553.2 ]
```

Thanks!

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

**Comment by sanchez** [comment]
Thanks, I was also wondering if the interactive notebook is available somewhere online?

**Comment by sanchez** [comment]
I tried with asterisks, and still received the same error as the above. Thanks

**Comment by jonsequitur** [comment]
We'll add the full sample to that PR or one shortly after.

The published version of the ExtensionLab is [here](https://www.nuget.org/packages/Microsoft.DotNet.Interactive.ExtensionLab/) so if the wildcards aren't working, you should be able to specify the exact version, e.g. `#r "nuget:Microsoft.DotNet.Interactive.ExtensionLab,1.0.0-beta.20553.2`

**Comment by ax0l0tl** [comment]
Hi, I still get the same error as @sanchez with
`#r "nuget:Microsoft.DotNet.Interactive.ExtensionLab,1.0.0-beta.20553.2"`
I'd love to try it...

**Comment by ax0l0tl** [comment]
After reonpening Visual Studio Code Insiders the nuget include seems to work but I get another error, System.CommandLine seems to be unavailable in version 2.0.0-beta1.20478.1:

```
Error: AppData\Local\Temp\nuget\30148--d65cd857-3d98-414d-87fb-bca833ccb787\Project.fsproj : error NU1102: Das Paket "System.CommandLine" der Version (>= 2.0.0-beta1.20478.1) wurde nicht gefunden.
AppData\Local\Temp\nuget\30148--d65cd857-3d98-414d-87fb-bca833ccb787\Project.fsproj : error NU1102: - 15 Version(en) gefunden in "nuget.org" [ N�chste Version: 2.0.0-beta1.20427.1 ]
AppData\Local\Temp\nuget\30148--d65cd857-3d98-414d-87fb-bca833ccb787\Project.fsproj : error NU1102: - 0 Version(en) gefunden in Microsoft Visual Studio Offline Packages.
AppData\Local\Temp\nuget\30148--d65cd857-3d98-414d-87fb-bca833ccb787\Project.fsproj : error NU1102: - 0 Version(en) gefunden in https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json.
```

**Comment by sanchez** [comment]
I seem to be able to fix it by putting: `#r "nuget:System.CommandLine,2.0.0-*"` in a cell then in the same cell after running the above add the following below it: `#r "nuget:Microsoft.DotNet.Interactive.ExtensionLab,1.0.0-beta.20553.2"`. You will need to do this in a blank notebook because of nuget trying to cache the previous requests or something

**Comment by ax0l0tl** [comment]
It worked, thanks!
