### ISSUE TITLE
Cannot install nuget packages

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/interactive#877]
### Describe the bug
Throwing exceptions during installation (see screenshots)

### Version
1.0.156101+537f46e89a1690a55315d805eb90a5877aff9de2

- OS
    - [x] Windows 10
 - Browser
    - [x] Firefox
    - [x] Opera
 - Frontend
    - [x] Jupyter Notebook

### Screenshots

![image](https://user-images.githubusercontent.com/31178401/98936037-739a1f80-24f5-11eb-804b-f6d5c2e81d32.png)

**Comment by WhiteBlackGoose** [comment]
Dotnet version: 5.0.100
I guess it might be the issue

**Comment by jonsequitur** [comment]
This is an old version, when our Jupyter support was part of `dotnet-try`. This is no longer the case. 

Please install the latest using `dotnet tool install -g Microsoft.dotnet-interactive`, run `dotnet interactive jupyter install`, and give it another try.

**Comment by WhiteBlackGoose** [comment]
Hm, indeed. Must've confused some articles and used an old way to install, now it works, thanks
