### ISSUE TITLE
[Question] Is it possible to customize the way types are drawn in jupyter?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/interactive#878]
I noticed that we can use `display`, but is there a way to make it look like we do it in python? Maybe some method overload so that my type's output is some specific html code?
In python there is `_repr_html_` for that

I'm sorry if it's a duplicate, but I didn't find it.

**Comment by jonsequitur** [comment]
You can customize formatting for any type using the `Formatter` APIs. What you can see here is the default behavior (`ToString`) and then the modified behavior. 

![image](https://user-images.githubusercontent.com/547415/98967867-d5d92d00-24c1-11eb-8cb3-957ffcc38522.png)

(This assumes a notebook default MIME type of `text/html`. This might change to `text/plain`. See #642.)

More details here: https://github.com/dotnet/interactive/blob/main/docs/formatting.md

Also take a look at [`PocketView`](https://github.com/dotnet/interactive/blob/main/docs/pocketview.md) if you don't want to handle your own string interpolation and HTML encoding.

**Comment by WhiteBlackGoose** [comment]
Amazing, thanks! I was making it for a lib
![image](https://user-images.githubusercontent.com/31178401/98970625-33e92d00-2521-11eb-8dac-be9eaeb46ebe.png)

**Comment by colombod** [comment]
> Amazing, thanks! I was making it for a lib
> ![image](https://user-images.githubusercontent.com/31178401/98970625-33e92d00-2521-11eb-8dac-be9eaeb46ebe.png)

ohh can you expand, this is too cool

**Comment by jonsequitur** [comment]
This is a perfect use case for a kernel extension. In case this wasn't on your radar: https://github.com/dotnet/interactive/tree/main/samples/extensions

**Comment by WhiteBlackGoose** [comment]
@colombod 
I'm building a symbolic algebra lib, and I managed to use mathjax inside html I was rendering via that formatter registration. That is how it's being rendered now XD

**Comment by colombod** [comment]
@WhiteBlackGoose I would like it a lot as extensions that people can use in .NET Interactive, very powerful tools for scientific notebooks and education applications

**Comment by WhiteBlackGoose** [comment]
@colombod Now imagine I will (hopefully) soon push a nuget package that will override this rendering by default so that people will experience same thing as they would in python's sympy... but in .NET. It's awesome, isn't it?
