### ISSUE TITLE
F#'s printfn adds newlines around format specifiers in VSCode extension

### ISSUE THREAD

**Issue by bisen2** [dotnet/interactive#879]
### Describe the bug
In a notebook using the VSCode extension, strings printed with F#'s `printfn` have newlines before and after a format specifier, but strings constructed using `sprintf` and piped to `Console.WriteLine` do not. For example, see screenshot below. This seems to be isolated to the VSCode frontend as I have not been able to reproduce it in Jupyter (locally or on Binder).

### Version:

Version: 1.0.156101+537f46e89a1690a55315d805eb90a5877aff9de2
Build Date: 2020-11-12T14:16:54.6407468Z

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/39412411/98964622-0bd4dc00-24d7-11eb-967d-773adb1e2a3d.png)

**Comment by jonsequitur** [comment]
This is probably the same issue as #799.
