### ISSUE TITLE
EntityFrameworkCore: System.BadImageFormatException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces

### ISSUE THREAD

**Issue by trmcnealy** [dotnet/interactive#88]
#### Describe the bug
Jupyter Lab Notebook loading assembly that uses Microsoft.EntityFrameworkCore.

#### Did this error occur while using `dotnet try` or online?
 .NET Jupyter Lab Notebook localhost

#### What kind of error was it?
System.BadImageFormatException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Submission#4.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

   at Submission#4.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

#### Please complete the following:
 - OS
    - [ ] Windows 10
 - Browser 
    - [ ] Chrome

**Comment by colombod** [comment]
@trmcnealy I was trying to repro the issue using your binder but it seems that the versions of nuget packages loaded in the TexasOilGasProduction.ipynb notebook have different apis that are not compatible with the notebook code.

Do you still have the bad image format issue? 

To make notebooks more reproduceable you can use the version when importing the pakcages
```
#r "nuget:VegaLite.NET,1.0.8"
#r "nuget:OilGas.Data,1.0.1"
```

That way your notebooks should be resilient to new package published

**Comment by trmcnealy** [comment]
I've updated those libraries several times since posting this. I ran the notebook again with the versions used to generate the error. System.BadImageFormatException didnt show up but neither did any data. I'm working on finished up my remote DB and I will test the notebook out then.
