### ISSUE TITLE
Failed to create dbcontext

### ISSUE THREAD

**Issue by sanchez** [dotnet/interactive#880]
I have been continuing down the path of trying to get the SQL functionality within vs notebooks working and I have hit another error. Currently I am trying to create a dbcontext like demonstrated here: [https://youtu.be/938jBJ-tK3c?t=1281](https://youtu.be/938jBJ-tK3c?t=1281)

However I receive an error of: `C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json. [Project.fsproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error : Response status code does not indicate success: 429 (). [Project.fsproj]` (I have removed the directory of Project.fsproj in the error log there, it was in my temp directory under nuget under a guid folder)

The command I was running: `#!connect --kernel-name worldwideimporters mssql "Data Source=localhost;Initial Catalog=license;Integrated Security=True" --create-dbcontext`

OS: Windows 10
Frontend: VS Code

**Comment by jonsequitur** [comment]
This is an HTTP throttling error on the NuGet package source. Is it still happening?

**Comment by sanchez** [comment]
This error seems to be resolved currently, I have received a new error however while still trying to create the dbcontext. Would you like me to open a new issue or just continue this thread?

**Comment by jonsequitur** [comment]
Is it this issue? #883.

If so, we can track it there, but otherwise feel free to add info to this issue.

**Comment by sanchez** [comment]
Sadly no, the error I am getting is as follows:

```
Error: (11,1): error CS1705: Assembly 'Microsoft.EntityFrameworkCore.Design' with identity 'Microsoft.EntityFrameworkCore.Design, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.DependencyInjection.Abstractions' with identity 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
(16,1): error CS1705: Assembly 'Microsoft.EntityFrameworkCore' with identity 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.DependencyInjection.Abstractions' with identity 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

**Comment by jonsequitur** [comment]
This should now work using the latest packages from our CI feeds:

```csharp
```
