### ISSUE TITLE
Can't install .NET Jupyter in WSL2 after installing .NET Core 5.0

### ISSUE THREAD

**Issue by MaximoTrinidad** [dotnet/interactive#882]
### Describe the bug
Please provide as much information as you can.

After installing .NET Components in Linux Ubuntu 20.04, I can't proceed to install Jupyter interactive:
```
(base) max_t@maxtlaptop1:~$ dotnet interactive jupyter install
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.0 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.20.04-x64
(base) max_t@maxtlaptop1:~$
```

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

Following .NET command didn't work:
```
(base) max_t@maxtlaptop1:~$ dotnet interactive --versions
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.0 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.20.04-x64
(base) max_t@maxtlaptop1:~$
```
Strangely, the error is pointing to _"framework_version=3.1.0"_.

This other command works:
```
(base) max_t@maxtlaptop1:~$ dotnet --version
5.0.100
(base) max_t@maxtlaptop1:~$
```
Listing runtimes:
```
(base) max_t@maxtlaptop1:~$ dotnet --list-runtimes
Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
(base) max_t@maxtlaptop1:~$
```

- OS
    - [ X] Windows 10 - ver.2004 (OSBuild 20257.1)
    - [ ] macOS
    - [ X] Linux (Please specify distro) - Ubuntu 20.04
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
![Jupyter_InstallError_01_2020-11-16_10-19-56](https://user-images.githubusercontent.com/19892435/99272137-7054ab80-27f5-11eb-9391-1a8f4c2da169.png)

**Comment by kurt-mueller-osumc** [comment]
I think dotnet interactive only supports dotnet core 3.0 for now.

**Comment by colombod** [comment]
> I think dotnet interactive only supports dotnet core 3.0 for now.

You are right, the tool it is a netcoreapp3 profile, you need to install also the LTS version of .NET SDK

**Comment by MaximoTrinidad** [comment]
@kurt-mueller-osumc 

But... if it doesn't, why it install the runtimes:
```
(base) max_t@maxtlaptop1:~$ dotnet --list-runtimes
Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
(base) max_t@maxtlaptop1:~$
```

And, PowerShell is updated to 7.1.0.
```
(base) max_t@maxtlaptop1:~$ dotnet tool list --global
Package Id                        Version         Commands
--------------------------------------------------------------------
microsoft.dotnet-interactive      1.0.155302      dotnet-interactive
powershell                        7.1.0           pwsh
(base) max_t@maxtlaptop1:~$
```

I would guess the possibility that they miss updating the Jupyter piece.

:)

**Comment by MaximoTrinidad** [comment]
@colombod 

Interesting! I always follow the instructions on Microsoft Document at:
https://docs.microsoft.com/en-us/dotnet/core/install/linux#ubuntu

It shows .NET Core 5.0 support for Ubuntu 20.04.
:)

**Comment by MaximoTrinidad** [comment]
So, after looking around the repository, when can we expect "**.NET Interactive Jupyter kernel**" to be updated to support .NET Core 5.0?
At least the PowerShell tool got updated to v7.1.0.

**Comment by jonsequitur** [comment]
Related: #869

**Comment by colombod** [comment]
@MaximoTrinidad We did update to .NET 5.0 is it now working for you?

**Comment by MaximoTrinidad** [comment]
@colombod,

Sorry for the late response! I just survive a stroke  couple weeks ago before Christmass.  I'm good now  getting back to my normal self.

i reinStall WSL2 I'm still can'tmake dotnel Jupyter work in WSL2.

```
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.1 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

```
dotnet --info
```
(base) max_t@maxtlaptop1:~$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
dotnet --list-runtimes
```
(base) max_t@maxtlaptop1:~$ dotnet --list-runtimes
Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
dotnet interactive jupyter install
```
(base) max_t@maxtlaptop1:~$ dotnet interactive jupyter install
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.1 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.18.04-x64
(base) max_t@maxtlaptop1:~$
```
see image
![donet jupyter_01_2020-12-27_12-11-20](https://user-images.githubusercontent.com/19892435/103177040-b49b8880-4844-11eb-8514-e53e447928cc.png)

**Comment by MaximoTrinidad** [comment]
@iSazonov,

the error finally is resolved after updating the "dotnet. interactive" component  with the following command in WSL:

```
PS /home/max_t> dotnet tool update -g --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" Microsoft.dotnet-interactive
```
Then followed by the command that used to would failed at the end;
```
PS /home/max_t> dotnet interactive jupyter install

Welcome to .NET Interactive!
---------------------
Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience.The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Installing using jupyter kernelspec module.
Installed ".NET (C#)" kernel.
Installing using jupyter kernelspec module.
Installed ".NET (PowerShell)" kernel.
Installing using jupyter kernelspec module.
Installed ".NET (F#)" kernel.
```

![no error_2021-01-17_20-54-02](https://user-images.githubusercontent.com/19892435/104865136-32652800-5909-11eb-8695-d7e99ced9676.png)

I updated PowerShell global ;

```
PS /home/max_t> dotnet tool update -g Microsoft.dotnet-interactive
Tool 'microsoft.dotnet-interactive' was reinstalled with the latest stable version (version '1.0.155302').
PS /home/max_t> dotnet tool update -g powershell
Tool 'powershell' was successfully updated from version '7.1.0' to version '7.1.1'.
```
But when run jupyter notebook and use the $PSVersion it's showing an older version that doesn't exist in my system. 

So my question is when can I expect the newer version of PowerShell to BE available for Notebook?

![nopwsh update_2021-01-17_20-54-02](https://user-images.githubusercontent.com/19892435/104865162-414bda80-5909-11eb-9a2d-eb2b8c6560a9.png)

**Comment by iSazonov** [comment]
> So my question is when can I expect the newer version of PowerShell to BE available for Notebook?

/cc @TylerLeonhardt

**Comment by jonsequitur** [comment]
@MaximoTrinidad .NET Interactive carries its own version of PowerShell, which is why the discrepancy.

**Comment by MaximoTrinidad** [comment]
@jonsequitur 

Thanks!

**Comment by colombod** [comment]
@MaximoTrinidad hope you are doing good! Can this issue be closed?

**Comment by MaximoTrinidad** [comment]
@colombod 

Let me do another round of updates on my WSL2 and I will let you know today. 
Thanks for your patience!

**Comment by MaximoTrinidad** [comment]
Woohoo!!

I ran the updates commands:

`dotnet tool update -g Microsoft.dotnet-interactive`
`dotnet tool update -g powershell`

And it works:
```
(base) max_t@maxtlaptop1:~$ dotnet tool update -g Microsoft.dotnet-interactive

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.201

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Tool 'microsoft.dotnet-interactive' was successfully updated from version '1.0.212202' to version '1.0.221505'.
(base) max_t@maxtlaptop1:~$ dotnet tool update -g powershell
Tool 'powershell' was successfully updated from version '7.1.2' to version '7.1.3'.

```
![jupyterGood](https://user-images.githubusercontent.com/19892435/115794836-b9a8b880-a39c-11eb-881c-2624523a9468.jpg)

I'm closing this issue!
Thanks
