### ISSUE TITLE
[EXTERNAL] Display of one string result is truncating last character

### ISSUE THREAD

**Issue by thanasis31** [dotnet/interactive#887]
### Describe the bug
Trying to print a string truncates the last character (both in F# and C#)
When trying to print/display a tuple, it works as expected.

VS Code insiders
Version: 1.52.0-insider (user setup)
Commit: d19c7c52fd364dda47aa34d4284b4d3ff43c69b0
Date: 2020-11-17T06:05:20.789Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

.NET Interactive Version
Version: 1.0.156101+537f46e89a1690a55315d805eb90a5877aff9de2
Build date: 2020-11-13T15:38:16.8734918Z

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/7754433/99441383-b0a84c80-290f-11eb-9542-96b28f23f36d.png)

**Comment by brettfo** [comment]
Issue is confirmed to be in VS Code and not this extension.  I've filed the issue here: microsoft/vscode#110826.

**Comment by brettfo** [comment]
Confirmed fixed in today's Code Insiders release.
