### ISSUE TITLE
Command line invocation of dib files

### ISSUE THREAD

**Issue by onionhammer** [dotnet/interactive#892]
Execute `dotnet interactive run file.dib -o report.md` to run the entire report and export as markdown or HTML. This would be great to be able to generate reports periodically that can be consumed by non-developers.

**Comment by jonsequitur** [comment]
Thanks for the suggestion. This is something we're actively looking into. 

I'm going to close this as it's a duplicate of #483. Feel free to add suggestions there for how you'd like to see this work.
