### ISSUE TITLE
new kernels ignored, working with winpython

### ISSUE THREAD

**Issue by yilmazdurmaz** [dotnet/interactive#898]
**Is your feature request related to a problem? Please describe.**
I use both dotnet core and winpython from their no-install packages. dotnet paths are set in environment and I use winpython command line starter to set python environment then start programs in it. likewise, nteract is in a folder extracted from its zipped file.

dotnet and/or winpython, for some reason, install new kernels into "%WinPython%\settings\kernels\" . however nteract seems to check only "%WinPython%\%python%\share\jupyter\kernels\" thus does not recognize those other kernels. manually copying kernel files (after all they are just simple interface json setting files) helps nteract to see them, but time consuming for every new kernel and it is prone to problems if a kernel happens to depend on location.

**Describe the solution you'd like**

Checking for winpython distribution and then adding kernels in the mentioned "settings" folder would be nice to have addition.

**Describe alternatives you've considered**
manual copying of kernels

**Comment by jonsequitur** [comment]
We have a few conventions in place for locating the Jupyter kernelspec path and this might be worth considering.

Another option that we currently support is specifying the `--path` option when you run `dotnet interactive jupyter install`:

```console
> dotnet interactive jupyter install -h
install:
  Install the .NET kernel for Jupyter

Usage:
  dotnet-interactive jupyter <connection-file> install [options]

Arguments:
  <connection-file>

Options:
  --http-port-range <http-port-range>    Specifies the range of ports to use to enable
                                         HTTP services [default: Microsoft.DotNet.Interac
                                         tive.Http.HttpPortRange]
  --path <path>                          Installs the kernelspecs to the specified
                                         directory
  --log-path <log-path>                  Enable file logging to the specified directory
  --verbose                              Enable verbose logging to the console
  -?, -h, --help                         Show help and usage information
```

**Comment by yilmazdurmaz** [comment]
@jonsequitur  I just noticed I made a mistake.

I was trying to use "nteract" to see how it does compared to "jupyter lab/notebook" and the problem I described belongs to "nteract". I couldnt notice this until I was trying to recreate some of my works with it.  I am not sure if other kernels installs the same location as dotnet does. in any case I will copy the content to nteract's issues page.

the topic may stay alive for a while depending on the relevance about kernel path, else feel free to close the issue.

and thanks for the answer

**Comment by jonsequitur** [comment]
Feel free to link the issue here. Installers are always a game of increments so it helps to keep an eye on all of the edge cases.

When I have an nteract question of course I always try to page @captainsafia...

**Comment by captainsafia** [comment]
The associated issue in nteract is https://github.com/nteract/nteract/issues/5366.

nteract checks the Jupyter data dirs to determine where kernelspecs are installed. What is the result of running the following on the command prompt on your machine?

```
> jupyter --paths
```

**Comment by yilmazdurmaz** [comment]
@captainsafia  here are what jupyter shows

`jupyter --paths`
```
config:
    C:\Users\durmaz\.jupyter
    t:\Tools\WinPython64\python-3.8.3.amd64\etc\jupyter
    C:\ProgramData\jupyter
data:
    T:\Tools\WinPython64\settings
    t:\Tools\WinPython64\python-3.8.3.amd64\share\jupyter
    C:\ProgramData\jupyter
runtime:
    T:\Tools\WinPython64\settings\runtime
```
"C:\ProgramData\jupyter" does not exist, yet I guess they put the path for when it does

I played with `jupyter kernelspec list` command along with copying/renaming kernels into folders shown in the list above; config and data folders.

jupyter itself recognizes kernels in the order their folders appear in the list above. it interestingly uses "t:\Tools\WinPython64\python-3.8.3.amd64\lib\site-packages\ipykernel\resources" if there are no "kernels" folder in those directories.

nteract responds kernels only inside  "t:\Tools\WinPython64\python-3.8.3.amd64\share\jupyter". (it also somehow finds a kernel related to my old winpython at "t:\Tools\WPy64-3760\" but it is another story in another issue I guess)

**Comment by captainsafia** [comment]
@yilmazdurmaz Thanks for sharing. Yeah, there's definitely some weirdness that ends up happening with the way that paths are configured when you use WinPython. I've seen a few issues related to this in the different repos.

The `jupyter_client` that is used by the Jupyter server when you run `jupyter notebook` has a lot more hardening when it comes to stuff like this but nteract communicates with the kernel over 0mq directly which is where these errors come up.

@jonsequitur I don't think this is dotnet-interactive related so feel free to close this in favor of the issue in the nteract repo.

**Comment by jonsequitur** [comment]
Cool. Thanks for helping out!
