### ISSUE TITLE
Nuget package installation failure in Jupyter notebook

### ISSUE THREAD

**Issue by kasozivincent** [dotnet/interactive#901]
Hello.
I have been trying to install C# in jupyter notebook but it seems things aren't working well for me. I was able to install the C# and F# kernel but when i try to install a nuget package from the notebook, i get an exception.
![image](https://user-images.githubusercontent.com/56205969/99868229-8fe13080-2b75-11eb-84ad-395f52a0dabb.png)
I will be grateful for your help pls.

**Comment by jonsequitur** [comment]
This stack trace indicates that you're using the original preview of the Jupyter support in `dotnet-try`. 

In your console, please run:

```console
> dotnet tool install -g Microsoft.dotnet-interactive
```

Then in an Anaconda prompt (or other Jupyter-aware console), please run:

```console
> dotnet interactive jupyter install
```

Restart Jupyter and see if this solves it.

If not, please post the output of the following commands:

```console
> dotnet tool list -g
> dotnet --info 
```

**Comment by kasozivincent** [comment]
[image: image.png]
Hello, good evening Mr. Jon Sequeira. I tried running the first 2 commands
but for dotnet tool install -g Microsoft.dotnet-interactive, I am told that
it already exists and for "dotnet interactive jupyter install", I am told
it is not a valid command. Above is the output of the last 2 commands that
you asked me to run. Thanks

**Comment by jonsequitur** [comment]
The image didn't come through.

**Comment by kasozivincent** [comment]
What could be the procedure for unistalling dotnet-try from my pc? Thank you

**Comment by kasozivincent** [comment]
[image: image.png]

**Comment by kasozivincent** [comment]
It seems i am having both dotnet-try and dotnet-interactive installed. I
wonder how i can remove dotnet-try. Any help will be appreciated. Thanks

**Comment by jonsequitur** [comment]
You can remove `dotnet-try` by running either/both of:

```console
> dotnet tool uninstall -g dotnet-try
> dotnet tool uninstall -g Microsoft.dotnet-try
```

You can update the existing `dotnet-interactive` install by doing:

```console
> dotnet tool update -g Microsoft.dotnet-interactive
```

Then try running this again, from your Anaconda prompt:

```console
> dotnet interactive jupyter install
```

**Comment by kasozivincent** [comment]
Hello. Why is it saying « Required command was not provided » when I tried
to run these first 2 commands that you sent me?

**Comment by jonsequitur** [comment]
Can you post the entire console input and output?

**Comment by kasozivincent** [comment]
Sorry for the inconveniences. I had typed the command wrongly. Now am
trying to uninstall but it seems the folder .dotnet where dotnet-try can be
accessed. Access denied even when I ran cmd with administrator rights

**Comment by gkiryaziev** [comment]
I have error with nuget, when I try to add package with #r command.
dotnet: 5.0.100
dotnet-interactive: 1.0.157409+69b86441f75e5663aa2c1568ae971127de9cd02e

![2020-11-30_092418](https://user-images.githubusercontent.com/8873218/100582000-343f4180-32f1-11eb-902f-32c85f3a5d37.png)

**Comment by jonsequitur** [comment]
Are you still running into issues, @kasozivincent?

**Comment by kasozivincent** [comment]
No, everything is fine now. Thanks
