### ISSUE TITLE
External Kernel Extensions with Formatters cannot load anymore `System.MissingMethodException`

### ISSUE THREAD

**Issue by WalternativE** [dotnet/interactive#908]
### Describe the bug
Since the newest update, kernel extension containing a call to `Formatter.Register` will fail with the following stack trace

```
Loading kernel extension "ClockKernelExtension" from assembly /home/gregor/.nuget/packages/clockextension/1.3.5/interactive-extensions/dotnet/ClockExtension.dll
Error: Microsoft.DotNet.Interactive.KernelExtensionLoadException: Failure loading Kernel Extension
---> System.MissingMethodException: Method not found: 'Void Microsoft.DotNet.Interactive.Formatting.Formatter.Register(System.Action`2<!!0,System.IO.TextWriter>, System.String, Boolean)'.
at ClockExtension.ClockKernelExtension.OnLoadAsync(Kernel kernel)
at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembly(FileInfo assemblyFile, Kernel kernel, KernelInvocationContext context) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 130
--- End of inner exception stack trace ---
```

I tested the most common overloads using the different `Func` and `Action` delegates as well as the one taking an `ITypeFormatter`. The behavior is reproducible with extensions written in F# (currently all my extensions are failing unfortunately) as well as the ones in C# (I tested the `ClockExtension` in this repo to see if it only hits F# projects - it appears to impact everything).

I tried to snoop around in the source code but I fear, that I don't understand it well enough to find the problem. If I can add any more info I'm always happy to help.

### Please complete the following:

VSCode Plugin Version:  v1.0.157302 (Git SHA 6dfc99911743a633b5edbac09a8c5fe5e5e9f980)

![image](https://user-images.githubusercontent.com/5071748/100163643-72360300-2eb6-11eb-8373-b1b7099c44d7.png)

- OS
    - [ x] Windows 10 (remote on WSL2 Ubuntu 20.04)
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [x] Not applicable
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/5071748/100163668-811cb580-2eb6-11eb-8626-0953288e9c77.png)

![image](https://user-images.githubusercontent.com/5071748/100163696-8d087780-2eb6-11eb-8145-6ac294d82506.png)

**Comment by colombod** [comment]
Hi, We introduced some breaking changes with Preview3 and we are still in the process of formalising the extension api. The clock extension in the repo is up to date and should help you understanding the changes.

Is it possible for you to upgrade your custom F# extensions?

**Comment by WalternativE** [comment]
Hi @colombod! Thanks for looking into it. I wouldn't know how to change my extensions because the clock extension is also broken for me. I'm currently at commit `61d231529ce8657172c65b389e3524ae72cd30b7` (should be the head of the repo). I'm using the `ClockExtension.ipynb` notebook to build and load the extension. Unfortunately it doesn't load successfully - the failure message is the same as stated above. Am I missing something?

Are you referring to another extension I'm not aware of? Can I somehow reproduce the working behavior with some other extension in the repo? If there is a way I'd be happy to add the changes to my projects.

**Comment by colombod** [comment]
I am pushing an update for the project, this is what I see using the extension
![image](https://user-images.githubusercontent.com/375556/100459006-a0852f80-30bc-11eb-8242-109007b9f280.png)
with this .NET Interactive
![image](https://user-images.githubusercontent.com/375556/100459056-b266d280-30bc-11eb-8d38-5fafb7da5edd.png)

**Comment by colombod** [comment]
Look at #913 to see the changes

**Comment by WalternativE** [comment]
I tested my extension packages with your suggested changes. It works perfectly 🎉🎉🎉🎉 Thank you very much for your help and for your patience with my issue. Really loving to see dotnet interactive being updated to .NET 5 that quickly.

**Comment by colombod** [comment]
@WalternativE you are most welcome
