### ISSUE TITLE
create-dbcontext gives error Microsoft.Extensions.DependencyInjection.Abstractions version

### ISSUE THREAD

**Issue by hansderks** [dotnet/interactive#915]
Using command:
`#!connect --kernel-name portaldbcontext mssql "Persist Security Info=false;Initial Catalog=PortalDB;Server=localhost\mssqlserver2019;Integrated Security=true;" --create-dbcontext `

Gives error:
Scaffolding a DbContext and initializing an instance of it called portaldbcontext in the C# kernel.

Installed package Microsoft.EntityFrameworkCore.SqlServer version 5.0.0
Installed package Microsoft.EntityFrameworkCore.Design version 5.0.0
Error: (11,1): error CS1705: Assembly 'Microsoft.EntityFrameworkCore.Design' with identity 'Microsoft.EntityFrameworkCore.Design, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.DependencyInjection.Abstractions' with identity 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
(16,1): error CS1705: Assembly 'Microsoft.EntityFrameworkCore' with identity 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.DependencyInjection.Abstractions' with identity 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

Using package Microsoft.DotNet.Interactive.ExtensionLab version 1.0.0-beta.20574.9

What I've tried:
* Clean local nuget caches
* In a cell before #r "nuget:Microsoft.Extensions.DependencyInjection.Abstractions"

Any idea how to fix this?

**Comment by jonsequitur** [comment]
This should now work using the latest packages from our CI feeds:

```csharp
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json"
#r "nuget:Microsoft.DotNet.Interactive.ExtensionLab,*-*"
```
