### ISSUE TITLE
Error with nuget while adding package with #r command.

### ISSUE THREAD

**Issue by gkiryaziev** [dotnet/interactive#916]
I have error with nuget, when I try to add package with #r command. And this happens with adding of any packages.

dotnet: 5.0.100
dotnet-interactive: 1.0.157409+69b86441f75e5663aa2c1568ae971127de9cd02e
python (venv): 3.6.8

![2020-11-30_092418](https://user-images.githubusercontent.com/8873218/100582000-343f4180-32f1-11eb-902f-32c85f3a5d37.png)

But at this time in RoslynPad everything works.

![2020-11-30_095453](https://user-images.githubusercontent.com/8873218/100582684-48377300-32f2-11eb-8f11-90f88e90b569.png)

**Comment by brettfo** [comment]
Can you try with a different syntax for specifying the package version?  The slash `/` between the package name and version number isn't supported by .NET Interactive, but a comma `,` is.

E.g.,

```
#r "nuget:PuppeteerSharp,2.0.4"
```

![image](https://user-images.githubusercontent.com/926281/100686366-0844b000-3333-11eb-8433-e92856a07713.png)

**Comment by gkiryaziev** [comment]
Thanks a lot, yes, the slash **/** was the problem. Everything works well now. Even without specifying a version.

![2020-12-02_095128](https://user-images.githubusercontent.com/8873218/100844313-6339ec80-3484-11eb-9b6b-990c67dcbbc2.png)
