### ISSUE TITLE
Jupyter and .NET interactive extension side by side

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/interactive#917]
### **Scenario**: User has .NET Interactive extension and has installed the Jupyter Extension

**Environment**

Installed 
- .NET Core 3.1 and 5.0 
- .NET Interactive extension
- VS Code Insiders  

Not installed 
- python 
- Jupyter 

### Out of box experience (OOB)
- Installed the Jupyter extension 
- Created a Jupyter:Create New Blank Jupyter Notebook (ctrl + shift + P)
- This happens 
![image](https://user-images.githubusercontent.com/2546640/99831743-8e8c1580-2b2d-11eb-90af-f46ac249410d.png)
- Default language is python - suggestion/ question: If Python is not installed default to the kernel on available or ask user to select language?
![image](https://user-images.githubusercontent.com/2546640/99832968-5dace000-2b2f-11eb-842e-c8a62501afa7.png)
- I selected C# Interactive using the language picker and hit run. 
- Prompted to select notebook - kernel to run this notebook. 
**Note**:  From a user perspective they could be left unsure what to do at this point. 

![image](https://user-images.githubusercontent.com/2546640/99833430-f80d2380-2b2f-11eb-9059-91879508c4c3.png)

**Note**: There is C# kernel and .NET Interactive C# kernel in the kernel provider list. This could confuse our customers. 

### Tried workaround 

- Install the dotnet interactive global tool

` dotnet tool install -g --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" Microsoft.dotnet-interactive`

- This works temporarily 

### Issues 
-  .NET IntelliSense is gone in this experience. 
-  Polyglot notebooks doesn't seem to work either
- If you close then open VS Code Insiders then try creating or open a C# .ipynb file the OOB experience happens again. 

**Additional Notes**
- If you open and run a notebook in .NET Interactive then open a new notebook in the Jupyter extension the cell will run.

**Comment by jonsequitur** [comment]
Related: 

https://github.com/microsoft/vscode/issues/106694
https://github.com/microsoft/vscode/issues/113937

**Comment by jonsequitur** [comment]
Can this be closed?

**Comment by LadyNaggaga** [comment]
Yes, we can. I can no longer repo this issue.
