### ISSUE TITLE
VS Code extension won't start - Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by TylerLeonhardt** [dotnet/interactive#934]
### Describe the bug

The VS Code extension won't start. If I look in the dev tools, this is what I see:

![image](https://user-images.githubusercontent.com/2644648/101522535-3b430100-393c-11eb-8b51-48249978a18c.png)

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.

From VS Code:

> Installing .NET Interactive version 1.0.160204...

* VS Code: 1.52-insiders
* .NET Interactive extension: v1.0.160204
* .NET Install Tool extension: v1.0.0

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

**Comment by TylerLeonhardt** [comment]
I just got this with the Jupyter Notebooks extension too so this might not be your fault... cc @rebornix

**Comment by bmitchell-cfs** [comment]
I am having this issue as well, both when trying to open an existing notebook and when trying to open a new one. I'm on Windows 10 in Visual Studio Code with .NET Interactive Notebooks v1.0.160901.

![image](https://user-images.githubusercontent.com/64422988/101837831-ab54b100-3b0d-11eb-97c4-d176a0e753a7.png)

**Comment by jonsequitur** [comment]
Do you have .NET 5 installed?

**Comment by bmitchell-cfs** [comment]
I thought I had (to get .NET 5 features of F#), but apparently not on this machine:

```
PS C;\> dotnet --list-sdks
3.1.301 [C:\Program Files\dotnet\sdk]
3.1.401 [C:\Program Files\dotnet\sdk]
```

But this is the only machine I've used .NET Interactive on. I developed the F# interactive notebook I was trying to open on this same computer. The version of the .NET Interactive extension was different though since it automatically upgraded itself.

I have been using a released version of Visual Studio Code though. I went ahead now and downloaded Visual Studio Code Insiders and installed the .NET Interactive extension. It said it was downloading the .NET runtime (in the lower toolbar) and when I clicked on it, it gave:

```
Downloading .NET runtime version(s) 5.0.1 ............ Done!
.NET 5.0.1 executable path: c:\Users\bmitchell\AppData\Roaming\Code - Insiders\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\5.0.1\dotnet.exe
```

but then it gave the same error as above. I saw the same message as downloading .NET runtime earlier for the released version as well, but didn't see the output message.

**Comment by bmitchell-cfs** [comment]
I'm sorry, I listed the wrong command earlier. It listed SDKs and not runtimes. However, .NET 5 is still not a registered installed runtime according to the command.

```
PS C:\> dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by jonsequitur** [comment]
The F# 5 language features have been available in .NET Interactive since the outset, on .NET Core 3.1, without needing the .NET 5 SDK. However, we've recently changed .NET Interactive to depend upon the .NET 5 SDK. 

Could you try installing the .NET 5 SDK and see if the issue persists?

Apologies for any confusion.

**Comment by bmitchell-cfs** [comment]
That indeed fixed it! I installed .NET 5 SDK through the Visual Studio Installer.

```
PS C:\> dotnet --list-sdks
3.1.401 [C:\Program Files\dotnet\sdk]
5.0.101 [C:\Program Files\dotnet\sdk]
```

Now my notebook opens properly. Apologies if I missed a change in the prerequisites and if the issue I described is different than the original issue above. Hopefully the solution is the same for them. Thanks for the help!

**Comment by jonsequitur** [comment]
@TylerLeonhardt Can you repro this with the .NET 5 SDK installed?

**Comment by TylerLeonhardt** [comment]
I thought the extension installs .NET 5?

**Comment by jonsequitur** [comment]
It installs the runtime but not the SDK.

**Comment by EverybodyKurts** [comment]
I have `.net5.0` installed, just created a brand new interactive notebook with dotnet-interactive and now get this error message when I attempt to open the notebook in vs code insiders:

```
Unable to open 'notebook.ipynb': Cannot read property 'rendererId' of undefined.
``

**Comment by jonsequitur** [comment]
I haven't been able to reproduce this issue recently. If anyone can, please reopen it and comment here with what version of the extension you're using.

Thanks.

**Comment by grenaad** [comment]
I have similar error when opening a notebook that had a R kernel:
`Unable to open 'a.ipynb': Cannot read property 'Error' of undefined.`

Also when creating a new Python Notebook, making statements in the cells is working, when trying to display them it just runs forever (image below). I tried looking at logs for vscode (Extension Host Logs and the Console logs). But could not see any error been raised. I can open the notebooks with Jupyter (`jupyter notebook`) and it work's as expected.

![image](https://user-images.githubusercontent.com/62886631/107872344-69037380-6eb2-11eb-9dd8-68fddf1b1c85.png)

Are there any other places that I can check for logs?

OS: Linux Pop-OS, kernel 5.8.0
.NET SDK: 5.0.103
VS Code: 1.54-insiders
.NET Interactive extension: v1.0.210803
.NET Install Tool extension: v1.0.0

**Comment by RCKSE** [comment]
I just had this issue occur for the first time today following an update to VS Code Insiders v1.54.0-insider. I am no longer able to open notebook files that opened fine yesterday, and that continue to open fine in the non-insider's version. The issue persists after installing the .NET 5.103 SDK .

I was able to reproduce the problem on another machine that had not yet updated to this version: everything worked as expected, restarted VSCode to update, now unable to open any notebooks in VS Code Insiders following the update. 

Not seeing any newer issues reported on this problem, so I estimate it's not widespread for this Insider's update. Anyone else experience/fix this issue?

![image](https://user-images.githubusercontent.com/37892286/107988808-a6850100-6f85-11eb-9c04-045171a953a1.png)

Version: 1.54.0-insider (user setup)
Commit: a699ffaee62010c4634d301da2bbdb7646b8d1da
Date: 2021-02-15T05:17:48.792Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363
