### ISSUE TITLE
NuGet package installation using #r should time out if unsuccessful

### ISSUE THREAD

**Issue by Niharikadutta** [dotnet/interactive#941]
### Describe the bug
When a NuGet package that is requested to be installed via `#r` doesn't have any information or the information is not in the valid format, the installation should time out after a reasonable amount of time.

### Please complete the following:

**Which version of .NET Interactive are you using?**
1.0.148005+edf63ecfafe2edf40db46afa555c86542b9fe26f

- OS
    - [ ] Windows 10
    - [ ] macOS
    - [x] Linux (Ubuntu 16.04)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [x] Other (Azure Synapse)

### Screenshots
As seen in the below screenshot, `Spark.NET-Binaries` is never successfully installed and shows up even when trying to install a different NuGet package:

![image](https://user-images.githubusercontent.com/8151864/101717927-14c4b900-3a55-11eb-9ac7-ec07e28c38af.png)

This can be avoided if installing an invalid NuGet package is timed out after some set time.

**Comment by KevinRansom** [comment]
Thanks for this, I added a timeout to our package managemer, it times out after 3 minutes.

I will add an issue to implement a user controlled timeout value.
