### ISSUE TITLE
Kernels immediately restart after "Stop all notebook kernels" command is invoked

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#946]
After invoking **Stop all notebook kernels**:

![image](https://user-images.githubusercontent.com/547415/102527252-b057ba00-4051-11eb-9f1f-6a83b5872d1b.png)

**Comment by brettfo** [comment]
Can you try this with your mouse cursor outside of the VS Code window?  Any action on a notebook will start the kernel if it's not present and I'm wondering if you stopped the kernels, but then a mouse move triggered a hover text request which would have restarted the kernels again.

**Comment by jonsequitur** [comment]
Same behavior, and in fact when I have multiple notebooks open, all of them stop and restart. Could the async diagnostics be triggering this?

**Comment by brettfo** [comment]
This has been fixed.
