### ISSUE TITLE
Using printf or printfn with F# incorrectly inserts newlines

### ISSUE THREAD

**Issue by bmitc** [dotnet/interactive#951]
### Describe the bug
When using `printf` and `printfn` in an F# cell, newlines get entered before and after parameterized values. For example, if one runs:

```
printfn "Number = %.2f, String = %s" 2.123 "testing"
```

Then the result looks like this:
![image](https://user-images.githubusercontent.com/65685447/102704788-66cfc080-4245-11eb-9eb5-f5b974372a9f.png)

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

**Version**: 1.0.160901+a5db2e2c034eb03ecb446220826ca6aacaa4cb84
**Build date**: 2020-12-11T03:28:04.8026136Z

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
See above.

**Comment by jonsequitur** [comment]
This looks like a duplicate of #799.

**Comment by bmitc** [comment]
Hi @jonsequitur. Thanks for the link. And apologies, as I didn't see either of those other two issues (the one you linked and the F# one linked there which describes this same issue). I can close this one and make a comment on the other issue with my screenshot.
