### ISSUE TITLE
Executing a cell with FsCheck outputs a long block

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [dotnet/interactive#952]
### Describe the bug

Executing a cell with the following code creates very long output.

```fsharp
#r "nuget: FsCheck"

open FsCheck

let revRevIsOrig (xs:list<int>) = List.rev(List.rev xs) = xs
Check.Quick revRevIsOrig
```

https://user-images.githubusercontent.com/66080261/103019338-a7189280-4514-11eb-89c1-e289ec562a5a.mov

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

```
Version: 1.0.160901+a5db2e2c034eb03ecb446220826ca6aacaa4cb84

Build date: 2020-12-09T16:07:16.0000000Z
```

- OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

**Comment by bisen2** [comment]
It looks like this is probably a symptom of the same issue as #799 (along with #879 and #951). FsCheck has a few places that format together a long sequence of mostly empty strings to get their desired output, but each of those "%s" formats is getting wrapped in newlines due to #799.
