### ISSUE TITLE
Custom magic command options seems to be empty in F#

### ISSUE THREAD

**Issue by PawelStadnicki** [dotnet/interactive#959]
I have my own magic command created like this:
```
let command = new Command("#!mymagiccommand")
command.AddOption(new Option<string>("--load"))
command.AddOption(new Option<string>("--name"))
//this is not necessary, just to ensure typing
let d = System.Func<string, string, KernelInvocationContext, Task>(commandHandler)
command.Handler <-CommandHandler.Create(d)
```
Options seems to be registered correctly:
#!mymagicommand -h :
```
  #!mymagiccommand [options]

Options:
  --load <load>
  --name <name>    
  -?, -h, --help       Show help and usage information
```

However inside the command handler the option parameters seems to be empty 

```
let commandHandler (load:string) (name:string) (context:KernelInvocationContext): Task = 
        context.Display (sprintf "load param is %s" load) |> ignore
        context.Display (sprintf $"name param is {name}") |> ignore
```

as 

`#!mymagiccommand --load loader --name name`
or
`#!mymagiccommand --load "loader" --name "name"`
results with

```
load param is
name param is
```

Any clues ? Do I use it wrongly somehow or F# is not well supported in this case?

**Comment by jonsequitur** [comment]
This looks like you're hitting a common System.CommandLine gotcha. Your handler parameters will be bound based on the parameter names, so you need to have named parameters for your command handler method, e.g. `load` and `name`.

**Comment by PawelStadnicki** [comment]
How it should be different from commandHandler I already have?

`let commandHandler (load:string) (name:string) (context:KernelInvocationContext): Task = ...`

**Comment by PawelStadnicki** [comment]
Ok, I didn't notice earlier that System.Command is used. Found this [issue](https://github.com/dotnet/command-line-api/issues/941) which drove me to this working code:

```
type Opt(name, load, context) =
    member val Context:KernelInvocationContext = context
    member val Name: string = name
    member val Load: string = load 
```

**Comment by jonsequitur** [comment]
We have an alternative proposal for setting up handlers which doesn't use name-based matching, which you can see here: https://github.com/dotnet/command-line-api/pull/1012

Feel free to weigh in.
