### ISSUE TITLE
[EXTERNAL] Opening .ipynb files fails with error "Cannot read property `rendererId` of undefined" 

### ISSUE THREAD

**Issue by EverybodyKurts** [dotnet/interactive#961]
### Describe the bug

Attempting to open up a `dotnet-interactive` notebooks faisl with an error of:

```
Unable to open 'clean-code-with-ces.ipynb': Cannot read property 'rendererId' of undefined.
```

Here's a repo with the notebook in question: https://github.com/EverybodyKurts/corrupted-dotnet-interactive-notebook/blob/main/clean-code-with-ces.ipynb

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* At the command line, run `dotnet interactive --version`.

```bash
% dotnet interactive --version
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.1 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=osx.11.0-x64
```

Here's what happens if I try to install the tool:

```bash
% dotnet tool install -g Microsoft.dotnet-interactive
Tool 'microsoft.dotnet-interactive' is already installed.
```

- OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

<img width="452" alt="Screen Shot 2021-01-02 at 11 56 54 AM" src="https://user-images.githubusercontent.com/879734/103462363-c40e4c00-4cf2-11eb-8c41-24b6aae06dc3.png">

**Comment by jonsequitur** [comment]
It looks like you might need to install the .NET 5 SDK.

**Comment by EverybodyKurts** [comment]
```bash
% dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

```bash
 % dotnet tool list -g
Package Id                        Version         Commands
--------------------------------------------------------------------
dotnet-ef                         5.0.1           dotnet-ef
fake-cli                          5.19.1          fake
fantomas-tool                     4.3.0           fantomas
microsoft.dotnet-interactive      1.0.155302      dotnet-interactive
paket                             5.243.0         paket
```

**Comment by brettfo** [comment]
As far as I can trace this, it appears to be an issue with VS Code and how they handle notebook cells.  I've opened issue microsoft/vscode#113933 on their end.  This issue will stay open for tracking.

**Comment by reinux** [comment]
Is there a workaround or a way to recover a notebook?

**Comment by jonsequitur** [comment]
Is this issue still reproducible?

**Comment by jonsequitur** [comment]
> Is there a workaround or a way to recover a notebook?

@reinux I'm not sure what you're asking so feel free to clarify. We're not aware of a file corruption issue, if that's what you're asking. The problem here is a VS Code API compatibility problem, I believe.

**Comment by reinux** [comment]
I still have occasional problems opening notebooks, but not this particular error anymore.

Might it be something specific to F# or to languages not Python? Because the issues that I still do have tend to have to do with it thinking I'm still in Python.

**Comment by reinux** [comment]
> > Is there a workaround or a way to recover a notebook?
> 
> @reinux I'm not sure what you're asking so feel free to clarify. We're not aware of a file corruption issue, if that's what you're asking. The problem here is a VS Code API compatibility problem, I believe.

The issue I was having was that along with this error, it seemed to be corrupting output cells or saving unrenderable output cells. I managed to get it working again a lot of the time by stripping down the output fields in the .ipynb.

**Comment by jonsequitur** [comment]
Am I correct in assuming that was happening in VS Code? If so and you still have a repro, could you provide more details?

**Comment by jonsequitur** [comment]
> I still have occasional problems opening notebooks, but not this particular error anymore.

> Might it be something specific to F# or to languages not Python? Because the issues that I still do have tend to have to do with it thinking I'm still in Python.

Maybe one of this cluster of issues? https://github.com/dotnet/interactive/issues?q=is%3Aissue+is%3Aopen+label%3A%22Area-VS+Code+Jupyter+Extension+Interop%22

**Comment by reinux** [comment]
Just in Insiders. I haven't been able to repro this particular error since then, but I'll keep an eye out for both this issue as well as the other ones I'm experiencing, and report back when they happen.

I'm not even able to get it to recognize F# unless I save the notebook first, so maybe something weird's going on with my install as well.
