### ISSUE TITLE
[Question] Jupyter Hub integration

### ISSUE THREAD

**Issue by cosmintiru** [dotnet/interactive#964]
Hello,

I have no idea if you can point me to the right direction, or I was just not able to find the proper documentation for this.

I've deployed JupyterHub against an AKS cluster and everything works fine apart the dotnet interactive integration. I've tried different docker images, build myself a couple of them, but I still can't get the kernels to show up in the launcher. 

The dotnet sdk is installed fine, the docker image installs interactive as well and enables the kernels, but when the user space is spawned, all I get is the dotnet sdk. Everything else is gone.

Am I missing something?

**Comment by locke520** [comment]
@cosmintiru I'm seeing this same issue. Do you have a fix?
