### ISSUE TITLE
Running some external executables (git) from PowerShell causes a hang in VS Code but OK In Jupyter. 

### ISSUE THREAD

**Issue by jhoneill** [dotnet/interactive#969]
### Describe the bug
I have a notebook setup to guide very new team members through some early use of git. 
https://github.com/jhoneill/Notebooks/blob/master/notebooks/Git%20tutorial.ipynb 

It performs some simple git tasks (create a directory, run git init, , add files and run , git add, git commit, git log and git status )
This works as expected loading the file in a web browser using Jupyter. 

Running the same git commands with the notebook loaded in VS code, the notebook hangs - in some cases it returns after 50-70 seconds in others it hangs indefinitely. Multiple copies of git.exe are found to be running and if they are terminated (e.g. by running `get-process git | stop-process` in the vs code terminal window)  control returns to the notebook.  

**Which version of .NET Interactive are you using?**  1.0.160901
- OS
    - [X ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge (89.0.752.1)
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [X] Jupyter Notebook   (Works)
    - [X] Visual Studio Code  (fails)

**Comment by brettfo** [comment]
This should have been addressed in #1907.

**Comment by jhoneill** [comment]
@brettfo  Just tested this and it does seem to be working properly for me now (although I have a new problem I'll open an issue for). 
Thanks 
J
