### ISSUE TITLE
With the PowerShell Kernel in VS Code some executables do not exit - OK in Jupyter.

### ISSUE THREAD

**Issue by jhoneill** [dotnet/interactive#970]
### Describe the bug
I have a notebook setup to guide very new team members through some early use of git. 
https://github.com/jhoneill/Notebooks/blob/master/notebooks/Git%20tutorial.ipynb 

It performs some simple git tasks (create a directory, run git init, add files and run , git add, git commit, git log and git status )
This works as expected loading the file in a web browser using Jupyter. 

Running the same git commands with the notebook loaded in VS code, the notebook hangs - in some cases it returns after 50-70 seconds in others it hangs indefinitely. Multiple copies of git.exe are found to be running and if they are terminated (e.g. by running `get-process git | stop-process` in the vs code terminal window)  control returns to the notebook.  It's not clear why git.exe doesn't exit, it doesn't seem to be a problem sending output anywhere because redirecting it doesn't change anything. 

**Which version of .NET Interactive are you using?**  1.0.160901
- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge (89.0.752.1)
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [X] Jupyter Notebook   (Works)
    - [X] Visual Studio Code  (fails)

**Comment by jonsequitur** [comment]
Is there a specific cell that hangs? I'm wondering if we can narrow down the repro.

**Comment by jhoneill** [comment]
the first one
```
cd ~
del dummyProj -rec -force -ErrorAction SilentlyContinue
git config --list | out-string
```
Took  18 seconds to return and would be almost instant in a normal shell (2-3 seconds of that is starting the kernel). 

The 9th cell does
```
git add *  
git status | Out-String
``` 
Took  37 seconds

This one 
```
cd ~/dummyProj
git commit -m "two"  |out-string
```
39 seconds

and then this one
```
git commit -m "three"  | out-string
```
Ran for 500 seconds before I killed three git processes and got control back.

**Comment by wgross** [comment]
I observed today a similar behavior. Not with git but with ssh: I'm making 'notes' of interactions with my raspi-cluster and the extraction of my config took  literally 219 seconds to process while the same commands in a powershell terminal took less the 2 seconds. Theses were the commands I run: 

$config = ssh "ubuntu@picu1" microk8s config
$config | Out-File $HOME/.kube/config.1
$config

The notebook did nothing else.
