### ISSUE TITLE
Can't save notebooks: "No file system provider found for resource"

### ISSUE THREAD

**Issue by thelazydogsback** [dotnet/interactive#988]
Version: 1.0.206106+f90ff415badc98a82c7db599658df94ad527328

I am unable to save my notebooks, I get the following error:

`Failed to save 'xxx.ipynb': No file system provider found for resource 'vscode-notebook:/c%3A/Users/uuu/source/.../Notebooks/xxx.ipynb'`

My only recourse seems to be to find the copy created in `.../AppData/Roaming/code-insiders/...` and copy it back to it's source location

**Comment by markjamesm** [comment]
I'm currently running into the same issue on VSCode 1.53.0-insider.

Attempting to close the editor through the file menu or CTRL-F4 brings up a save menu. Choosing Save or Don't save closes the dialog box but doesn't exit VSCode. Relaunching VSCode loads an auto saved copy and the issue persists.

**Comment by jonsequitur** [comment]
@markjamesm Could you restart Code Insiders to make sure any pending automatic update has happened, then run `#!about` in a notebook and post the output here?

Thanks.

**Comment by markjamesm** [comment]
> @markjamesm Could you restart Code Insiders to make sure any pending automatic update has happened, then run `#!about` in a notebook and post the output here?
> 
> Thanks.

No problem! I've restarted Code, and clicking on Help --> Check for updates says that "There are currently no updates available". 

The output of #!about is:

```
.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.207203+f90ff415badc98a82c7db599658df94ad527328a
Build date: 2021-01-28T21:18:17.5764282Z
https://github.com/dotnet/interactive
```

**Comment by jonsequitur** [comment]
Thanks. I'm still not able to repro this one, so a few more questions.

Does this affect all of your notebook files? How did you create the document that won't close? Are other documents open? If you create a new document (**_.NET Interactive: Create new blank notebook_**), can you now close the original one? What's the exact filename you're entering in the save dialog, and what do you have selected in the file extension dropdown?

**Comment by markjamesm** [comment]
> Thanks. I'm still not able to repro this one, so a few more questions.
> 
> Does this affect all of your notebook files? How did you create the document that won't close? Are other documents open? If you create a new document (**_.NET Interactive: Create new blank notebook_**), can you now close the original one? What's the exact filename you're entering in the save dialog, and what do you have selected in the file extension dropdown?

I only recently downloaded .NET Interactive, and so far haven't created any other notebooks. The filename is "Analytics Test.ipynb". I would share the notebook, but unfortunately it contains sensitive information. Attempting to "Save as" returns the following message:

`File system provider for vscode-notebook:/c%3A/Users/path/Analytics%20Test.ipynb is not available.
`

The notebook in question uses the .NET F# engine and opens and saves fine when opened in Jupyter (.NET F# kernel):

```
Server Information:
You are using Jupyter notebook.

The version of the notebook server is: 6.1.4
The server is running on this version of Python:
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
```
Please note that the kernel information section is blank.

In addition, I created a new notebook in VSCode and transferred my code into it. Saving was enabled for the new notebook (Testing.ipynb),  but I cannot close the old notebook tab. When I try closing the notebook (either by right clicking and selecting close, or by clicking the X), a dialog box pops up asking me to save. Choosing "Save" or "Do not save" closes the prompt without doing anything:

![Test](https://user-images.githubusercontent.com/20845425/106513289-c655f880-64a0-11eb-9619-b34cc1b0b0a3.png)

**Comment by markjamesm** [comment]
Upon some further inspection, it seems that this issue may be closely related:

https://github.com/dotnet/interactive/issues/1013

**Comment by jonsequitur** [comment]
Am I correct that the problem only reproduces with this one specific notebook file? How did you create that file (which app, which command)?

**Comment by markjamesm** [comment]
> Am I correct that the problem only reproduces with this one specific notebook file? How did you create that file (which app, which command)?

That's correct, although I haven't made very many notebooks yet. 

To create the notebook, I opened VS Code Insiders and then pressed Ctrl-Shift-P and chose ".NET Interactive: Create New Blank Notebook." I then clicked on C# (.NET Interactive) in the right side of the notebook and switched it to F# (.NET Interactive). 

I then began writing my code and saved the file at some point. I later opened VSCode again (the file was already present in the editor) and started to work on it again. This time when I tried saving, I ran into the error.

**Comment by thelazydogsback** [comment]
> To create the notebook, I opened VS Code Insiders and then pressed Ctrl-Shift-P and chose ".NET Interactive: Create New Blank Notebook." I then clicked on C# (.NET Interactive) in the right side of the notebook and switched it to F# (.NET Interactive).

 I created mine the same way, except C#.

**Comment by thelazydogsback** [comment]
This seems to be fixed for me now with the latest update to VSC and the extension that was downloaded this morning. (It's been a few weeks since I've tried the notebooks.)

**Comment by markjamesm** [comment]
I've upgraded this morning to the latest version but am still running into the error. My current VSCode version is:

```
Version: 1.53.0-insider (user setup)
Commit: e1c818a171168eedf78b62fdc7f4e3458d5dea7c
Date: 2021-02-03T08:23:41.329Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by jonsequitur** [comment]
@markjamesm Can you also please reconfirm the .NET Interactive Notebooks extension version and the output of running `#!about` in the notebook?

**Comment by markjamesm** [comment]
> @markjamesm Can you also please reconfirm the .NET Interactive Notebooks extension version and the output of running `#!about` in the notebook?

`.NET Interactive Notebooks v1.0.207203`

!#about
```
.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.207203+f90ff415badc98a82c7db599658df94ad527328a
Build date: 2021-01-28T21:18:17.5764282Z
https://github.com/dotnet/interactive
```

**Comment by jonsequitur** [comment]
@thelazydogsback @markjamesm Are you still seeing this issue in either Code Insiders or VS Code stable?

**Comment by markjamesm** [comment]
> @thelazydogsback @markjamesm Are you still seeing this issue in either Code Insiders or VS Code stable?

The issue seems to have resolved after installing one of the recent VS Code Insiders release. Have not tested on stable.

**Comment by colombod** [comment]
> > @thelazydogsback @markjamesm Are you still seeing this issue in either Code Insiders or VS Code stable?
> 
> The issue seems to have resolved after installing one of the recent VS Code Insiders release. Have not tested on stable.

How is it going for you with VS Code Stable release?

**Comment by jonsequitur** [comment]
I think this one is resolved. @thelazydogsback feel free to reopen if it you see it again.
