### ISSUE TITLE
[EXTERNAL] Can't scroll the output of a code cell

### ISSUE THREAD

**Issue by vchirikov** [dotnet/interactive#989]
### Describe the bug

Hi. I can't scroll the output of a code cell in `ms-dotnettools.dotnet-interactive-vscode`

```bash
> #!about
.NET Interactive
Version: 1.0.206106+f90ff415badc98a82c7db599658df94ad527328a
Build date: 2021-01-17T18:56:34.7387164Z

> dotnet interactive --version
1.0.155302+ea10eecdeb2eb5f0ccbac5d7eec8b97a99453388
```

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/40987940/105030594-124a7b80-5a65-11eb-881a-30b51aa54da0.png)

**Comment by vchirikov** [comment]
Also sometimes I see something like:

![image](https://user-images.githubusercontent.com/40987940/105032106-5d658e00-5a67-11eb-9561-1dcd5e161ee7.png)

**Comment by JayDee23** [comment]
Any update on this?

**Comment by jonsequitur** [comment]
I realized that I didn't link the underlying issue in VS Code: https://github.com/microsoft/vscode-jupyter/issues/4406

**Comment by rebornix** [comment]
The original issue should already be fixed now
